import type { Word } from "../words";

export const band1: Word[] = [
  {
    word: "want",
    pos: "verb",
    kidMeaning: "Wish for something very much.",
    examples: ["She wants a new toy.", "He wants to play football."],
    emoji: "😊",
    syllables: "want",
    distractorGroup: "desire",
  },
  {
    word: "need",
    pos: "verb",
    kidMeaning: "Must have something to live or do.",
    examples: ["You need water to drink.", "We need a book for school."],
    emoji: "📌",
    syllables: "need",
    distractorGroup: "necessity",
  },
  {
    word: "keep",
    pos: "verb",
    kidMeaning: "Have something and not let it go.",
    examples: ["Keep your toys in the box.", "She keeps her money in a jar."],
    emoji: "🗝️",
    syllables: "keep",
    distractorGroup: "possession",
  },
  {
    word: "bring",
    pos: "verb",
    kidMeaning: "Carry something to a place.",
    examples: ["Bring your bag to school.", "He brings lunch to work."],
    emoji: "🛫",
    syllables: "bring",
    distractorGroup: "movement",
  },
  {
    word: "carry",
    pos: "verb",
    kidMeaning: "Hold and move something from place to place.",
    examples: ["She carries her books to class.", "He carries the box upstairs."],
    emoji: "💪",
    syllables: "car-ry",
    distractorGroup: "movement",
  },
  {
    word: "turn",
    pos: "verb",
    kidMeaning: "Spin or go in a different direction.",
    examples: ["Turn left at the corner.", "He turns the page of the book."],
    emoji: "🔄",
    syllables: "turn",
    distractorGroup: "movement",
  },
  {
    word: "show",
    pos: "verb",
    kidMeaning: "Let someone see something.",
    examples: ["Show me your drawing.", "She shows her toys to her friend."],
    emoji: "👉",
    syllables: "show",
    distractorGroup: "communication",
  },
  {
    word: "leave",
    pos: "verb",
    kidMeaning: "Go away from a place.",
    examples: ["Leave the room quietly.", "She leaves home at eight o'clock."],
    emoji: "🚪",
    syllables: "leave",
    distractorGroup: "movement",
  },
  {
    word: "mean",
    pos: "verb",
    kidMeaning: "Have a certain meaning or purpose.",
    examples: ["What does this word mean?", "He means to help his mother."],
    emoji: "🤔",
    syllables: "mean",
    distractorGroup: "communication",
  },
  {
    word: "find",
    pos: "verb",
    kidMeaning: "Look for something and discover it.",
    examples: ["Find your shoes under the bed.", "She finds her ring in the drawer."],
    emoji: "🔍",
    syllables: "find",
    distractorGroup: "discovery",
  },
  {
    word: "use",
    pos: "verb",
    kidMeaning: "Make something work or do something with it.",
    examples: ["Use a pencil to write.", "She uses a spoon to eat soup."],
    emoji: "🖊️",
    syllables: "use",
    distractorGroup: "action",
  },
  {
    word: "make",
    pos: "verb",
    kidMeaning: "Create or build something.",
    examples: ["Make a cake for the party.", "He makes a paper plane."],
    emoji: "🛠️",
    syllables: "make",
    distractorGroup: "creation",
  },
  {
    word: "take",
    pos: "verb",
    kidMeaning: "Get something and hold it.",
    examples: ["Take your umbrella when it rains.", "She takes medicine when ill."],
    emoji: "✋",
    syllables: "take",
    distractorGroup: "possession",
  },
  {
    word: "give",
    pos: "verb",
    kidMeaning: "Let someone have something.",
    examples: ["Give this book to your sister.", "She gives food to the cat."],
    emoji: "🎁",
    syllables: "give",
    distractorGroup: "possession",
  },
  {
    word: "come",
    pos: "verb",
    kidMeaning: "Move towards a place.",
    examples: ["Come here, please.", "He comes to school by bus."],
    emoji: "👋",
    syllables: "come",
    distractorGroup: "movement",
  },
  {
    word: "go",
    pos: "verb",
    kidMeaning: "Move away from a place.",
    examples: ["Go to bed now.", "She goes to the market every day."],
    emoji: "🚶",
    syllables: "go",
    distractorGroup: "movement",
  },
  {
    word: "put",
    pos: "verb",
    kidMeaning: "Place something in a location.",
    examples: ["Put your things away.", "He puts the milk in the fridge."],
    emoji: "📍",
    syllables: "put",
    distractorGroup: "placement",
  },
  {
    word: "say",
    pos: "verb",
    kidMeaning: "Speak words out loud.",
    examples: ["Say the word slowly.", "She says hello every morning."],
    emoji: "💬",
    syllables: "say",
    distractorGroup: "speaking",
  },
  {
    word: "see",
    pos: "verb",
    kidMeaning: "Look at and notice something.",
    examples: ["See the bird in the tree.", "He sees his friend at school."],
    emoji: "👀",
    syllables: "see",
    distractorGroup: "sensing",
  },
  {
    word: "know",
    pos: "verb",
    kidMeaning: "Have information about something.",
    examples: ["Know your address and phone number.", "She knows the answer to the question."],
    emoji: "🧠",
    syllables: "know",
    distractorGroup: "knowledge",
  },
  {
    word: "think",
    pos: "verb",
    kidMeaning: "Use your mind to figure something out.",
    examples: ["Think hard before you answer.", "He thinks about tomorrow's trip."],
    emoji: "💭",
    syllables: "think",
    distractorGroup: "cognition",
  },
  {
    word: "look",
    pos: "verb",
    kidMeaning: "Turn your eyes toward something.",
    examples: ["Look at the picture.", "She looks out the window."],
    emoji: "👁️",
    syllables: "look",
    distractorGroup: "sensing",
  },
  {
    word: "hear",
    pos: "verb",
    kidMeaning: "Listen and receive sound.",
    examples: ["Hear the bell ring.", "He hears music from the radio."],
    emoji: "👂",
    syllables: "hear",
    distractorGroup: "sensing",
  },
  {
    word: "feel",
    pos: "verb",
    kidMeaning: "Have an emotion or sense a touch.",
    examples: ["Feel the soft blanket.", "She feels happy at the party."],
    emoji: "🤗",
    syllables: "feel",
    distractorGroup: "emotion",
  },
  {
    word: "move",
    pos: "verb",
    kidMeaning: "Change position from one place to another.",
    examples: ["Move to the next line.", "He moves the chair to the corner."],
    emoji: "➡️",
    syllables: "move",
    distractorGroup: "movement",
  },
  {
    word: "open",
    pos: "verb",
    kidMeaning: "Make something not closed.",
    examples: ["Open the door for me.", "She opens her book to page ten."],
    emoji: "🚪",
    syllables: "o-pen",
    distractorGroup: "action",
  },
  {
    word: "close",
    pos: "verb",
    kidMeaning: "Make something shut.",
    examples: ["Close your eyes.", "He closes the window at night."],
    emoji: "🤐",
    syllables: "close",
    distractorGroup: "action",
  },
  {
    word: "cut",
    pos: "verb",
    kidMeaning: "Use a knife or scissors to separate.",
    examples: ["Cut the paper with scissors.", "She cuts the apple into pieces."],
    emoji: "✂️",
    syllables: "cut",
    distractorGroup: "action",
  },
  {
    word: "break",
    pos: "verb",
    kidMeaning: "Make something separate into pieces.",
    examples: ["Be careful not to break the glass.", "He breaks the toy by accident."],
    emoji: "💥",
    syllables: "break",
    distractorGroup: "damage",
  },
  {
    word: "push",
    pos: "verb",
    kidMeaning: "Press against something to move it.",
    examples: ["Push the door to open it.", "She pushes the swing high."],
    emoji: "💪",
    syllables: "push",
    distractorGroup: "force",
  },
  {
    word: "pull",
    pos: "verb",
    kidMeaning: "Draw something towards you.",
    examples: ["Pull your chair closer.", "He pulls the rope hard."],
    emoji: "🎣",
    syllables: "pull",
    distractorGroup: "force",
  },
  {
    word: "throw",
    pos: "verb",
    kidMeaning: "Send something through the air with force.",
    examples: ["Throw the ball to me.", "She throws the stone into the water."],
    emoji: "⚾",
    syllables: "throw",
    distractorGroup: "motion",
  },
  {
    word: "catch",
    pos: "verb",
    kidMeaning: "Grab something that is moving.",
    examples: ["Catch the ball.", "He catches fish in the river."],
    emoji: "🤲",
    syllables: "catch",
    distractorGroup: "motion",
  },
  {
    word: "run",
    pos: "verb",
    kidMeaning: "Move very fast on foot.",
    examples: ["Run to the gate.", "She runs every morning."],
    emoji: "🏃",
    syllables: "run",
    distractorGroup: "movement",
  },
  {
    word: "walk",
    pos: "verb",
    kidMeaning: "Move on foot at normal speed.",
    examples: ["Walk to school.", "He walks his dog in the park."],
    emoji: "🚶",
    syllables: "walk",
    distractorGroup: "movement",
  },
  {
    word: "sit",
    pos: "verb",
    kidMeaning: "Rest on your bottom in a chair.",
    examples: ["Sit down on the bench.", "She sits next to me in class."],
    emoji: "🪑",
    syllables: "sit",
    distractorGroup: "position",
  },
  {
    word: "stand",
    pos: "verb",
    kidMeaning: "Be on your feet upright.",
    examples: ["Stand up straight.", "He stands in line at the shop."],
    emoji: "🧍",
    syllables: "stand",
    distractorGroup: "position",
  },
  {
    word: "lie",
    pos: "verb",
    kidMeaning: "Rest flat on your back.",
    examples: ["Lie down on the bed.", "She lies on the grass."],
    emoji: "🛏️",
    syllables: "lie",
    distractorGroup: "position",
  },
  {
    word: "sleep",
    pos: "verb",
    kidMeaning: "Rest at night with eyes closed.",
    examples: ["Sleep eight hours every night.", "He sleeps after lunch."],
    emoji: "😴",
    syllables: "sleep",
    distractorGroup: "rest",
  },
  {
    word: "eat",
    pos: "verb",
    kidMeaning: "Put food in your mouth and chew.",
    examples: ["Eat your vegetables.", "She eats lunch at twelve o'clock."],
    emoji: "🍽️",
    syllables: "eat",
    distractorGroup: "consumption",
  },
  {
    word: "drink",
    pos: "verb",
    kidMeaning: "Swallow liquid.",
    examples: ["Drink your milk.", "He drinks water after playing."],
    emoji: "🥤",
    syllables: "drink",
    distractorGroup: "consumption",
  },
  {
    word: "play",
    pos: "verb",
    kidMeaning: "Do something for fun.",
    examples: ["Play with your friends.", "She plays football on Saturdays."],
    emoji: "⚽",
    syllables: "play",
    distractorGroup: "recreation",
  },
  {
    word: "work",
    pos: "verb",
    kidMeaning: "Do a job or task.",
    examples: ["Work hard in school.", "He works in a shop."],
    emoji: "💼",
    syllables: "work",
    distractorGroup: "labour",
  },
  {
    word: "learn",
    pos: "verb",
    kidMeaning: "Gain new knowledge or skill.",
    examples: ["Learn to read and write.", "She learns English at school."],
    emoji: "📚",
    syllables: "learn",
    distractorGroup: "education",
  },
  {
    word: "teach",
    pos: "verb",
    kidMeaning: "Help someone learn something.",
    examples: ["Teach me how to swim.", "He teaches mathematics in school."],
    emoji: "👨‍🏫",
    syllables: "teach",
    distractorGroup: "education",
  },
  {
    word: "read",
    pos: "verb",
    kidMeaning: "Look at words and understand them.",
    examples: ["Read the story to me.", "She reads a book every day."],
    emoji: "📖",
    syllables: "read",
    distractorGroup: "education",
  },
  {
    word: "write",
    pos: "verb",
    kidMeaning: "Make letters and words on paper.",
    examples: ["Write your name on the paper.", "He writes a story about his holiday."],
    emoji: "✏️",
    syllables: "write",
    distractorGroup: "creation",
  },
  {
    word: "talk",
    pos: "verb",
    kidMeaning: "Speak to someone.",
    examples: ["Talk to your friend.", "She talks on the phone."],
    emoji: "🗣️",
    syllables: "talk",
    distractorGroup: "communication",
  },
  {
    word: "listen",
    pos: "verb",
    kidMeaning: "Pay attention to sounds.",
    examples: ["Listen to the teacher.", "He listens to music."],
    emoji: "🎧",
    syllables: "lis-ten",
    distractorGroup: "sensing",
  },
  {
    word: "watch",
    pos: "verb",
    kidMeaning: "Look at something for a while.",
    examples: ["Watch the movie.", "She watches television in the evening."],
    emoji: "📺",
    syllables: "watch",
    distractorGroup: "sensing",
  },
  {
    word: "help",
    pos: "verb",
    kidMeaning: "Do something for someone.",
    examples: ["Help your mother with dinner.", "He helps his brother with homework."],
    emoji: "🤝",
    syllables: "help",
    distractorGroup: "assistance",
  },
  {
    word: "ask",
    pos: "verb",
    kidMeaning: "Request information or something.",
    examples: ["Ask the teacher a question.", "She asks for milk at breakfast."],
    emoji: "🙋",
    syllables: "ask",
    distractorGroup: "communication",
  },
  {
    word: "tell",
    pos: "verb",
    kidMeaning: "Inform or give information.",
    examples: ["Tell me your name.", "He tells a funny story."],
    emoji: "💬",
    syllables: "tell",
    distractorGroup: "communication",
  },
  {
    word: "sing",
    pos: "verb",
    kidMeaning: "Make music with your voice.",
    examples: ["Sing the national anthem.", "She sings in the choir."],
    emoji: "🎵",
    syllables: "sing",
    distractorGroup: "performance",
  },
  {
    word: "dance",
    pos: "verb",
    kidMeaning: "Move to music.",
    examples: ["Dance at the party.", "He dances ballet."],
    emoji: "💃",
    syllables: "dance",
    distractorGroup: "performance",
  },
  {
    word: "draw",
    pos: "verb",
    kidMeaning: "Make a picture with pencil or pen.",
    examples: ["Draw a picture of your house.", "She draws animals in art class."],
    emoji: "🎨",
    syllables: "draw",
    distractorGroup: "creation",
  },
  {
    word: "paint",
    pos: "verb",
    kidMeaning: "Cover with coloured liquid.",
    examples: ["Paint the wall white.", "He paints pictures with watercolour."],
    emoji: "🖌️",
    syllables: "paint",
    distractorGroup: "creation",
  },
  {
    word: "build",
    pos: "verb",
    kidMeaning: "Construct or put together.",
    examples: ["Build a sandcastle at the beach.", "She builds a house with blocks."],
    emoji: "🏗️",
    syllables: "build",
    distractorGroup: "creation",
  },
  {
    word: "buy",
    pos: "verb",
    kidMeaning: "Give money to get something.",
    examples: ["Buy milk at the shop.", "She buys new shoes for school."],
    emoji: "🛍️",
    syllables: "buy",
    distractorGroup: "commerce",
  },
  {
    word: "sell",
    pos: "verb",
    kidMeaning: "Give something and get money.",
    examples: ["Sell your old toys.", "He sells ice cream."],
    emoji: "💰",
    syllables: "sell",
    distractorGroup: "commerce",
  },
  {
    word: "grow",
    pos: "verb",
    kidMeaning: "Get bigger or develop.",
    examples: ["Grow taller every year.", "She grows tomatoes in the garden."],
    emoji: "🌱",
    syllables: "grow",
    distractorGroup: "change",
  },
  {
    word: "count",
    pos: "verb",
    kidMeaning: "Say numbers in order.",
    examples: ["Count to one hundred.", "She counts her money."],
    emoji: "🔢",
    syllables: "count",
    distractorGroup: "cognition",
  },
  {
    word: "wait",
    pos: "verb",
    kidMeaning: "Stay in one place until something happens.",
    examples: ["Wait for the bus.", "She waits for her friend."],
    emoji: "⏳",
    syllables: "wait",
    distractorGroup: "time",
  },
  {
    word: "follow",
    pos: "verb",
    kidMeaning: "Go behind someone or something.",
    examples: ["Follow me to the classroom.", "He follows his father to the market."],
    emoji: "👣",
    syllables: "fol-low",
    distractorGroup: "motion",
  },
  {
    word: "laugh",
    pos: "verb",
    kidMeaning: "Make a happy sound.",
    examples: ["Laugh at the funny joke.", "She laughs at the cartoon."],
    emoji: "😂",
    syllables: "laugh",
    distractorGroup: "expression",
  },
  {
    word: "start",
    pos: "verb",
    kidMeaning: "Begin doing something.",
    examples: ["Start your homework.", "She starts school at eight o'clock."],
    emoji: "🚀",
    syllables: "start",
    distractorGroup: "time",
  },
  {
    word: "stop",
    pos: "verb",
    kidMeaning: "End or cease an action.",
    examples: ["Stop playing and come for dinner.", "He stops the car at the red light."],
    emoji: "🛑",
    syllables: "stop",
    distractorGroup: "time",
  },
  {
    word: "finish",
    pos: "verb",
    kidMeaning: "Complete something.",
    examples: ["Finish your dinner.", "He finishes the painting."],
    emoji: "✅",
    syllables: "fin-ish",
    distractorGroup: "time",
  },
  {
    word: "wash",
    pos: "verb",
    kidMeaning: "Clean with water and soap.",
    examples: ["Wash your hands before eating.", "He washes the car on Saturday."],
    emoji: "🧼",
    syllables: "wash",
    distractorGroup: "cleanliness",
  },
  {
    word: "cook",
    pos: "verb",
    kidMeaning: "Prepare food with heat.",
    examples: ["Cook dinner for the family.", "She cooks rice every day."],
    emoji: "👨‍🍳",
    syllables: "cook",
    distractorGroup: "food preparation",
  },
  {
    word: "bake",
    pos: "verb",
    kidMeaning: "Make bread or cakes in an oven.",
    examples: ["Bake a cake for the birthday.", "He bakes biscuits every Sunday."],
    emoji: "🍰",
    syllables: "bake",
    distractorGroup: "food preparation",
  },
  {
    word: "win",
    pos: "verb",
    kidMeaning: "Be first or best in a competition.",
    examples: ["Win the race.", "She wins the first prize."],
    emoji: "🥇",
    syllables: "win",
    distractorGroup: "achievement",
  },
  {
    word: "lose",
    pos: "verb",
    kidMeaning: "Not win or no longer have something.",
    examples: ["Lose the match.", "He loses his book."],
    emoji: "😞",
    syllables: "lose",
    distractorGroup: "loss",
  },
  {
    word: "try",
    pos: "verb",
    kidMeaning: "Attempt to do something.",
    examples: ["Try to solve the puzzle.", "She will try hard in sports."],
    emoji: "💪",
    syllables: "try",
    distractorGroup: "effort",
  },
  {
    word: "reach",
    pos: "verb",
    kidMeaning: "Stretch your arm to get something.",
    examples: ["Reach the book on the shelf.", "He reaches for the apple."],
    emoji: "🙌",
    syllables: "reach",
    distractorGroup: "motion",
  },
  {
    word: "join",
    pos: "verb",
    kidMeaning: "Become part of a group.",
    examples: ["Join our club.", "She joins the football team."],
    emoji: "🤲",
    syllables: "join",
    distractorGroup: "participation",
  },
  {
    word: "miss",
    pos: "verb",
    kidMeaning: "Fail to hit or not be present.",
    examples: ["Miss the ball.", "She misses her friend."],
    emoji: "😞",
    syllables: "miss",
    distractorGroup: "absence",
  },
  {
    word: "begin",
    pos: "verb",
    kidMeaning: "Start or commence.",
    examples: ["Begin the lesson.", "She begins her work at nine."],
    emoji: "▶️",
    syllables: "be-gin",
    distractorGroup: "time",
  },
  {
    word: "boy",
    pos: "noun",
    kidMeaning: "A male child.",
    examples: ["The boy is playing football.", "She knows a boy named Sam."],
    emoji: "👦",
    syllables: "boy",
    distractorGroup: "people",
  },
  {
    word: "girl",
    pos: "noun",
    kidMeaning: "A female child.",
    examples: ["The girl is reading a book.", "He knows a girl named Sara."],
    emoji: "👧",
    syllables: "girl",
    distractorGroup: "people",
  },
  {
    word: "man",
    pos: "noun",
    kidMeaning: "A male adult human.",
    examples: ["The man is walking in the garden.", "She sees a man at the shop."],
    emoji: "👨",
    syllables: "man",
    distractorGroup: "people",
  },
  {
    word: "woman",
    pos: "noun",
    kidMeaning: "A female adult human.",
    examples: ["The woman is reading a book.", "He talks to the woman."],
    emoji: "👩",
    syllables: "wom-an",
    distractorGroup: "people",
  },
  {
    word: "baby",
    pos: "noun",
    kidMeaning: "A very young child.",
    examples: ["The baby is sleeping.", "She holds the baby."],
    emoji: "👶",
    syllables: "ba-by",
    distractorGroup: "people",
  },
  {
    word: "friend",
    pos: "noun",
    kidMeaning: "A person you like and spend time with.",
    examples: ["My friend lives next to me.", "She invites her friend to play."],
    emoji: "👫",
    syllables: "friend",
    distractorGroup: "people",
  },
  {
    word: "family",
    pos: "noun",
    kidMeaning: "Parents and children together.",
    examples: ["My family lives in a house.", "She has a big family."],
    emoji: "👨‍👩‍👧‍👦",
    syllables: "fam-i-ly",
    distractorGroup: "people",
  },
  {
    word: "mother",
    pos: "noun",
    kidMeaning: "A female parent.",
    examples: ["My mother cooks dinner.", "She helps her mother."],
    emoji: "👩",
    syllables: "moth-er",
    distractorGroup: "family",
  },
  {
    word: "father",
    pos: "noun",
    kidMeaning: "A male parent.",
    examples: ["My father reads the newspaper.", "He plays with his father."],
    emoji: "👨",
    syllables: "fath-er",
    distractorGroup: "family",
  },
  {
    word: "brother",
    pos: "noun",
    kidMeaning: "A male sibling.",
    examples: ["My brother is taller than me.", "He fights with his brother."],
    emoji: "👬",
    syllables: "broth-er",
    distractorGroup: "family",
  },
  {
    word: "sister",
    pos: "noun",
    kidMeaning: "A female sibling.",
    examples: ["My sister goes to school.", "She plays with her sister."],
    emoji: "👭",
    syllables: "sis-ter",
    distractorGroup: "family",
  },
  {
    word: "teacher",
    pos: "noun",
    kidMeaning: "A person who teaches in school.",
    examples: ["Our teacher is very kind.", "She asks the teacher a question."],
    emoji: "👨‍🏫",
    syllables: "teach-er",
    distractorGroup: "job",
  },
  {
    word: "doctor",
    pos: "noun",
    kidMeaning: "A person who treats sick people.",
    examples: ["The doctor checks my health.", "He goes to the doctor."],
    emoji: "👨‍⚕️",
    syllables: "doc-tor",
    distractorGroup: "job",
  },
  {
    word: "nurse",
    pos: "noun",
    kidMeaning: "A person who helps the doctor.",
    examples: ["The nurse gives me medicine.", "She is a nurse at the hospital."],
    emoji: "👩‍⚕️",
    syllables: "nurse",
    distractorGroup: "job",
  },
  {
    word: "time",
    pos: "noun",
    kidMeaning: "The hours and minutes.",
    examples: ["What time is it?", "She plays for a long time."],
    emoji: "⏰",
    syllables: "time",
    distractorGroup: "time",
  },
  {
    word: "day",
    pos: "noun",
    kidMeaning: "The light time between sunrise and sunset.",
    examples: ["It is a sunny day.", "She plays outside every day."],
    emoji: "☀️",
    syllables: "day",
    distractorGroup: "time",
  },
  {
    word: "week",
    pos: "noun",
    kidMeaning: "Seven days together.",
    examples: ["There are seven days in a week.", "She visits her grandmother once a week."],
    emoji: "📅",
    syllables: "week",
    distractorGroup: "time",
  },
  {
    word: "month",
    pos: "noun",
    kidMeaning: "About thirty days, one part of a year.",
    examples: ["There are twelve months in a year.", "He was born in January month."],
    emoji: "📆",
    syllables: "month",
    distractorGroup: "time",
  },
  {
    word: "year",
    pos: "noun",
    kidMeaning: "Twelve months together.",
    examples: ["I grow taller every year.", "She has lived here for five years."],
    emoji: "📅",
    syllables: "year",
    distractorGroup: "time",
  },
  {
    word: "morning",
    pos: "noun",
    kidMeaning: "The early part of the day when it is light.",
    examples: ["I eat breakfast in the morning.", "She goes to school every morning."],
    emoji: "🌅",
    syllables: "morn-ing",
    distractorGroup: "time",
  },
  {
    word: "afternoon",
    pos: "noun",
    kidMeaning: "The middle part of the day after midday.",
    examples: ["We have lunch in the afternoon.", "He sleeps in the afternoon."],
    emoji: "🌤️",
    syllables: "af-ter-noon",
    distractorGroup: "time",
  },
  {
    word: "evening",
    pos: "noun",
    kidMeaning: "The time after sunset when it gets dark.",
    examples: ["We watch television in the evening.", "She plays with her friend in the evening."],
    emoji: "🌆",
    syllables: "eve-ning",
    distractorGroup: "time",
  },
  {
    word: "night",
    pos: "noun",
    kidMeaning: "The dark time when the sun is down.",
    examples: ["We sleep at night.", "She reads a book at night."],
    emoji: "🌙",
    syllables: "night",
    distractorGroup: "time",
  },
  {
    word: "home",
    pos: "noun",
    kidMeaning: "The place where you live.",
    examples: ["I go home after school.", "She lives in a home near the park."],
    emoji: "🏠",
    syllables: "home",
    distractorGroup: "place",
  },
  {
    word: "house",
    pos: "noun",
    kidMeaning: "A building where people live.",
    examples: ["Our house is big.", "He lives in a stone house."],
    emoji: "🏠",
    syllables: "house",
    distractorGroup: "place",
  },
  {
    word: "room",
    pos: "noun",
    kidMeaning: "A part of a building with walls.",
    examples: ["My bedroom is upstairs.", "She cleans the room."],
    emoji: "🚪",
    syllables: "room",
    distractorGroup: "place",
  },
  {
    word: "school",
    pos: "noun",
    kidMeaning: "A place for learning.",
    examples: ["She goes to school every day.", "He likes his new school."],
    emoji: "🏫",
    syllables: "school",
    distractorGroup: "place",
  },
  {
    word: "park",
    pos: "noun",
    kidMeaning: "A green space with trees and grass.",
    examples: ["She plays in the park.", "He rides his bike in the park."],
    emoji: "🌳",
    syllables: "park",
    distractorGroup: "place",
  },
  {
    word: "street",
    pos: "noun",
    kidMeaning: "A road in a town or city.",
    examples: ["She lives on Main Street.", "He crosses the street carefully."],
    emoji: "🛣️",
    syllables: "street",
    distractorGroup: "place",
  },
  {
    word: "city",
    pos: "noun",
    kidMeaning: "A large town with many buildings.",
    examples: ["She lives in the city.", "There are many people in the city."],
    emoji: "🏙️",
    syllables: "cit-y",
    distractorGroup: "place",
  },
  {
    word: "book",
    pos: "noun",
    kidMeaning: "Pages with words and pictures bound together.",
    examples: ["I read a book every day.", "She borrows books from the library."],
    emoji: "📖",
    syllables: "book",
    distractorGroup: "object",
  },
  {
    word: "pen",
    pos: "noun",
    kidMeaning: "A tool for writing with ink.",
    examples: ["She writes with a pen.", "I need a pen for the test."],
    emoji: "🖊️",
    syllables: "pen",
    distractorGroup: "object",
  },
  {
    word: "pencil",
    pos: "noun",
    kidMeaning: "A tool for writing with lead.",
    examples: ["He uses a pencil to draw.", "She sharpens her pencil."],
    emoji: "✏️",
    syllables: "pen-cil",
    distractorGroup: "object",
  },
  {
    word: "paper",
    pos: "noun",
    kidMeaning: "A flat material for writing.",
    examples: ["She writes on paper.", "He draws on coloured paper."],
    emoji: "📄",
    syllables: "pa-per",
    distractorGroup: "object",
  },
  {
    word: "doll",
    pos: "noun",
    kidMeaning: "A toy that looks like a person.",
    examples: ["She has many dolls.", "He plays with his favourite doll."],
    emoji: "🎀",
    syllables: "doll",
    distractorGroup: "object",
  },
  {
    word: "puzzle",
    pos: "noun",
    kidMeaning: "A game with pieces to put together.",
    examples: ["They solve a puzzle together.", "She loves doing puzzles."],
    emoji: "🧩",
    syllables: "puzz-le",
    distractorGroup: "activity",
  },
  {
    word: "ball",
    pos: "noun",
    kidMeaning: "A round object for playing.",
    examples: ["She kicks the ball.", "The ball is red and white."],
    emoji: "⚽",
    syllables: "ball",
    distractorGroup: "object",
  },
  {
    word: "water",
    pos: "noun",
    kidMeaning: "Clear liquid you drink and need to live.",
    examples: ["She drinks water every day.", "Water is cold and wet."],
    emoji: "💧",
    syllables: "wa-ter",
    distractorGroup: "nature",
  },
  {
    word: "food",
    pos: "noun",
    kidMeaning: "Something to eat.",
    examples: ["She eats good food.", "The food is delicious."],
    emoji: "🍽️",
    syllables: "food",
    distractorGroup: "consumption",
  },
  {
    word: "bread",
    pos: "noun",
    kidMeaning: "Baked dough made from flour.",
    examples: ["She eats bread with butter.", "The bread is fresh."],
    emoji: "🍞",
    syllables: "bread",
    distractorGroup: "food",
  },
  {
    word: "milk",
    pos: "noun",
    kidMeaning: "White liquid from animals or plants.",
    examples: ["She drinks milk.", "The milk is cold."],
    emoji: "🥛",
    syllables: "milk",
    distractorGroup: "food",
  },
  {
    word: "egg",
    pos: "noun",
    kidMeaning: "A round object laid by birds.",
    examples: ["She eats eggs for breakfast.", "The egg is brown."],
    emoji: "🥚",
    syllables: "egg",
    distractorGroup: "food",
  },
  {
    word: "sun",
    pos: "noun",
    kidMeaning: "The bright star in the sky that gives light.",
    examples: ["The sun is hot.", "She plays in the sun."],
    emoji: "☀️",
    syllables: "sun",
    distractorGroup: "nature",
  },
  {
    word: "moon",
    pos: "noun",
    kidMeaning: "The bright object in the night sky.",
    examples: ["The moon is round.", "She sees the moon at night."],
    emoji: "🌙",
    syllables: "moon",
    distractorGroup: "nature",
  },
  {
    word: "star",
    pos: "noun",
    kidMeaning: "A small bright light in the night sky.",
    examples: ["She sees many stars.", "The star is very far away."],
    emoji: "⭐",
    syllables: "star",
    distractorGroup: "nature",
  },
  {
    word: "rain",
    pos: "noun",
    kidMeaning: "Water falling from clouds.",
    examples: ["It rains on Monday.", "She plays in the rain."],
    emoji: "🌧️",
    syllables: "rain",
    distractorGroup: "weather",
  },
  {
    word: "snow",
    pos: "noun",
    kidMeaning: "White frozen water that falls from clouds.",
    examples: ["It snows in winter.", "She plays with snow."],
    emoji: "❄️",
    syllables: "snow",
    distractorGroup: "weather",
  },
  {
    word: "fire",
    pos: "noun",
    kidMeaning: "Heat and light from burning.",
    examples: ["The fire is very hot.", "She sits near the fire."],
    emoji: "🔥",
    syllables: "fire",
    distractorGroup: "nature",
  },
  {
    word: "money",
    pos: "noun",
    kidMeaning: "Coins and paper to buy things.",
    examples: ["She saves her money.", "He spends money on books."],
    emoji: "💰",
    syllables: "mon-ey",
    distractorGroup: "commerce",
  },
  {
    word: "toy",
    pos: "noun",
    kidMeaning: "Something for playing.",
    examples: ["She plays with a toy.", "The toy is broken."],
    emoji: "🧸",
    syllables: "toy",
    distractorGroup: "object",
  },
  {
    word: "tree",
    pos: "noun",
    kidMeaning: "A large plant with a trunk and branches.",
    examples: ["She climbs a tree.", "The tree has many leaves."],
    emoji: "🌳",
    syllables: "tree",
    distractorGroup: "nature",
  },
  {
    word: "flower",
    pos: "noun",
    kidMeaning: "A coloured plant part that smells nice.",
    examples: ["She picks a flower.", "The flower is red."],
    emoji: "🌹",
    syllables: "flow-er",
    distractorGroup: "nature",
  },
  {
    word: "cat",
    pos: "noun",
    kidMeaning: "A small furry pet.",
    examples: ["She has a cat.", "The cat sleeps on the bed."],
    emoji: "🐱",
    syllables: "cat",
    distractorGroup: "animal",
  },
  {
    word: "dog",
    pos: "noun",
    kidMeaning: "A loyal animal pet.",
    examples: ["She has a dog.", "The dog runs in the park."],
    emoji: "🐕",
    syllables: "dog",
    distractorGroup: "animal",
  },
  {
    word: "bird",
    pos: "noun",
    kidMeaning: "An animal with wings that can fly.",
    examples: ["She sees a bird in the tree.", "The bird sings beautifully."],
    emoji: "🐦",
    syllables: "bird",
    distractorGroup: "animal",
  },
  {
    word: "table",
    pos: "noun",
    kidMeaning: "A piece of furniture with legs.",
    examples: ["We eat at the table.", "She sits at the table to study."],
    emoji: "🪑",
    syllables: "ta-ble",
    distractorGroup: "furniture",
  },
  {
    word: "chair",
    pos: "noun",
    kidMeaning: "Furniture you sit on.",
    examples: ["Sit on the chair.", "She moves the chair."],
    emoji: "🪑",
    syllables: "chair",
    distractorGroup: "furniture",
  },
  {
    word: "bed",
    pos: "noun",
    kidMeaning: "Furniture for sleeping.",
    examples: ["She sleeps in a bed.", "He makes his bed every morning."],
    emoji: "🛏️",
    syllables: "bed",
    distractorGroup: "furniture",
  },
  {
    word: "door",
    pos: "noun",
    kidMeaning: "The way to enter or leave a room.",
    examples: ["Open the door.", "She closes the door."],
    emoji: "🚪",
    syllables: "door",
    distractorGroup: "part",
  },
  {
    word: "window",
    pos: "noun",
    kidMeaning: "An opening to see outside.",
    examples: ["She looks out the window.", "The window is clean."],
    emoji: "🪟",
    syllables: "win-dow",
    distractorGroup: "part",
  },
  {
    word: "big",
    pos: "adjective",
    kidMeaning: "Very large in size.",
    examples: ["He has a big house.", "The elephant is big."],
    emoji: "🐘",
    syllables: "big",
    distractorGroup: "size",
  },
  {
    word: "small",
    pos: "adjective",
    kidMeaning: "Not large, little.",
    examples: ["She has a small toy.", "The mouse is small."],
    emoji: "🐭",
    syllables: "small",
    distractorGroup: "size",
  },
  {
    word: "good",
    pos: "adjective",
    kidMeaning: "Nice or right.",
    examples: ["That is a good idea.", "She is a good student."],
    emoji: "👍",
    syllables: "good",
    distractorGroup: "quality",
  },
  {
    word: "bad",
    pos: "adjective",
    kidMeaning: "Not good or wrong.",
    examples: ["That is a bad idea.", "He has a bad cold."],
    emoji: "👎",
    syllables: "bad",
    distractorGroup: "quality",
  },
  {
    word: "hot",
    pos: "adjective",
    kidMeaning: "Having high temperature.",
    examples: ["The water is hot.", "It is a hot day."],
    emoji: "🔥",
    syllables: "hot",
    distractorGroup: "temperature",
  },
  {
    word: "cold",
    pos: "adjective",
    kidMeaning: "Having low temperature.",
    examples: ["The ice is cold.", "It is a cold day."],
    emoji: "❄️",
    syllables: "cold",
    distractorGroup: "temperature",
  },
  {
    word: "wet",
    pos: "adjective",
    kidMeaning: "Covered with water.",
    examples: ["Her clothes are wet.", "The ground is wet."],
    emoji: "💧",
    syllables: "wet",
    distractorGroup: "state",
  },
  {
    word: "dry",
    pos: "adjective",
    kidMeaning: "Not wet.",
    examples: ["The clothes are dry.", "The ground is dry."],
    emoji: "🏜️",
    syllables: "dry",
    distractorGroup: "state",
  },
  {
    word: "clean",
    pos: "adjective",
    kidMeaning: "Free from dirt.",
    examples: ["She has clean hands.", "The room is clean."],
    emoji: "✨",
    syllables: "clean",
    distractorGroup: "state",
  },
  {
    word: "dirty",
    pos: "adjective",
    kidMeaning: "Covered with dirt.",
    examples: ["His clothes are dirty.", "The floor is dirty."],
    emoji: "🤎",
    syllables: "dirt-y",
    distractorGroup: "state",
  },
  {
    word: "new",
    pos: "adjective",
    kidMeaning: "Recently made or bought.",
    examples: ["She has a new bike.", "The car is new."],
    emoji: "✨",
    syllables: "new",
    distractorGroup: "age",
  },
  {
    word: "old",
    pos: "adjective",
    kidMeaning: "Not new, ancient.",
    examples: ["He has an old book.", "The house is old."],
    emoji: "📚",
    syllables: "old",
    distractorGroup: "age",
  },
  {
    word: "long",
    pos: "adjective",
    kidMeaning: "Covering great distance.",
    examples: ["She has long hair.", "The road is long."],
    emoji: "📏",
    syllables: "long",
    distractorGroup: "size",
  },
  {
    word: "short",
    pos: "adjective",
    kidMeaning: "Not long or tall.",
    examples: ["He has short hair.", "The pencil is short."],
    emoji: "📏",
    syllables: "short",
    distractorGroup: "size",
  },
  {
    word: "fast",
    pos: "adjective",
    kidMeaning: "Moving quickly.",
    examples: ["She is fast at running.", "The car is fast."],
    emoji: "🏎️",
    syllables: "fast",
    distractorGroup: "speed",
  },
  {
    word: "slow",
    pos: "adjective",
    kidMeaning: "Not fast.",
    examples: ["He is slow at walking.", "The turtle is slow."],
    emoji: "🐢",
    syllables: "slow",
    distractorGroup: "speed",
  },
  {
    word: "happy",
    pos: "adjective",
    kidMeaning: "Feeling joy.",
    examples: ["She is happy.", "He looks happy."],
    emoji: "😊",
    syllables: "hap-py",
    distractorGroup: "emotion",
  },
  {
    word: "sad",
    pos: "adjective",
    kidMeaning: "Feeling unhappy.",
    examples: ["She is sad.", "He looks sad."],
    emoji: "😢",
    syllables: "sad",
    distractorGroup: "emotion",
  },
  {
    word: "angry",
    pos: "adjective",
    kidMeaning: "Very displeased.",
    examples: ["He is angry.", "She sounds angry."],
    emoji: "😠",
    syllables: "an-gry",
    distractorGroup: "emotion",
  },
  {
    word: "sick",
    pos: "adjective",
    kidMeaning: "Unwell or ill.",
    examples: ["She is sick.", "He feels sick."],
    emoji: "🤒",
    syllables: "sick",
    distractorGroup: "health",
  },
  {
    word: "strong",
    pos: "adjective",
    kidMeaning: "Having much power.",
    examples: ["He is strong.", "The wind is strong."],
    emoji: "💪",
    syllables: "strong",
    distractorGroup: "quality",
  },
  {
    word: "weak",
    pos: "adjective",
    kidMeaning: "Not strong.",
    examples: ["She is weak.", "The wind is weak."],
    emoji: "😩",
    syllables: "weak",
    distractorGroup: "quality",
  },
  {
    word: "beautiful",
    pos: "adjective",
    kidMeaning: "Pleasing to look at.",
    examples: ["She is beautiful.", "The flower is beautiful."],
    emoji: "🌹",
    syllables: "beau-ti-ful",
    distractorGroup: "appearance",
  },
  {
    word: "ugly",
    pos: "adjective",
    kidMeaning: "Not pleasing to look at.",
    examples: ["The monster is ugly.", "The building is ugly."],
    emoji: "👹",
    syllables: "ug-ly",
    distractorGroup: "appearance",
  },
  {
    word: "easy",
    pos: "adjective",
    kidMeaning: "Not difficult.",
    examples: ["The question is easy.", "It is easy to learn."],
    emoji: "✅",
    syllables: "eas-y",
    distractorGroup: "difficulty",
  },
  {
    word: "hard",
    pos: "adjective",
    kidMeaning: "Difficult.",
    examples: ["The question is hard.", "It is hard to learn."],
    emoji: "💪",
    syllables: "hard",
    distractorGroup: "difficulty",
  },
  {
    word: "soft",
    pos: "adjective",
    kidMeaning: "Not hard or rough.",
    examples: ["The pillow is soft.", "The blanket is soft."],
    emoji: "☁️",
    syllables: "soft",
    distractorGroup: "texture",
  },
  {
    word: "bright",
    pos: "adjective",
    kidMeaning: "Giving much light.",
    examples: ["The sun is bright.", "The room is bright."],
    emoji: "☀️",
    syllables: "bright",
    distractorGroup: "light",
  },
  {
    word: "dark",
    pos: "adjective",
    kidMeaning: "Without light.",
    examples: ["The night is dark.", "The room is dark."],
    emoji: "🌙",
    syllables: "dark",
    distractorGroup: "light",
  },
  {
    word: "only",
    pos: "adjective",
    kidMeaning: "One and no more.",
    examples: ["She has only one sister.", "There is only one apple."],
    emoji: "☝️",
    syllables: "on-ly",
    distractorGroup: "quantity",
  },
  {
    word: "other",
    pos: "adjective",
    kidMeaning: "Different one.",
    examples: ["Give me the other book.", "There are other ways."],
    emoji: "🔄",
    syllables: "oth-er",
    distractorGroup: "quantity",
  },
  {
    word: "same",
    pos: "adjective",
    kidMeaning: "Exactly alike.",
    examples: ["We wear the same colour.", "They go to the same school."],
    emoji: "🟰",
    syllables: "same",
    distractorGroup: "comparison",
  },
  {
    word: "different",
    pos: "adjective",
    kidMeaning: "Not the same.",
    examples: ["We wear different colours.", "They go to different schools."],
    emoji: "🔀",
    syllables: "dif-fer-ent",
    distractorGroup: "comparison",
  },
  {
    word: "today",
    pos: "adverb",
    kidMeaning: "On this day.",
    examples: ["She plays today.", "He works today."],
    emoji: "📆",
    syllables: "to-day",
    distractorGroup: "time",
  },
  {
    word: "here",
    pos: "adverb",
    kidMeaning: "In this place.",
    examples: ["Come here.", "She sits here."],
    emoji: "📍",
    syllables: "here",
    distractorGroup: "place",
  },
  {
    word: "there",
    pos: "adverb",
    kidMeaning: "In that place.",
    examples: ["Go there.", "She lives there."],
    emoji: "🎯",
    syllables: "there",
    distractorGroup: "place",
  },
  {
    word: "always",
    pos: "adverb",
    kidMeaning: "Every time without fail.",
    examples: ["She always comes early.", "He always helps."],
    emoji: "♾️",
    syllables: "al-ways",
    distractorGroup: "frequency",
  },
  {
    word: "never",
    pos: "adverb",
    kidMeaning: "Not at any time.",
    examples: ["She never tells lies.", "He never gets tired."],
    emoji: "🚫",
    syllables: "nev-er",
    distractorGroup: "frequency",
  },
  {
    word: "sometimes",
    pos: "adverb",
    kidMeaning: "Not always but now and then.",
    examples: ["She sometimes plays outside.", "He sometimes reads."],
    emoji: "🌗",
    syllables: "some-times",
    distractorGroup: "frequency",
  },
  {
    word: "often",
    pos: "adverb",
    kidMeaning: "Many times.",
    examples: ["She goes often.", "He plays often."],
    emoji: "🔄",
    syllables: "oft-en",
    distractorGroup: "frequency",
  },
  {
    word: "really",
    pos: "adverb",
    kidMeaning: "Very or truly.",
    examples: ["That is really good.", "She really likes it."],
    emoji: "✨",
    syllables: "real-ly",
    distractorGroup: "emphasis",
  },
  {
    word: "very",
    pos: "adverb",
    kidMeaning: "To a great degree.",
    examples: ["She is very happy.", "That is very good."],
    emoji: "💯",
    syllables: "ver-y",
    distractorGroup: "emphasis",
  },
  {
    word: "also",
    pos: "adverb",
    kidMeaning: "As well or too.",
    examples: ["She comes also.", "He plays also."],
    emoji: "➕",
    syllables: "al-so",
    distractorGroup: "addition",
  },
  {
    word: "just",
    pos: "adverb",
    kidMeaning: "Recently or only.",
    examples: ["She just left.", "He just has one."],
    emoji: "✨",
    syllables: "just",
    distractorGroup: "time",
  },
  {
    word: "already",
    pos: "adverb",
    kidMeaning: "Before now.",
    examples: ["She already finished.", "He already knows."],
    emoji: "✅",
    syllables: "al-read-y",
    distractorGroup: "time",
  },
  {
    word: "still",
    pos: "adverb",
    kidMeaning: "Even now or up to now.",
    examples: ["She still plays with dolls.", "He is still sleeping."],
    emoji: "🧍",
    syllables: "still",
    distractorGroup: "duration",
  },
  {
    word: "together",
    pos: "adverb",
    kidMeaning: "With or joined.",
    examples: ["They play together.", "They work together."],
    emoji: "🤝",
    syllables: "to-geth-er",
    distractorGroup: "company",
  },
  {
    word: "maybe",
    pos: "adverb",
    kidMeaning: "Perhaps or possibly.",
    examples: ["Maybe she comes.", "He says maybe."],
    emoji: "🤷",
    syllables: "may-be",
    distractorGroup: "possibility",
  },
  {
    word: "quite",
    pos: "adverb",
    kidMeaning: "Rather or fairly.",
    examples: ["That is quite good.", "She is quite tall."],
    emoji: "👍",
    syllables: "quite",
    distractorGroup: "degree",
  },
  {
    word: "almost",
    pos: "adverb",
    kidMeaning: "Nearly or not quite.",
    examples: ["She almost falls.", "It is almost time."],
    emoji: "🤏",
    syllables: "al-most",
    distractorGroup: "degree",
  },
  {
    word: "in",
    pos: "preposition",
    kidMeaning: "Inside a place.",
    examples: ["She sits in the room.", "The book is in the bag."],
    emoji: "📦",
    syllables: "in",
    distractorGroup: "location",
  },
  {
    word: "on",
    pos: "preposition",
    kidMeaning: "Above something touching it.",
    examples: ["She sits on the chair.", "The book is on the table."],
    emoji: "🪑",
    syllables: "on",
    distractorGroup: "location",
  },
  {
    word: "at",
    pos: "preposition",
    kidMeaning: "A specific place or time.",
    examples: ["She is at school.", "He arrives at six."],
    emoji: "📍",
    syllables: "at",
    distractorGroup: "location",
  },
  {
    word: "to",
    pos: "preposition",
    kidMeaning: "Towards a direction.",
    examples: ["She goes to school.", "He gives it to her."],
    emoji: "➡️",
    syllables: "to",
    distractorGroup: "direction",
  },
  {
    word: "from",
    pos: "preposition",
    kidMeaning: "Starting point or origin.",
    examples: ["She comes from home.", "The gift is from her."],
    emoji: "📤",
    syllables: "from",
    distractorGroup: "origin",
  },
  {
    word: "with",
    pos: "preposition",
    kidMeaning: "Together with someone.",
    examples: ["She plays with him.", "He eats with his family."],
    emoji: "🤝",
    syllables: "with",
    distractorGroup: "company",
  },
  {
    word: "for",
    pos: "preposition",
    kidMeaning: "Intended or because of.",
    examples: ["She studies for the test.", "She does it for fun."],
    emoji: "🎯",
    syllables: "for",
    distractorGroup: "purpose",
  },
  {
    word: "over",
    pos: "preposition",
    kidMeaning: "Above or across.",
    examples: ["She jumps over the rope.", "She walks over the bridge."],
    emoji: "🌉",
    syllables: "o-ver",
    distractorGroup: "position",
  },
  {
    word: "under",
    pos: "preposition",
    kidMeaning: "Below something.",
    examples: ["She sits under the tree.", "The pen is under the desk."],
    emoji: "🌳",
    syllables: "un-der",
    distractorGroup: "position",
  },
  {
    word: "between",
    pos: "preposition",
    kidMeaning: "In the middle of two things.",
    examples: ["She sits between them.", "The park is between the shops."],
    emoji: "🪑🤝🪑",
    syllables: "be-tween",
    distractorGroup: "position",
  },
  {
    word: "before",
    pos: "preposition",
    kidMeaning: "Earlier in time.",
    examples: ["She comes before him.", "Eat before bed."],
    emoji: "⏰",
    syllables: "be-fore",
    distractorGroup: "time",
  },
  {
    word: "after",
    pos: "preposition",
    kidMeaning: "Later in time.",
    examples: ["She comes after him.", "Play after school."],
    emoji: "⏰",
    syllables: "aft-er",
    distractorGroup: "time",
  },
  {
    word: "during",
    pos: "preposition",
    kidMeaning: "Throughout a period of time.",
    examples: ["She sleeps during the night.", "He plays during the day."],
    emoji: "⏰",
    syllables: "dur-ing",
    distractorGroup: "time",
  },
  {
    word: "through",
    pos: "preposition",
    kidMeaning: "From one side to the other.",
    examples: ["She walks through the forest.", "Light comes through the window."],
    emoji: "🪟",
    syllables: "through",
    distractorGroup: "direction",
  },
  {
    word: "across",
    pos: "preposition",
    kidMeaning: "From one side to the other.",
    examples: ["She walks across the road.", "He swims across the river."],
    emoji: "🌊",
    syllables: "a-cross",
    distractorGroup: "direction",
  },
  {
    word: "along",
    pos: "preposition",
    kidMeaning: "Following the length of.",
    examples: ["She walks along the road.", "He sits along the wall."],
    emoji: "🛣️",
    syllables: "a-long",
    distractorGroup: "direction",
  },
  {
    word: "behind",
    pos: "preposition",
    kidMeaning: "At the back of.",
    examples: ["She sits behind him.", "The door is behind the wall."],
    emoji: "🪵",
    syllables: "be-hind",
    distractorGroup: "position",
  },
  {
    word: "I",
    pos: "pronoun",
    kidMeaning: "The speaker or writer.",
    examples: ["I go to school.", "I like apples."],
    emoji: "👇",
    syllables: "I",
    distractorGroup: "personal",
  },
  {
    word: "you",
    pos: "pronoun",
    kidMeaning: "The person being spoken to.",
    examples: ["You go to school.", "You like apples."],
    emoji: "👉",
    syllables: "you",
    distractorGroup: "personal",
  },
  {
    word: "he",
    pos: "pronoun",
    kidMeaning: "A male person or animal.",
    examples: ["He goes to school.", "He likes apples."],
    emoji: "👨",
    syllables: "he",
    distractorGroup: "personal",
  },
  {
    word: "she",
    pos: "pronoun",
    kidMeaning: "A female person or animal.",
    examples: ["She goes to school.", "She likes apples."],
    emoji: "👩",
    syllables: "she",
    distractorGroup: "personal",
  },
  {
    word: "it",
    pos: "pronoun",
    kidMeaning: "A thing or animal.",
    examples: ["It runs fast.", "It looks nice."],
    emoji: "📦",
    syllables: "it",
    distractorGroup: "personal",
  },
  {
    word: "we",
    pos: "pronoun",
    kidMeaning: "The speaker and other people.",
    examples: ["We go to school.", "We like apples."],
    emoji: "👥",
    syllables: "we",
    distractorGroup: "personal",
  },
  {
    word: "they",
    pos: "pronoun",
    kidMeaning: "More than one person or thing.",
    examples: ["They go to school.", "They like apples."],
    emoji: "👥",
    syllables: "they",
    distractorGroup: "personal",
  },
  {
    word: "me",
    pos: "pronoun",
    kidMeaning: "The speaker (object form).",
    examples: ["Give it to me.", "She helps me."],
    emoji: "👇",
    syllables: "me",
    distractorGroup: "personal",
  },
  {
    word: "him",
    pos: "pronoun",
    kidMeaning: "A male person (object form).",
    examples: ["Give it to him.", "She helps him."],
    emoji: "👨",
    syllables: "him",
    distractorGroup: "personal",
  },
  {
    word: "her",
    pos: "pronoun",
    kidMeaning: "A female person (object form).",
    examples: ["Give it to her.", "He helps her."],
    emoji: "👩",
    syllables: "her",
    distractorGroup: "personal",
  },
  {
    word: "us",
    pos: "pronoun",
    kidMeaning: "The speaker and others (object form).",
    examples: ["Give it to us.", "They help us."],
    emoji: "👥",
    syllables: "us",
    distractorGroup: "personal",
  },
  {
    word: "them",
    pos: "pronoun",
    kidMeaning: "More than one person (object form).",
    examples: ["Give it to them.", "He helps them."],
    emoji: "👥",
    syllables: "them",
    distractorGroup: "personal",
  },
  {
    word: "my",
    pos: "pronoun",
    kidMeaning: "Belonging to me.",
    examples: ["That is my book.", "My house is big."],
    emoji: "👇",
    syllables: "my",
    distractorGroup: "possessive",
  },
  {
    word: "your",
    pos: "pronoun",
    kidMeaning: "Belonging to you.",
    examples: ["That is your book.", "Your house is big."],
    emoji: "👉",
    syllables: "your",
    distractorGroup: "possessive",
  },
  {
    word: "his",
    pos: "pronoun",
    kidMeaning: "Belonging to a male.",
    examples: ["That is his book.", "His house is big."],
    emoji: "👨",
    syllables: "his",
    distractorGroup: "possessive",
  },
  {
    word: "our",
    pos: "pronoun",
    kidMeaning: "Belonging to us.",
    examples: ["That is our book.", "Our house is big."],
    emoji: "👥",
    syllables: "our",
    distractorGroup: "possessive",
  },
  {
    word: "their",
    pos: "pronoun",
    kidMeaning: "Belonging to them.",
    examples: ["That is their book.", "Their house is big."],
    emoji: "👥",
    syllables: "their",
    distractorGroup: "possessive",
  },
  {
    word: "this",
    pos: "pronoun",
    kidMeaning: "A thing that is near or close.",
    examples: ["This is mine.", "This is a book."],
    emoji: "👆",
    syllables: "this",
    distractorGroup: "demonstrative",
  },
  {
    word: "that",
    pos: "pronoun",
    kidMeaning: "A thing that is far.",
    examples: ["That is mine.", "That is a book."],
    emoji: "👉",
    syllables: "that",
    distractorGroup: "demonstrative",
  },
  {
    word: "these",
    pos: "pronoun",
    kidMeaning: "More than one thing that is near.",
    examples: ["These are mine.", "These are books."],
    emoji: "👆",
    syllables: "these",
    distractorGroup: "demonstrative",
  },
  {
    word: "those",
    pos: "pronoun",
    kidMeaning: "More than one thing that is far.",
    examples: ["Those are mine.", "Those are books."],
    emoji: "👉",
    syllables: "those",
    distractorGroup: "demonstrative",
  },
  {
    word: "what",
    pos: "pronoun",
    kidMeaning: "What thing.",
    examples: ["What is that?", "She asks what."],
    emoji: "❓",
    syllables: "what",
    distractorGroup: "question",
  },
  {
    word: "who",
    pos: "pronoun",
    kidMeaning: "What person.",
    examples: ["Who is that?", "She asks who."],
    emoji: "🤷",
    syllables: "who",
    distractorGroup: "question",
  },
  {
    word: "which",
    pos: "pronoun",
    kidMeaning: "Which one of two or more.",
    examples: ["Which is yours?", "She asks which."],
    emoji: "❓",
    syllables: "which",
    distractorGroup: "question",
  },
  {
    word: "hand",
    pos: "noun",
    kidMeaning: "The part of your arm with fingers.",
    examples: ["She holds the ball in her hand.", "He raises his hand."],
    emoji: "✋",
    syllables: "hand",
    distractorGroup: "body",
  },
  {
    word: "head",
    pos: "noun",
    kidMeaning: "The top part of your body with brain.",
    examples: ["She touches her head.", "He nods his head."],
    emoji: "🧠",
    syllables: "head",
    distractorGroup: "body",
  },
  {
    word: "eye",
    pos: "noun",
    kidMeaning: "The part you see with.",
    examples: ["She has brown eyes.", "He closes his eye."],
    emoji: "👁️",
    syllables: "eye",
    distractorGroup: "body",
  },
  {
    word: "foot",
    pos: "noun",
    kidMeaning: "The part of your leg you walk on.",
    examples: ["She wears shoes on each foot.", "He hurts his foot."],
    emoji: "🦶",
    syllables: "foot",
    distractorGroup: "body",
  },
  {
    word: "mouth",
    pos: "noun",
    kidMeaning: "The part you eat and speak with.",
    examples: ["She opens her mouth.", "He covers his mouth."],
    emoji: "👄",
    syllables: "mouth",
    distractorGroup: "body",
  },
  {
    word: "nose",
    pos: "noun",
    kidMeaning: "The part you smell and breathe with.",
    examples: ["She touches her nose.", "He blows his nose."],
    emoji: "👃",
    syllables: "nose",
    distractorGroup: "body",
  },
  {
    word: "ear",
    pos: "noun",
    kidMeaning: "The part you hear with.",
    examples: ["She has big ears.", "He covers his ears."],
    emoji: "👂",
    syllables: "ear",
    distractorGroup: "body",
  },
  {
    word: "arm",
    pos: "noun",
    kidMeaning: "The part from shoulder to hand.",
    examples: ["She raises her arm.", "He hurts his arm."],
    emoji: "💪",
    syllables: "arm",
    distractorGroup: "body",
  },
  {
    word: "leg",
    pos: "noun",
    kidMeaning: "The part you walk with.",
    examples: ["She kicks with her leg.", "He has strong legs."],
    emoji: "🦵",
    syllables: "leg",
    distractorGroup: "body",
  },
  {
    word: "hair",
    pos: "noun",
    kidMeaning: "The strands that grow on your head.",
    examples: ["She has long hair.", "He combs his hair."],
    emoji: "💇",
    syllables: "hair",
    distractorGroup: "body",
  },
  {
    word: "tooth",
    pos: "noun",
    kidMeaning: "One of the hard parts in your mouth.",
    examples: ["She has a missing tooth.", "He brushes every tooth daily."],
    emoji: "🦷",
    syllables: "tooth",
    distractorGroup: "body",
  },
  {
    word: "heart",
    pos: "noun",
    kidMeaning: "The organ that pumps blood.",
    examples: ["She has a kind heart.", "He loves with his heart."],
    emoji: "❤️",
    syllables: "heart",
    distractorGroup: "body",
  },
  {
    word: "fruit",
    pos: "noun",
    kidMeaning: "Sweet food that grows on trees.",
    examples: ["She eats fruit every day.", "The fruit is fresh."],
    emoji: "🍎",
    syllables: "fruit",
    distractorGroup: "food",
  },
  {
    word: "vegetable",
    pos: "noun",
    kidMeaning: "A plant part you eat.",
    examples: ["He likes green vegetables.", "She eats vegetables."],
    emoji: "🥬",
    syllables: "veg-e-ta-ble",
    distractorGroup: "food",
  },
  {
    word: "cheese",
    pos: "noun",
    kidMeaning: "Solid food made from milk.",
    examples: ["She likes cheese.", "The cheese is yellow."],
    emoji: "🧀",
    syllables: "cheese",
    distractorGroup: "food",
  },
  {
    word: "chicken",
    pos: "noun",
    kidMeaning: "A bird that gives eggs and meat.",
    examples: ["She sees a chicken on the farm.", "The chicken lays eggs."],
    emoji: "🐔",
    syllables: "chick-en",
    distractorGroup: "animal",
  },
  {
    word: "fish",
    pos: "noun",
    kidMeaning: "An animal that lives in water.",
    examples: ["She sees fish in the river.", "The fish swims fast."],
    emoji: "🐠",
    syllables: "fish",
    distractorGroup: "animal",
  },
  {
    word: "lion",
    pos: "noun",
    kidMeaning: "A large wild cat that roars.",
    examples: ["She sees a lion at the zoo.", "The lion is very big."],
    emoji: "🦁",
    syllables: "li-on",
    distractorGroup: "animal",
  },
  {
    word: "elephant",
    pos: "noun",
    kidMeaning: "A very large animal with a trunk.",
    examples: ["She sees an elephant at the zoo.", "The elephant is grey."],
    emoji: "🐘",
    syllables: "el-e-phant",
    distractorGroup: "animal",
  },
  {
    word: "tiger",
    pos: "noun",
    kidMeaning: "A large wild cat with stripes.",
    examples: ["She sees a tiger at the zoo.", "The tiger is orange."],
    emoji: "🐯",
    syllables: "ti-ger",
    distractorGroup: "animal",
  },
  {
    word: "monkey",
    pos: "noun",
    kidMeaning: "An animal that climbs and eats fruit.",
    examples: ["She sees a monkey at the zoo.", "The monkey eats bananas."],
    emoji: "🐵",
    syllables: "mon-key",
    distractorGroup: "animal",
  },
  {
    word: "bear",
    pos: "noun",
    kidMeaning: "A large wild animal covered in fur.",
    examples: ["She sees a bear in the forest.", "The bear is brown."],
    emoji: "🐻",
    syllables: "bear",
    distractorGroup: "animal",
  },
  {
    word: "mouse",
    pos: "noun",
    kidMeaning: "A very small animal with a long tail.",
    examples: ["She sees a mouse in the house.", "The mouse is grey."],
    emoji: "🐭",
    syllables: "mouse",
    distractorGroup: "animal",
  },
  {
    word: "rabbit",
    pos: "noun",
    kidMeaning: "A small animal with long ears.",
    examples: ["She has a rabbit as a pet.", "The rabbit is white."],
    emoji: "🐰",
    syllables: "rab-bit",
    distractorGroup: "animal",
  },
  {
    word: "snake",
    pos: "noun",
    kidMeaning: "A long animal with no legs.",
    examples: ["She sees a snake in the garden.", "The snake is green."],
    emoji: "🐍",
    syllables: "snake",
    distractorGroup: "animal",
  },
  {
    word: "garden",
    pos: "noun",
    kidMeaning: "A place where plants grow.",
    examples: ["She works in the garden.", "His garden has many flowers."],
    emoji: "🌻",
    syllables: "gar-den",
    distractorGroup: "place",
  },
  {
    word: "mountain",
    pos: "noun",
    kidMeaning: "A very high hill.",
    examples: ["She climbs the mountain.", "The mountain is very tall."],
    emoji: "⛰️",
    syllables: "moun-tain",
    distractorGroup: "place",
  },
  {
    word: "river",
    pos: "noun",
    kidMeaning: "A large stream of flowing water.",
    examples: ["She swims in the river.", "The river is very wide."],
    emoji: "🌊",
    syllables: "riv-er",
    distractorGroup: "place",
  },
  {
    word: "beach",
    pos: "noun",
    kidMeaning: "The sandy edge of a sea.",
    examples: ["She builds sandcastles at the beach.", "He plays on the beach."],
    emoji: "🏖️",
    syllables: "beach",
    distractorGroup: "place",
  },
  {
    word: "desert",
    pos: "noun",
    kidMeaning: "A very dry place with little water.",
    examples: ["She travels in the desert.", "The desert is hot."],
    emoji: "🏜️",
    syllables: "des-ert",
    distractorGroup: "place",
  },
  {
    word: "forest",
    pos: "noun",
    kidMeaning: "A large area covered with trees.",
    examples: ["She walks in the forest.", "The forest is dark."],
    emoji: "🌲",
    syllables: "for-est",
    distractorGroup: "place",
  },
  {
    word: "lake",
    pos: "noun",
    kidMeaning: "A large body of freshwater.",
    examples: ["She swims in the lake.", "The lake is blue."],
    emoji: "💧",
    syllables: "lake",
    distractorGroup: "place",
  },
  {
    word: "cloud",
    pos: "noun",
    kidMeaning: "White fluffy shape in the sky.",
    examples: ["She looks at the clouds.", "The cloud is white."],
    emoji: "☁️",
    syllables: "cloud",
    distractorGroup: "weather",
  },
  {
    word: "wind",
    pos: "noun",
    kidMeaning: "Moving air.",
    examples: ["The wind is strong.", "She flies her kite in the wind."],
    emoji: "💨",
    syllables: "wind",
    distractorGroup: "weather",
  },
  {
    word: "shade",
    pos: "noun",
    kidMeaning: "A particular colour or darkness.",
    examples: ["The shade is dark blue.", "The shade is bright."],
    emoji: "🎨",
    syllables: "shade",
    distractorGroup: "property",
  },
  {
    word: "picture",
    pos: "noun",
    kidMeaning: "An image or drawing.",
    examples: ["She draws a picture.", "The picture is colourful."],
    emoji: "🖼️",
    syllables: "pic-ture",
    distractorGroup: "object",
  },
  {
    word: "letter",
    pos: "noun",
    kidMeaning: "A piece of paper with a message.",
    examples: ["She writes a letter.", "The letter arrives today."],
    emoji: "💌",
    syllables: "let-ter",
    distractorGroup: "object",
  },
  {
    word: "number",
    pos: "noun",
    kidMeaning: "A figure or digit.",
    examples: ["She learns numbers.", "The number is five."],
    emoji: "🔢",
    syllables: "num-ber",
    distractorGroup: "abstract",
  },
  {
    word: "song",
    pos: "noun",
    kidMeaning: "A short piece of music with words.",
    examples: ["She sings a song.", "The song is popular."],
    emoji: "🎤",
    syllables: "song",
    distractorGroup: "art",
  },
  {
    word: "music",
    pos: "noun",
    kidMeaning: "Organised sounds that people enjoy.",
    examples: ["She likes music.", "The music is beautiful."],
    emoji: "🎵",
    syllables: "mus-ic",
    distractorGroup: "art",
  },
  {
    word: "performance",
    pos: "noun",
    kidMeaning: "An act of dancing or singing.",
    examples: ["She does a performance.", "The performance is beautiful."],
    emoji: "💃",
    syllables: "per-for-mance",
    distractorGroup: "art",
  },
  {
    word: "sport",
    pos: "noun",
    kidMeaning: "An activity for exercise and fun.",
    examples: ["Football is a popular sport.", "She plays three sports."],
    emoji: "⚽",
    syllables: "sport",
    distractorGroup: "activity",
  },
  {
    word: "prize",
    pos: "noun",
    kidMeaning: "Something given as a reward.",
    examples: ["She wins a prize.", "The prize is a book."],
    emoji: "🏆",
    syllables: "prize",
    distractorGroup: "reward",
  },
  {
    word: "gift",
    pos: "noun",
    kidMeaning: "Something given to show love.",
    examples: ["She gets a gift for her birthday.", "He opens his gift."],
    emoji: "🎁",
    syllables: "gift",
    distractorGroup: "object",
  },
  {
    word: "sound",
    pos: "noun",
    kidMeaning: "Something you hear.",
    examples: ["She hears a loud sound.", "The sound is pleasant."],
    emoji: "🔊",
    syllables: "sound",
    distractorGroup: "property",
  },
  {
    word: "taste",
    pos: "noun",
    kidMeaning: "The flavour of something.",
    examples: ["She likes the taste.", "The taste is sweet."],
    emoji: "👅",
    syllables: "taste",
    distractorGroup: "sense",
  },
  {
    word: "smell",
    pos: "noun",
    kidMeaning: "An odour or scent.",
    examples: ["She smells a flower.", "The smell is nice."],
    emoji: "👃",
    syllables: "smell",
    distractorGroup: "sense",
  },
  {
    word: "touch",
    pos: "noun",
    kidMeaning: "The feeling when something is touched.",
    examples: ["The touch is soft.", "She feels the soft touch."],
    emoji: "👆",
    syllables: "touch",
    distractorGroup: "sense",
  },
  {
    word: "pain",
    pos: "noun",
    kidMeaning: "A bad feeling from hurt.",
    examples: ["She has a pain in her head.", "He feels pain."],
    emoji: "😣",
    syllables: "pain",
    distractorGroup: "feeling",
  },
  {
    word: "joy",
    pos: "noun",
    kidMeaning: "A feeling of great happiness.",
    examples: ["She feels joy.", "The joy is great."],
    emoji: "😄",
    syllables: "joy",
    distractorGroup: "feeling",
  },
  {
    word: "fear",
    pos: "noun",
    kidMeaning: "A feeling of being scared.",
    examples: ["She has no fear.", "He feels fear."],
    emoji: "😨",
    syllables: "fear",
    distractorGroup: "feeling",
  },
  {
    word: "love",
    pos: "noun",
    kidMeaning: "A strong feeling of care and affection.",
    examples: ["She has love for her family.", "He shows love."],
    emoji: "❤️",
    syllables: "love",
    distractorGroup: "feeling",
  },
  {
    word: "anger",
    pos: "noun",
    kidMeaning: "A feeling of being very displeased.",
    examples: ["She has anger.", "He shows anger."],
    emoji: "😠",
    syllables: "an-ger",
    distractorGroup: "feeling",
  },
  {
    word: "size",
    pos: "noun",
    kidMeaning: "How big or small something is.",
    examples: ["What size are your shoes?", "The size is too small."],
    emoji: "📏",
    syllables: "size",
    distractorGroup: "property",
  },
  {
    word: "shape",
    pos: "noun",
    kidMeaning: "The outline or form of something.",
    examples: ["The shape is round.", "She draws a square shape."],
    emoji: "⬜",
    syllables: "shape",
    distractorGroup: "property",
  },
  {
    word: "weight",
    pos: "noun",
    kidMeaning: "How heavy something is.",
    examples: ["She measures the weight.", "The weight is light."],
    emoji: "⚖️",
    syllables: "weight",
    distractorGroup: "property",
  },
  {
    word: "width",
    pos: "noun",
    kidMeaning: "How wide something is.",
    examples: ["She measures the width.", "The width is small."],
    emoji: "↔️",
    syllables: "width",
    distractorGroup: "property",
  },
  {
    word: "length",
    pos: "noun",
    kidMeaning: "How long something is.",
    examples: ["She measures the length.", "The length is great."],
    emoji: "↕️",
    syllables: "length",
    distractorGroup: "property",
  },
  {
    word: "depth",
    pos: "noun",
    kidMeaning: "How deep something is.",
    examples: ["She measures the depth.", "The depth is great."],
    emoji: "⬇️",
    syllables: "depth",
    distractorGroup: "property",
  },
  {
    word: "speed",
    pos: "noun",
    kidMeaning: "How fast something moves.",
    examples: ["She runs with great speed.", "The speed is high."],
    emoji: "⚡",
    syllables: "speed",
    distractorGroup: "property",
  },
  {
    word: "strength",
    pos: "noun",
    kidMeaning: "How strong something or someone is.",
    examples: ["She has great strength.", "He shows strength."],
    emoji: "💪",
    syllables: "strength",
    distractorGroup: "property",
  },
  {
    word: "reason",
    pos: "noun",
    kidMeaning: "Why something happens.",
    examples: ["She asks the reason.", "The reason is clear."],
    emoji: "🤔",
    syllables: "rea-son",
    distractorGroup: "abstract",
  },
  {
    word: "idea",
    pos: "noun",
    kidMeaning: "A thought or suggestion.",
    examples: ["She has a good idea.", "The idea is interesting."],
    emoji: "💡",
    syllables: "i-de-a",
    distractorGroup: "abstract",
  },
  {
    word: "truth",
    pos: "noun",
    kidMeaning: "What is real and not false.",
    examples: ["She tells the truth.", "The truth is important."],
    emoji: "✔️",
    syllables: "truth",
    distractorGroup: "abstract",
  },
  {
    word: "mistake",
    pos: "noun",
    kidMeaning: "An error or something done wrong.",
    examples: ["She makes a mistake.", "The mistake is small."],
    emoji: "❌",
    syllables: "mis-take",
    distractorGroup: "abstract",
  },
  {
    word: "failure",
    pos: "noun",
    kidMeaning: "Not achieving a goal.",
    examples: ["She learns from failure.", "The failure is disappointing."],
    emoji: "😞",
    syllables: "fail-ure",
    distractorGroup: "abstract",
  },
  {
    word: "change",
    pos: "noun",
    kidMeaning: "To become different.",
    examples: ["She sees a change.", "The change is good."],
    emoji: "🔄",
    syllables: "change",
    distractorGroup: "abstract",
  },
  {
    word: "beginning",
    pos: "noun",
    kidMeaning: "The start of something.",
    examples: ["She is at the beginning.", "The beginning is exciting."],
    emoji: "▶️",
    syllables: "be-gin-ning",
    distractorGroup: "time",
  },
  {
    word: "end",
    pos: "noun",
    kidMeaning: "The last part of something.",
    examples: ["She reaches the end.", "The end is happy."],
    emoji: "⏹️",
    syllables: "end",
    distractorGroup: "time",
  },
  {
    word: "middle",
    pos: "noun",
    kidMeaning: "The centre or halfway point.",
    examples: ["She sits in the middle.", "The middle is safe."],
    emoji: "🎯",
    syllables: "mid-dle",
    distractorGroup: "position",
  },
  {
    word: "top",
    pos: "noun",
    kidMeaning: "The highest point.",
    examples: ["She stands at the top.", "The top is high."],
    emoji: "⬆️",
    syllables: "top",
    distractorGroup: "position",
  },
  {
    word: "bottom",
    pos: "noun",
    kidMeaning: "The lowest point.",
    examples: ["She sits at the bottom.", "The bottom is low."],
    emoji: "⬇️",
    syllables: "bot-tom",
    distractorGroup: "position",
  },
  {
    word: "side",
    pos: "noun",
    kidMeaning: "An edge or surface.",
    examples: ["She stands on the side.", "The side is flat."],
    emoji: "◀️",
    syllables: "side",
    distractorGroup: "position",
  },
  {
    word: "corner",
    pos: "noun",
    kidMeaning: "Where two edges meet.",
    examples: ["She sits in the corner.", "The corner is sharp."],
    emoji: "📐",
    syllables: "cor-ner",
    distractorGroup: "position",
  },
  {
    word: "edge",
    pos: "noun",
    kidMeaning: "The border of something.",
    examples: ["She stands at the edge.", "The edge is sharp."],
    emoji: "⚔️",
    syllables: "edge",
    distractorGroup: "position",
  },
  {
    word: "path",
    pos: "noun",
    kidMeaning: "A way or route.",
    examples: ["She follows the path.", "The path is clear."],
    emoji: "🛤️",
    syllables: "path",
    distractorGroup: "location",
  },
  {
    word: "road",
    pos: "noun",
    kidMeaning: "A way for cars to travel.",
    examples: ["She crosses the road.", "The road is busy."],
    emoji: "🛣️",
    syllables: "road",
    distractorGroup: "location",
  },
  {
    word: "bridge",
    pos: "noun",
    kidMeaning: "A structure over water or gap.",
    examples: ["She walks over the bridge.", "The bridge is strong."],
    emoji: "🌉",
    syllables: "bridge",
    distractorGroup: "structure",
  },
  {
    word: "building",
    pos: "noun",
    kidMeaning: "A structure with walls and roof.",
    examples: ["She enters the building.", "The building is tall."],
    emoji: "🏢",
    syllables: "build-ing",
    distractorGroup: "structure",
  },
  {
    word: "wall",
    pos: "noun",
    kidMeaning: "A vertical surface.",
    examples: ["She leans on the wall.", "The wall is thick."],
    emoji: "🧱",
    syllables: "wall",
    distractorGroup: "structure",
  },
  {
    word: "floor",
    pos: "noun",
    kidMeaning: "The ground inside a building.",
    examples: ["She sits on the floor.", "The floor is clean."],
    emoji: "🪵",
    syllables: "floor",
    distractorGroup: "structure",
  },
  {
    word: "roof",
    pos: "noun",
    kidMeaning: "The top part of a building.",
    examples: ["She looks at the roof.", "The roof is red."],
    emoji: "🏠",
    syllables: "roof",
    distractorGroup: "structure",
  },
  {
    word: "step",
    pos: "noun",
    kidMeaning: "A stair or movement forward.",
    examples: ["She climbs the step.", "The step is high."],
    emoji: "👣",
    syllables: "step",
    distractorGroup: "structure",
  },
  {
    word: "hole",
    pos: "noun",
    kidMeaning: "An opening in something.",
    examples: ["She finds a hole.", "The hole is deep."],
    emoji: "⚫",
    syllables: "hole",
    distractorGroup: "opening",
  },
  {
    word: "entrance",
    pos: "noun",
    kidMeaning: "The way to enter a place.",
    examples: ["She opens the entrance.", "The entrance is closed."],
    emoji: "🚪",
    syllables: "en-trance",
    distractorGroup: "opening",
  },
  {
    word: "gate",
    pos: "noun",
    kidMeaning: "An opening in a fence.",
    examples: ["She goes through the gate.", "The gate is open."],
    emoji: "🚪",
    syllables: "gate",
    distractorGroup: "opening",
  },
  {
    word: "key",
    pos: "noun",
    kidMeaning: "A tool that opens a lock.",
    examples: ["She uses the key.", "The key is small."],
    emoji: "🔑",
    syllables: "key",
    distractorGroup: "object",
  },
  {
    word: "lock",
    pos: "noun",
    kidMeaning: "A device that keeps things closed.",
    examples: ["She opens the lock.", "The lock is strong."],
    emoji: "🔒",
    syllables: "lock",
    distractorGroup: "object",
  },
  {
    word: "rope",
    pos: "noun",
    kidMeaning: "A thick cord.",
    examples: ["She pulls the rope.", "The rope is strong."],
    emoji: "🪢",
    syllables: "rope",
    distractorGroup: "object",
  },
  {
    word: "chain",
    pos: "noun",
    kidMeaning: "Connected rings of metal.",
    examples: ["She holds the chain.", "The chain is long."],
    emoji: "⛓️",
    syllables: "chain",
    distractorGroup: "object",
  },
  {
    word: "cord",
    pos: "noun",
    kidMeaning: "A thick string or thin rope.",
    examples: ["She climbs the cord.", "The cord is strong."],
    emoji: "🪢",
    syllables: "cord",
    distractorGroup: "object",
  },
  {
    word: "stick",
    pos: "noun",
    kidMeaning: "A thin piece of wood.",
    examples: ["He finds a stick.", "The stick is thin."],
    emoji: "🌳",
    syllables: "stick",
    distractorGroup: "object",
  },
  {
    word: "stone",
    pos: "noun",
    kidMeaning: "A hard rock.",
    examples: ["She throws a stone.", "The stone is hard."],
    emoji: "🪨",
    syllables: "stone",
    distractorGroup: "object",
  },
  {
    word: "glass",
    pos: "noun",
    kidMeaning: "A clear hard material.",
    examples: ["She drinks from glass.", "The glass is transparent."],
    emoji: "🥤",
    syllables: "glass",
    distractorGroup: "material",
  },
  {
    word: "metal",
    pos: "noun",
    kidMeaning: "A strong hard material.",
    examples: ["She touches the metal.", "The metal is cold."],
    emoji: "🔩",
    syllables: "met-al",
    distractorGroup: "material",
  },
  {
    word: "wood",
    pos: "noun",
    kidMeaning: "Material from trees.",
    examples: ["She cuts the wood.", "The wood is hard."],
    emoji: "🪵",
    syllables: "wood",
    distractorGroup: "material",
  },
  {
    word: "plastic",
    pos: "noun",
    kidMeaning: "A soft man-made material.",
    examples: ["She uses plastic.", "The plastic is light."],
    emoji: "♻️",
    syllables: "plas-tic",
    distractorGroup: "material",
  },
  {
    word: "fabric",
    pos: "noun",
    kidMeaning: "A woven material for clothes.",
    examples: ["She sews the fabric.", "The fabric is soft."],
    emoji: "👗",
    syllables: "fab-ric",
    distractorGroup: "material",
  },
  {
    word: "leather",
    pos: "noun",
    kidMeaning: "Material made from animal skin.",
    examples: ["She wears leather.", "The leather is soft."],
    emoji: "👠",
    syllables: "leath-er",
    distractorGroup: "material",
  },
  {
    word: "silk",
    pos: "noun",
    kidMeaning: "A soft smooth material.",
    examples: ["She wears silk.", "The silk is soft."],
    emoji: "✨",
    syllables: "silk",
    distractorGroup: "material",
  },
  {
    word: "cotton",
    pos: "noun",
    kidMeaning: "A soft white material.",
    examples: ["She wears cotton.", "The cotton is soft."],
    emoji: "🌾",
    syllables: "cot-ton",
    distractorGroup: "material",
  },
  {
    word: "rubber",
    pos: "noun",
    kidMeaning: "A stretchy material.",
    examples: ["She uses rubber.", "The rubber is stretchy."],
    emoji: "🛞",
    syllables: "rub-ber",
    distractorGroup: "material",
  },
  {
    word: "oil",
    pos: "noun",
    kidMeaning: "A slippery liquid.",
    examples: ["She pours oil.", "The oil is thick."],
    emoji: "💧",
    syllables: "oil",
    distractorGroup: "substance",
  },
  {
    word: "dirt",
    pos: "noun",
    kidMeaning: "Soil or earth.",
    examples: ["She plays in the dirt.", "The dirt is brown."],
    emoji: "🤎",
    syllables: "dirt",
    distractorGroup: "substance",
  },
  {
    word: "mud",
    pos: "noun",
    kidMeaning: "Wet dirt.",
    examples: ["She plays in the mud.", "The mud is wet."],
    emoji: "💨",
    syllables: "mud",
    distractorGroup: "substance",
  },
  {
    word: "salt",
    pos: "noun",
    kidMeaning: "A white substance that makes things salty.",
    examples: ["She uses salt.", "The salt is white."],
    emoji: "🧂",
    syllables: "salt",
    distractorGroup: "substance",
  },
];
