import type { Word } from "../words";

// Band 4: general mid-frequency words (verbs, adjectives, nouns, linking adverbs)
// for a weak Primary 4 reader — words a strong Primary 5 pupil would already know.
export const band4: Word[] = [
  // ---- Verbs ----
  {
    word: "avoid",
    pos: "verb",
    kidMeaning: "Stay away from something you do not want.",
    examples: ["She tries to avoid the puddles on the path.", "He avoids eating too much sugar."],
    emoji: "🚫",
    syllables: "a-void",
    distractorGroup: "actions",
  },
  {
    word: "continue",
    pos: "verb",
    kidMeaning: "Keep doing something without stopping.",
    examples: ["They continue walking after the rain stops.", "She continues to read her book."],
    emoji: "▶️",
    syllables: "con-tin-ue",
    distractorGroup: "actions",
  },
  {
    word: "describe",
    pos: "verb",
    kidMeaning: "Tell what something is like in words.",
    examples: ["He describes his new puppy to his friend.", "Can you describe the picture for me?"],
    emoji: "🗣️",
    syllables: "de-scribe",
    distractorGroup: "actions",
  },
  {
    word: "include",
    pos: "verb",
    kidMeaning: "Have something as one part of a group.",
    examples: ["The price includes breakfast and lunch.", "Please include your name on the form."],
    emoji: "➕",
    syllables: "in-clude",
    distractorGroup: "actions",
  },
  {
    word: "mention",
    pos: "verb",
    kidMeaning: "Say something briefly without explaining much.",
    examples: ["She mentions the trip during dinner.", "He forgot to mention the meeting time."],
    emoji: "💬",
    syllables: "men-tion",
    distractorGroup: "actions",
  },
  {
    word: "prefer",
    pos: "verb",
    kidMeaning: "Like one thing more than another thing.",
    examples: ["I prefer tea to coffee in the morning.", "She prefers the blue dress to the red one."],
    emoji: "👍",
    syllables: "pre-fer",
    distractorGroup: "actions",
  },
  {
    word: "protect",
    pos: "verb",
    kidMeaning: "Keep someone or something safe from harm.",
    examples: ["A helmet protects your head when cycling.", "Parents protect their children from danger."],
    emoji: "🛡️",
    syllables: "pro-tect",
    distractorGroup: "actions",
  },
  {
    word: "reduce",
    pos: "verb",
    kidMeaning: "Make something smaller or less in amount.",
    examples: ["We should reduce the amount of rubbish we throw.", "The shop reduces its prices every June."],
    emoji: "📉",
    syllables: "re-duce",
    distractorGroup: "actions",
  },
  {
    word: "repeat",
    pos: "verb",
    kidMeaning: "Say or do something again.",
    examples: ["Please repeat the question, I did not hear it.", "He repeats the word until he learns it."],
    emoji: "🔁",
    syllables: "re-peat",
    distractorGroup: "actions",
  },
  {
    word: "replace",
    pos: "verb",
    kidMeaning: "Put a new thing in place of an old one.",
    examples: ["We need to replace the broken window.", "She replaces the batteries in the torch."],
    emoji: "🔄",
    syllables: "re-place",
    distractorGroup: "actions",
  },
  {
    word: "require",
    pos: "verb",
    kidMeaning: "Need something to happen or to be there.",
    examples: ["This puzzle requires a lot of patience.", "The trip requires a warm coat."],
    emoji: "📋",
    syllables: "re-quire",
    distractorGroup: "actions",
  },
  {
    word: "suppose",
    pos: "verb",
    kidMeaning: "Think that something is probably true.",
    examples: ["I suppose it will rain later today.", "She supposes he is still at school."],
    emoji: "🤔",
    syllables: "sup-pose",
    distractorGroup: "actions",
  },
  {
    word: "add",
    pos: "verb",
    kidMeaning: "Put something together with other things.",
    examples: ["Add two eggs to the mixing bowl.", "She adds her name to the list."],
    emoji: "➕",
    syllables: "add",
    distractorGroup: "actions",
  },
  {
    word: "allow",
    pos: "verb",
    kidMeaning: "Say that someone is permitted to do something.",
    examples: ["Mum allows me to stay up a bit later.", "The teacher allows us to use pencils."],
    emoji: "✅",
    syllables: "al-low",
    distractorGroup: "actions",
  },
  {
    word: "appear",
    pos: "verb",
    kidMeaning: "Come into sight, or seem to be true.",
    examples: ["A rainbow appears after the rain.", "She appears sleepy after the long walk."],
    emoji: "👀",
    syllables: "ap-pear",
    distractorGroup: "actions",
  },
  {
    word: "attach",
    pos: "verb",
    kidMeaning: "Join or fix one thing to another thing.",
    examples: ["Please attach the photo to your email.", "He attaches a label to his bag."],
    emoji: "📎",
    syllables: "at-tach",
    distractorGroup: "actions",
  },
  {
    word: "attract",
    pos: "verb",
    kidMeaning: "Pull something towards you or make it interested.",
    examples: ["Bright flowers attract many bees and butterflies.", "The show attracts a big crowd."],
    emoji: "🧲",
    syllables: "at-tract",
    distractorGroup: "actions",
  },
  {
    word: "behave",
    pos: "verb",
    kidMeaning: "Act in a certain way, good or bad.",
    examples: ["The children behave well in the library.", "He behaves badly when he is sleepy."],
    emoji: "🙂",
    syllables: "be-have",
    distractorGroup: "actions",
  },
  {
    word: "belong",
    pos: "verb",
    kidMeaning: "Be owned by someone, or be part of a group.",
    examples: ["This bike belongs to my brother.", "She feels like she belongs in the team."],
    emoji: "🏠",
    syllables: "be-long",
    distractorGroup: "actions",
  },
  {
    word: "blame",
    pos: "verb",
    kidMeaning: "Say that someone caused something bad.",
    examples: ["Do not blame your sister for your mistake.", "He blames himself for losing the match."],
    emoji: "👉",
    syllables: "blame",
    distractorGroup: "actions",
  },
  {
    word: "bother",
    pos: "verb",
    kidMeaning: "Cause trouble or worry to someone.",
    examples: ["The loud noise bothers the baby.", "Please do not bother your sister while she studies."],
    emoji: "😣",
    syllables: "both-er",
    distractorGroup: "actions",
  },
  {
    word: "bury",
    pos: "verb",
    kidMeaning: "Put something under the ground or cover it up.",
    examples: ["The dog buries its bone in the garden.", "They bury the time capsule under the tree."],
    emoji: "⛏️",
    syllables: "bur-y",
    distractorGroup: "actions",
  },
  {
    word: "calculate",
    pos: "verb",
    kidMeaning: "Work out a number or amount using maths.",
    examples: ["She calculates the total cost of the trip.", "We calculate how many days are left."],
    emoji: "🔢",
    syllables: "cal-cu-late",
    distractorGroup: "actions",
  },
  {
    word: "capture",
    pos: "verb",
    kidMeaning: "Catch a person, animal or moment.",
    examples: ["The photo captures a happy family moment.", "Hunters try to capture the runaway goat."],
    emoji: "📸",
    syllables: "cap-ture",
    distractorGroup: "actions",
  },
  {
    word: "cause",
    pos: "verb",
    kidMeaning: "Make something happen.",
    examples: ["Heavy rain can cause the road to flood.", "Loud music causes the dog to bark."],
    emoji: "⚡",
    syllables: "cause",
    distractorGroup: "actions",
  },
  {
    word: "celebrate",
    pos: "verb",
    kidMeaning: "Do something fun to mark a special event.",
    examples: ["We celebrate my grandma's birthday every June.", "The team celebrates their win with a party."],
    emoji: "🎉",
    syllables: "cel-e-brate",
    distractorGroup: "actions",
  },
  {
    word: "check",
    pos: "verb",
    kidMeaning: "Look at something to make sure it is right.",
    examples: ["Please check your answers before you hand in the test.", "He checks the time on his watch."],
    emoji: "✔️",
    syllables: "check",
    distractorGroup: "actions",
  },
  {
    word: "combine",
    pos: "verb",
    kidMeaning: "Mix or join two or more things together.",
    examples: ["Combine the flour and sugar in a bowl.", "The two schools combine for the sports day."],
    emoji: "🔗",
    syllables: "com-bine",
    distractorGroup: "actions",
  },
  {
    word: "contain",
    pos: "verb",
    kidMeaning: "Have something inside.",
    examples: ["The box contains old toys and books.", "This drink contains a lot of sugar."],
    emoji: "📦",
    syllables: "con-tain",
    distractorGroup: "actions",
  },
  {
    word: "control",
    pos: "verb",
    kidMeaning: "Have the power to make something do what you want.",
    examples: ["She controls the remote for the television.", "He learns to control his temper."],
    emoji: "🎮",
    syllables: "con-trol",
    distractorGroup: "actions",
  },
  {
    word: "cover",
    pos: "verb",
    kidMeaning: "Put something over another thing to hide or protect it.",
    examples: ["Snow covers the whole garden this morning.", "She covers the pot while the soup cooks."],
    emoji: "🧣",
    syllables: "cov-er",
    distractorGroup: "actions",
  },
  {
    word: "create",
    pos: "verb",
    kidMeaning: "Make something new that did not exist before.",
    examples: ["The artist creates a colourful mural on the wall.", "Children create a fort out of pillows."],
    emoji: "🎨",
    syllables: "cre-ate",
    distractorGroup: "actions",
  },
  {
    word: "cure",
    pos: "verb",
    kidMeaning: "Make an illness or problem go away.",
    examples: ["The medicine cures her cough in a few days.", "Rest and water help cure a headache."],
    emoji: "💊",
    syllables: "cure",
    distractorGroup: "actions",
  },
  {
    word: "damage",
    pos: "verb",
    kidMeaning: "Harm or spoil something.",
    examples: ["The storm damages many roofs in the village.", "Please be careful not to damage the toy."],
    emoji: "💥",
    syllables: "dam-age",
    distractorGroup: "actions",
  },
  {
    word: "deal",
    pos: "verb",
    kidMeaning: "Handle a problem, or do business with someone.",
    examples: ["She deals with the angry customer calmly.", "He deals with his homework before dinner."],
    emoji: "🤝",
    syllables: "deal",
    distractorGroup: "actions",
  },
  {
    word: "defend",
    pos: "verb",
    kidMeaning: "Protect someone or something from attack.",
    examples: ["The goalkeeper defends the goal well.", "He defends his little sister from bullies."],
    emoji: "🛡️",
    syllables: "de-fend",
    distractorGroup: "actions",
  },
  {
    word: "depend",
    pos: "verb",
    kidMeaning: "Need help or support from someone or something.",
    examples: ["Plants depend on sunlight and water to grow.", "The picnic depends on the weather."],
    emoji: "🔗",
    syllables: "de-pend",
    distractorGroup: "actions",
  },
  {
    word: "deserve",
    pos: "verb",
    kidMeaning: "Have earned something because of what you did.",
    examples: ["She deserves a prize for her hard work.", "They deserve a rest after the long hike."],
    emoji: "🏅",
    syllables: "de-serve",
    distractorGroup: "actions",
  },
  {
    word: "destroy",
    pos: "verb",
    kidMeaning: "Break or ruin something completely.",
    examples: ["The fire destroys the old wooden barn.", "A strong storm can destroy small boats."],
    emoji: "💣",
    syllables: "de-stroy",
    distractorGroup: "actions",
  },
  {
    word: "disappear",
    pos: "verb",
    kidMeaning: "Go out of sight suddenly.",
    examples: ["The magician makes the coin disappear.", "The sun disappears behind the clouds."],
    emoji: "💨",
    syllables: "dis-ap-pear",
    distractorGroup: "actions",
  },
  {
    word: "dislike",
    pos: "verb",
    kidMeaning: "Not like something or someone.",
    examples: ["He dislikes the taste of bitter gourd.", "She dislikes waiting in long queues."],
    emoji: "👎",
    syllables: "dis-like",
    distractorGroup: "actions",
  },
  {
    word: "display",
    pos: "verb",
    kidMeaning: "Show something so people can see it.",
    examples: ["The shop displays new toys in the window.", "She displays her artwork on the wall."],
    emoji: "🖼️",
    syllables: "dis-play",
    distractorGroup: "actions",
  },
  {
    word: "divide",
    pos: "verb",
    kidMeaning: "Split something into two or more parts.",
    examples: ["Divide the cake into eight equal slices.", "The teacher divides the class into groups."],
    emoji: "➗",
    syllables: "di-vide",
    distractorGroup: "actions",
  },
  {
    word: "double",
    pos: "verb",
    kidMeaning: "Make something two times as much.",
    examples: ["The bakery doubles its orders before the festival.", "She doubles the recipe to feed more guests."],
    emoji: "✌️",
    syllables: "dou-ble",
    distractorGroup: "actions",
  },
  {
    word: "earn",
    pos: "verb",
    kidMeaning: "Get money or a reward by working for it.",
    examples: ["He earns pocket money by washing the car.", "She earns a badge for good behaviour."],
    emoji: "💰",
    syllables: "earn",
    distractorGroup: "actions",
  },
  {
    word: "enter",
    pos: "verb",
    kidMeaning: "Go into a place, or join a competition.",
    examples: ["Please enter the hall quietly.", "She enters the drawing contest at school."],
    emoji: "🚪",
    syllables: "en-ter",
    distractorGroup: "actions",
  },
  {
    word: "face",
    pos: "verb",
    kidMeaning: "Deal with a hard problem, or turn towards something.",
    examples: ["Everyone must face their fears sometimes.", "She faces the front of the class."],
    emoji: "😤",
    syllables: "face",
    distractorGroup: "actions",
  },
  {
    word: "fail",
    pos: "verb",
    kidMeaning: "Not succeed at doing something.",
    examples: ["He fails his first attempt at the test.", "The old torch fails to switch on."],
    emoji: "❌",
    syllables: "fail",
    distractorGroup: "actions",
  },
  {
    word: "fasten",
    pos: "verb",
    kidMeaning: "Fix or tie something firmly shut.",
    examples: ["Please fasten your seatbelt before we drive.", "She fastens the buttons on her coat."],
    emoji: "🔒",
    syllables: "fas-ten",
    distractorGroup: "actions",
  },
  {
    word: "fill",
    pos: "verb",
    kidMeaning: "Make something full.",
    examples: ["He fills the bottle with cold water.", "She fills the basket with fresh fruit."],
    emoji: "🪣",
    syllables: "fill",
    distractorGroup: "actions",
  },
  {
    word: "fit",
    pos: "verb",
    kidMeaning: "Be the right size or shape for something.",
    examples: ["These shoes fit her feet perfectly.", "The key fits the old lock."],
    emoji: "👟",
    syllables: "fit",
    distractorGroup: "actions",
  },
  {
    word: "focus",
    pos: "verb",
    kidMeaning: "Give all your attention to one thing.",
    examples: ["Please focus on your homework, not the television.", "She focuses hard during the spelling test."],
    emoji: "🎯",
    syllables: "fo-cus",
    distractorGroup: "actions",
  },
  {
    word: "force",
    pos: "verb",
    kidMeaning: "Make someone do something, using strength or power.",
    examples: ["The wind forces the door shut.", "Nobody forces her to join the club."],
    emoji: "💪",
    syllables: "force",
    distractorGroup: "actions",
  },
  {
    word: "glance",
    pos: "verb",
    kidMeaning: "Look at something quickly.",
    examples: ["She glances at the clock during the lesson.", "He glances out of the window at the rain."],
    emoji: "👁️",
    syllables: "glance",
    distractorGroup: "actions",
  },
  {
    word: "handle",
    pos: "verb",
    kidMeaning: "Deal with something, or hold it with your hand.",
    examples: ["She handles the difficult question calmly.", "He handles the fragile vase with care."],
    emoji: "🖐️",
    syllables: "han-dle",
    distractorGroup: "actions",
  },
  {
    word: "happen",
    pos: "verb",
    kidMeaning: "Take place; occur.",
    examples: ["A surprise party happens at her house.", "Nothing much happens during the holidays."],
    emoji: "❗",
    syllables: "hap-pen",
    distractorGroup: "actions",
  },
  {
    word: "harm",
    pos: "verb",
    kidMeaning: "Hurt or damage someone or something.",
    examples: ["Loud noise can harm your ears.", "The gentle dog would never harm anyone."],
    emoji: "⚠️",
    syllables: "harm",
    distractorGroup: "actions",
  },
  {
    word: "hurt",
    pos: "verb",
    kidMeaning: "Cause pain or sadness.",
    examples: ["Her unkind words hurt his feelings.", "He hurts his knee when he falls."],
    emoji: "🤕",
    syllables: "hurt",
    distractorGroup: "actions",
  },
  {
    word: "identify",
    pos: "verb",
    kidMeaning: "Say who or what something is.",
    examples: ["She identifies the bird by its bright feathers.", "Can you identify the mystery smell?"],
    emoji: "🔍",
    syllables: "i-den-ti-fy",
    distractorGroup: "actions",
  },
  {
    word: "ignore",
    pos: "verb",
    kidMeaning: "Not pay attention to something on purpose.",
    examples: ["He ignores the ringing phone during class.", "Please do not ignore your homework."],
    emoji: "🙈",
    syllables: "ig-nore",
    distractorGroup: "actions",
  },
  {
    word: "increase",
    pos: "verb",
    kidMeaning: "Make something bigger, or become bigger.",
    examples: ["The bus fare increases next month.", "Practice increases her confidence at swimming."],
    emoji: "📈",
    syllables: "in-crease",
    distractorGroup: "actions",
  },
  {
    word: "inform",
    pos: "verb",
    kidMeaning: "Tell someone important information.",
    examples: ["The teacher informs us about the school trip.", "Please inform your parents about the change."],
    emoji: "📢",
    syllables: "in-form",
    distractorGroup: "actions",
  },
  {
    word: "introduce",
    pos: "verb",
    kidMeaning: "Tell people someone's name for the first time.",
    examples: ["She introduces her new friend to the class.", "He introduces the topic before the lesson starts."],
    emoji: "👋",
    syllables: "in-tro-duce",
    distractorGroup: "actions",
  },
  {
    word: "invent",
    pos: "verb",
    kidMeaning: "Make or think of something new.",
    examples: ["She invents a game using old bottle caps.", "Scientists invent new machines every year."],
    emoji: "💡",
    syllables: "in-vent",
    distractorGroup: "actions",
  },
  {
    word: "lead",
    pos: "verb",
    kidMeaning: "Go in front to show the way.",
    examples: ["The guide leads the tourists through the museum.", "She leads her team to victory."],
    emoji: "🚩",
    syllables: "lead",
    distractorGroup: "actions",
  },
  {
    word: "link",
    pos: "verb",
    kidMeaning: "Join two things together.",
    examples: ["A bridge links the two islands.", "This clue links to the next puzzle."],
    emoji: "🔗",
    syllables: "link",
    distractorGroup: "actions",
  },
  {
    word: "manage",
    pos: "verb",
    kidMeaning: "Be able to do something, or be in charge.",
    examples: ["She manages to finish her homework before dinner.", "He manages the small shop for his uncle."],
    emoji: "🗂️",
    syllables: "man-age",
    distractorGroup: "actions",
  },
  {
    word: "mark",
    pos: "verb",
    kidMeaning: "Put a sign on something, or give a grade.",
    examples: ["The teacher marks our spelling tests.", "She marks the page with a sticky note."],
    emoji: "✏️",
    syllables: "mark",
    distractorGroup: "actions",
  },
  {
    word: "match",
    pos: "verb",
    kidMeaning: "Be the same as, or go well together.",
    examples: ["Her socks do not match her shoes.", "This puzzle piece matches the corner."],
    emoji: "🧩",
    syllables: "match",
    distractorGroup: "actions",
  },
  {
    word: "multiply",
    pos: "verb",
    kidMeaning: "Make a number bigger a certain number of times.",
    examples: ["We multiply four by three to get twelve.", "Rabbits multiply very quickly on the farm."],
    emoji: "✖️",
    syllables: "mul-ti-ply",
    distractorGroup: "actions",
  },
  {
    word: "offer",
    pos: "verb",
    kidMeaning: "Ask if someone wants something.",
    examples: ["He offers his seat to the elderly man.", "She offers to help wash the dishes."],
    emoji: "🤲",
    syllables: "of-fer",
    distractorGroup: "actions",
  },
  {
    word: "own",
    pos: "verb",
    kidMeaning: "Have something that belongs to you.",
    examples: ["She owns a bright red bicycle.", "They own a small dog and two cats."],
    emoji: "🔑",
    syllables: "own",
    distractorGroup: "actions",
  },
  {
    word: "persuade",
    pos: "verb",
    kidMeaning: "Get someone to agree by talking to them.",
    examples: ["She persuades her mum to buy the puppy.", "He persuades his friends to join the club."],
    emoji: "🗣️",
    syllables: "per-suade",
    distractorGroup: "actions",
  },
  {
    word: "plan",
    pos: "verb",
    kidMeaning: "Decide what to do before doing it.",
    examples: ["We plan our trip a week before we go.", "She plans a surprise for her friend."],
    emoji: "📝",
    syllables: "plan",
    distractorGroup: "actions",
  },
  {
    word: "predict",
    pos: "verb",
    kidMeaning: "Say what you think will happen next.",
    examples: ["She predicts it will rain this afternoon.", "Can you predict the ending of the story?"],
    emoji: "🔮",
    syllables: "pre-dict",
    distractorGroup: "actions",
  },
  {
    word: "present",
    pos: "verb",
    kidMeaning: "Give something to someone, or show it.",
    examples: ["He presents his project to the whole class.", "She presents the trophy to the winner."],
    emoji: "🎁",
    syllables: "pre-sent",
    distractorGroup: "actions",
  },
  {
    word: "press",
    pos: "verb",
    kidMeaning: "Push something firmly.",
    examples: ["She presses the button to call the lift.", "He presses hard on the door to shut it."],
    emoji: "👆",
    syllables: "press",
    distractorGroup: "actions",
  },
  {
    word: "pretend",
    pos: "verb",
    kidMeaning: "Act as if something is true when it is not.",
    examples: ["The children pretend to be pirates on a ship.", "She pretends to be asleep."],
    emoji: "🎭",
    syllables: "pre-tend",
    distractorGroup: "actions",
  },
  {
    word: "prevent",
    pos: "verb",
    kidMeaning: "Stop something from happening.",
    examples: ["A raincoat prevents you from getting wet.", "Washing hands prevents germs from spreading."],
    emoji: "🚫",
    syllables: "pre-vent",
    distractorGroup: "actions",
  },
  {
    word: "produce",
    pos: "verb",
    kidMeaning: "Make or grow something.",
    examples: ["The farm produces fresh vegetables every week.", "The factory produces hundreds of toys a day."],
    emoji: "🏭",
    syllables: "pro-duce",
    distractorGroup: "actions",
  },
  {
    word: "prove",
    pos: "verb",
    kidMeaning: "Show that something is true.",
    examples: ["The test results prove her idea is correct.", "He proves he can swim across the pool."],
    emoji: "✅",
    syllables: "prove",
    distractorGroup: "actions",
  },
  {
    word: "punish",
    pos: "verb",
    kidMeaning: "Make someone suffer for doing something wrong.",
    examples: ["The teacher punishes latecomers with extra work.", "Parents should not punish honest mistakes too harshly."],
    emoji: "⛔",
    syllables: "pun-ish",
    distractorGroup: "actions",
  },
  {
    word: "question",
    pos: "verb",
    kidMeaning: "Ask about something, or doubt it.",
    examples: ["She questions the strange noise outside.", "He questions why the shop is closed today."],
    emoji: "❓",
    syllables: "ques-tion",
    distractorGroup: "actions",
  },
  {
    word: "record",
    pos: "verb",
    kidMeaning: "Write down or save information for later.",
    examples: ["She records her voice singing a song.", "He records the score of every match."],
    emoji: "🎙️",
    syllables: "re-cord",
    distractorGroup: "actions",
  },
  {
    word: "refuse",
    pos: "verb",
    kidMeaning: "Say no to something firmly.",
    examples: ["He refuses to eat his vegetables.", "She refuses to give up during the race."],
    emoji: "🙅",
    syllables: "re-fuse",
    distractorGroup: "actions",
  },
  {
    word: "reject",
    pos: "verb",
    kidMeaning: "Not accept something.",
    examples: ["The judge rejects his messy entry.", "She rejects the offer to swap seats."],
    emoji: "🚫",
    syllables: "re-ject",
    distractorGroup: "actions",
  },
  {
    word: "rely",
    pos: "verb",
    kidMeaning: "Trust and depend on someone or something.",
    examples: ["She relies on her sister for help with maths.", "We rely on the bus to get to school."],
    emoji: "🤝",
    syllables: "re-ly",
    distractorGroup: "actions",
  },
  {
    word: "remove",
    pos: "verb",
    kidMeaning: "Take something away or off.",
    examples: ["Please remove your shoes before entering the house.", "She removes the stain from her shirt."],
    emoji: "🧹",
    syllables: "re-move",
    distractorGroup: "actions",
  },
  {
    word: "respond",
    pos: "verb",
    kidMeaning: "Answer or react to something.",
    examples: ["She responds quickly to the teacher's question.", "He responds to the text message at once."],
    emoji: "💬",
    syllables: "re-spond",
    distractorGroup: "actions",
  },
  {
    word: "reveal",
    pos: "verb",
    kidMeaning: "Show something that was hidden or secret.",
    examples: ["The magician reveals his trick at the end.", "She reveals the surprise gift to her friend."],
    emoji: "🎊",
    syllables: "re-veal",
    distractorGroup: "actions",
  },
  {
    word: "select",
    pos: "verb",
    kidMeaning: "Choose one thing from a group.",
    examples: ["She selects a book from the shelf.", "He selects his favourite colour for the poster."],
    emoji: "👆",
    syllables: "se-lect",
    distractorGroup: "actions",
  },
  {
    word: "serve",
    pos: "verb",
    kidMeaning: "Give food or help to someone.",
    examples: ["The waiter serves our food quickly.", "She serves as the class monitor this term."],
    emoji: "🍽️",
    syllables: "serve",
    distractorGroup: "actions",
  },
  {
    word: "settle",
    pos: "verb",
    kidMeaning: "Come to rest, or sort out a problem.",
    examples: ["The dust settles after the workers leave.", "They settle their argument calmly."],
    emoji: "🤲",
    syllables: "set-tle",
    distractorGroup: "actions",
  },
  {
    word: "shock",
    pos: "verb",
    kidMeaning: "Give someone a big surprise.",
    examples: ["The loud bang shocks everyone in the hall.", "The news shocks the whole family."],
    emoji: "😲",
    syllables: "shock",
    distractorGroup: "actions",
  },
  {
    word: "sign",
    pos: "verb",
    kidMeaning: "Write your name, or show a signal.",
    examples: ["Please sign your name at the bottom.", "He signs to his friend across the room."],
    emoji: "✍️",
    syllables: "sign",
    distractorGroup: "actions",
  },
  {
    word: "solve",
    pos: "verb",
    kidMeaning: "Find the answer to a problem.",
    examples: ["She solves the puzzle in five minutes.", "He solves the tricky maths question."],
    emoji: "🧩",
    syllables: "solve",
    distractorGroup: "actions",
  },
  {
    word: "sort",
    pos: "verb",
    kidMeaning: "Put things into groups, or arrange them.",
    examples: ["She sorts the socks into matching pairs.", "He sorts his books by colour."],
    emoji: "🗃️",
    syllables: "sort",
    distractorGroup: "actions",
  },
  {
    word: "spread",
    pos: "verb",
    kidMeaning: "Open out wide, or cover a larger area.",
    examples: ["She spreads jam on her toast.", "The news spreads quickly around the school."],
    emoji: "🌐",
    syllables: "spread",
    distractorGroup: "actions",
  },
  {
    word: "succeed",
    pos: "verb",
    kidMeaning: "Do well and get what you were trying for.",
    examples: ["She succeeds in passing her swimming test.", "He succeeds after trying many times."],
    emoji: "🏆",
    syllables: "suc-ceed",
    distractorGroup: "actions",
  },
  {
    word: "supply",
    pos: "verb",
    kidMeaning: "Give people what they need.",
    examples: ["The shop supplies fresh bread every morning.", "Farmers supply vegetables to the market."],
    emoji: "📦",
    syllables: "sup-ply",
    distractorGroup: "actions",
  },
  {
    word: "suspect",
    pos: "verb",
    kidMeaning: "Think something is true, without being sure.",
    examples: ["She suspects her brother ate the last biscuit.", "He suspects it will rain soon."],
    emoji: "🤨",
    syllables: "sus-pect",
    distractorGroup: "actions",
  },
  {
    word: "treat",
    pos: "verb",
    kidMeaning: "Behave towards someone, or deal with an illness.",
    examples: ["She treats her pet with great kindness.", "The doctor treats his sore throat."],
    emoji: "💊",
    syllables: "treat",
    distractorGroup: "actions",
  },
  {
    word: "trust",
    pos: "verb",
    kidMeaning: "Believe that someone is honest and good.",
    examples: ["She trusts her best friend with her secret.", "You can trust him to keep his promise."],
    emoji: "🤝",
    syllables: "trust",
    distractorGroup: "actions",
  },
  {
    word: "weigh",
    pos: "verb",
    kidMeaning: "Find out how heavy something is.",
    examples: ["She weighs the apples at the market.", "He weighs himself every Sunday morning."],
    emoji: "⚖️",
    syllables: "weigh",
    distractorGroup: "actions",
  },
  {
    word: "wrap",
    pos: "verb",
    kidMeaning: "Cover something by folding paper or cloth round it.",
    examples: ["She wraps the present in bright paper.", "He wraps a scarf around his neck."],
    emoji: "🎁",
    syllables: "wrap",
    distractorGroup: "actions",
  },

  // ---- Adjectives ----
  {
    word: "available",
    pos: "adjective",
    kidMeaning: "Free to be used, or ready to help.",
    examples: ["Extra chairs are available at the back of the hall.", "Is the teacher available after school today?"],
    emoji: "✅",
    syllables: "a-vail-a-ble",
    distractorGroup: "qualities",
  },
  {
    word: "brief",
    pos: "adjective",
    kidMeaning: "Lasting only a short time.",
    examples: ["She gives a brief answer to the question.", "It was a brief visit to the zoo."],
    emoji: "⏱️",
    syllables: "brief",
    distractorGroup: "qualities",
  },
  {
    word: "capable",
    pos: "adjective",
    kidMeaning: "Able to do something well.",
    examples: ["He is capable of solving hard puzzles.", "She is a capable swimmer for her age."],
    emoji: "💪",
    syllables: "ca-pa-ble",
    distractorGroup: "qualities",
  },
  {
    word: "cautious",
    pos: "adjective",
    kidMeaning: "Careful to avoid danger or mistakes.",
    examples: ["Be cautious when crossing the busy road.", "She is cautious about trying new food."],
    emoji: "⚠️",
    syllables: "cau-tious",
    distractorGroup: "qualities",
  },
  {
    word: "certain",
    pos: "adjective",
    kidMeaning: "Sure and without doubt.",
    examples: ["I am certain the bus leaves at three.", "She is certain she locked the door."],
    emoji: "✔️",
    syllables: "cer-tain",
    distractorGroup: "qualities",
  },
  {
    word: "correct",
    pos: "adjective",
    kidMeaning: "Right, with no mistakes.",
    examples: ["Her spelling of the word is correct.", "Please tick the correct answer."],
    emoji: "✅",
    syllables: "cor-rect",
    distractorGroup: "qualities",
  },
  {
    word: "current",
    pos: "adjective",
    kidMeaning: "Happening right now, in the present time.",
    examples: ["The current weather is warm and sunny.", "This is her current favourite song."],
    emoji: "📅",
    syllables: "cur-rent",
    distractorGroup: "qualities",
  },
  {
    word: "dangerous",
    pos: "adjective",
    kidMeaning: "Able to cause harm or hurt someone.",
    examples: ["Swimming in the storm is dangerous.", "The broken glass is dangerous to touch."],
    emoji: "⚠️",
    syllables: "dan-ger-ous",
    distractorGroup: "qualities",
  },
  {
    word: "definite",
    pos: "adjective",
    kidMeaning: "Sure and fixed, not likely to change.",
    examples: ["We have a definite plan for the trip.", "There is no definite answer yet."],
    emoji: "📌",
    syllables: "def-i-nite",
    spellingTip: "Has 'finite' inside: de-FINITE, not de-fin-ate.",
    distractorGroup: "qualities",
  },
  {
    word: "difficult",
    pos: "adjective",
    kidMeaning: "Hard to do or understand.",
    examples: ["This maths question is very difficult.", "It was a difficult climb up the hill."],
    emoji: "😓",
    syllables: "dif-fi-cult",
    distractorGroup: "qualities",
  },
  {
    word: "direct",
    pos: "adjective",
    kidMeaning: "Going straight to a place, with no stops.",
    examples: ["This is a direct flight to London.", "She gave a direct answer to the question."],
    emoji: "➡️",
    syllables: "di-rect",
    distractorGroup: "qualities",
  },
  {
    word: "entire",
    pos: "adjective",
    kidMeaning: "The whole of something, all of it.",
    examples: ["She ate the entire bowl of noodles.", "The entire class went on the trip."],
    emoji: "🌐",
    syllables: "en-tire",
    distractorGroup: "qualities",
  },
  {
    word: "equal",
    pos: "adjective",
    kidMeaning: "The same in size, amount or value.",
    examples: ["Cut the cake into equal pieces.", "Both teams have an equal chance to win."],
    emoji: "⚖️",
    syllables: "e-qual",
    distractorGroup: "qualities",
  },
  {
    word: "essential",
    pos: "adjective",
    kidMeaning: "Very important and needed.",
    examples: ["Water is essential for all living things.", "A good night's sleep is essential for health."],
    emoji: "⭐",
    syllables: "es-sen-tial",
    distractorGroup: "qualities",
  },
  {
    word: "exact",
    pos: "adjective",
    kidMeaning: "Completely correct, with no error at all.",
    examples: ["Tell me the exact time the bus leaves.", "She gave the exact amount of money owed."],
    emoji: "🎯",
    syllables: "ex-act",
    distractorGroup: "qualities",
  },
  {
    word: "excellent",
    pos: "adjective",
    kidMeaning: "Extremely good.",
    examples: ["She did an excellent job on her project.", "The food at the party was excellent."],
    emoji: "🌟",
    syllables: "ex-cel-lent",
    distractorGroup: "qualities",
  },
  {
    word: "extra",
    pos: "adjective",
    kidMeaning: "More than what is usual or needed.",
    examples: ["Bring an extra pencil in case yours breaks.", "There is extra rice if you are hungry."],
    emoji: "➕",
    syllables: "ex-tra",
    distractorGroup: "qualities",
  },
  {
    word: "familiar",
    pos: "adjective",
    kidMeaning: "Well known to you; easy to recognise.",
    examples: ["That song sounds very familiar to her.", "He feels familiar with the new school."],
    emoji: "🙂",
    syllables: "fa-mil-iar",
    distractorGroup: "qualities",
  },
  {
    word: "famous",
    pos: "adjective",
    kidMeaning: "Known by many people.",
    examples: ["The singer is famous all over the world.", "This is a famous painting in the museum."],
    emoji: "⭐",
    syllables: "fa-mous",
    distractorGroup: "qualities",
  },
  {
    word: "final",
    pos: "adjective",
    kidMeaning: "Last, at the end.",
    examples: ["This is the final question of the quiz.", "They reached the final stage of the race."],
    emoji: "🏁",
    syllables: "fi-nal",
    distractorGroup: "qualities",
  },
  {
    word: "firm",
    pos: "adjective",
    kidMeaning: "Not easily moved; steady and strong.",
    examples: ["He gives a firm handshake to his coach.", "The table stands firm on the floor."],
    emoji: "💪",
    syllables: "firm",
    distractorGroup: "qualities",
  },
  {
    word: "fond",
    pos: "adjective",
    kidMeaning: "Liking someone or something a lot.",
    examples: ["She is fond of her old teddy bear.", "He is very fond of his grandmother."],
    emoji: "🥰",
    syllables: "fond",
    distractorGroup: "qualities",
  },
  {
    word: "fortunate",
    pos: "adjective",
    kidMeaning: "Lucky; having good things happen to you.",
    examples: ["We are fortunate to have such fine weather.", "She feels fortunate to have kind friends."],
    emoji: "🍀",
    syllables: "for-tu-nate",
    distractorGroup: "qualities",
  },
  {
    word: "frequent",
    pos: "adjective",
    kidMeaning: "Happening often.",
    examples: ["He makes frequent trips to the library.", "There are frequent buses on this road."],
    emoji: "🔁",
    syllables: "fre-quent",
    distractorGroup: "qualities",
  },
  {
    word: "general",
    pos: "adjective",
    kidMeaning: "About most things, not one exact detail.",
    examples: ["She gave a general idea of the plan.", "In general, the weather here is warm."],
    emoji: "🌍",
    syllables: "gen-er-al",
    distractorGroup: "qualities",
  },
  {
    word: "genuine",
    pos: "adjective",
    kidMeaning: "Real and true, not fake.",
    examples: ["Her smile was warm and genuine.", "This is a genuine gold ring."],
    emoji: "💎",
    syllables: "gen-u-ine",
    distractorGroup: "qualities",
  },
  {
    word: "ideal",
    pos: "adjective",
    kidMeaning: "The best possible; perfect for a purpose.",
    examples: ["The park is an ideal place for a picnic.", "This is the ideal size for her hand."],
    emoji: "👌",
    syllables: "i-de-al",
    distractorGroup: "qualities",
  },
  {
    word: "identical",
    pos: "adjective",
    kidMeaning: "Exactly the same as another thing.",
    examples: ["The twins wear identical outfits to school.", "Her drawing is identical to the picture."],
    emoji: "👯",
    syllables: "i-den-ti-cal",
    distractorGroup: "qualities",
  },
  {
    word: "immediate",
    pos: "adjective",
    kidMeaning: "Happening right away, with no delay.",
    examples: ["She gave an immediate reply to the message.", "He needs immediate help with his homework."],
    emoji: "⚡",
    syllables: "im-me-di-ate",
    spellingTip: "Double m: im-mediate.",
    distractorGroup: "qualities",
  },
  {
    word: "important",
    pos: "adjective",
    kidMeaning: "Having great value or meaning.",
    examples: ["It is important to wash your hands.", "This is an important letter for Dad."],
    emoji: "❗",
    syllables: "im-por-tant",
    distractorGroup: "qualities",
  },
  {
    word: "impossible",
    pos: "adjective",
    kidMeaning: "Not able to happen or be done.",
    examples: ["It seems impossible to finish the maze.", "Flying without wings is impossible for humans."],
    emoji: "🚫",
    syllables: "im-pos-si-ble",
    distractorGroup: "qualities",
  },
  {
    word: "individual",
    pos: "adjective",
    kidMeaning: "Single; for one person only.",
    examples: ["Each pupil gets an individual desk.", "She has her own individual style of dancing."],
    emoji: "👤",
    syllables: "in-di-vid-u-al",
    distractorGroup: "qualities",
  },
  {
    word: "instant",
    pos: "adjective",
    kidMeaning: "Happening at once, very quickly.",
    examples: ["The soup gives instant warmth on a cold day.", "He felt instant relief when the pain stopped."],
    emoji: "⚡",
    syllables: "in-stant",
    distractorGroup: "qualities",
  },
  {
    word: "intelligent",
    pos: "adjective",
    kidMeaning: "Clever; able to learn and understand quickly.",
    examples: ["The intelligent dog learns tricks very fast.", "She is an intelligent and curious pupil."],
    emoji: "🧠",
    syllables: "in-tel-li-gent",
    distractorGroup: "qualities",
  },
  {
    word: "level",
    pos: "adjective",
    kidMeaning: "Flat and even, or equal in height.",
    examples: ["The floor must be level before you build.", "Their scores are level after the last round."],
    emoji: "📏",
    syllables: "lev-el",
    distractorGroup: "qualities",
  },
  {
    word: "likely",
    pos: "adjective",
    kidMeaning: "Probably going to happen.",
    examples: ["It is likely to rain this afternoon.", "She is likely to win the race."],
    emoji: "🤞",
    syllables: "like-ly",
    distractorGroup: "qualities",
  },
  {
    word: "local",
    pos: "adjective",
    kidMeaning: "From or belonging to a nearby place.",
    examples: ["We shop at the local market every week.", "The local library is close to my house."],
    emoji: "📍",
    syllables: "lo-cal",
    distractorGroup: "qualities",
  },
  {
    word: "loose",
    pos: "adjective",
    kidMeaning: "Not tight; able to move freely.",
    examples: ["Her shoelace came loose during the race.", "The old gate has a loose hinge."],
    emoji: "🔓",
    syllables: "loose",
    confusedWith: "lose",
    spellingTip: "Loose has two o's like a baggy loop; lose has one o.",
    distractorGroup: "qualities",
  },
  {
    word: "major",
    pos: "adjective",
    kidMeaning: "Very large or important.",
    examples: ["Losing her bag was a major problem.", "There was a major storm last night."],
    emoji: "⭐",
    syllables: "ma-jor",
    distractorGroup: "qualities",
  },
  {
    word: "minor",
    pos: "adjective",
    kidMeaning: "Small and not very important.",
    examples: ["He has a minor scratch on his arm.", "It was only a minor mistake."],
    emoji: "🔹",
    syllables: "mi-nor",
    distractorGroup: "qualities",
  },
  {
    word: "necessary",
    pos: "adjective",
    kidMeaning: "Needed; must be done or had.",
    examples: ["A helmet is necessary when you cycle.", "It is necessary to eat before the trip."],
    emoji: "✅",
    syllables: "nec-es-sar-y",
    spellingTip: "One collar, two socks: ne-c-e-s-s-ary.",
    distractorGroup: "qualities",
  },
  {
    word: "normal",
    pos: "adjective",
    kidMeaning: "Usual; the way things are most of the time.",
    examples: ["It is normal to feel nervous before a test.", "Her temperature is back to normal now."],
    emoji: "👍",
    syllables: "nor-mal",
    distractorGroup: "qualities",
  },
  {
    word: "ordinary",
    pos: "adjective",
    kidMeaning: "Not special or unusual; plain and normal.",
    examples: ["It was just an ordinary school day.", "He wore his ordinary clothes to the shop."],
    emoji: "🙂",
    syllables: "or-di-nar-y",
    distractorGroup: "qualities",
  },
  {
    word: "particular",
    pos: "adjective",
    kidMeaning: "One specific thing, not just any.",
    examples: ["She likes this particular colour of blue.", "He is very particular about his room being tidy."],
    emoji: "👆",
    syllables: "par-tic-u-lar",
    distractorGroup: "qualities",
  },
  {
    word: "personal",
    pos: "adjective",
    kidMeaning: "Belonging to or about one person.",
    examples: ["That is a personal question to ask.", "She keeps a personal diary every day."],
    emoji: "👤",
    syllables: "per-son-al",
    distractorGroup: "qualities",
  },
  {
    word: "physical",
    pos: "adjective",
    kidMeaning: "About the body, not the mind.",
    examples: ["Running is good physical exercise.", "He felt physical tiredness after the hike."],
    emoji: "💪",
    syllables: "phys-i-cal",
    distractorGroup: "qualities",
  },
  {
    word: "plain",
    pos: "adjective",
    kidMeaning: "Simple, with nothing extra added.",
    examples: ["She wore a plain white dress.", "He likes plain rice with his curry."],
    emoji: "⬜",
    syllables: "plain",
    distractorGroup: "qualities",
  },
  {
    word: "pleasant",
    pos: "adjective",
    kidMeaning: "Nice and enjoyable.",
    examples: ["It was a pleasant afternoon in the park.", "She has a pleasant smile."],
    emoji: "😊",
    syllables: "pleas-ant",
    distractorGroup: "qualities",
  },
  {
    word: "positive",
    pos: "adjective",
    kidMeaning: "Hopeful and good; not negative.",
    examples: ["She stays positive even when things go wrong.", "The test result was positive news for him."],
    emoji: "👍",
    syllables: "pos-i-tive",
    distractorGroup: "qualities",
  },
  {
    word: "possible",
    pos: "adjective",
    kidMeaning: "Able to happen or be done.",
    examples: ["It is possible to finish the race in time.", "Is it possible to borrow your pencil?"],
    emoji: "✅",
    syllables: "pos-si-ble",
    distractorGroup: "qualities",
  },
  {
    word: "previous",
    pos: "adjective",
    kidMeaning: "Coming before this one; earlier.",
    examples: ["Her previous school was near the market.", "He forgot what happened in the previous chapter."],
    emoji: "⏮️",
    syllables: "pre-vi-ous",
    distractorGroup: "qualities",
  },
  {
    word: "private",
    pos: "adjective",
    kidMeaning: "Only for one person; not shared with others.",
    examples: ["This is her private diary.", "They spoke in a private corner of the room."],
    emoji: "🔒",
    syllables: "pri-vate",
    distractorGroup: "qualities",
  },
  {
    word: "proper",
    pos: "adjective",
    kidMeaning: "Correct and suitable for the situation.",
    examples: ["Wear the proper shoes for gym class.", "There is a proper way to hold chopsticks."],
    emoji: "✅",
    syllables: "prop-er",
    distractorGroup: "qualities",
  },
  {
    word: "public",
    pos: "adjective",
    kidMeaning: "For everyone to use or see.",
    examples: ["The public park is open to everyone.", "She spoke in front of a public crowd."],
    emoji: "🌍",
    syllables: "pub-lic",
    distractorGroup: "qualities",
  },
  {
    word: "ready",
    pos: "adjective",
    kidMeaning: "Fully prepared to do something.",
    examples: ["Are you ready for the spelling test?", "The food is ready to be served."],
    emoji: "✅",
    syllables: "read-y",
    distractorGroup: "qualities",
  },
  {
    word: "real",
    pos: "adjective",
    kidMeaning: "Actually existing; not made up or fake.",
    examples: ["That is a real diamond, not plastic.", "Her worry about the test is real."],
    emoji: "💎",
    syllables: "re-al",
    distractorGroup: "qualities",
  },
  {
    word: "recent",
    pos: "adjective",
    kidMeaning: "Happening a short time ago.",
    examples: ["Her recent drawing is her best one yet.", "This is a recent photo of the family."],
    emoji: "🕐",
    syllables: "re-cent",
    distractorGroup: "qualities",
  },
  {
    word: "related",
    pos: "adjective",
    kidMeaning: "Connected to another thing or person.",
    examples: ["This story is related to the one before.", "She is related to the boy next door."],
    emoji: "🔗",
    syllables: "re-lat-ed",
    distractorGroup: "qualities",
  },
  {
    word: "rich",
    pos: "adjective",
    kidMeaning: "Having a lot of money, or full of something good.",
    examples: ["The rich soil helps the plants grow well.", "He became rich after selling his invention."],
    emoji: "💰",
    syllables: "rich",
    distractorGroup: "qualities",
  },
  {
    word: "satisfied",
    pos: "adjective",
    kidMeaning: "Pleased because you got what you wanted.",
    examples: ["She feels satisfied after finishing her homework.", "He was satisfied with his test score."],
    emoji: "😌",
    syllables: "sat-is-fied",
    distractorGroup: "qualities",
  },
  {
    word: "secure",
    pos: "adjective",
    kidMeaning: "Safe and firmly fixed; free from worry.",
    examples: ["Check that the ladder is secure before climbing.", "She feels secure with her family around her."],
    emoji: "🔒",
    syllables: "se-cure",
    distractorGroup: "qualities",
  },
  {
    word: "serious",
    pos: "adjective",
    kidMeaning: "Important and needing careful thought; not funny.",
    examples: ["This is a serious matter to discuss.", "He looked serious during the meeting."],
    emoji: "😐",
    syllables: "se-ri-ous",
    distractorGroup: "qualities",
  },
  {
    word: "several",
    pos: "adjective",
    kidMeaning: "More than two, but not a huge number.",
    examples: ["She has several pens in her bag.", "Several pupils were late for school today."],
    emoji: "🔢",
    syllables: "sev-er-al",
    distractorGroup: "qualities",
  },
  {
    word: "similar",
    pos: "adjective",
    kidMeaning: "Almost the same as something else.",
    examples: ["Her jacket is similar to her sister's.", "The two stories have a similar ending."],
    emoji: "👯",
    syllables: "sim-i-lar",
    spellingTip: "No extra i — sim-i-lar, not similiar.",
    distractorGroup: "qualities",
  },
  {
    word: "simple",
    pos: "adjective",
    kidMeaning: "Easy to do or understand.",
    examples: ["The instructions are quite simple to follow.", "It was a simple mistake to fix."],
    emoji: "👌",
    syllables: "sim-ple",
    distractorGroup: "qualities",
  },
  {
    word: "single",
    pos: "adjective",
    kidMeaning: "Only one; not more than one.",
    examples: ["She ate a single slice of cake.", "Not a single pupil was late today."],
    emoji: "1️⃣",
    syllables: "sin-gle",
    distractorGroup: "qualities",
  },
  {
    word: "social",
    pos: "adjective",
    kidMeaning: "About being with other people.",
    examples: ["She is a friendly, social child.", "The party was a fun social event."],
    emoji: "👥",
    syllables: "so-cial",
    distractorGroup: "qualities",
  },
  {
    word: "sorry",
    pos: "adjective",
    kidMeaning: "Feeling sad about something you did wrong.",
    examples: ["He is sorry for breaking the vase.", "She said sorry for being late."],
    emoji: "😔",
    syllables: "sor-ry",
    distractorGroup: "qualities",
  },
  {
    word: "spare",
    pos: "adjective",
    kidMeaning: "Extra; kept in case it is needed.",
    examples: ["He keeps a spare key under the mat.", "Do you have a spare pencil I can use?"],
    emoji: "🔑",
    syllables: "spare",
    distractorGroup: "qualities",
  },
  {
    word: "special",
    pos: "adjective",
    kidMeaning: "Not ordinary; different in a good way.",
    examples: ["Today is a special day, it's her birthday.", "She has a special place in her heart for dogs."],
    emoji: "⭐",
    syllables: "spe-cial",
    distractorGroup: "qualities",
  },
  {
    word: "specific",
    pos: "adjective",
    kidMeaning: "Exact and clearly stated.",
    examples: ["Please give a specific time for the meeting.", "She has a specific reason for being upset."],
    emoji: "🎯",
    syllables: "spe-cif-ic",
    distractorGroup: "qualities",
  },
  {
    word: "steady",
    pos: "adjective",
    kidMeaning: "Firm and not shaking; staying the same.",
    examples: ["Hold the ladder steady while he climbs.", "Her grades have been steady all year."],
    emoji: "🧍",
    syllables: "stead-y",
    distractorGroup: "qualities",
  },
  {
    word: "strange",
    pos: "adjective",
    kidMeaning: "Odd or unusual.",
    examples: ["She heard a strange noise in the night.", "That is a strange way to solve the puzzle."],
    emoji: "😯",
    syllables: "strange",
    distractorGroup: "qualities",
  },
  {
    word: "stupid",
    pos: "adjective",
    kidMeaning: "Not sensible; showing a lack of thought.",
    examples: ["It was stupid to leave the door open.", "He felt stupid for forgetting his homework."],
    emoji: "🤦",
    syllables: "stu-pid",
    distractorGroup: "qualities",
  },
  {
    word: "suitable",
    pos: "adjective",
    kidMeaning: "Right for a certain purpose or person.",
    examples: ["This book is suitable for young readers.", "Her shoes are not suitable for hiking."],
    emoji: "✅",
    syllables: "suit-a-ble",
    distractorGroup: "qualities",
  },
  {
    word: "sure",
    pos: "adjective",
    kidMeaning: "Certain about something.",
    examples: ["She is sure the answer is correct.", "Are you sure you locked the gate?"],
    emoji: "👍",
    syllables: "sure",
    distractorGroup: "qualities",
  },
  {
    word: "tight",
    pos: "adjective",
    kidMeaning: "Fitting closely, or fixed firmly in place.",
    examples: ["These shoes feel too tight on her feet.", "He keeps a tight hold on the rope."],
    emoji: "🔒",
    syllables: "tight",
    distractorGroup: "qualities",
  },
  {
    word: "total",
    pos: "adjective",
    kidMeaning: "Whole; the complete amount.",
    examples: ["The total cost of the trip is fifty dollars.", "There were a total of twenty pupils there."],
    emoji: "🔢",
    syllables: "to-tal",
    distractorGroup: "qualities",
  },
  {
    word: "typical",
    pos: "adjective",
    kidMeaning: "Usual; the normal kind of something.",
    examples: ["A typical school day starts at seven thirty.", "This is a typical example of her work."],
    emoji: "📋",
    syllables: "typ-i-cal",
    distractorGroup: "qualities",
  },
  {
    word: "unusual",
    pos: "adjective",
    kidMeaning: "Not common or normal; strange.",
    examples: ["It is unusual for it to snow here.", "She wore an unusual hat to the party."],
    emoji: "❓",
    syllables: "un-u-su-al",
    distractorGroup: "qualities",
  },
  {
    word: "urgent",
    pos: "adjective",
    kidMeaning: "Needing quick action right away.",
    examples: ["This is an urgent message for the teacher.", "He made an urgent call for help."],
    emoji: "🚨",
    syllables: "ur-gent",
    distractorGroup: "qualities",
  },
  {
    word: "useful",
    pos: "adjective",
    kidMeaning: "Helpful; good for doing something.",
    examples: ["A torch is useful in the dark.", "She gave some useful tips for the test."],
    emoji: "🛠️",
    syllables: "use-ful",
    distractorGroup: "qualities",
  },
  {
    word: "usual",
    pos: "adjective",
    kidMeaning: "Happening most of the time; normal.",
    examples: ["She took her usual seat by the window.", "It rained more than usual this week."],
    emoji: "🔄",
    syllables: "u-su-al",
    distractorGroup: "qualities",
  },
  {
    word: "valid",
    pos: "adjective",
    kidMeaning: "Correct and acceptable; based on good reason.",
    examples: ["Her ticket is valid for one more day.", "That is a valid reason to be late."],
    emoji: "✅",
    syllables: "val-id",
    distractorGroup: "qualities",
  },
  {
    word: "various",
    pos: "adjective",
    kidMeaning: "Of many different kinds.",
    examples: ["The shop sells various colours of ribbon.", "She tried various ways to solve the puzzle."],
    emoji: "🌈",
    syllables: "var-i-ous",
    distractorGroup: "qualities",
  },
  {
    word: "wealthy",
    pos: "adjective",
    kidMeaning: "Having a lot of money.",
    examples: ["The wealthy man donated to the school.", "Her family became wealthy after the shop opened."],
    emoji: "💰",
    syllables: "wealth-y",
    distractorGroup: "qualities",
  },
  {
    word: "weird",
    pos: "adjective",
    kidMeaning: "Very strange or odd.",
    examples: ["He had a weird dream about flying fish.", "That is a weird sound coming from the shed."],
    emoji: "😵",
    syllables: "weird",
    distractorGroup: "qualities",
  },
  {
    word: "whole",
    pos: "adjective",
    kidMeaning: "All of something; complete.",
    examples: ["She ate the whole apple, even the skin.", "The whole class cheered for the winner."],
    emoji: "🌐",
    syllables: "whole",
    confusedWith: "hole",
    distractorGroup: "qualities",
  },
  {
    word: "wise",
    pos: "adjective",
    kidMeaning: "Having good judgement and common sense.",
    examples: ["The wise old owl gave good advice.", "It was a wise choice to bring an umbrella."],
    emoji: "🦉",
    syllables: "wise",
    distractorGroup: "qualities",
  },
  {
    word: "worth",
    pos: "adjective",
    kidMeaning: "Having a certain value; deserving of.",
    examples: ["This old coin is worth a lot of money.", "The film is worth watching twice."],
    emoji: "💰",
    syllables: "worth",
    distractorGroup: "qualities",
  },

  // ---- Nouns ----
  {
    word: "advantage",
    pos: "noun",
    kidMeaning: "A good or helpful thing about something.",
    examples: ["Being tall is an advantage in basketball.", "The team has the advantage of a home crowd."],
    emoji: "👍",
    syllables: "ad-van-tage",
    distractorGroup: "ideas",
  },
  {
    word: "amount",
    pos: "noun",
    kidMeaning: "How much of something there is.",
    examples: ["Add a small amount of salt to the soup.", "She saved a large amount of money."],
    emoji: "🔢",
    syllables: "a-mount",
    distractorGroup: "amounts",
  },
  {
    word: "ability",
    pos: "noun",
    kidMeaning: "The power or skill to do something.",
    examples: ["He has the ability to run very fast.", "Her ability to draw is amazing."],
    emoji: "💪",
    syllables: "a-bil-i-ty",
    distractorGroup: "ideas",
  },
  {
    word: "aim",
    pos: "noun",
    kidMeaning: "The thing you are trying to do or reach.",
    examples: ["Her aim is to win the spelling contest.", "The team's aim was to score more goals."],
    emoji: "🎯",
    syllables: "aim",
    distractorGroup: "ideas",
  },
  {
    word: "aspect",
    pos: "noun",
    kidMeaning: "One part or side of something.",
    examples: ["The best aspect of the trip was the beach.", "She talked about every aspect of her project."],
    emoji: "🧩",
    syllables: "as-pect",
    distractorGroup: "ideas",
  },
  {
    word: "attitude",
    pos: "noun",
    kidMeaning: "The way someone thinks or feels about something.",
    examples: ["She has a cheerful attitude towards school.", "His attitude changed after the good news."],
    emoji: "🙂",
    syllables: "at-ti-tude",
    distractorGroup: "ideas",
  },
  {
    word: "authority",
    pos: "noun",
    kidMeaning: "The power to give orders or make rules.",
    examples: ["The head teacher has authority over the school.", "Police officers have the authority to stop traffic."],
    emoji: "👮",
    syllables: "au-thor-i-ty",
    distractorGroup: "ideas",
  },
  {
    word: "benefit",
    pos: "noun",
    kidMeaning: "A good result or help you get from something.",
    examples: ["One benefit of walking is good health.", "The trip has many benefits for the pupils."],
    emoji: "✅",
    syllables: "ben-e-fit",
    distractorGroup: "ideas",
  },
  {
    word: "category",
    pos: "noun",
    kidMeaning: "A group of things that are similar.",
    examples: ["Fruits and vegetables are in different categories.", "This book fits into the mystery category."],
    emoji: "🗂️",
    syllables: "cat-e-go-ry",
    distractorGroup: "ideas",
  },
  {
    word: "chance",
    pos: "noun",
    kidMeaning: "A possibility that something might happen.",
    examples: ["There is a chance of rain this evening.", "She has a good chance of winning the race."],
    emoji: "🍀",
    syllables: "chance",
    distractorGroup: "ideas",
  },
  {
    word: "choice",
    pos: "noun",
    kidMeaning: "The act of picking one thing from many.",
    examples: ["She made a good choice of book to read.", "He has a difficult choice to make."],
    emoji: "🤔",
    syllables: "choice",
    distractorGroup: "ideas",
  },
  {
    word: "comment",
    pos: "noun",
    kidMeaning: "Something said about a person or thing.",
    examples: ["The teacher wrote a kind comment on her essay.", "He made a funny comment during class."],
    emoji: "💬",
    syllables: "com-ment",
    distractorGroup: "ideas",
  },
  {
    word: "decision",
    pos: "noun",
    kidMeaning: "A choice you make after thinking about it.",
    examples: ["It was a hard decision to leave her toy behind.", "She made the decision to join the choir."],
    emoji: "🤔",
    syllables: "de-ci-sion",
    distractorGroup: "ideas",
  },
  {
    word: "detail",
    pos: "noun",
    kidMeaning: "A small piece of information about something.",
    examples: ["She noticed every detail in the painting.", "Please give more detail about the trip."],
    emoji: "🔍",
    syllables: "de-tail",
    distractorGroup: "ideas",
  },
  {
    word: "direction",
    pos: "noun",
    kidMeaning: "The way something is facing or moving.",
    examples: ["He walked in the wrong direction to school.", "The wind changed direction suddenly."],
    emoji: "🧭",
    syllables: "di-rec-tion",
    distractorGroup: "ideas",
  },
  {
    word: "duty",
    pos: "noun",
    kidMeaning: "Something you must do because it is your job.",
    examples: ["It is her duty to feed the class pet.", "He takes his duty as monitor seriously."],
    emoji: "✅",
    syllables: "du-ty",
    distractorGroup: "ideas",
  },
  {
    word: "effect",
    pos: "noun",
    kidMeaning: "A change caused by something else.",
    examples: ["The medicine had a good effect on his cough.", "Loud music has an effect on her mood."],
    emoji: "⚡",
    syllables: "ef-fect",
    distractorGroup: "ideas",
  },
  {
    word: "effort",
    pos: "noun",
    kidMeaning: "Hard work put into doing something.",
    examples: ["She put a lot of effort into her project.", "It took great effort to finish the race."],
    emoji: "💪",
    syllables: "ef-fort",
    distractorGroup: "ideas",
  },
  {
    word: "example",
    pos: "noun",
    kidMeaning: "One thing that shows what a group is like.",
    examples: ["The teacher gave an example of a good sentence.", "This drawing is a fine example of her work."],
    emoji: "📝",
    syllables: "ex-am-ple",
    distractorGroup: "ideas",
  },
  {
    word: "fact",
    pos: "noun",
    kidMeaning: "Something that is true and can be checked.",
    examples: ["It is a fact that the sun rises in the east.", "She shared an interesting fact about sharks."],
    emoji: "✅",
    syllables: "fact",
    distractorGroup: "ideas",
  },
  {
    word: "feature",
    pos: "noun",
    kidMeaning: "A part of something that stands out.",
    examples: ["The best feature of the house is the garden.", "Bright colours are a feature of the poster."],
    emoji: "⭐",
    syllables: "fea-ture",
    distractorGroup: "ideas",
  },
  {
    word: "figure",
    pos: "noun",
    kidMeaning: "A number, or a person's shape.",
    examples: ["The exact figure of pupils is forty.", "She saw a figure standing by the gate."],
    emoji: "🔢",
    syllables: "fig-ure",
    distractorGroup: "ideas",
  },
  {
    word: "goal",
    pos: "noun",
    kidMeaning: "Something you want to achieve.",
    examples: ["Her goal is to read ten books this year.", "The team's goal was to win the cup."],
    emoji: "🎯",
    syllables: "goal",
    distractorGroup: "ideas",
  },
  {
    word: "ground",
    pos: "noun",
    kidMeaning: "The reason for something, or the surface of the earth.",
    examples: ["She fell to the ground during the race.", "He has good ground for his complaint."],
    emoji: "🌍",
    syllables: "ground",
    distractorGroup: "ideas",
  },
  {
    word: "importance",
    pos: "noun",
    kidMeaning: "How much something matters.",
    examples: ["The teacher explained the importance of sleep.", "She understands the importance of being kind."],
    emoji: "❗",
    syllables: "im-por-tance",
    distractorGroup: "ideas",
  },
  {
    word: "improvement",
    pos: "noun",
    kidMeaning: "A change that makes something better.",
    examples: ["Her spelling shows great improvement this term.", "There is room for improvement in his writing."],
    emoji: "📈",
    syllables: "im-prove-ment",
    distractorGroup: "ideas",
  },
  {
    word: "information",
    pos: "noun",
    kidMeaning: "Facts or details about something.",
    examples: ["The poster gives information about the school fair.", "She looked for information about volcanoes."],
    emoji: "ℹ️",
    syllables: "in-for-ma-tion",
    distractorGroup: "ideas",
  },
  {
    word: "issue",
    pos: "noun",
    kidMeaning: "A problem or subject to be discussed.",
    examples: ["They talked about an important issue at the meeting.", "There is an issue with the printer."],
    emoji: "❗",
    syllables: "is-sue",
    distractorGroup: "ideas",
  },
  {
    word: "limit",
    pos: "noun",
    kidMeaning: "The most or least that is allowed.",
    examples: ["There is a limit to how many books you can borrow.", "The speed limit near the school is low."],
    emoji: "🚧",
    syllables: "lim-it",
    distractorGroup: "amounts",
  },
  {
    word: "list",
    pos: "noun",
    kidMeaning: "A group of names or things written down.",
    examples: ["She makes a list of things to pack.", "His name is on the list of winners."],
    emoji: "📝",
    syllables: "list",
    distractorGroup: "ideas",
  },
  {
    word: "manner",
    pos: "noun",
    kidMeaning: "The way something is done.",
    examples: ["She spoke in a polite manner to the guest.", "He solved the puzzle in a clever manner."],
    emoji: "🙂",
    syllables: "man-ner",
    distractorGroup: "ideas",
  },
  {
    word: "matter",
    pos: "noun",
    kidMeaning: "A subject or something to think about.",
    examples: ["It is a matter for the head teacher to decide.", "This is a serious matter for the class."],
    emoji: "❗",
    syllables: "mat-ter",
    distractorGroup: "ideas",
  },
  {
    word: "means",
    pos: "noun",
    kidMeaning: "A way of doing something.",
    examples: ["The bus is a cheap means of travel.", "Talking calmly is the best means to solve it."],
    emoji: "🔧",
    syllables: "means",
    distractorGroup: "ideas",
  },
  {
    word: "method",
    pos: "noun",
    kidMeaning: "A way of doing something, step by step.",
    examples: ["She uses a new method to learn spelling.", "This method of cooking rice is quick."],
    emoji: "🔧",
    syllables: "meth-od",
    distractorGroup: "ideas",
  },
  {
    word: "minority",
    pos: "noun",
    kidMeaning: "The smaller part of a group.",
    examples: ["Only a minority of pupils chose art class.", "A minority of the crowd left early."],
    emoji: "🔹",
    syllables: "mi-nor-i-ty",
    distractorGroup: "amounts",
  },
  {
    word: "mixture",
    pos: "noun",
    kidMeaning: "Two or more things put together.",
    examples: ["The cake batter is a mixture of eggs and flour.", "Her feelings were a mixture of joy and worry."],
    emoji: "🥣",
    syllables: "mix-ture",
    distractorGroup: "ideas",
  },
  {
    word: "nature",
    pos: "noun",
    kidMeaning: "The character of a person or thing.",
    examples: ["It is in her nature to be kind.", "The nature of the problem was quite simple."],
    emoji: "🌿",
    syllables: "na-ture",
    distractorGroup: "ideas",
  },
  {
    word: "necessity",
    pos: "noun",
    kidMeaning: "Something you must have.",
    examples: ["Water is a necessity for every living thing.", "A good night's rest is a necessity before exams."],
    emoji: "✅",
    syllables: "ne-ces-si-ty",
    distractorGroup: "ideas",
  },
  {
    word: "notion",
    pos: "noun",
    kidMeaning: "An idea or belief about something.",
    examples: ["She has a strange notion about ghosts.", "He had no notion of what to say."],
    emoji: "💭",
    syllables: "no-tion",
    distractorGroup: "ideas",
  },
  {
    word: "opinion",
    pos: "noun",
    kidMeaning: "What someone thinks about something.",
    examples: ["Everyone has a different opinion about the film.", "She shared her opinion during the class talk."],
    emoji: "💭",
    syllables: "o-pin-ion",
    distractorGroup: "ideas",
  },
  {
    word: "opportunity",
    pos: "noun",
    kidMeaning: "A good chance to do something.",
    examples: ["The trip is a great opportunity to learn.", "She had the opportunity to sing on stage."],
    emoji: "🌟",
    syllables: "op-por-tu-ni-ty",
    spellingTip: "Double p: op-portunity.",
    distractorGroup: "ideas",
  },
  {
    word: "option",
    pos: "noun",
    kidMeaning: "A choice you can make.",
    examples: ["Rice or noodles are both good options for lunch.", "There is only one option left on the menu."],
    emoji: "✅",
    syllables: "op-tion",
    distractorGroup: "ideas",
  },
  {
    word: "outcome",
    pos: "noun",
    kidMeaning: "The result of something.",
    examples: ["The outcome of the match surprised everyone.", "She waited nervously for the outcome of the test."],
    emoji: "🏁",
    syllables: "out-come",
    distractorGroup: "ideas",
  },
  {
    word: "pace",
    pos: "noun",
    kidMeaning: "The speed at which something happens.",
    examples: ["She walks at a fast pace to school.", "The story moves at a slow pace."],
    emoji: "🏃",
    syllables: "pace",
    distractorGroup: "amounts",
  },
  {
    word: "plenty",
    pos: "noun",
    kidMeaning: "A large amount; more than enough.",
    examples: ["There is plenty of food at the party.", "We have plenty of time before the bus arrives."],
    emoji: "🍚",
    syllables: "plen-ty",
    distractorGroup: "amounts",
  },
  {
    word: "point",
    pos: "noun",
    kidMeaning: "An idea, or a mark used in scoring.",
    examples: ["Her point about safety was very clear.", "He scored the winning point for his team."],
    emoji: "📍",
    syllables: "point",
    distractorGroup: "ideas",
  },
  {
    word: "portion",
    pos: "noun",
    kidMeaning: "A part or share of something.",
    examples: ["She ate a small portion of the pie.", "Each pupil gets an equal portion of clay."],
    emoji: "🍰",
    syllables: "por-tion",
    distractorGroup: "amounts",
  },
  {
    word: "position",
    pos: "noun",
    kidMeaning: "The place where something or someone is.",
    examples: ["She held her position at the front of the queue.", "The ball is now in a good position."],
    emoji: "📍",
    syllables: "po-si-tion",
    distractorGroup: "ideas",
  },
  {
    word: "possibility",
    pos: "noun",
    kidMeaning: "A chance that something could happen.",
    examples: ["There is a possibility of rain tomorrow.", "She considered the possibility of losing the race."],
    emoji: "🤔",
    syllables: "pos-si-bil-i-ty",
    distractorGroup: "ideas",
  },
  {
    word: "preference",
    pos: "noun",
    kidMeaning: "A liking for one thing over another.",
    examples: ["Her preference is tea instead of milk.", "He has a strong preference for window seats."],
    emoji: "👍",
    syllables: "pref-er-ence",
    distractorGroup: "ideas",
  },
  {
    word: "presence",
    pos: "noun",
    kidMeaning: "The fact of being somewhere.",
    examples: ["Her presence at the party made everyone happy.", "The teacher noticed his presence at the back."],
    emoji: "🙋",
    syllables: "pres-ence",
    distractorGroup: "ideas",
  },
  {
    word: "principle",
    pos: "noun",
    kidMeaning: "A basic rule or belief about what is right.",
    examples: ["Honesty is an important principle for her.", "He follows the principle of being kind to all."],
    emoji: "📜",
    syllables: "prin-ci-ple",
    confusedWith: "principal",
    spellingTip: "A principLE is a ruLE you live by.",
    distractorGroup: "ideas",
  },
  {
    word: "progress",
    pos: "noun",
    kidMeaning: "Movement forward or getting better at something.",
    examples: ["She is making good progress in swimming.", "The builders checked the progress of the work."],
    emoji: "📈",
    syllables: "prog-ress",
    distractorGroup: "ideas",
  },
  {
    word: "proportion",
    pos: "noun",
    kidMeaning: "The size of one part compared to the whole.",
    examples: ["A large proportion of the class likes maths.", "The recipe needs the right proportion of sugar."],
    emoji: "⚖️",
    syllables: "pro-por-tion",
    distractorGroup: "amounts",
  },
  {
    word: "purpose",
    pos: "noun",
    kidMeaning: "The reason something is done.",
    examples: ["The purpose of the trip is to learn about history.", "What is the purpose of this tool?"],
    emoji: "🎯",
    syllables: "pur-pose",
    distractorGroup: "ideas",
  },
  {
    word: "quality",
    pos: "noun",
    kidMeaning: "How good or bad something is.",
    examples: ["The quality of her work improved this term.", "This shop sells good quality shoes."],
    emoji: "⭐",
    syllables: "qual-i-ty",
    distractorGroup: "ideas",
  },
  {
    word: "quantity",
    pos: "noun",
    kidMeaning: "The amount of something.",
    examples: ["Buy a large quantity of paper for the project.", "The quantity of rain this week was surprising."],
    emoji: "🔢",
    syllables: "quan-ti-ty",
    distractorGroup: "amounts",
  },
  {
    word: "range",
    pos: "noun",
    kidMeaning: "A group of different things, or a stretch of distance.",
    examples: ["The shop sells a wide range of toys.", "The mountains stretch across a huge range."],
    emoji: "🌈",
    syllables: "range",
    distractorGroup: "amounts",
  },
  {
    word: "rate",
    pos: "noun",
    kidMeaning: "How fast something happens, or a fixed price.",
    examples: ["Her heart rate goes up when she runs.", "The shop offers a special rate for pupils."],
    emoji: "📊",
    syllables: "rate",
    distractorGroup: "amounts",
  },
  {
    word: "reaction",
    pos: "noun",
    kidMeaning: "What you do or feel because of something else.",
    examples: ["Her reaction to the surprise was a big smile.", "His reaction to the news was quiet."],
    emoji: "😲",
    syllables: "re-ac-tion",
    distractorGroup: "ideas",
  },
  {
    word: "relation",
    pos: "noun",
    kidMeaning: "A connection between two things.",
    examples: ["There is a relation between sleep and health.", "The teacher explained the relation between the two events."],
    emoji: "🔗",
    syllables: "re-la-tion",
    distractorGroup: "ideas",
  },
  {
    word: "requirement",
    pos: "noun",
    kidMeaning: "Something that is needed or must be done.",
    examples: ["A helmet is a requirement for cycling here.", "Passing the test is a requirement to move up."],
    emoji: "✅",
    syllables: "re-quire-ment",
    distractorGroup: "ideas",
  },
  {
    word: "resource",
    pos: "noun",
    kidMeaning: "Something useful that can be used to help you.",
    examples: ["Books are a great resource for learning.", "Water is an important resource for farmers."],
    emoji: "📚",
    syllables: "re-source",
    distractorGroup: "ideas",
  },
  {
    word: "respect",
    pos: "noun",
    kidMeaning: "A feeling of admiration for someone.",
    examples: ["She shows respect to her teachers.", "He has great respect for his grandfather."],
    emoji: "🙏",
    syllables: "re-spect",
    distractorGroup: "ideas",
  },
  {
    word: "result",
    pos: "noun",
    kidMeaning: "What happens because of something else.",
    examples: ["The result of the match was a tie.", "She was happy with her test result."],
    emoji: "🏁",
    syllables: "re-sult",
    distractorGroup: "ideas",
  },
  {
    word: "role",
    pos: "noun",
    kidMeaning: "The part someone plays in a group or a play.",
    examples: ["She has the main role in the school play.", "Each pupil has a role in the project."],
    emoji: "🎭",
    syllables: "role",
    distractorGroup: "ideas",
  },
  {
    word: "section",
    pos: "noun",
    kidMeaning: "One part of something bigger.",
    examples: ["This section of the book is about animals.", "She sits in the front section of the bus."],
    emoji: "📑",
    syllables: "sec-tion",
    distractorGroup: "ideas",
  },
  {
    word: "sense",
    pos: "noun",
    kidMeaning: "The ability to understand or feel something.",
    examples: ["She has a good sense of direction.", "His idea makes a lot of sense."],
    emoji: "🧠",
    syllables: "sense",
    distractorGroup: "ideas",
  },
  {
    word: "sequence",
    pos: "noun",
    kidMeaning: "A set of things in a certain order.",
    examples: ["Put the pictures in the correct sequence.", "She follows the sequence of steps carefully."],
    emoji: "🔢",
    syllables: "se-quence",
    distractorGroup: "ideas",
  },
  {
    word: "series",
    pos: "noun",
    kidMeaning: "A number of things that come one after another.",
    examples: ["She enjoys a whole series of adventure books.", "The show has a new series every year."],
    emoji: "📚",
    syllables: "se-ries",
    distractorGroup: "ideas",
  },
  {
    word: "situation",
    pos: "noun",
    kidMeaning: "What is happening at a certain time or place.",
    examples: ["The teacher handled the difficult situation calmly.", "It was an awkward situation at the party."],
    emoji: "🎬",
    syllables: "sit-u-a-tion",
    distractorGroup: "ideas",
  },
  {
    word: "skill",
    pos: "noun",
    kidMeaning: "The ability to do something well.",
    examples: ["Swimming is a useful skill to learn.", "She has great skill at drawing animals."],
    emoji: "🎨",
    syllables: "skill",
    distractorGroup: "ideas",
  },
  {
    word: "solution",
    pos: "noun",
    kidMeaning: "The answer to a problem.",
    examples: ["She found a clever solution to the puzzle.", "There is no easy solution to this problem."],
    emoji: "💡",
    syllables: "so-lu-tion",
    distractorGroup: "ideas",
  },
  {
    word: "source",
    pos: "noun",
    kidMeaning: "The place where something comes from.",
    examples: ["The sun is a source of light and heat.", "She found the source of the strange smell."],
    emoji: "🔦",
    syllables: "source",
    distractorGroup: "ideas",
  },
  {
    word: "stage",
    pos: "noun",
    kidMeaning: "A step in a process, or a raised platform.",
    examples: ["The chick is at an early stage of growth.", "She sang on the stage at the concert."],
    emoji: "🎭",
    syllables: "stage",
    distractorGroup: "ideas",
  },
  {
    word: "standard",
    pos: "noun",
    kidMeaning: "The usual level that something should reach.",
    examples: ["Her work meets a high standard.", "The school has a strict standard for uniforms."],
    emoji: "📏",
    syllables: "stan-dard",
    distractorGroup: "ideas",
  },
  {
    word: "statement",
    pos: "noun",
    kidMeaning: "Something said or written clearly.",
    examples: ["He made a bold statement in class.", "Her statement about the accident was clear."],
    emoji: "💬",
    syllables: "state-ment",
    distractorGroup: "ideas",
  },
  {
    word: "status",
    pos: "noun",
    kidMeaning: "A person's position or condition at a certain time.",
    examples: ["She checked the status of her parcel online.", "His status in the team changed after the match."],
    emoji: "📋",
    syllables: "sta-tus",
    distractorGroup: "ideas",
  },
  {
    word: "structure",
    pos: "noun",
    kidMeaning: "The way parts of something are put together.",
    examples: ["The structure of the story has a clear ending.", "The old bridge has a strong structure."],
    emoji: "🏗️",
    syllables: "struc-ture",
    distractorGroup: "ideas",
  },
  {
    word: "style",
    pos: "noun",
    kidMeaning: "The way something is made, done or worn.",
    examples: ["She has her own style of writing.", "He likes the style of the new shoes."],
    emoji: "👗",
    syllables: "style",
    distractorGroup: "ideas",
  },
  {
    word: "subject",
    pos: "noun",
    kidMeaning: "A topic that is talked about or studied.",
    examples: ["Maths is her favourite subject at school.", "They changed the subject during dinner."],
    emoji: "📖",
    syllables: "sub-ject",
    distractorGroup: "ideas",
  },
  {
    word: "substance",
    pos: "noun",
    kidMeaning: "A material or type of matter.",
    examples: ["The sticky substance on the floor was jam.", "Water is a substance found everywhere on Earth."],
    emoji: "🧪",
    syllables: "sub-stance",
    distractorGroup: "ideas",
  },
  {
    word: "suggestion",
    pos: "noun",
    kidMeaning: "An idea offered for others to think about.",
    examples: ["Her suggestion was to visit the museum.", "He made a helpful suggestion during the meeting."],
    emoji: "💡",
    syllables: "sug-ges-tion",
    spellingTip: "Double g: sug-gestion.",
    distractorGroup: "ideas",
  },
  {
    word: "summary",
    pos: "noun",
    kidMeaning: "A short account giving the main points.",
    examples: ["She wrote a summary of the storybook.", "The teacher gave a summary of the lesson."],
    emoji: "📝",
    syllables: "sum-ma-ry",
    distractorGroup: "ideas",
  },
  {
    word: "surface",
    pos: "noun",
    kidMeaning: "The outside or top part of something.",
    examples: ["The water's surface was calm and still.", "Dust covered the surface of the shelf."],
    emoji: "🌊",
    syllables: "sur-face",
    distractorGroup: "ideas",
  },
  {
    word: "system",
    pos: "noun",
    kidMeaning: "A set of parts that work together.",
    examples: ["The school has a new library system.", "Her body's system fights off the cold quickly."],
    emoji: "⚙️",
    syllables: "sys-tem",
    distractorGroup: "ideas",
  },
  {
    word: "target",
    pos: "noun",
    kidMeaning: "A goal you are trying to reach or hit.",
    examples: ["Her target is to read a book every week.", "The arrow hit the centre of the target."],
    emoji: "🎯",
    syllables: "tar-get",
    distractorGroup: "ideas",
  },
  {
    word: "task",
    pos: "noun",
    kidMeaning: "A piece of work that must be done.",
    examples: ["Cleaning her room is her weekend task.", "The group finished the task before lunch."],
    emoji: "📋",
    syllables: "task",
    distractorGroup: "ideas",
  },
  {
    word: "technique",
    pos: "noun",
    kidMeaning: "A special way of doing something skilfully.",
    examples: ["She learns a new technique for painting.", "His running technique improved after practice."],
    emoji: "🎨",
    syllables: "tech-nique",
    distractorGroup: "ideas",
  },
  {
    word: "tendency",
    pos: "noun",
    kidMeaning: "A habit of doing something often.",
    examples: ["He has a tendency to forget his keys.", "She has a tendency to talk very fast."],
    emoji: "🔁",
    syllables: "ten-den-cy",
    distractorGroup: "ideas",
  },
  {
    word: "theory",
    pos: "noun",
    kidMeaning: "An idea that explains why something happens.",
    examples: ["She has a theory about why the plant died.", "His theory about the missing sock was funny."],
    emoji: "💭",
    syllables: "the-o-ry",
    distractorGroup: "ideas",
  },
  {
    word: "tool",
    pos: "noun",
    kidMeaning: "Something used to help you do a job.",
    examples: ["A hammer is a useful tool for building.", "She keeps her art tools in a small box."],
    emoji: "🛠️",
    syllables: "tool",
    distractorGroup: "ideas",
  },
  {
    word: "topic",
    pos: "noun",
    kidMeaning: "The subject being talked or written about.",
    examples: ["The topic of her essay is the rainforest.", "They discussed a new topic in class today."],
    emoji: "📖",
    syllables: "top-ic",
    distractorGroup: "ideas",
  },
  {
    word: "type",
    pos: "noun",
    kidMeaning: "A group of things with the same features.",
    examples: ["This is a rare type of butterfly.", "She likes every type of fruit."],
    emoji: "🏷️",
    syllables: "type",
    distractorGroup: "ideas",
  },
  {
    word: "unit",
    pos: "noun",
    kidMeaning: "One single part of a bigger group.",
    examples: ["Each unit of the book covers one topic.", "The soldiers marched as a single unit."],
    emoji: "🧱",
    syllables: "u-nit",
    distractorGroup: "ideas",
  },
  {
    word: "value",
    pos: "noun",
    kidMeaning: "How much something is worth or matters.",
    examples: ["The old coin has great value.", "She understands the value of hard work."],
    emoji: "💎",
    syllables: "val-ue",
    distractorGroup: "ideas",
  },
  {
    word: "version",
    pos: "noun",
    kidMeaning: "One form of something that may have others.",
    examples: ["This is a shorter version of the story.", "He prefers the older version of the game."],
    emoji: "📖",
    syllables: "ver-sion",
    distractorGroup: "ideas",
  },
  {
    word: "view",
    pos: "noun",
    kidMeaning: "What you can see, or an opinion.",
    examples: ["The hill has a lovely view of the sea.", "She shared her view about the new rule."],
    emoji: "👀",
    syllables: "view",
    distractorGroup: "ideas",
  },
  {
    word: "way",
    pos: "noun",
    kidMeaning: "A method of doing something, or a path.",
    examples: ["There is a quick way to solve this sum.", "She knows the way to the library."],
    emoji: "🛤️",
    syllables: "way",
    distractorGroup: "ideas",
  },
  {
    word: "wish",
    pos: "noun",
    kidMeaning: "A hope or want for something to happen.",
    examples: ["She made a wish before blowing the candles.", "His biggest wish is to visit the zoo."],
    emoji: "🌠",
    syllables: "wish",
    distractorGroup: "ideas",
  },

  // ---- Linking adverbs ----
  {
    word: "absolutely",
    pos: "adverb",
    kidMeaning: "Completely; totally, without doubt.",
    examples: ["She is absolutely certain about the answer.", "The soup is absolutely delicious tonight."],
    emoji: "💯",
    syllables: "ab-so-lute-ly",
    distractorGroup: "linking words",
  },
  {
    word: "actually",
    pos: "adverb",
    kidMeaning: "In fact; really, in truth.",
    examples: ["He actually finished his homework early today.", "She is actually quite good at football."],
    emoji: "✅",
    syllables: "ac-tu-al-ly",
    distractorGroup: "linking words",
  },
  {
    word: "afterwards",
    pos: "adverb",
    kidMeaning: "At a later time; after something else happens.",
    examples: ["We had lunch and went home afterwards.", "She felt sleepy afterwards from all the running."],
    emoji: "⏭️",
    syllables: "af-ter-wards",
    distractorGroup: "linking words",
  },
  {
    word: "briefly",
    pos: "adverb",
    kidMeaning: "For a short time.",
    examples: ["She briefly explained the rules of the game.", "He stopped briefly to tie his shoelace."],
    emoji: "⏱️",
    syllables: "brief-ly",
    distractorGroup: "linking words",
  },
  {
    word: "certainly",
    pos: "adverb",
    kidMeaning: "Without any doubt; for sure.",
    examples: ["She will certainly come to the party.", "That is certainly the right answer."],
    emoji: "✔️",
    syllables: "cer-tain-ly",
    distractorGroup: "linking words",
  },
  {
    word: "clearly",
    pos: "adverb",
    kidMeaning: "In a way that is easy to see or understand.",
    examples: ["She spoke clearly so everyone could hear.", "The instructions were written clearly on the board."],
    emoji: "👀",
    syllables: "clear-ly",
    distractorGroup: "linking words",
  },
  {
    word: "completely",
    pos: "adverb",
    kidMeaning: "Fully; in every way.",
    examples: ["The bag was completely empty.", "He completely forgot about the meeting."],
    emoji: "💯",
    syllables: "com-plete-ly",
    distractorGroup: "linking words",
  },
  {
    word: "definitely",
    pos: "adverb",
    kidMeaning: "For certain; without any doubt at all.",
    examples: ["She will definitely be at the show.", "This is definitely the best cake I've tried."],
    emoji: "✔️",
    syllables: "def-i-nite-ly",
    distractorGroup: "linking words",
  },
  {
    word: "directly",
    pos: "adverb",
    kidMeaning: "In a straight line, or right away.",
    examples: ["Please come directly home after school.", "She spoke directly to the teacher about it."],
    emoji: "➡️",
    syllables: "di-rect-ly",
    distractorGroup: "linking words",
  },
  {
    word: "especially",
    pos: "adverb",
    kidMeaning: "More than usual; most of all.",
    examples: ["She loves fruit, especially mangoes.", "It was hot today, especially in the afternoon."],
    emoji: "⭐",
    syllables: "es-pe-cial-ly",
    distractorGroup: "linking words",
  },
  {
    word: "exactly",
    pos: "adverb",
    kidMeaning: "Precisely; in an exact way.",
    examples: ["She knew exactly what to say.", "He arrived exactly on time."],
    emoji: "🎯",
    syllables: "ex-act-ly",
    distractorGroup: "linking words",
  },
  {
    word: "extremely",
    pos: "adverb",
    kidMeaning: "Very, to a great degree.",
    examples: ["The soup was extremely hot.", "She was extremely happy about the surprise."],
    emoji: "🔥",
    syllables: "ex-treme-ly",
    distractorGroup: "linking words",
  },
  {
    word: "fairly",
    pos: "adverb",
    kidMeaning: "Quite; to some extent.",
    examples: ["The test was fairly easy for her.", "He is fairly good at chess."],
    emoji: "👍",
    syllables: "fair-ly",
    distractorGroup: "linking words",
  },
  {
    word: "finally",
    pos: "adverb",
    kidMeaning: "At last, after a long time.",
    examples: ["She finally finished her homework.", "The bus finally arrived after a long wait."],
    emoji: "🏁",
    syllables: "fi-nal-ly",
    distractorGroup: "linking words",
  },
  {
    word: "fortunately",
    pos: "adverb",
    kidMeaning: "Luckily; it was good that this happened.",
    examples: ["Fortunately, the rain stopped before the picnic.", "Fortunately, she found her lost key."],
    emoji: "🍀",
    syllables: "for-tu-nate-ly",
    distractorGroup: "linking words",
  },
  {
    word: "generally",
    pos: "adverb",
    kidMeaning: "Usually; in most cases.",
    examples: ["She generally walks to school with her friend.", "Generally, the weather here is warm."],
    emoji: "🌍",
    syllables: "gen-er-al-ly",
    distractorGroup: "linking words",
  },
  {
    word: "gradually",
    pos: "adverb",
    kidMeaning: "Slowly, little by little.",
    examples: ["The sky gradually turned dark.", "She gradually improved her spelling scores."],
    emoji: "🐌",
    syllables: "grad-u-al-ly",
    distractorGroup: "linking words",
  },
  {
    word: "hopefully",
    pos: "adverb",
    kidMeaning: "It is hoped that something will happen.",
    examples: ["Hopefully, the rain will stop soon.", "She hopefully waited for her name to be called."],
    emoji: "🤞",
    syllables: "hope-ful-ly",
    distractorGroup: "linking words",
  },
  {
    word: "however",
    pos: "adverb",
    kidMeaning: "But; even though something else happened.",
    examples: ["The rain was heavy. However, we still went out.", "She lost the race. However, she felt proud."],
    emoji: "🔀",
    syllables: "how-ev-er",
    distractorGroup: "linking words",
  },
  {
    word: "instead",
    pos: "adverb",
    kidMeaning: "In place of something else.",
    examples: ["She chose water instead of juice.", "He stayed home instead of going out."],
    emoji: "🔄",
    syllables: "in-stead",
    distractorGroup: "linking words",
  },
  {
    word: "mainly",
    pos: "adverb",
    kidMeaning: "Mostly; for the most part.",
    examples: ["The garden is mainly full of roses.", "She mainly reads adventure stories."],
    emoji: "👍",
    syllables: "main-ly",
    distractorGroup: "linking words",
  },
  {
    word: "meanwhile",
    pos: "adverb",
    kidMeaning: "At the same time as something else.",
    examples: ["He cooked dinner. Meanwhile, she set the table.", "Meanwhile, the dog waited by the door."],
    emoji: "⏳",
    syllables: "mean-while",
    distractorGroup: "linking words",
  },
  {
    word: "mostly",
    pos: "adverb",
    kidMeaning: "Mainly; most of the time.",
    examples: ["The class is mostly quiet during reading time.", "She mostly plays outside after school."],
    emoji: "👍",
    syllables: "most-ly",
    distractorGroup: "linking words",
  },
  {
    word: "nearly",
    pos: "adverb",
    kidMeaning: "Almost, but not quite.",
    examples: ["She is nearly finished with her homework.", "It is nearly time for dinner."],
    emoji: "⏳",
    syllables: "near-ly",
    distractorGroup: "linking words",
  },
  {
    word: "normally",
    pos: "adverb",
    kidMeaning: "Usually, as a general rule.",
    examples: ["She normally wakes up at seven.", "The shop is normally open on Sundays."],
    emoji: "🔄",
    syllables: "nor-mal-ly",
    distractorGroup: "linking words",
  },
  {
    word: "otherwise",
    pos: "adverb",
    kidMeaning: "If not; in a different way.",
    examples: ["Wear a coat, otherwise you will be cold.", "She had to walk, otherwise she would be late."],
    emoji: "🔀",
    syllables: "oth-er-wise",
    distractorGroup: "linking words",
  },
  {
    word: "perhaps",
    pos: "adverb",
    kidMeaning: "Maybe; possibly.",
    examples: ["Perhaps she will join us later.", "It will perhaps rain this weekend."],
    emoji: "🤷",
    syllables: "per-haps",
    distractorGroup: "linking words",
  },
  {
    word: "possibly",
    pos: "adverb",
    kidMeaning: "Maybe; it might happen.",
    examples: ["She could possibly win the race.", "It will possibly rain tomorrow."],
    emoji: "🤔",
    syllables: "pos-si-bly",
    distractorGroup: "linking words",
  },
  {
    word: "probably",
    pos: "adverb",
    kidMeaning: "Most likely; almost certainly.",
    examples: ["He is probably still asleep.", "She will probably come to the party."],
    emoji: "🤔",
    syllables: "prob-a-bly",
    distractorGroup: "linking words",
  },
  {
    word: "properly",
    pos: "adverb",
    kidMeaning: "In the correct or right way.",
    examples: ["She tied her shoelaces properly.", "Please chew your food properly."],
    emoji: "✅",
    syllables: "prop-er-ly",
    distractorGroup: "linking words",
  },
  {
    word: "rather",
    pos: "adverb",
    kidMeaning: "To some degree; more willingly.",
    examples: ["The soup is rather hot today.", "She would rather read than watch television."],
    emoji: "🤔",
    syllables: "rath-er",
    distractorGroup: "linking words",
  },
  {
    word: "recently",
    pos: "adverb",
    kidMeaning: "Not long ago.",
    examples: ["She recently moved to a new house.", "He has recently learned to swim."],
    emoji: "🕐",
    syllables: "re-cent-ly",
    distractorGroup: "linking words",
  },
  {
    word: "regularly",
    pos: "adverb",
    kidMeaning: "Happening often, at fixed times.",
    examples: ["She practises the piano regularly.", "He regularly walks his dog after school."],
    emoji: "🔁",
    syllables: "reg-u-lar-ly",
    distractorGroup: "linking words",
  },
  {
    word: "simply",
    pos: "adverb",
    kidMeaning: "Just; in a simple way.",
    examples: ["She simply forgot to bring her bag.", "It was simply a small mistake."],
    emoji: "👌",
    syllables: "sim-ply",
    distractorGroup: "linking words",
  },
  {
    word: "slightly",
    pos: "adverb",
    kidMeaning: "A little bit; not very much.",
    examples: ["The soup is slightly too salty.", "She is slightly taller than her brother."],
    emoji: "🔹",
    syllables: "slight-ly",
    distractorGroup: "linking words",
  },
];
