import type { Word } from "../words";

export const band5: Word[] = [
  { word: "ant", pos: "noun", kidMeaning: "A tiny insect that works in groups.", examples: ["The ant carries food.", "Ants build colonies."], emoji: "🐜", syllables: "ant", distractorGroup: "nature" },
  { word: "ape", pos: "noun", kidMeaning: "A large monkey with no tail.", examples: ["The ape is strong.", "Apes are intelligent."], emoji: "🦍", syllables: "ape", distractorGroup: "nature" },
  { word: "calf", pos: "noun", kidMeaning: "A young cow.", examples: ["The calf is with its mother.", "Calves are cute."], emoji: "🐄", syllables: "calf", distractorGroup: "nature" },
  { word: "camel", pos: "noun", kidMeaning: "A desert animal with humps.", examples: ["The camel stores water.", "Camels live in deserts."], emoji: "🐫", syllables: "cam-el", distractorGroup: "nature" },
  { word: "caterpillar", pos: "noun", kidMeaning: "A small worm that becomes a butterfly.", examples: ["The caterpillar eats leaves.", "Caterpillars are green."], emoji: "🐛", syllables: "cat-er-pil-lar", distractorGroup: "nature" },
  { word: "cheetah", pos: "noun", kidMeaning: "A fast hunting cat.", examples: ["The cheetah runs very fast.", "Cheetahs have spots."], emoji: "🐆", syllables: "chee-tah", distractorGroup: "nature" },
  { word: "chimpanzee", pos: "noun", kidMeaning: "A clever ape.", examples: ["The chimpanzee climbs trees.", "Chimpanzees are smart."], emoji: "🐵", syllables: "chim-pan-zee", distractorGroup: "nature" },
  { word: "coyote", pos: "noun", kidMeaning: "A wild dog-like animal.", examples: ["The coyote howls.", "Coyotes hunt at night."], emoji: "🐕", syllables: "coy-o-te", distractorGroup: "nature" },
  { word: "crab", pos: "noun", kidMeaning: "A sea animal with claws.", examples: ["The crab walks sideways.", "Crabs have hard shells."], emoji: "🦀", syllables: "crab", distractorGroup: "nature" },
  { word: "cricket", pos: "noun", kidMeaning: "A jumping insect that makes noise.", examples: ["The cricket chirps at night.", "Crickets are brown."], emoji: "🦗", syllables: "crick-et", distractorGroup: "nature" },
  { word: "crocodile", pos: "noun", kidMeaning: "A large reptile with teeth.", examples: ["The crocodile swims in water.", "Crocodiles are dangerous."], emoji: "🐊", syllables: "croc-o-dile", distractorGroup: "nature" },
  { word: "crow", pos: "noun", kidMeaning: "A black bird that caws.", examples: ["The crow is black.", "Crows eat seeds."], emoji: "🐦", syllables: "crow", distractorGroup: "nature" },
  { word: "deer", pos: "noun", kidMeaning: "An animal with antlers.", examples: ["The deer runs in the forest.", "Deer eat grass."], emoji: "🦌", syllables: "deer", distractorGroup: "nature" },
  { word: "dinosaur", pos: "noun", kidMeaning: "An ancient reptile.", examples: ["Dinosaurs are extinct.", "Dinosaurs were huge."], emoji: "🦖", syllables: "di-no-saur", distractorGroup: "nature" },
  { word: "dolphin", pos: "noun", kidMeaning: "A smart ocean animal.", examples: ["The dolphin jumps high.", "Dolphins are friendly."], emoji: "🐬", syllables: "dol-phin", distractorGroup: "nature" },
  { word: "donkey", pos: "noun", kidMeaning: "A small horse-like animal.", examples: ["The donkey is stubborn.", "Donkeys work on farms."], emoji: "🐴", syllables: "don-key", distractorGroup: "nature" },
  { word: "dragonfly", pos: "noun", kidMeaning: "A flying insect with long wings.", examples: ["The dragonfly is fast.", "Dragonflies live near water."], emoji: "🐉", syllables: "drag-on-fly", distractorGroup: "nature" },
  { word: "duck", pos: "noun", kidMeaning: "A water bird with webbed feet.", examples: ["The duck swims in the pond.", "Ducks quack loudly."], emoji: "🦆", syllables: "duck", distractorGroup: "nature" },
  { word: "eagle", pos: "noun", kidMeaning: "A large hunting bird.", examples: ["The eagle flies very high.", "Eagles have strong eyes."], emoji: "🦅", syllables: "ea-gle", distractorGroup: "nature" },
  { word: "eel", pos: "noun", kidMeaning: "A long fish.", examples: ["The eel is slimy.", "Eels look like snakes."], emoji: "🐍", syllables: "eel", distractorGroup: "nature" },
  { word: "elk", pos: "noun", kidMeaning: "A very large deer.", examples: ["The elk has big antlers.", "Elks are powerful."], emoji: "🦌", syllables: "elk", distractorGroup: "nature" },
  { word: "emu", pos: "noun", kidMeaning: "A large bird from Australia.", examples: ["The emu cannot fly.", "Emus run fast."], emoji: "🦆", syllables: "e-mu", distractorGroup: "nature" },
  { word: "falcon", pos: "noun", kidMeaning: "A fast hunting bird.", examples: ["The falcon dives fast.", "Falcons hunt birds."], emoji: "🦅", syllables: "fal-con", distractorGroup: "nature" },
  { word: "ferret", pos: "noun", kidMeaning: "A small furry animal.", examples: ["The ferret is playful.", "Ferrets are quick."], emoji: "🦡", syllables: "fer-ret", distractorGroup: "nature" },
  { word: "finch", pos: "noun", kidMeaning: "A small singing bird.", examples: ["The finch sings nicely.", "Finches are colourful."], emoji: "🐦", syllables: "finch", distractorGroup: "nature" },
  { word: "firefly", pos: "noun", kidMeaning: "An insect that lights up.", examples: ["The firefly glows in the dark.", "Fireflies are magical."], emoji: "🐝", syllables: "fire-fly", distractorGroup: "nature" },
  { word: "flamingo", pos: "noun", kidMeaning: "A pink wading bird.", examples: ["The flamingo is pink.", "Flamingos stand on one leg."], emoji: "🦩", syllables: "fla-min-go", distractorGroup: "nature" },
  { word: "flea", pos: "noun", kidMeaning: "A tiny jumping insect.", examples: ["Fleas jump on pets.", "Fleas are small."], emoji: "🦟", syllables: "flea", distractorGroup: "nature" },
  { word: "fly", pos: "noun", kidMeaning: "A small insect with wings.", examples: ["The fly buzzes around.", "A fly lands on food."], emoji: "🪰", syllables: "fly", distractorGroup: "nature" },
  { word: "foal", pos: "noun", kidMeaning: "A baby horse.", examples: ["The foal is with its mother.", "Foals are young."], emoji: "🐴", syllables: "foal", distractorGroup: "nature" },
  { word: "fox", pos: "noun", kidMeaning: "It is a wild animal like a dog.", examples: ["The fox is clever.", "Foxes hunt at night."], emoji: "🦊", syllables: "fox", distractorGroup: "nature" },
  { word: "frog", pos: "noun", kidMeaning: "An animal that lives in water and on land.", examples: ["The frog jumps high.", "Frogs croak loudly."], emoji: "🐸", syllables: "frog", distractorGroup: "nature" },
  { word: "giraffe", pos: "noun", kidMeaning: "A tall animal with a long neck.", examples: ["The giraffe eats from tall trees.", "Giraffes have spotted fur."], emoji: "🦒", syllables: "gi-raffe", distractorGroup: "nature" },
  { word: "goat", pos: "noun", kidMeaning: "A farm animal with horns.", examples: ["The goat jumps well.", "Goats eat grass."], emoji: "🐐", syllables: "goat", distractorGroup: "nature" },
  { word: "goldfish", pos: "noun", kidMeaning: "A small orange fish.", examples: ["The goldfish swims in a tank.", "Goldfish are pretty."], emoji: "🐠", syllables: "gold-fish", distractorGroup: "nature" },
  { word: "goose", pos: "noun", kidMeaning: "A large water bird.", examples: ["The goose honks loudly.", "The goose swims in water."], emoji: "🦆", syllables: "goose", distractorGroup: "nature" },
  { word: "gorilla", pos: "noun", kidMeaning: "A large ape.", examples: ["The gorilla is strong.", "Gorillas live in forests."], emoji: "🦍", syllables: "go-ril-la", distractorGroup: "nature" },
  { word: "grasshopper", pos: "noun", kidMeaning: "A jumping insect.", examples: ["The grasshopper jumps high.", "Grasshoppers are green."], emoji: "🦗", syllables: "grass-hop-per", distractorGroup: "nature" },
  { word: "acorn", pos: "noun", kidMeaning: "A seed from an oak tree.", examples: ["An acorn grows into an oak.", "Squirrels collect acorns."], emoji: "🌰", syllables: "a-corn", distractorGroup: "nature" },
  { word: "algae", pos: "noun", kidMeaning: "A green plant in water.", examples: ["Algae floats in the pond.", "Algae is a simple plant."], emoji: "🌿", syllables: "al-gae", distractorGroup: "nature" },
  { word: "aloe", pos: "noun", kidMeaning: "A plant that helps burnt skin.", examples: ["Aloe is soothing.", "Aloe vera helps burns."], emoji: "🌿", syllables: "a-loe", distractorGroup: "nature" },
  { word: "aster", pos: "noun", kidMeaning: "A small colourful flower.", examples: ["The aster is pretty.", "Asters bloom in autumn."], emoji: "🌸", syllables: "as-ter", distractorGroup: "nature" },
  { word: "azalea", pos: "noun", kidMeaning: "A colourful garden flower.", examples: ["The azalea is pink.", "Azaleas bloom in spring."], emoji: "🌸", syllables: "a-za-lea", distractorGroup: "nature" },
  { word: "basil", pos: "noun", kidMeaning: "A green herb used in cooking.", examples: ["Basil smells nice.", "Basil is used in Italian food."], emoji: "🌿", syllables: "ba-sil", distractorGroup: "nature" },
  { word: "branch", pos: "noun", kidMeaning: "A part of a tree with leaves.", examples: ["The branch bends in wind.", "Branches grow from trunk."], emoji: "🌳", syllables: "branch", distractorGroup: "nature" },
  { word: "bud", pos: "noun", kidMeaning: "The start of a flower or leaf.", examples: ["The bud opens into a flower.", "Buds appear in spring."], emoji: "🌱", syllables: "bud", distractorGroup: "nature" },
  { word: "bulb", pos: "noun", kidMeaning: "A round underground plant part.", examples: ["The bulb grows roots.", "Bulbs need water to grow."], emoji: "🌷", syllables: "bulb", distractorGroup: "nature" },
  { word: "buttercup", pos: "noun", kidMeaning: "A yellow flower.", examples: ["Buttercups are bright yellow.", "The buttercup shines."], emoji: "🌼", syllables: "but-ter-cup", distractorGroup: "nature" },
  { word: "cactus", pos: "noun", kidMeaning: "A prickly desert plant.", examples: ["The cactus stores water.", "Cacti have thorns."], emoji: "🌵", syllables: "cac-tus", distractorGroup: "nature" },
  { word: "cedar", pos: "noun", kidMeaning: "A tall evergreen tree.", examples: ["The cedar smells nice.", "Cedar wood is strong."], emoji: "🌲", syllables: "ce-dar", distractorGroup: "nature" },
  { word: "clover", pos: "noun", kidMeaning: "A small plant with round leaves.", examples: ["The clover has four leaves.", "Clover grows in grass."], emoji: "🍀", syllables: "clo-ver", distractorGroup: "nature" },
  { word: "corn", pos: "noun", kidMeaning: "A tall grain plant.", examples: ["The corn grows tall.", "Corn kernels are sweet."], emoji: "🌽", syllables: "corn", distractorGroup: "nature" },
  { word: "crocus", pos: "noun", kidMeaning: "A small spring flower.", examples: ["Crocus blooms early.", "Crocuses are purple."], emoji: "🌷", syllables: "cro-cus", distractorGroup: "nature" },
  { word: "daffodil", pos: "noun", kidMeaning: "A yellow spring flower.", examples: ["Daffodils bloom in spring.", "Daffodils are yellow."], emoji: "🌼", syllables: "daf-fo-dil", distractorGroup: "nature" },
  { word: "daisy", pos: "noun", kidMeaning: "A small white and yellow flower.", examples: ["The daisy is pretty.", "Daisies grow in grass."], emoji: "🌼", syllables: "dai-sy", distractorGroup: "nature" },
  { word: "dandelion", pos: "noun", kidMeaning: "A yellow flower that spreads seeds.", examples: ["The dandelion is yellow.", "Dandelions grow wild."], emoji: "🌼", syllables: "dan-de-li-on", distractorGroup: "nature" },
  { word: "elm", pos: "noun", kidMeaning: "A tall tree.", examples: ["Elm trees are large.", "Elm wood is hard."], emoji: "🌳", syllables: "elm", distractorGroup: "nature" },
  { word: "fern", pos: "noun", kidMeaning: "A green plant with feathery leaves.", examples: ["The fern likes shade.", "Ferns need moisture."], emoji: "🌿", syllables: "fern", distractorGroup: "nature" },
  { word: "fig", pos: "noun", kidMeaning: "A sweet fruit with many seeds.", examples: ["The fig is sweet.", "Figs grow on trees."], emoji: "🍃", syllables: "fig", distractorGroup: "nature" },
  { word: "fir", pos: "noun", kidMeaning: "An evergreen tree.", examples: ["Fir trees are green.", "Fir wood is useful."], emoji: "🌲", syllables: "fir", distractorGroup: "nature" },
  { word: "foxglove", pos: "noun", kidMeaning: "A tall flower with tubes.", examples: ["Foxglove has pink flowers.", "Foxglove grows tall."], emoji: "🌸", syllables: "fox-glove", distractorGroup: "nature" },
  { word: "fungus", pos: "noun", kidMeaning: "A plant-like organism like mushroom.", examples: ["Fungus grows on damp wood.", "Mushrooms are fungi."], emoji: "🍄", syllables: "fun-gus", distractorGroup: "nature" },
  { word: "gardenia", pos: "noun", kidMeaning: "A white fragrant flower.", examples: ["The gardenia smells lovely.", "Gardenias are white."], emoji: "🌸", syllables: "gar-de-nia", distractorGroup: "nature" },
  { word: "geranium", pos: "noun", kidMeaning: "A colourful flowering plant.", examples: ["Geraniums are red.", "Geraniums like sun."], emoji: "🌸", syllables: "ge-ra-ni-um", distractorGroup: "nature" },
  { word: "ginger", pos: "noun", kidMeaning: "A plant with spicy roots.", examples: ["Ginger tastes spicy.", "Ginger is used in cooking."], emoji: "🌿", syllables: "gin-ger", distractorGroup: "nature" },
  { word: "calm", pos: "adjective", kidMeaning: "Not windy or stormy.", examples: ["The calm sea is peaceful.", "Calm weather is nice."], emoji: "🌊", syllables: "calm", distractorGroup: "nature" },
  { word: "drought", pos: "noun", kidMeaning: "A long time without rain.", examples: ["The drought dried the land.", "Drought harms crops."], emoji: "🏜️", syllables: "drought", distractorGroup: "nature" },
  { word: "fog", pos: "noun", kidMeaning: "Thick mist.", examples: ["The fog hides the road.", "Fog makes it cold and wet."], emoji: "🌫️", syllables: "fog", distractorGroup: "nature" },
  { word: "freeze", pos: "verb", kidMeaning: "To turn into ice.", examples: ["Water freezes in winter.", "Ice cream freezes hard."], emoji: "❄️", syllables: "freeze", distractorGroup: "nature" },
  { word: "frost", pos: "noun", kidMeaning: "Ice crystals on ground.", examples: ["Frost covers the grass.", "Frost appears at night."], emoji: "❄️", syllables: "frost", distractorGroup: "nature" },
  { word: "hail", pos: "noun", kidMeaning: "Balls of ice from clouds.", examples: ["Hail falls in summer storms.", "Hail makes loud noise."], emoji: "🌨️", syllables: "hail", distractorGroup: "nature" },
  { word: "heat", pos: "noun", kidMeaning: "Warmth.", examples: ["The heat of the sun burns.", "Heat makes you sweat."], emoji: "🔥", syllables: "heat", distractorGroup: "nature" },
  { word: "melt", pos: "verb", kidMeaning: "To turn from solid to liquid.", examples: ["Ice melts in warmth.", "Heat melts chocolate."], emoji: "🔥", syllables: "melt", distractorGroup: "nature" },
  { word: "mist", pos: "noun", kidMeaning: "Light fog.", examples: ["The mist covers the valley.", "Mist hides the view."], emoji: "🌫️", syllables: "mist", distractorGroup: "nature" },
  { word: "season", pos: "noun", kidMeaning: "A time of year.", examples: ["Autumn is my favourite season.", "Each season is different."], emoji: "🍂", syllables: "sea-son", distractorGroup: "nature" },
  { word: "storm", pos: "noun", kidMeaning: "Rough weather with wind and rain.", examples: ["The storm is loud and scary.", "Storms damage trees."], emoji: "⛈️", syllables: "storm", distractorGroup: "nature" },
  { word: "cave", pos: "noun", kidMeaning: "A hole in a mountain.", examples: ["The cave is dark inside.", "Caves are cool and damp."], emoji: "🕳️", syllables: "cave", distractorGroup: "nature" },
  { word: "cliff", pos: "noun", kidMeaning: "A steep rock face.", examples: ["The cliff is very high.", "Cliffs overlook the sea."], emoji: "⛰️", syllables: "cliff", distractorGroup: "nature" },
  { word: "coast", pos: "noun", kidMeaning: "The edge of land by sea.", examples: ["The coast has rocks.", "Coasts have beaches."], emoji: "🏖️", syllables: "coast", distractorGroup: "nature" },
  { word: "glacier", pos: "noun", kidMeaning: "A huge ice sheet.", examples: ["The glacier is very cold.", "Glaciers move slowly."], emoji: "🧊", syllables: "gla-cier", distractorGroup: "nature" },
  { word: "hill", pos: "noun", kidMeaning: "A small mountain.", examples: ["The hill is not very high.", "Hills are rounded."], emoji: "⛰️", syllables: "hill", distractorGroup: "nature" },
  { word: "ocean", pos: "noun", kidMeaning: "The very large sea.", examples: ["The ocean is vast.", "Oceans have many fish."], emoji: "🌊", syllables: "o-cean", distractorGroup: "nature" },
  { word: "rock", pos: "noun", kidMeaning: "A hard stone.", examples: ["The rock is hard.", "Rocks last forever."], emoji: "🪨", syllables: "rock", distractorGroup: "nature" },
  { word: "shore", pos: "noun", kidMeaning: "The edge of water.", examples: ["The shore is sandy.", "Shells wash on shore."], emoji: "🏖️", syllables: "shore", distractorGroup: "nature" },
  { word: "volcano", pos: "noun", kidMeaning: "A mountain that erupts.", examples: ["The volcano is dangerous.", "Volcanoes have lava."], emoji: "🌋", syllables: "vol-ca-no", distractorGroup: "nature" },
  { word: "waterfall", pos: "noun", kidMeaning: "Water falling from high.", examples: ["The waterfall is beautiful.", "Waterfalls roar loudly."], emoji: "💧", syllables: "wa-ter-fall", distractorGroup: "nature" },
  { word: "comet", pos: "noun", kidMeaning: "An icy object in space.", examples: ["The comet has a tail.", "Comets orbit the sun."], emoji: "☄️", syllables: "com-et", distractorGroup: "nature" },
  { word: "galaxy", pos: "noun", kidMeaning: "A large group of stars in space.", examples: ["The galaxy is very far.", "Galaxies have many stars."], emoji: "⭐", syllables: "gal-ax-y", distractorGroup: "nature" },
  { word: "earth", pos: "noun", kidMeaning: "The planet we live on.", examples: ["Earth has water.", "Earth is our home."], emoji: "🌍", syllables: "earth", distractorGroup: "nature" },
  { word: "gravity", pos: "noun", kidMeaning: "The force pulling down.", examples: ["Gravity keeps you on ground.", "Gravity pulls objects down."], emoji: "⬇️", syllables: "grav-i-ty", distractorGroup: "nature" },
  { word: "meteor", pos: "noun", kidMeaning: "A space rock burning up.", examples: ["The meteor lights the sky.", "Meteors fall fast."], emoji: "☄️", syllables: "me-te-or", distractorGroup: "nature" },
  { word: "orbit", pos: "noun", kidMeaning: "A path around something.", examples: ["The orbit is circular.", "Planets have orbits."], emoji: "🪐", syllables: "or-bit", distractorGroup: "nature" },
  { word: "planet", pos: "noun", kidMeaning: "A large round object in space.", examples: ["Planet Earth is our home.", "Planets orbit the sun."], emoji: "🪐", syllables: "plan-et", distractorGroup: "nature" },
  { word: "satellite", pos: "noun", kidMeaning: "An object orbiting a planet.", examples: ["A satellite orbits earth.", "Satellites send signals."], emoji: "🛰️", syllables: "sat-el-lite", distractorGroup: "nature" },
  { word: "universe", pos: "noun", kidMeaning: "Everything in space.", examples: ["The universe is huge.", "Universe has galaxies."], emoji: "🌌", syllables: "u-ni-verse", distractorGroup: "nature" },
  { word: "cardboard", pos: "noun", kidMeaning: "Thick paper.", examples: ["Cardboard makes boxes.", "Cardboard is stiff."], emoji: "📦", syllables: "card-board", distractorGroup: "nature" },
  { word: "clay", pos: "noun", kidMeaning: "Soft earth that hardens.", examples: ["Clay is soft and wet.", "Clay hardens when dry."], emoji: "🪶", syllables: "clay", distractorGroup: "nature" },
  { word: "cloth", pos: "noun", kidMeaning: "Woven material.", examples: ["Cloth makes clothes.", "Cloth is soft."], emoji: "🧵", syllables: "cloth", distractorGroup: "nature" },
  { word: "gold", pos: "noun", kidMeaning: "A precious yellow metal.", examples: ["Gold is shiny and rare.", "Gold is very valuable."], emoji: "🪙", syllables: "gold", distractorGroup: "nature" },
  { word: "iron", pos: "noun", kidMeaning: "A strong metal.", examples: ["Iron makes strong things.", "Iron is heavy."], emoji: "⚙️", syllables: "i-ron", distractorGroup: "nature" },
  { word: "silver", pos: "noun", kidMeaning: "A shiny white metal.", examples: ["Silver is shiny.", "Silver is valuable."], emoji: "🪙", syllables: "sil-ver", distractorGroup: "nature" },
  { word: "ankle", pos: "noun", kidMeaning: "The joint between foot and leg.", examples: ["The ankle bends.", "Ankles support your body."], emoji: "🦵", syllables: "an-kle", distractorGroup: "nature" },
  { word: "chin", pos: "noun", kidMeaning: "The lower part of the face.", examples: ["The chin sticks out.", "Chins have dimples."], emoji: "😊", syllables: "chin", distractorGroup: "nature" },
  { word: "finger", pos: "noun", kidMeaning: "One of five on each hand.", examples: ["You have ten fingers.", "Fingers are useful."], emoji: "✋", syllables: "fin-ger", distractorGroup: "nature" },
  { word: "heartbeat", pos: "noun", kidMeaning: "The pulse of the heart.", examples: ["Your heartbeat is fast.", "Heartbeats show life."], emoji: "❤️", syllables: "heart-beat", distractorGroup: "nature" },
  { word: "lung", pos: "noun", kidMeaning: "The body part for breathing.", examples: ["Lungs take in air.", "Lungs help you breathe."], emoji: "🫁", syllables: "lung", distractorGroup: "nature" },
  { word: "muscle", pos: "noun", kidMeaning: "The soft tissue that moves body.", examples: ["Muscles make you strong.", "Muscles help you move."], emoji: "💪", syllables: "mus-cle", distractorGroup: "nature" },
  { word: "skin", pos: "noun", kidMeaning: "The outer covering of body.", examples: ["Skin protects inside.", "Skin is the largest organ."], emoji: "🫀", syllables: "skin", distractorGroup: "nature" },
  { word: "sweat", pos: "noun", kidMeaning: "Water from the skin.", examples: ["Sweat comes when hot.", "Sweat cools your body."], emoji: "💧", syllables: "sweat", distractorGroup: "nature" },
  { word: "thumb", pos: "noun", kidMeaning: "The thick finger.", examples: ["Thumbs are strong.", "Thumbs help you grip."], emoji: "👍", syllables: "thumb", distractorGroup: "nature" },
  { word: "toe", pos: "noun", kidMeaning: "One of five on each foot.", examples: ["Toes help you balance.", "Toes wiggle."], emoji: "🦶", syllables: "toe", distractorGroup: "nature" },
  { word: "wrist", pos: "noun", kidMeaning: "Joint between hand and arm.", examples: ["Wrists bend easily.", "Watches go on wrists."], emoji: "⌚", syllables: "wrist", distractorGroup: "nature" },
  { word: "allergy", pos: "noun", kidMeaning: "Bad reaction to something.", examples: ["An allergy makes you sneeze.", "Allergies are uncomfortable."], emoji: "🤧", syllables: "al-ler-gy", distractorGroup: "nature" },
  { word: "fever", pos: "noun", kidMeaning: "Higher body temperature.", examples: ["A fever means you are sick.", "Fever makes you hot."], emoji: "🤒", syllables: "fe-ver", distractorGroup: "nature" },
  { word: "exercise", pos: "noun", kidMeaning: "Moving to get stronger.", examples: ["Exercise makes you healthy.", "Exercise is fun."], emoji: "🏃", syllables: "ex-er-cise", distractorGroup: "nature" },
  { word: "germ", pos: "noun", kidMeaning: "A tiny thing that makes sick.", examples: ["Germs spread sickness.", "Germs are invisible."], emoji: "🦠", syllables: "germ", distractorGroup: "nature" },
  { word: "healthy", pos: "adjective", kidMeaning: "Not sick.", examples: ["Healthy food is good.", "Healthy people are strong."], emoji: "💚", syllables: "health-y", distractorGroup: "nature" },
  { word: "medicine", pos: "noun", kidMeaning: "Something to make you well.", examples: ["Medicine helps you heal.", "Medicine tastes bitter."], emoji: "💊", syllables: "med-i-cine", distractorGroup: "nature" },
  { word: "vaccine", pos: "noun", kidMeaning: "Medicine that prevents sickness.", examples: ["Vaccines protect you.", "Vaccines stop diseases."], emoji: "💉", syllables: "vac-cine", distractorGroup: "nature" },
  { word: "boil", pos: "verb", kidMeaning: "To heat until bubbles.", examples: ["Water boils at hot temps.", "Boiling makes steam."], emoji: "🔥", syllables: "boil", distractorGroup: "nature" },
  { word: "breathe", pos: "verb", kidMeaning: "To take in air.", examples: ["Breathe in and out.", "Breathing gives life."], emoji: "💨", syllables: "breathe", distractorGroup: "nature" },
  { word: "burn", pos: "verb", kidMeaning: "To destroy with heat.", examples: ["Fire burns wood.", "Burning makes smoke."], emoji: "🔥", syllables: "burn", distractorGroup: "nature" },
  { word: "dissolve", pos: "verb", kidMeaning: "To mix into liquid.", examples: ["Sugar dissolves in water.", "Dissolve means disappear."], emoji: "💧", syllables: "dis-solve", distractorGroup: "nature" },
  { word: "float", pos: "verb", kidMeaning: "To stay on liquid.", examples: ["Boats float on water.", "Floating means not sinking."], emoji: "🚤", syllables: "float", distractorGroup: "nature" },
  { word: "flow", pos: "verb", kidMeaning: "To move like water.", examples: ["Water flows downhill.", "Flow means movement."], emoji: "💧", syllables: "flow", distractorGroup: "nature" },
  { word: "glow", pos: "verb", kidMeaning: "To shine softly.", examples: ["Stars glow at night.", "Glowing means bright."], emoji: "✨", syllables: "glow", distractorGroup: "nature" },
  { word: "mix", pos: "verb", kidMeaning: "To combine together.", examples: ["Mix red and blue.", "Mixing makes new colour."], emoji: "🎨", syllables: "mix", distractorGroup: "nature" },
  { word: "reflect", pos: "verb", kidMeaning: "To bounce back light.", examples: ["Mirrors reflect light.", "Reflecting bounces back."], emoji: "✨", syllables: "re-flect", distractorGroup: "nature" },
  { word: "sink", pos: "verb", kidMeaning: "To go down in water.", examples: ["Heavy things sink.", "Sinking means going down."], emoji: "⬇️", syllables: "sink", distractorGroup: "nature" },
  { word: "centimetre", pos: "noun", kidMeaning: "It is a small length measure.", examples: ["A centimetre is small.", "Centimetres measure length."], emoji: "📏", syllables: "cen-ti-me-tre", distractorGroup: "nature" },
  { word: "degree", pos: "noun", kidMeaning: "A measure of temperature.", examples: ["Temperature is twenty degrees.", "Degrees show heat level."], emoji: "🌡️", syllables: "de-gree", distractorGroup: "nature" },
  { word: "gram", pos: "noun", kidMeaning: "It is a small weight measure.", examples: ["A gram is light.", "Grams measure weight."], emoji: "⚖️", syllables: "gram", distractorGroup: "nature" },
  { word: "kilogram", pos: "noun", kidMeaning: "It is a heavy weight measure.", examples: ["A kilogram is heavy.", "Kilograms weigh things."], emoji: "⚖️", syllables: "kil-o-gram", distractorGroup: "nature" },
  { word: "kilometre", pos: "noun", kidMeaning: "It is a long distance measure.", examples: ["Kilometre is very far.", "Kilometres measure roads."], emoji: "📏", syllables: "kil-o-me-tre", distractorGroup: "nature" },
  { word: "litre", pos: "noun", kidMeaning: "A measure of liquid.", examples: ["A litre holds liquid.", "Litres measure volume."], emoji: "🥛", syllables: "li-tre", distractorGroup: "nature" },
  { word: "measure", pos: "verb", kidMeaning: "To find size.", examples: ["Measure with a ruler.", "Measuring finds length."], emoji: "📏", syllables: "meas-ure", distractorGroup: "nature" },
  { word: "metre", pos: "noun", kidMeaning: "It is a length measure.", examples: ["A metre is one hundred centimetres.", "Metres measure length."], emoji: "📏", syllables: "me-tre", distractorGroup: "nature" },
  { word: "scale", pos: "noun", kidMeaning: "A machine to weigh.", examples: ["The scale shows weight.", "Scales measure heaviness."], emoji: "⚖️", syllables: "scale", distractorGroup: "nature" },
  { word: "amphibian", pos: "noun", kidMeaning: "An animal that lives in water and on land.", examples: ["A frog is an amphibian.", "Salamanders are amphibians."], emoji: "🦎", syllables: "am-phib-i-an", distractorGroup: "nature" },
  { word: "anchor", pos: "noun", kidMeaning: "A heavy metal that holds boats.", examples: ["The anchor holds the ship.", "Anchors drop in water."], emoji: "⚓", syllables: "an-chor", distractorGroup: "nature" },
  { word: "animal", pos: "noun", kidMeaning: "A living creature.", examples: ["An animal needs food.", "Animals can move."], emoji: "🐾", syllables: "an-i-mal", distractorGroup: "nature" },
  { word: "antelope", pos: "noun", kidMeaning: "A fast running animal.", examples: ["The antelope runs fast.", "Antelopes have horns."], emoji: "🦌", syllables: "an-te-lope", distractorGroup: "nature" },
  { word: "backbone", pos: "noun", kidMeaning: "The spine inside the body.", examples: ["Your backbone is straight.", "Backbones support you."], emoji: "🦴", syllables: "back-bone", distractorGroup: "nature" },
  { word: "beech", pos: "noun", kidMeaning: "A type of tree.", examples: ["Beech trees are large.", "Beech wood is hard."], emoji: "🌳", syllables: "beech", distractorGroup: "nature" },
  { word: "bog", pos: "noun", kidMeaning: "Wet swampy ground.", examples: ["The bog is muddy.", "Bogs are wet places."], emoji: "🪱", syllables: "bog", distractorGroup: "nature" },
  { word: "bony", pos: "adjective", kidMeaning: "Having many bones.", examples: ["Fish are bony.", "Bony means thin."], emoji: "🦴", syllables: "bo-ny", distractorGroup: "nature" },
  { word: "boot", pos: "noun", kidMeaning: "A foot covering.", examples: ["Boots keep feet warm.", "Boots are sturdy."], emoji: "👢", syllables: "boot", distractorGroup: "nature" },
  { word: "branching", pos: "verb", kidMeaning: "Splitting into parts.", examples: ["Trees are branching.", "Branching means dividing."], emoji: "🌳", syllables: "branch-ing", distractorGroup: "nature" },
  { word: "breed", pos: "verb", kidMeaning: "To have babies.", examples: ["Rabbits breed fast.", "Breeding makes babies."], emoji: "🐰", syllables: "breed", distractorGroup: "nature" },
  { word: "brick", pos: "noun", kidMeaning: "A hard building block.", examples: ["Bricks are red.", "Bricks build walls."], emoji: "🧱", syllables: "brick", distractorGroup: "nature" },
  { word: "brittle", pos: "adjective", kidMeaning: "Breaks easily.", examples: ["Brittle means fragile.", "Brittle branches snap."], emoji: "🍂", syllables: "brit-tle", distractorGroup: "nature" },
  { word: "broad", pos: "adjective", kidMeaning: "Very wide.", examples: ["Broad means wide.", "Broad rivers are big."], emoji: "🌊", syllables: "broad", distractorGroup: "nature" },
  { word: "buffer", pos: "noun", kidMeaning: "Something that protects.", examples: ["A buffer stops impacts.", "Buffers absorb force."], emoji: "🛡️", syllables: "buf-fer", distractorGroup: "nature" },
  { word: "bulge", pos: "verb", kidMeaning: "To swell out.", examples: ["The pocket bulges.", "Bulging means swelling."], emoji: "🔴", syllables: "bulge", distractorGroup: "nature" },
  { word: "bulk", pos: "noun", kidMeaning: "The size or mass.", examples: ["Bulk means large size.", "Bulk matters."], emoji: "📦", syllables: "bulk", distractorGroup: "nature" },
  { word: "bunch", pos: "noun", kidMeaning: "A group together.", examples: ["A bunch of grapes.", "Bunches are groups."], emoji: "🍇", syllables: "bunch", distractorGroup: "nature" },
  { word: "bush", pos: "noun", kidMeaning: "A thick plant.", examples: ["The bush is green.", "Bushes have leaves."], emoji: "🌿", syllables: "bush", distractorGroup: "nature" },
  { word: "cell", pos: "noun", kidMeaning: "The smallest living unit.", examples: ["Cells make up bodies.", "Cells are tiny."], emoji: "🧬", syllables: "cell", distractorGroup: "nature" },
  { word: "chalk", pos: "noun", kidMeaning: "A white writing substance.", examples: ["Chalk draws on boards.", "Chalk is soft."], emoji: "✏️", syllables: "chalk", distractorGroup: "nature" },
  { word: "chart", pos: "noun", kidMeaning: "A map or graph.", examples: ["The chart shows data.", "Charts display info."], emoji: "📊", syllables: "chart", distractorGroup: "nature" },
  { word: "chemical", pos: "noun", kidMeaning: "A substance.", examples: ["Water is a chemical.", "Chemicals mix."], emoji: "🧪", syllables: "chem-i-cal", distractorGroup: "nature" },
  { word: "chew", pos: "verb", kidMeaning: "To bite and grind.", examples: ["Chew your food.", "Chewing breaks it down."], emoji: "😋", syllables: "chew", distractorGroup: "nature" },
  { word: "chimp", pos: "noun", kidMeaning: "A short name for chimpanzee.", examples: ["The chimp swings.", "Chimps are clever."], emoji: "🐵", syllables: "chimp", distractorGroup: "nature" },
  { word: "chip", pos: "noun", kidMeaning: "A small piece broken off.", examples: ["A chip of wood.", "Chips are small."], emoji: "💎", syllables: "chip", distractorGroup: "nature" },
  { word: "chord", pos: "noun", kidMeaning: "Musical notes together.", examples: ["The chord sounds nice.", "Chords have three notes."], emoji: "🎵", syllables: "chord", distractorGroup: "nature" },
  { word: "chosen", pos: "adjective", kidMeaning: "Selected or picked.", examples: ["The chosen one.", "Chosen means picked."], emoji: "✓", syllables: "cho-sen", distractorGroup: "nature" },
  { word: "chunk", pos: "noun", kidMeaning: "A thick piece.", examples: ["A chunk of bread.", "Chunks are large."], emoji: "📦", syllables: "chunk", distractorGroup: "nature" },
  { word: "circuit", pos: "noun", kidMeaning: "A complete path.", examples: ["The circuit is closed.", "Circuits conduct electricity."], emoji: "⚡", syllables: "cir-cuit", distractorGroup: "nature" },
  { word: "circulation", pos: "noun", kidMeaning: "The movement of blood.", examples: ["Blood circulation is vital.", "Circulation keeps you alive."], emoji: "❤️", syllables: "cir-cu-la-tion", distractorGroup: "nature" },
  { word: "coil", pos: "noun", kidMeaning: "A loop of rope.", examples: ["The coil is tight.", "Coils are spirals."], emoji: "🔄", syllables: "coil", distractorGroup: "nature" },
  { word: "reptile", pos: "noun", kidMeaning: "An animal with scales and cold blood.", examples: ["Reptiles like snakes are scaly.", "Reptiles need sun to warm."], emoji: "🦎", syllables: "rep-tile", distractorGroup: "nature" },
  { word: "collapse", pos: "verb", kidMeaning: "To fall down.", examples: ["The building collapsed.", "Collapsing means falling."], emoji: "💥", syllables: "col-lapse", distractorGroup: "nature" },
  { word: "colony", pos: "noun", kidMeaning: "A group living together.", examples: ["An ant colony.", "Colonies are communities."], emoji: "🏘️", syllables: "col-o-ny", distractorGroup: "nature" },
  { word: "command", pos: "verb", kidMeaning: "To order.", examples: ["Command the troops.", "Commanding means ordering."], emoji: "🎖️", syllables: "com-mand", distractorGroup: "nature" },
  { word: "common", pos: "adjective", kidMeaning: "Found often.", examples: ["Common means usual.", "Common birds are sparrows."], emoji: "🐦", syllables: "com-mon", distractorGroup: "nature" },
  { word: "companion", pos: "noun", kidMeaning: "A friend.", examples: ["A companion is a friend.", "Companions help."], emoji: "👥", syllables: "com-pan-ion", distractorGroup: "nature" },
  { word: "compare", pos: "verb", kidMeaning: "To look at differences.", examples: ["Compare these.", "Comparing looks at both."], emoji: "⚖️", syllables: "com-pare", distractorGroup: "nature" },
  { word: "compass", pos: "noun", kidMeaning: "A tool showing directions.", examples: ["The compass points north.", "Compasses find direction."], emoji: "🧭", syllables: "com-pass", distractorGroup: "nature" },
  { word: "complete", pos: "adjective", kidMeaning: "Having all parts.", examples: ["Complete means finished.", "Complete sets are full."], emoji: "✓", syllables: "com-plete", distractorGroup: "nature" },
  { word: "complex", pos: "adjective", kidMeaning: "Difficult to understand.", examples: ["Complex means hard.", "Complex systems have parts."], emoji: "🧩", syllables: "com-plex", distractorGroup: "nature" },
  { word: "concentrate", pos: "verb", kidMeaning: "To focus attention.", examples: ["Concentrate on work.", "Concentrating means focusing."], emoji: "🧠", syllables: "con-cen-trate", distractorGroup: "nature" },
  { word: "concern", pos: "verb", kidMeaning: "To matter to.", examples: ["It concerns me.", "Concerning means worrying."], emoji: "😟", syllables: "con-cern", distractorGroup: "nature" },
  { word: "concrete", pos: "noun", kidMeaning: "Hard material used to build.", examples: ["Concrete is hard.", "Concrete sidewalks."], emoji: "🪨", syllables: "con-crete", distractorGroup: "nature" },
  { word: "condition", pos: "noun", kidMeaning: "A situation or state.", examples: ["Good condition means healthy.", "Conditions vary."], emoji: "📊", syllables: "con-di-tion", distractorGroup: "nature" },
  { word: "conduct", pos: "verb", kidMeaning: "To carry or guide.", examples: ["Conduct the orchestra.", "Conducting means leading."], emoji: "🎵", syllables: "con-duct", distractorGroup: "nature" },
  { word: "cone", pos: "noun", kidMeaning: "A shape pointed at one end.", examples: ["A pine cone.", "Cones are pointed."], emoji: "🌲", syllables: "cone", distractorGroup: "nature" },
  { word: "confirm", pos: "verb", kidMeaning: "To say it is true.", examples: ["Confirm your answer.", "Confirming means verifying."], emoji: "✓", syllables: "con-firm", distractorGroup: "nature" },
  { word: "confuse", pos: "verb", kidMeaning: "To make unclear.", examples: ["Confuse the issue.", "Confusing means unclear."], emoji: "🤔", syllables: "con-fuse", distractorGroup: "nature" },
  { word: "connect", pos: "verb", kidMeaning: "To join together.", examples: ["Connect the dots.", "Connecting means linking."], emoji: "🔗", syllables: "con-nect", distractorGroup: "nature" },
  { word: "wildlife", pos: "noun", kidMeaning: "Animals and plants in nature.", examples: ["Wildlife lives in forests.", "Wildlife needs protection."], emoji: "🌿", syllables: "wild-life", distractorGroup: "nature" },
  { word: "conserve", pos: "verb", kidMeaning: "To save.", examples: ["Conserve water.", "Conserving saves things."], emoji: "💧", syllables: "con-serve", distractorGroup: "nature" },
  { word: "consider", pos: "verb", kidMeaning: "To think about.", examples: ["Consider your options.", "Considering means thinking."], emoji: "🤔", syllables: "con-sid-er", distractorGroup: "nature" },
  { word: "hoof", pos: "noun", kidMeaning: "The hard part of an animal's foot.", examples: ["The horse has hard hooves.", "Hooves help animals walk."], emoji: "🐴", syllables: "hoof", distractorGroup: "nature" },
  { word: "mane", pos: "noun", kidMeaning: "Long hair on an animal's neck.", examples: ["The lion has a big mane.", "Manes are thick and long."], emoji: "🦁", syllables: "mane", distractorGroup: "nature" },
  { word: "tusk", pos: "noun", kidMeaning: "A long pointed tooth.", examples: ["Elephants have tusks.", "Tusks are white and long."], emoji: "🐘", syllables: "tusk", distractorGroup: "nature" },
  { word: "gill", pos: "noun", kidMeaning: "Part of a fish for breathing.", examples: ["Fish use gills to breathe.", "Gills take oxygen from water."], emoji: "🐟", syllables: "gill", distractorGroup: "nature" },
  { word: "snout", pos: "noun", kidMeaning: "The front face part of an animal.", examples: ["The pig's snout is pink.", "Snouts help animals smell."], emoji: "🐷", syllables: "snout", distractorGroup: "nature" },
  { word: "fur", pos: "noun", kidMeaning: "Hair covering an animal.", examples: ["The cat has soft fur.", "Fur keeps animals warm."], emoji: "🐱", syllables: "fur", distractorGroup: "nature" },
  { word: "wing", pos: "noun", kidMeaning: "Body part for flying.", examples: ["The bird's wing is strong.", "Wings help birds move."], emoji: "🦅", syllables: "wing", distractorGroup: "nature" },
  { word: "paw", pos: "noun", kidMeaning: "The foot of an animal.", examples: ["The dog's paw is soft.", "Paws have pads."], emoji: "🐾", syllables: "paw", distractorGroup: "nature" },
  { word: "den", pos: "noun", kidMeaning: "A wild animal's home.", examples: ["The bear lives in a den.", "Dens are dark places."], emoji: "🏠", syllables: "den", distractorGroup: "nature" },
  { word: "herd", pos: "noun", kidMeaning: "A group of animals.", examples: ["The cattle form a herd.", "Herds stay together."], emoji: "🐄", syllables: "herd", distractorGroup: "nature" },
  { word: "flock", pos: "noun", kidMeaning: "A group of birds.", examples: ["The flock flies together.", "Flocks move fast."], emoji: "🐦", syllables: "flock", distractorGroup: "nature" },
  { word: "swarm", pos: "noun", kidMeaning: "A group of insects.", examples: ["The bees form a swarm.", "Swarms are very active."], emoji: "🐝", syllables: "swarm", distractorGroup: "nature" },
  { word: "pod", pos: "noun", kidMeaning: "A group of whales.", examples: ["The whale pod is large.", "Pods live together."], emoji: "🐋", syllables: "pod", distractorGroup: "nature" },
  { word: "graze", pos: "verb", kidMeaning: "To eat grass from ground.", examples: ["Cows graze in the field.", "Grazing keeps cows fed."], emoji: "🌾", syllables: "graze", distractorGroup: "nature" },
  { word: "hatch", pos: "verb", kidMeaning: "To come out of an egg.", examples: ["Chicks hatch in spring.", "Hatching means born."], emoji: "🐣", syllables: "hatch", distractorGroup: "nature" },
  { word: "sting", pos: "verb", kidMeaning: "To poke with a sharp point.", examples: ["Bees sting when angry.", "Stinging hurts."], emoji: "🐝", syllables: "sting", distractorGroup: "nature" },
  { word: "roar", pos: "verb", kidMeaning: "To make a loud sound.", examples: ["Lions roar loudly.", "Roaring is very loud."], emoji: "🦁", syllables: "roar", distractorGroup: "nature" },
  { word: "prowl", pos: "verb", kidMeaning: "To move quietly and hidden.", examples: ["Cats prowl at night.", "Prowling means sneaking."], emoji: "🌙", syllables: "prowl", distractorGroup: "nature" },
  { word: "burrow", pos: "verb", kidMeaning: "To dig a hole.", examples: ["Rabbits burrow underground.", "Burrowing makes tunnels."], emoji: "🐰", syllables: "bur-row", distractorGroup: "nature" },
  { word: "howl", pos: "verb", kidMeaning: "To make a long loud cry.", examples: ["Wolves howl at night.", "Howling is spooky."], emoji: "🐺", syllables: "howl", distractorGroup: "nature" },
  { word: "moo", pos: "verb", kidMeaning: "To make a cow sound.", examples: ["Cows moo in fields.", "Mooing is their voice."], emoji: "🐄", syllables: "moo", distractorGroup: "nature" },
  { word: "neigh", pos: "verb", kidMeaning: "To make a horse sound.", examples: ["Horses neigh loudly.", "Neighing means hello."], emoji: "🐴", syllables: "neigh", distractorGroup: "nature" },
  { word: "quack", pos: "verb", kidMeaning: "To make a duck sound.", examples: ["Ducks quack in ponds.", "Quacking is noisy."], emoji: "🦆", syllables: "quack", distractorGroup: "nature" },
  { word: "moth", pos: "noun", kidMeaning: "It is an insect like a butterfly.", examples: ["Moths fly at night.", "Moths like light."], emoji: "🦋", syllables: "moth", distractorGroup: "nature" },
  { word: "wasp", pos: "noun", kidMeaning: "A flying insect that stings.", examples: ["Wasps can sting you.", "Wasps are angry."], emoji: "🐝", syllables: "wasp", distractorGroup: "nature" },
  { word: "spider", pos: "noun", kidMeaning: "An eight-legged creature.", examples: ["Spiders spin webs.", "Spiders catch bugs."], emoji: "🕷️", syllables: "spi-der", distractorGroup: "nature" },
  { word: "scorpion", pos: "noun", kidMeaning: "A creature with a venomous tail.", examples: ["Scorpions hide in sand.", "Scorpions sting hard."], emoji: "🦂", syllables: "scor-pi-on", distractorGroup: "nature" },
  { word: "cocoon", pos: "noun", kidMeaning: "A silk wrapping for pupae.", examples: ["Cocoons protect insects.", "Cocoons are brown."], emoji: "🫘", syllables: "co-coon", distractorGroup: "nature" },
  { word: "jellyfish", pos: "noun", kidMeaning: "A sea creature with tentacles.", examples: ["Jellyfish float in water.", "Jellyfish can sting."], emoji: "🪼", syllables: "jel-ly-fish", distractorGroup: "nature" },
  { word: "starfish", pos: "noun", kidMeaning: "A sea creature with five arms.", examples: ["Starfish live on rocks.", "Starfish move slowly."], emoji: "⭐", syllables: "star-fish", distractorGroup: "nature" },
  { word: "oyster", pos: "noun", kidMeaning: "A shellfish with a shell.", examples: ["Oysters have pearls.", "Oysters live in shells."], emoji: "🐚", syllables: "oys-ter", distractorGroup: "nature" },
  { word: "clam", pos: "noun", kidMeaning: "A shellfish in two shells.", examples: ["Clams close tight.", "Clams live in sand."], emoji: "🦪", syllables: "clam", distractorGroup: "nature" },
  { word: "snail", pos: "noun", kidMeaning: "A slow creature with a shell.", examples: ["Snails have shells.", "Snails move very slow."], emoji: "🐌", syllables: "snail", distractorGroup: "nature" },
  { word: "squid", pos: "noun", kidMeaning: "A sea creature with tentacles.", examples: ["Squids have eight arms.", "Squids can squirt ink."], emoji: "🦑", syllables: "squid", distractorGroup: "nature" },
  { word: "octopus", pos: "noun", kidMeaning: "A sea creature with eight arms.", examples: ["Octopuses are smart.", "Octopuses hide well."], emoji: "🐙", syllables: "oc-to-pus", distractorGroup: "nature" },
  { word: "seahorse", pos: "noun", kidMeaning: "A small sea horse-like fish.", examples: ["Seahorses are tiny.", "Seahorses change colour."], emoji: "🌊", syllables: "sea-horse", distractorGroup: "nature" },
  { word: "shark", pos: "noun", kidMeaning: "A big ocean hunter.", examples: ["Sharks have sharp teeth.", "Sharks swim fast."], emoji: "🦈", syllables: "shark", distractorGroup: "nature" },
  { word: "ray", pos: "noun", kidMeaning: "A flat sea fish.", examples: ["Rays glide through water.", "Rays have flat bodies."], emoji: "🦑", syllables: "ray", distractorGroup: "nature" },
  { word: "whale", pos: "noun", kidMeaning: "A huge ocean mammal.", examples: ["Whales sing songs.", "Whales eat small food."], emoji: "🐋", syllables: "whale", distractorGroup: "nature" },
  { word: "seal", pos: "noun", kidMeaning: "A sea mammal with flippers.", examples: ["Seals are playful.", "Seals swim fast."], emoji: "🦭", syllables: "seal", distractorGroup: "nature" },
  { word: "petal", pos: "noun", kidMeaning: "Colourful part of a flower.", examples: ["Petals are soft.", "Petals make flowers pretty."], emoji: "🌼", syllables: "pet-al", distractorGroup: "nature" },
  { word: "thorn", pos: "noun", kidMeaning: "A sharp point on a plant.", examples: ["Thorns hurt fingers.", "Thorns protect plants."], emoji: "🌹", syllables: "thorn", distractorGroup: "nature" },
  { word: "stem", pos: "noun", kidMeaning: "The main part of a plant.", examples: ["Stems hold leaves.", "Stems carry water."], emoji: "🌱", syllables: "stem", distractorGroup: "nature" },
  { word: "root", pos: "noun", kidMeaning: "The part under the ground.", examples: ["Roots drink water.", "Roots hold plants up."], emoji: "🌾", syllables: "root", distractorGroup: "nature" },
  { word: "vine", pos: "noun", kidMeaning: "A plant that climbs.", examples: ["Vines climb walls.", "Vines have leaves."], emoji: "🍇", syllables: "vine", distractorGroup: "nature" },
  { word: "moss", pos: "noun", kidMeaning: "A soft green ground plant.", examples: ["Moss grows in shade.", "Moss is spongy."], emoji: "🌿", syllables: "moss", distractorGroup: "nature" },
  { word: "reed", pos: "noun", kidMeaning: "A tall grass-like plant.", examples: ["Reeds grow in water.", "Reeds sway in wind."], emoji: "🌾", syllables: "reed", distractorGroup: "nature" },
  { word: "shrub", pos: "noun", kidMeaning: "A small bush-like plant.", examples: ["Shrubs have leaves.", "Shrubs are small."], emoji: "🌿", syllables: "shrub", distractorGroup: "nature" },
  { word: "palm", pos: "noun", kidMeaning: "A tall tropical tree.", examples: ["Palms have big leaves.", "Palms grow in warm places."], emoji: "🌴", syllables: "palm", distractorGroup: "nature" },
  { word: "holly", pos: "noun", kidMeaning: "A plant with prickly leaves.", examples: ["Holly has red berries.", "Holly is a Christmas plant."], emoji: "🎄", syllables: "hol-ly", distractorGroup: "nature" },
  { word: "gust", pos: "noun", kidMeaning: "A sudden strong wind.", examples: ["Gusts blow things down.", "Gusts are quick."], emoji: "💨", syllables: "gust", distractorGroup: "nature" },
  { word: "sleet", pos: "noun", kidMeaning: "Mix of rain and snow.", examples: ["Sleet is cold.", "Sleet falls in winter."], emoji: "🌨️", syllables: "sleet", distractorGroup: "nature" },
  { word: "snowflake", pos: "noun", kidMeaning: "A single piece of snow.", examples: ["Snowflakes are white.", "Snowflakes are pretty."], emoji: "❄️", syllables: "snow-flake", distractorGroup: "nature" },
  { word: "dew", pos: "noun", kidMeaning: "Water drops on grass.", examples: ["Dew appears at dawn.", "Dew is very wet."], emoji: "💧", syllables: "dew", distractorGroup: "nature" },
  { word: "evaporate", pos: "verb", kidMeaning: "To turn into gas.", examples: ["Water evaporates in heat.", "Evaporating means disappearing."], emoji: "☀️", syllables: "e-vap-o-rate", distractorGroup: "nature" },
  { word: "pond", pos: "noun", kidMeaning: "A small body of water.", examples: ["Ponds have fish.", "Ponds are small."], emoji: "🐸", syllables: "pond", distractorGroup: "nature" },
  { word: "swamp", pos: "noun", kidMeaning: "A wetland with trees.", examples: ["Swamps are muddy.", "Swamps are wet."], emoji: "🌿", syllables: "swamp", distractorGroup: "nature" },
  { word: "meadow", pos: "noun", kidMeaning: "A field of grass.", examples: ["Meadows have flowers.", "Meadows are pretty."], emoji: "🌻", syllables: "mead-ow", distractorGroup: "nature" },
  { word: "marsh", pos: "noun", kidMeaning: "A wetland area.", examples: ["Marshes are soft.", "Marshes have tall plants."], emoji: "🦆", syllables: "marsh", distractorGroup: "nature" },
  { word: "ridge", pos: "noun", kidMeaning: "A long high hill line.", examples: ["Ridges are high.", "Ridges have slopes."], emoji: "🏔️", syllables: "ridge", distractorGroup: "nature" },
  { word: "creek", pos: "noun", kidMeaning: "A small stream.", examples: ["Creeks flow gently.", "Creeks are narrow."], emoji: "🌊", syllables: "creek", distractorGroup: "nature" },
  { word: "wetland", pos: "noun", kidMeaning: "A wet land area.", examples: ["Wetlands are soggy.", "Wetlands have wildlife."], emoji: "🌿", syllables: "wet-land", distractorGroup: "nature" },
  { word: "wool", pos: "noun", kidMeaning: "Soft hair from sheep.", examples: ["Wool is warm.", "Wool makes jumpers."], emoji: "🐑", syllables: "wool", distractorGroup: "nature" },
  { word: "linen", pos: "noun", kidMeaning: "A fabric from flax plant.", examples: ["Linen is cool.", "Linen is strong."], emoji: "👕", syllables: "lin-en", distractorGroup: "nature" },
  { word: "nylon", pos: "noun", kidMeaning: "A strong synthetic fabric.", examples: ["Nylon is tough.", "Nylon stretches."], emoji: "🧵", syllables: "ny-lon", distractorGroup: "nature" },
  { word: "steel", pos: "noun", kidMeaning: "A strong metal.", examples: ["Steel is hard.", "Steel is strong."], emoji: "⚙️", syllables: "steel", distractorGroup: "nature" },
  { word: "bronze", pos: "noun", kidMeaning: "A brown metal alloy.", examples: ["Bronze is old.", "Bronze is brown."], emoji: "🪙", syllables: "bronze", distractorGroup: "nature" },
  { word: "copper", pos: "noun", kidMeaning: "A shiny brown metal.", examples: ["Copper is red.", "Copper conducts heat."], emoji: "🪙", syllables: "cop-per", distractorGroup: "nature" },
  { word: "tin", pos: "noun", kidMeaning: "A silver metal.", examples: ["Tin is soft.", "Tin makes cans."], emoji: "🥫", syllables: "tin", distractorGroup: "nature" },
  { word: "marble", pos: "noun", kidMeaning: "A stone for building.", examples: ["Marble is smooth.", "Marble is fancy."], emoji: "🗿", syllables: "mar-ble", distractorGroup: "nature" },
  { word: "cement", pos: "noun", kidMeaning: "A powder that hardens.", examples: ["Cement binds things.", "Cement makes concrete."], emoji: "🏗️", syllables: "ce-ment", distractorGroup: "nature" },
  { word: "hip", pos: "noun", kidMeaning: "The body's side bone.", examples: ["Hips connect legs.", "Hips stick out."], emoji: "🦴", syllables: "hip", distractorGroup: "nature" },
  { word: "spine", pos: "noun", kidMeaning: "The bones down the back.", examples: ["Your spine is straight.", "Spine holds you up."], emoji: "🦴", syllables: "spine", distractorGroup: "nature" },
  { word: "rib", pos: "noun", kidMeaning: "One of many bones around chest.", examples: ["Ribs protect your heart.", "Ribs feel hard."], emoji: "🦴", syllables: "rib", distractorGroup: "nature" },
  { word: "skull", pos: "noun", kidMeaning: "The head bone.", examples: ["Skull protects brain.", "Skull holds teeth."], emoji: "💀", syllables: "skull", distractorGroup: "nature" },
  { word: "neck", pos: "noun", kidMeaning: "The part between head and body.", examples: ["Necks hold heads up.", "Necks can stretch."], emoji: "👤", syllables: "neck", distractorGroup: "nature" },
  { word: "waist", pos: "noun", kidMeaning: "The thin middle part.", examples: ["Waists show body shape.", "Waists bend easily."], emoji: "👤", syllables: "waist", distractorGroup: "nature" },
  { word: "thigh", pos: "noun", kidMeaning: "The upper leg.", examples: ["Thighs are strong.", "Thighs have muscles."], emoji: "💪", syllables: "thigh", distractorGroup: "nature" },
  { word: "heel", pos: "noun", kidMeaning: "The back part of foot.", examples: ["Heels help balance.", "Heels can hurt."], emoji: "🦶", syllables: "heel", distractorGroup: "nature" },
  { word: "sole", pos: "noun", kidMeaning: "The bottom of foot.", examples: ["Soles feel textures.", "Soles are tough."], emoji: "🦶", syllables: "sole", distractorGroup: "nature" },
  { word: "rash", pos: "noun", kidMeaning: "Skin irritation.", examples: ["Rashes are itchy.", "Rashes look red."], emoji: "🔴", syllables: "rash", distractorGroup: "nature" },
  { word: "scar", pos: "noun", kidMeaning: "A mark after healing.", examples: ["Scars fade over time.", "Scars show old wounds."], emoji: "🩹", syllables: "scar", distractorGroup: "nature" },
  { word: "sprain", pos: "noun", kidMeaning: "A stretched joint injury.", examples: ["Sprains are painful.", "Sprains need rest."], emoji: "🤕", syllables: "sprain", distractorGroup: "nature" },
  { word: "vitamin", pos: "noun", kidMeaning: "A needed food nutrient.", examples: ["Vitamins keep you healthy.", "Vitamins are in food."], emoji: "💊", syllables: "vi-ta-min", distractorGroup: "nature" },
  { word: "absorb", pos: "verb", kidMeaning: "To soak up liquid.", examples: ["Paper absorbs water.", "Absorbing means taking in."], emoji: "💧", syllables: "ab-sorb", distractorGroup: "nature" },
  { word: "magnify", pos: "verb", kidMeaning: "To make look bigger.", examples: ["Magnifying glasses enlarge things.", "Magnify means enlarge."], emoji: "🔍", syllables: "mag-ni-fy", distractorGroup: "nature" },
  { word: "expand", pos: "verb", kidMeaning: "To grow bigger.", examples: ["Heat makes things expand.", "Expanding means growing."], emoji: "📈", syllables: "ex-pand", distractorGroup: "nature" },
  { word: "contract", pos: "verb", kidMeaning: "To become smaller.", examples: ["Cold makes things contract.", "Contracting means shrinking."], emoji: "📉", syllables: "con-tract", distractorGroup: "nature" },
  { word: "eclipse", pos: "noun", kidMeaning: "When one object blocks another's light.", examples: ["An eclipse is spooky.", "Eclipses are rare."], emoji: "🌑", syllables: "e-clipse", distractorGroup: "nature" },
  { word: "crater", pos: "noun", kidMeaning: "A hole from impact.", examples: ["Craters are on the moon.", "Craters are deep."], emoji: "🌙", syllables: "cra-ter", distractorGroup: "nature" },
  { word: "millimetre", pos: "noun", kidMeaning: "A very small length measure.", examples: ["Millimetres are tiny.", "Millimetres measure precisely."], emoji: "📏", syllables: "mil-li-me-tre", distractorGroup: "nature" },
  { word: "area", pos: "noun", kidMeaning: "The space inside a shape.", examples: ["Area measures the size.", "Area is in squares."], emoji: "📐", syllables: "ar-ea", distractorGroup: "nature" },
];
