import type { Word } from "../words";

export const band2: Word[] = [
  {
    word: "neighbour",
    pos: "noun",
    kidMeaning: "A person who lives near you.",
    examples: ["My neighbour is very kind.", "She helps her neighbour with groceries."],
    emoji: "👫",
    syllables: "neigh-bour",
    distractorGroup: "people",
  },
  {
    word: "stranger",
    pos: "noun",
    kidMeaning: "A person you do not know.",
    examples: ["He does not talk to strangers.", "The stranger asked for directions."],
    emoji: "🚶",
    syllables: "stran-ger",
    distractorGroup: "people",
  },
  {
    word: "cousin",
    pos: "noun",
    kidMeaning: "Your aunt or uncle's child.",
    examples: ["My cousin lives in another town.", "She plays with her cousin every holiday."],
    emoji: "👨‍👩‍👧",
    syllables: "cou-sin",
    distractorGroup: "family",
  },
  {
    word: "classmate",
    pos: "noun",
    kidMeaning: "A person in your school class.",
    examples: ["His classmate sits next to him.", "She shares her lunch with a classmate."],
    emoji: "👬",
    syllables: "class-mate",
    distractorGroup: "people",
  },
  {
    word: "customer",
    pos: "noun",
    kidMeaning: "A person who buys things from a shop.",
    examples: ["The customer pays for the food.", "She serves many customers each day."],
    emoji: "🛍️",
    syllables: "cus-tom-er",
    distractorGroup: "people",
  },
  {
    word: "shopkeeper",
    pos: "noun",
    kidMeaning: "A person who owns or runs a shop.",
    examples: ["The shopkeeper opens the shop early.", "She is a shopkeeper at the mall."],
    emoji: "🏪",
    syllables: "shop-keep-er",
    distractorGroup: "people",
  },
  {
    word: "vendor",
    pos: "noun",
    kidMeaning: "A person who sells things at a stall.",
    examples: ["The vendor sells fruit at the market.", "He is a street vendor."],
    emoji: "🍎",
    syllables: "ven-dor",
    distractorGroup: "people",
  },
  {
    word: "cashier",
    pos: "noun",
    kidMeaning: "A person who takes money at a shop.",
    examples: ["The cashier scans the items.", "She works as a cashier."],
    emoji: "💳",
    syllables: "cash-ier",
    distractorGroup: "people",
  },
  {
    word: "passenger",
    pos: "noun",
    kidMeaning: "A person on a bus, train, or plane.",
    examples: ["The passenger gets on the train.", "She is a passenger in the car."],
    emoji: "✈️",
    syllables: "pas-sen-ger",
    distractorGroup: "people",
  },
  {
    word: "guide",
    pos: "noun",
    kidMeaning: "A person who shows you the way.",
    examples: ["The tour guide leads the group.", "He is a guide for tourists."],
    emoji: "🗺️",
    syllables: "guide",
    distractorGroup: "people",
  },
  {
    word: "host",
    pos: "noun",
    kidMeaning: "A person who welcomes guests.",
    examples: ["The host greets the visitors.", "She is the host of the party."],
    emoji: "🤝",
    syllables: "host",
    distractorGroup: "people",
  },
  {
    word: "guest",
    pos: "noun",
    kidMeaning: "A person visiting someone.",
    examples: ["The guest arrives at the door.", "She invites many guests to her home."],
    emoji: "🚪",
    syllables: "guest",
    distractorGroup: "people",
  },
  {
    word: "colleague",
    pos: "noun",
    kidMeaning: "A person you work with.",
    examples: ["My colleague helps me with the project.", "She works with her colleagues."],
    emoji: "👥",
    syllables: "col-league",
    distractorGroup: "people",
  },
  {
    word: "enemy",
    pos: "noun",
    kidMeaning: "A person who wants to hurt you.",
    examples: ["He does not want to see his enemy.", "She tries not to make enemies."],
    emoji: "⚔️",
    syllables: "en-e-my",
    distractorGroup: "people",
  },
  {
    word: "student",
    pos: "noun",
    kidMeaning: "A person who learns at school.",
    examples: ["The student listens to the teacher.", "He is a student in P4."],
    emoji: "📚",
    syllables: "stu-dent",
    distractorGroup: "people",
  },
  {
    word: "driver",
    pos: "noun",
    kidMeaning: "A person who controls a vehicle.",
    examples: ["The driver steers the car.", "She is a taxi driver."],
    emoji: "🚗",
    syllables: "driv-er",
    distractorGroup: "people",
  },
  {
    word: "pilot",
    pos: "noun",
    kidMeaning: "A person who flies an aeroplane.",
    examples: ["The pilot controls the plane.", "He is a pilot for the airline."],
    emoji: "✈️",
    syllables: "pi-lot",
    distractorGroup: "people",
  },
  {
    word: "captain",
    pos: "noun",
    kidMeaning: "A leader of a team or ship.",
    examples: ["The captain leads the ship.", "He is the captain of the football team."],
    emoji: "⛵",
    syllables: "cap-tain",
    distractorGroup: "people",
  },
  {
    word: "soldier",
    pos: "noun",
    kidMeaning: "A person in the army.",
    examples: ["The soldier serves the country.", "She meets a soldier at the parade."],
    emoji: "🪖",
    syllables: "sol-dier",
    distractorGroup: "people",
  },
  {
    word: "worker",
    pos: "noun",
    kidMeaning: "A person who does a job.",
    examples: ["The worker builds the house.", "He is a construction worker."],
    emoji: "👷",
    syllables: "work-er",
    distractorGroup: "people",
  },
  {
    word: "farmer",
    pos: "noun",
    kidMeaning: "A person who grows food on land.",
    examples: ["The farmer grows rice and vegetables.", "She is a farmer in the countryside."],
    emoji: "🚜",
    syllables: "farm-er",
    distractorGroup: "people",
  },
  {
    word: "baker",
    pos: "noun",
    kidMeaning: "A person who makes bread and cakes.",
    examples: ["The baker works in the bakery.", "She is a baker who makes good bread."],
    emoji: "🥖",
    syllables: "bak-er",
    distractorGroup: "people",
  },
  {
    word: "waiter",
    pos: "noun",
    kidMeaning: "A person who serves food in a restaurant.",
    examples: ["The waiter brings the food.", "She works as a waiter at the cafe."],
    emoji: "🍽️",
    syllables: "wait-er",
    distractorGroup: "people",
  },
  {
    word: "artist",
    pos: "noun",
    kidMeaning: "A person who makes paintings or sculptures.",
    examples: ["The artist paints beautiful pictures.", "She is an artist at the gallery."],
    emoji: "🎨",
    syllables: "ar-tist",
    distractorGroup: "people",
  },
  {
    word: "musician",
    pos: "noun",
    kidMeaning: "A person who plays music.",
    examples: ["The musician plays the piano.", "He is a musician in the band."],
    emoji: "🎵",
    syllables: "mu-si-cian",
    distractorGroup: "people",
  },
  {
    word: "actor",
    pos: "noun",
    kidMeaning: "A person who acts in films or plays.",
    examples: ["The actor performs on the stage.", "She is an actress in the drama."],
    emoji: "🎬",
    syllables: "ac-tor",
    distractorGroup: "people",
  },
  {
    word: "author",
    pos: "noun",
    kidMeaning: "A person who writes books.",
    examples: ["The author writes stories for children.", "She is an author of many books."],
    emoji: "📖",
    syllables: "au-thor",
    distractorGroup: "people",
  },
  {
    word: "player",
    pos: "noun",
    kidMeaning: "A person who plays a sport or game.",
    examples: ["The player kicks the ball.", "He is a football player."],
    emoji: "⚽",
    syllables: "play-er",
    distractorGroup: "people",
  },
  {
    word: "coach",
    pos: "noun",
    kidMeaning: "A person who trains a team.",
    examples: ["The coach teaches the players.", "She is a swimming coach."],
    emoji: "🏋️",
    syllables: "coach",
    distractorGroup: "people",
  },
  {
    word: "referee",
    pos: "noun",
    kidMeaning: "A person who watches a game and enforces rules.",
    examples: ["The referee blows the whistle.", "He is the referee for the match."],
    emoji: "🏅",
    syllables: "ref-er-ee",
    distractorGroup: "people",
  },
  {
    word: "explorer",
    pos: "noun",
    kidMeaning: "A person who travels to find new places.",
    examples: ["The explorer discovers new lands.", "She is an explorer of jungles."],
    emoji: "🧭",
    syllables: "ex-plor-er",
    distractorGroup: "people",
  },
  {
    word: "scientist",
    pos: "noun",
    kidMeaning: "A person who studies and does experiments.",
    examples: ["The scientist does experiments.", "He is a scientist in the lab."],
    emoji: "🔬",
    syllables: "sci-en-tist",
    distractorGroup: "people",
  },
  {
    word: "engineer",
    pos: "noun",
    kidMeaning: "A person who designs and builds things.",
    examples: ["The engineer builds bridges.", "She is an engineer for the company."],
    emoji: "🏗️",
    syllables: "en-gi-neer",
    distractorGroup: "people",
  },
  {
    word: "friendly",
    pos: "adjective",
    kidMeaning: "Kind and nice to other people.",
    examples: ["He is very friendly to everyone.", "The friendly dog wags its tail."],
    emoji: "😊",
    syllables: "friend-ly",
    distractorGroup: "manner",
  },
  {
    word: "honest",
    pos: "adjective",
    kidMeaning: "Telling the truth always.",
    examples: ["She is honest about her mistake.", "The honest boy tells the truth."],
    emoji: "✓",
    syllables: "hon-est",
    distractorGroup: "manner",
  },
  {
    word: "trustworthy",
    pos: "adjective",
    kidMeaning: "A person you can depend on.",
    examples: ["She is trustworthy with secrets.", "He is a trustworthy friend."],
    emoji: "🤝",
    syllables: "trust-wor-thy",
    distractorGroup: "manner",
  },
  {
    word: "lazy",
    pos: "adjective",
    kidMeaning: "Not wanting to work or move.",
    examples: ["He is lazy and sleeps all day.", "The lazy cat does not move."],
    emoji: "😴",
    syllables: "la-zy",
    distractorGroup: "manner",
  },
  {
    word: "hardworking",
    pos: "adjective",
    kidMeaning: "Putting effort into your work.",
    examples: ["She is hardworking in her studies.", "The hardworking farmer ploughs the field."],
    emoji: "💪",
    syllables: "hard-work-ing",
    distractorGroup: "manner",
  },
  {
    word: "shy",
    pos: "adjective",
    kidMeaning: "Nervous and quiet around people.",
    examples: ["She is shy when meeting new friends.", "The shy child hides behind his mother."],
    emoji: "😳",
    syllables: "shy",
    distractorGroup: "manner",
  },
  {
    word: "confident",
    pos: "adjective",
    kidMeaning: "Believing you can do something well.",
    examples: ["She is confident about the test.", "The confident player scores a goal."],
    emoji: "💪",
    syllables: "con-fi-dent",
    distractorGroup: "manner",
  },
  {
    word: "stall",
    pos: "noun",
    kidMeaning: "A small shop or stand at a market.",
    examples: ["The stall sells fresh fruit.", "She buys noodles from a stall."],
    emoji: "🏪",
    syllables: "stall",
    distractorGroup: "places",
  },
  {
    word: "hawker",
    pos: "noun",
    kidMeaning: "A person who sells food from a stall.",
    examples: ["The hawker grills chicken over fire.", "She asks the hawker for curry."],
    emoji: "🍜",
    syllables: "hawk-er",
    distractorGroup: "people",
  },
  {
    word: "corridor",
    pos: "noun",
    kidMeaning: "A long narrow passage in a building.",
    examples: ["The corridor leads to the classrooms.", "He walks down the corridor."],
    emoji: "🚪",
    syllables: "cor-ri-dor",
    distractorGroup: "places",
  },
  {
    word: "mall",
    pos: "noun",
    kidMeaning: "A large building with many shops inside.",
    examples: ["The mall is very crowded on weekends.", "He goes to the mall to shop."],
    emoji: "🛍️",
    syllables: "mall",
    distractorGroup: "places",
  },
  {
    word: "supermarket",
    pos: "noun",
    kidMeaning: "A large shop selling food and things.",
    examples: ["The supermarket has everything.", "She buys groceries at the supermarket."],
    emoji: "🛒",
    syllables: "su-per-mar-ket",
    distractorGroup: "places",
  },
  {
    word: "bank",
    pos: "noun",
    kidMeaning: "A place where people keep money.",
    examples: ["The bank is near the school.", "He goes to the bank to withdraw money."],
    emoji: "🏦",
    syllables: "bank",
    distractorGroup: "places",
  },
  {
    word: "library",
    pos: "noun",
    kidMeaning: "A place with many books to read.",
    examples: ["The library is quiet.", "She borrows books from the library."],
    emoji: "📚",
    syllables: "li-brar-y",
    distractorGroup: "places",
  },
  {
    word: "hospital",
    pos: "noun",
    kidMeaning: "A place where sick people get help.",
    examples: ["The hospital has many doctors.", "She stays at the hospital for treatment."],
    emoji: "🏥",
    syllables: "hos-pi-tal",
    distractorGroup: "places",
  },
  {
    word: "restaurant",
    pos: "noun",
    kidMeaning: "A place where you can buy and eat food.",
    examples: ["The restaurant serves Chinese food.", "They eat dinner at the restaurant."],
    emoji: "🍽️",
    syllables: "res-tau-rant",
    distractorGroup: "places",
  },
  {
    word: "cafe",
    pos: "noun",
    kidMeaning: "A small place that sells drinks and snacks.",
    examples: ["The cafe has good coffee.", "She meets her friend at the cafe."],
    emoji: "☕",
    syllables: "ca-fe",
    distractorGroup: "places",
  },
  {
    word: "butcher",
    pos: "noun",
    kidMeaning: "A person who cuts and sells meat.",
    examples: ["The butcher cuts the meat.", "She buys chicken at the butcher."],
    emoji: "🥩",
    syllables: "butch-er",
    distractorGroup: "places",
  },
  {
    word: "florist",
    pos: "noun",
    kidMeaning: "A shop that sells flowers.",
    examples: ["The florist arranges the flowers.", "He buys roses from the florist."],
    emoji: "🌹",
    syllables: "flor-ist",
    distractorGroup: "places",
  },
  {
    word: "pharmacy",
    pos: "noun",
    kidMeaning: "A shop where you get medicine.",
    examples: ["The pharmacy is in the mall.", "She gets cough syrup at the pharmacy."],
    emoji: "💊",
    syllables: "phar-ma-cy",
    distractorGroup: "places",
  },
  {
    word: "cinema",
    pos: "noun",
    kidMeaning: "A place where you watch films.",
    examples: ["The cinema shows new movies.", "He watches a film at the cinema."],
    emoji: "🎬",
    syllables: "cin-e-ma",
    distractorGroup: "places",
  },
  {
    word: "theatre",
    pos: "noun",
    kidMeaning: "A place where you watch plays.",
    examples: ["The theatre has a big stage.", "She watches a play at the theatre."],
    emoji: "🎭",
    syllables: "the-a-tre",
    distractorGroup: "places",
  },
  {
    word: "gallery",
    pos: "noun",
    kidMeaning: "A place where paintings are shown.",
    examples: ["The gallery displays modern art.", "She visits the art gallery."],
    emoji: "🖼️",
    syllables: "gal-ler-y",
    distractorGroup: "places",
  },
  {
    word: "gym",
    pos: "noun",
    kidMeaning: "A place where you exercise.",
    examples: ["The gym has exercise machines.", "He goes to the gym to lift weights."],
    emoji: "💪",
    syllables: "gym",
    distractorGroup: "places",
  },
  {
    word: "pool",
    pos: "noun",
    kidMeaning: "A large tank filled with water for swimming.",
    examples: ["The pool is very cold.", "She swims at the pool."],
    emoji: "🏊",
    syllables: "pool",
    distractorGroup: "places",
  },
  {
    word: "court",
    pos: "noun",
    kidMeaning: "A place where games are played with a net.",
    examples: ["The court is for tennis players.", "He plays badminton on the court."],
    emoji: "🏸",
    syllables: "court",
    distractorGroup: "places",
  },
  {
    word: "station",
    pos: "noun",
    kidMeaning: "A place where buses or trains stop.",
    examples: ["The station is crowded.", "She waits at the station."],
    emoji: "🚉",
    syllables: "sta-tion",
    distractorGroup: "places",
  },
  {
    word: "airport",
    pos: "noun",
    kidMeaning: "A place where aeroplanes take off and land.",
    examples: ["The airport is very busy.", "They go to the airport for their flight."],
    emoji: "✈️",
    syllables: "air-port",
    distractorGroup: "places",
  },
  {
    word: "harbour",
    pos: "noun",
    kidMeaning: "A sheltered place where ships stop.",
    examples: ["The harbour is full of boats.", "She watches ships in the harbour."],
    emoji: "⛵",
    syllables: "har-bour",
    distractorGroup: "places",
  },
  {
    word: "tunnel",
    pos: "noun",
    kidMeaning: "A passage through a mountain or under ground.",
    examples: ["The tunnel is very long.", "The car drives through the tunnel."],
    emoji: "🚗",
    syllables: "tun-nel",
    distractorGroup: "places",
  },
  {
    word: "lane",
    pos: "noun",
    kidMeaning: "A narrow path or road.",
    examples: ["The lane is very quiet.", "He walks down the lane to school."],
    emoji: "🛤️",
    syllables: "lane",
    distractorGroup: "places",
  },
  {
    word: "alley",
    pos: "noun",
    kidMeaning: "A narrow passage between buildings.",
    examples: ["The alley is dark at night.", "She takes the alley as a shortcut."],
    emoji: "🏘️",
    syllables: "al-ley",
    distractorGroup: "places",
  },
  {
    word: "flat",
    pos: "noun",
    kidMeaning: "A set of rooms in a building for living.",
    examples: ["The flat is on the tenth floor.", "She lives in a small flat."],
    emoji: "🏠",
    syllables: "flat",
    distractorGroup: "places",
  },
  {
    word: "office",
    pos: "noun",
    kidMeaning: "A place where people work.",
    examples: ["The office is on the third floor.", "She works in an office."],
    emoji: "💼",
    syllables: "of-fice",
    distractorGroup: "places",
  },
  {
    word: "workshop",
    pos: "noun",
    kidMeaning: "A place where things are made or fixed.",
    examples: ["The workshop is full of tools.", "He works in a carpentry workshop."],
    emoji: "🔧",
    syllables: "work-shop",
    distractorGroup: "places",
  },
  {
    word: "factory",
    pos: "noun",
    kidMeaning: "A large building where things are made.",
    examples: ["The factory makes toys.", "She works in a car factory."],
    emoji: "🏭",
    syllables: "fac-tor-y",
    distractorGroup: "places",
  },
  {
    word: "farm",
    pos: "noun",
    kidMeaning: "Land where crops grow and animals live.",
    examples: ["The farm has many chickens.", "He grows rice on his farm."],
    emoji: "🌾",
    syllables: "farm",
    distractorGroup: "places",
  },
  {
    word: "field",
    pos: "noun",
    kidMeaning: "A large area of land with grass.",
    examples: ["The field is very wide.", "He plays football in the field."],
    emoji: "🌾",
    syllables: "field",
    distractorGroup: "places",
  },
  {
    word: "valley",
    pos: "noun",
    kidMeaning: "A low area between hills.",
    examples: ["The valley is very green.", "She walks through the valley."],
    emoji: "🏞️",
    syllables: "val-ley",
    distractorGroup: "places",
  },
  {
    word: "island",
    pos: "noun",
    kidMeaning: "Land surrounded by water.",
    examples: ["The island is very small.", "He sails to the island."],
    emoji: "🏝️",
    syllables: "is-land",
    distractorGroup: "places",
  },
  {
    word: "sea",
    pos: "noun",
    kidMeaning: "A large body of salt water.",
    examples: ["The sea is very deep.", "She swims in the sea."],
    emoji: "🌊",
    syllables: "sea",
    distractorGroup: "places",
  },
  {
    word: "platform",
    pos: "noun",
    kidMeaning: "A raised area where passengers wait.",
    examples: ["The platform is crowded.", "She waits on the platform for the train."],
    emoji: "🚂",
    syllables: "plat-form",
    distractorGroup: "transport",
  },
  {
    word: "ticket",
    pos: "noun",
    kidMeaning: "A pass that allows you to travel.",
    examples: ["The ticket costs five dollars.", "He buys a train ticket."],
    emoji: "🎫",
    syllables: "tick-et",
    distractorGroup: "transport",
  },
  {
    word: "journey",
    pos: "noun",
    kidMeaning: "A trip from one place to another.",
    examples: ["The journey takes two hours.", "She enjoys her journey to school."],
    emoji: "🛤️",
    syllables: "jour-ney",
    distractorGroup: "travel",
  },
  {
    word: "luggage",
    pos: "noun",
    kidMeaning: "Bags and cases you carry when travelling.",
    examples: ["The luggage is very heavy.", "She packs her luggage for the trip."],
    emoji: "🧳",
    syllables: "lug-gage",
    distractorGroup: "transport",
  },
  {
    word: "arrive",
    pos: "verb",
    kidMeaning: "To come to a place.",
    examples: ["The bus arrives at the station.", "She arrives home at six."],
    emoji: "🚌",
    syllables: "ar-rive",
    distractorGroup: "actions",
  },
  {
    word: "depart",
    pos: "verb",
    kidMeaning: "To leave a place.",
    examples: ["The plane departs at ten.", "He departs for school at seven."],
    emoji: "✈️",
    syllables: "de-part",
    distractorGroup: "actions",
  },
  {
    word: "travel",
    pos: "verb",
    kidMeaning: "To go from one place to another.",
    examples: ["She travels by train.", "He travels around the world."],
    emoji: "🌍",
    syllables: "trav-el",
    distractorGroup: "actions",
  },
  {
    word: "drive",
    pos: "verb",
    kidMeaning: "To control a vehicle.",
    examples: ["He drives a car to work.", "She drives carefully on the road."],
    emoji: "🚗",
    syllables: "drive",
    distractorGroup: "actions",
  },
  {
    word: "bus",
    pos: "noun",
    kidMeaning: "A large vehicle that carries many people.",
    examples: ["The bus is very crowded.", "She takes the bus to school."],
    emoji: "🚌",
    syllables: "bus",
    distractorGroup: "transport",
  },
  {
    word: "taxi",
    pos: "noun",
    kidMeaning: "A car that takes people for money.",
    examples: ["The taxi is yellow.", "He calls a taxi to the airport."],
    emoji: "🚕",
    syllables: "tax-i",
    distractorGroup: "transport",
  },
  {
    word: "train",
    pos: "noun",
    kidMeaning: "A vehicle that runs on tracks.",
    examples: ["The train is very fast.", "She takes the train to the city."],
    emoji: "🚂",
    syllables: "train",
    distractorGroup: "transport",
  },
  {
    word: "car",
    pos: "noun",
    kidMeaning: "A vehicle with four wheels.",
    examples: ["The car is red.", "He drives a car."],
    emoji: "🚗",
    syllables: "car",
    distractorGroup: "transport",
  },
  {
    word: "aeroplane",
    pos: "noun",
    kidMeaning: "A vehicle that flies in the air.",
    examples: ["The aeroplane is very high.", "She flies in an aeroplane."],
    emoji: "✈️",
    syllables: "aer-o-plane",
    distractorGroup: "transport",
  },
  {
    word: "helicopter",
    pos: "noun",
    kidMeaning: "A flying machine with big blades.",
    examples: ["The helicopter lands on the roof.", "He flies in a helicopter."],
    emoji: "🚁",
    syllables: "hel-i-cop-ter",
    distractorGroup: "transport",
  },
  {
    word: "bicycle",
    pos: "noun",
    kidMeaning: "A vehicle with two wheels.",
    examples: ["The bicycle is fast.", "She rides a bicycle to school."],
    emoji: "🚴",
    syllables: "bi-cy-cle",
    distractorGroup: "transport",
  },
  {
    word: "motorcycle",
    pos: "noun",
    kidMeaning: "A vehicle with two wheels and an engine.",
    examples: ["The motorcycle is very loud.", "He rides a motorcycle fast."],
    emoji: "🏍️",
    syllables: "mo-tor-cy-cle",
    distractorGroup: "transport",
  },
  {
    word: "van",
    pos: "noun",
    kidMeaning: "A vehicle bigger than a car.",
    examples: ["The van is parked outside.", "She drives a van for her job."],
    emoji: "🚐",
    syllables: "van",
    distractorGroup: "transport",
  },
  {
    word: "boat",
    pos: "noun",
    kidMeaning: "A vehicle that floats on water.",
    examples: ["The boat is in the water.", "He sails the boat."],
    emoji: "⛵",
    syllables: "boat",
    distractorGroup: "transport",
  },
  {
    word: "ship",
    pos: "noun",
    kidMeaning: "A large boat for travel.",
    examples: ["The ship is very big.", "She sails on a ship."],
    emoji: "🚢",
    syllables: "ship",
    distractorGroup: "transport",
  },
  {
    word: "ferry",
    pos: "noun",
    kidMeaning: "A boat that carries people across water.",
    examples: ["The ferry crosses the sea.", "He takes the ferry to the island."],
    emoji: "⛴️",
    syllables: "fer-ry",
    distractorGroup: "transport",
  },
  {
    word: "canoe",
    pos: "noun",
    kidMeaning: "A small light boat.",
    examples: ["The canoe glides through the water.", "She paddles the canoe."],
    emoji: "🛶",
    syllables: "ca-noe",
    distractorGroup: "transport",
  },
  {
    word: "scooter",
    pos: "noun",
    kidMeaning: "A small vehicle with a platform.",
    examples: ["The scooter is fun to ride.", "He rides a scooter to the park."],
    emoji: "🛴",
    syllables: "scoot-er",
    distractorGroup: "transport",
  },
  {
    word: "skateboard",
    pos: "noun",
    kidMeaning: "A board with wheels for riding.",
    examples: ["The skateboard is cool.", "She rides her skateboard."],
    emoji: "🛹",
    syllables: "skate-board",
    distractorGroup: "transport",
  },
  {
    word: "trolley",
    pos: "noun",
    kidMeaning: "A cart with wheels for shopping.",
    examples: ["The trolley is full of groceries.", "She pushes the trolley."],
    emoji: "🛒",
    syllables: "trol-ley",
    distractorGroup: "transport",
  },
  {
    word: "suitcase",
    pos: "noun",
    kidMeaning: "A bag for carrying clothes when travelling.",
    examples: ["The suitcase is heavy.", "She packs her suitcase for the trip."],
    emoji: "🧳",
    syllables: "suit-case",
    distractorGroup: "transport",
  },
  {
    word: "route",
    pos: "noun",
    kidMeaning: "The way to go to a place.",
    examples: ["The route is very long.", "She takes the same route every day."],
    emoji: "🗺️",
    syllables: "route",
    distractorGroup: "travel",
  },
  {
    word: "distance",
    pos: "noun",
    kidMeaning: "How far apart two places are.",
    examples: ["The distance is ten kilometres.", "He measures the distance carefully."],
    emoji: "📏",
    syllables: "dis-tance",
    distractorGroup: "travel",
  },
  {
    word: "fuel",
    pos: "noun",
    kidMeaning: "Something burned to make a vehicle go.",
    examples: ["The fuel tank is empty.", "He puts fuel in the car."],
    emoji: "⛽",
    syllables: "fuel",
    distractorGroup: "transport",
  },
  {
    word: "petrol",
    pos: "noun",
    kidMeaning: "Liquid used to make cars go.",
    examples: ["The petrol is expensive.", "She fills up petrol at the station."],
    emoji: "⛽",
    syllables: "pet-rol",
    distractorGroup: "transport",
  },
  {
    word: "engine",
    pos: "noun",
    kidMeaning: "A machine that makes things move.",
    examples: ["The engine is very powerful.", "He fixes the car engine."],
    emoji: "🔧",
    syllables: "en-gine",
    distractorGroup: "transport",
  },
  {
    word: "wheel",
    pos: "noun",
    kidMeaning: "A round object that spins.",
    examples: ["The wheel turns very fast.", "He changes the wheel."],
    emoji: "🛞",
    syllables: "wheel",
    distractorGroup: "transport",
  },
  {
    word: "brake",
    pos: "noun",
    kidMeaning: "Something that stops a vehicle.",
    examples: ["The brake is working well.", "He uses the brake to stop."],
    emoji: "🛑",
    syllables: "brake",
    distractorGroup: "transport",
  },
  {
    word: "horn",
    pos: "noun",
    kidMeaning: "A device that makes a loud sound.",
    examples: ["The horn is very loud.", "She blows the horn."],
    emoji: "📯",
    syllables: "horn",
    distractorGroup: "transport",
  },
  {
    word: "headlight",
    pos: "noun",
    kidMeaning: "A light in front of a vehicle.",
    examples: ["The headlight is broken.", "He turns on the headlights."],
    emoji: "💡",
    syllables: "head-light",
    distractorGroup: "transport",
  },
  {
    word: "price",
    pos: "noun",
    kidMeaning: "The amount of money something costs.",
    examples: ["The price is too high.", "She checks the price of the shirt."],
    emoji: "💰",
    syllables: "price",
    distractorGroup: "money",
  },
  {
    word: "discount",
    pos: "noun",
    kidMeaning: "A reduction in the price of something.",
    examples: ["The discount is fifty per cent.", "She gets a discount on the dress."],
    emoji: "🏷️",
    syllables: "dis-count",
    distractorGroup: "money",
  },
  {
    word: "afford",
    pos: "verb",
    kidMeaning: "To have enough money to buy something.",
    examples: ["She can afford the toy.", "He cannot afford the expensive bike."],
    emoji: "💰",
    syllables: "af-ford",
    distractorGroup: "actions",
  },
  {
    word: "bargain",
    pos: "noun",
    kidMeaning: "Something sold at a very good price.",
    examples: ["The shirt is a bargain.", "She finds a bargain at the sale."],
    emoji: "🏷️",
    syllables: "bar-gain",
    distractorGroup: "money",
  },
  {
    word: "bill",
    pos: "noun",
    kidMeaning: "A statement of money owed.",
    examples: ["The bill is one hundred dollars.", "She pays the electricity bill."],
    emoji: "📄",
    syllables: "bill",
    distractorGroup: "money",
  },
  {
    word: "payment",
    pos: "noun",
    kidMeaning: "Money you give for something.",
    examples: ["The payment is by card.", "She makes a payment each month."],
    emoji: "💳",
    syllables: "pay-ment",
    distractorGroup: "money",
  },
  {
    word: "cost",
    pos: "verb",
    kidMeaning: "To have a certain price.",
    examples: ["The shirt costs ten dollars.", "It costs a lot of money."],
    emoji: "💰",
    syllables: "cost",
    distractorGroup: "actions",
  },
  {
    word: "charge",
    pos: "verb",
    kidMeaning: "To ask for money for something.",
    examples: ["The shop charges high prices.", "He charges for his service."],
    emoji: "💸",
    syllables: "charge",
    distractorGroup: "actions",
  },
  {
    word: "spend",
    pos: "verb",
    kidMeaning: "To use money to buy something.",
    examples: ["She spends money on books.", "He spends too much on toys."],
    emoji: "💸",
    syllables: "spend",
    distractorGroup: "actions",
  },
  {
    word: "save",
    pos: "verb",
    kidMeaning: "To keep money instead of spending it.",
    examples: ["She saves money for a holiday.", "He saves coins in a jar."],
    emoji: "🏦",
    syllables: "save",
    distractorGroup: "actions",
  },
  {
    word: "exchange",
    pos: "verb",
    kidMeaning: "To give one thing and get another.",
    examples: ["She exchanges the shirt for a smaller size.", "He exchanges his toy."],
    emoji: "🔄",
    syllables: "ex-change",
    distractorGroup: "actions",
  },
  {
    word: "refund",
    pos: "noun",
    kidMeaning: "Money given back for returned goods.",
    examples: ["The refund is complete.", "She gets a refund for the broken toy."],
    emoji: "💵",
    syllables: "re-fund",
    distractorGroup: "money",
  },
  {
    word: "guarantee",
    pos: "noun",
    kidMeaning: "A promise that something will work.",
    examples: ["The guarantee is for two years.", "It has a money-back guarantee."],
    emoji: "✓",
    syllables: "guar-an-tee",
    distractorGroup: "money",
  },
  {
    word: "interest",
    pos: "noun",
    kidMeaning: "Extra money paid for borrowing.",
    examples: ["The interest rate is five per cent.", "She pays interest on the loan."],
    emoji: "📊",
    syllables: "in-ter-est",
    distractorGroup: "money",
  },
  {
    word: "coin",
    pos: "noun",
    kidMeaning: "A round piece of metal money.",
    examples: ["The coin is gold.", "He counts his coins."],
    emoji: "🪙",
    syllables: "coin",
    distractorGroup: "money",
  },
  {
    word: "note",
    pos: "noun",
    kidMeaning: "A piece of paper money.",
    examples: ["The note is worth fifty dollars.", "She holds a ten dollar note."],
    emoji: "💵",
    syllables: "note",
    distractorGroup: "money",
  },
  {
    word: "wallet",
    pos: "noun",
    kidMeaning: "A small bag for holding money.",
    examples: ["The wallet is in his pocket.", "She keeps her money in a wallet."],
    emoji: "👝",
    syllables: "wal-let",
    distractorGroup: "money",
  },
  {
    word: "purse",
    pos: "noun",
    kidMeaning: "A small bag for money and things.",
    examples: ["The purse is red.", "She carries her purse everywhere."],
    emoji: "👜",
    syllables: "purse",
    distractorGroup: "money",
  },
  {
    word: "cash",
    pos: "noun",
    kidMeaning: "Money in coins or notes.",
    examples: ["She pays in cash.", "He has cash in his pocket."],
    emoji: "💰",
    syllables: "cash",
    distractorGroup: "money",
  },
  {
    word: "card",
    pos: "noun",
    kidMeaning: "A plastic thing used to buy things.",
    examples: ["She uses a credit card.", "He pays with a card."],
    emoji: "💳",
    syllables: "card",
    distractorGroup: "money",
  },
  {
    word: "budget",
    pos: "noun",
    kidMeaning: "A plan for using money.",
    examples: ["The family budget is tight.", "She makes a monthly budget."],
    emoji: "📊",
    syllables: "budg-et",
    distractorGroup: "money",
  },
  {
    word: "tip",
    pos: "noun",
    kidMeaning: "Extra money given for good service.",
    examples: ["The tip is generous.", "She leaves a tip for the waiter."],
    emoji: "💵",
    syllables: "tip",
    distractorGroup: "money",
  },
  {
    word: "sale",
    pos: "noun",
    kidMeaning: "A time when things are sold cheaply.",
    examples: ["The sale is this weekend.", "She shops during the sale."],
    emoji: "🏷️",
    syllables: "sale",
    distractorGroup: "money",
  },
  {
    word: "expensive",
    pos: "adjective",
    kidMeaning: "Costing a lot of money.",
    examples: ["The car is very expensive.", "She cannot afford expensive things."],
    emoji: "💸",
    syllables: "ex-pen-sive",
    distractorGroup: "quality",
  },
  {
    word: "cheap",
    pos: "adjective",
    kidMeaning: "Costing very little money.",
    examples: ["The shirt is cheap.", "He buys cheap toys."],
    emoji: "🏷️",
    syllables: "cheap",
    distractorGroup: "quality",
  },
  {
    word: "free",
    pos: "adjective",
    kidMeaning: "Costing no money.",
    examples: ["The book is free.", "She gets a free gift."],
    emoji: "🎁",
    syllables: "free",
    distractorGroup: "quality",
  },
  {
    word: "dawn",
    pos: "noun",
    kidMeaning: "Early morning when the sun rises.",
    examples: ["She wakes at dawn.", "The birds sing at dawn."],
    emoji: "🌅",
    syllables: "dawn",
    distractorGroup: "time",
  },
  {
    word: "noon",
    pos: "noun",
    kidMeaning: "Twelve o'clock in the middle of the day.",
    examples: ["We eat lunch at noon.", "The sun is high at noon."],
    emoji: "☀️",
    syllables: "noon",
    distractorGroup: "time",
  },
  {
    word: "midnight",
    pos: "noun",
    kidMeaning: "Twelve o'clock at night.",
    examples: ["Midnight is very late.", "The clock strikes midnight."],
    emoji: "🌙",
    syllables: "mid-night",
    distractorGroup: "time",
  },
  {
    word: "schedule",
    pos: "noun",
    kidMeaning: "A plan of when things happen.",
    examples: ["The schedule is on the wall.", "She checks the schedule."],
    emoji: "📅",
    syllables: "sched-ule",
    distractorGroup: "time",
  },
  {
    word: "punctual",
    pos: "adjective",
    kidMeaning: "Arriving or doing things on time.",
    examples: ["She is punctual for class.", "The punctual student is early."],
    emoji: "⏰",
    syllables: "punc-tu-al",
    distractorGroup: "manner",
  },
  {
    word: "delay",
    pos: "noun",
    kidMeaning: "A period of waiting time.",
    examples: ["The train has a delay.", "There is a delay in service."],
    emoji: "⏱️",
    syllables: "de-lay",
    distractorGroup: "time",
  },
  {
    word: "rush",
    pos: "verb",
    kidMeaning: "To move or do something very quickly.",
    examples: ["She rushes to school.", "He rushes through his homework."],
    emoji: "💨",
    syllables: "rush",
    distractorGroup: "actions",
  },
  {
    word: "hurry",
    pos: "verb",
    kidMeaning: "To move quickly to go somewhere.",
    examples: ["She hurries to catch the bus.", "He hurries home."],
    emoji: "💨",
    syllables: "hur-ry",
    distractorGroup: "actions",
  },
  {
    word: "rest",
    pos: "verb",
    kidMeaning: "To stop working and relax.",
    examples: ["She rests after school.", "He rests on the sofa."],
    emoji: "😴",
    syllables: "rest",
    distractorGroup: "actions",
  },
  {
    word: "wake",
    pos: "verb",
    kidMeaning: "To stop sleeping.",
    examples: ["She wakes up early.", "The alarm wakes him."],
    emoji: "👁️",
    syllables: "wake",
    distractorGroup: "actions",
  },
  {
    word: "routine",
    pos: "noun",
    kidMeaning: "A regular way of doing things.",
    examples: ["Her routine is very regular.", "He has a morning routine."],
    emoji: "📋",
    syllables: "rou-tine",
    distractorGroup: "time",
  },
  {
    word: "habit",
    pos: "noun",
    kidMeaning: "Something you do regularly.",
    examples: ["Reading is her good habit.", "He has a habit of waking early."],
    emoji: "🔁",
    syllables: "hab-it",
    distractorGroup: "time",
  },
  {
    word: "regular",
    pos: "adjective",
    kidMeaning: "Happening at the same time often.",
    examples: ["She has a regular class.", "He visits regularly."],
    emoji: "🔁",
    syllables: "reg-u-lar",
    distractorGroup: "time",
  },
  {
    word: "alarm",
    pos: "noun",
    kidMeaning: "A device that makes noise at a set time.",
    examples: ["The alarm rings at seven.", "She sets an alarm."],
    emoji: "⏰",
    syllables: "a-larm",
    distractorGroup: "time",
  },
  {
    word: "clock",
    pos: "noun",
    kidMeaning: "A device that shows the time.",
    examples: ["The clock shows nine.", "She looks at the clock."],
    emoji: "🕐",
    syllables: "clock",
    distractorGroup: "time",
  },
  {
    word: "timer",
    pos: "noun",
    kidMeaning: "A device that measures time.",
    examples: ["She sets a timer.", "The timer rings when time is up."],
    emoji: "⏱️",
    syllables: "ti-mer",
    distractorGroup: "time",
  },
  {
    word: "deadline",
    pos: "noun",
    kidMeaning: "The last day or time to do something.",
    examples: ["The deadline is Friday.", "She meets the deadline."],
    emoji: "📅",
    syllables: "dead-line",
    distractorGroup: "time",
  },
  {
    word: "century",
    pos: "noun",
    kidMeaning: "A period of one hundred years.",
    examples: ["The century has passed.", "She studies this century."],
    emoji: "⏳",
    syllables: "cen-tu-ry",
    distractorGroup: "time",
  },
  {
    word: "decade",
    pos: "noun",
    kidMeaning: "A period of ten years.",
    examples: ["The decade was exciting.", "He lives for many decades."],
    emoji: "📅",
    syllables: "dec-ade",
    distractorGroup: "time",
  },
  {
    word: "hour",
    pos: "noun",
    kidMeaning: "A period of sixty minutes.",
    examples: ["She studies for one hour.", "An hour has sixty minutes."],
    emoji: "⏰",
    syllables: "hour",
    distractorGroup: "time",
  },
  {
    word: "second",
    pos: "noun",
    kidMeaning: "A very short period of time.",
    examples: ["She waits one second.", "Give me a second."],
    emoji: "⏱️",
    syllables: "sec-ond",
    distractorGroup: "time",
  },
  {
    word: "greet",
    pos: "verb",
    kidMeaning: "To welcome someone with a hello.",
    examples: ["She greets her friend.", "He greets the teacher."],
    emoji: "👋",
    syllables: "greet",
    distractorGroup: "actions",
  },
  {
    word: "meet",
    pos: "verb",
    kidMeaning: "To come together with someone.",
    examples: ["She meets her friend at school.", "He meets the new student."],
    emoji: "👫",
    syllables: "meet",
    distractorGroup: "actions",
  },
  {
    word: "separate",
    pos: "verb",
    kidMeaning: "To move apart from someone.",
    examples: ["She separates from the group.", "He separates the objects."],
    emoji: "✂️",
    syllables: "sep-a-rate",
    distractorGroup: "actions",
  },
  {
    word: "approach",
    pos: "verb",
    kidMeaning: "To come near to someone or something.",
    examples: ["She approaches the building.", "He approaches slowly."],
    emoji: "🚶",
    syllables: "ap-proach",
    distractorGroup: "actions",
  },
  {
    word: "invite",
    pos: "verb",
    kidMeaning: "To ask someone to come to an event.",
    examples: ["She invites her friend.", "He invites many people."],
    emoji: "🎉",
    syllables: "in-vite",
    distractorGroup: "actions",
  },
  {
    word: "attend",
    pos: "verb",
    kidMeaning: "To go to or be present at.",
    examples: ["She attends the party.", "He attends school every day."],
    emoji: "✓",
    syllables: "at-tend",
    distractorGroup: "actions",
  },
  {
    word: "cooperate",
    pos: "verb",
    kidMeaning: "To work together with others.",
    examples: ["She cooperates with her team.", "He cooperates with friends."],
    emoji: "🤝",
    syllables: "co-op-er-ate",
    distractorGroup: "actions",
  },
  {
    word: "compete",
    pos: "verb",
    kidMeaning: "To try to do better than others.",
    examples: ["She competes in the race.", "He competes with his friend."],
    emoji: "🏆",
    syllables: "com-pete",
    distractorGroup: "actions",
  },
  {
    word: "gather",
    pos: "verb",
    kidMeaning: "To come together or collect things.",
    examples: ["They gather in the park.", "She gathers flowers."],
    emoji: "🌸",
    syllables: "gath-er",
    distractorGroup: "actions",
  },
  {
    word: "scatter",
    pos: "verb",
    kidMeaning: "To spread things around.",
    examples: ["She scatters the seeds.", "The wind scatters the leaves."],
    emoji: "🌪️",
    syllables: "scat-ter",
    distractorGroup: "actions",
  },
  {
    word: "arrange",
    pos: "verb",
    kidMeaning: "To put things in order.",
    examples: ["She arranges the chairs.", "He arranges the flowers."],
    emoji: "📐",
    syllables: "ar-range",
    distractorGroup: "actions",
  },
  {
    word: "search",
    pos: "verb",
    kidMeaning: "To look carefully for something.",
    examples: ["She searches for her keys.", "He searches through the bag."],
    emoji: "🔍",
    syllables: "search",
    distractorGroup: "actions",
  },
  {
    word: "discover",
    pos: "verb",
    kidMeaning: "To find something for the first time.",
    examples: ["She discovers a new path.", "He discovers an old toy."],
    emoji: "🔍",
    syllables: "dis-cov-er",
    distractorGroup: "actions",
  },
  {
    word: "explore",
    pos: "verb",
    kidMeaning: "To travel around to see new places.",
    examples: ["She explores the beach.", "He explores the cave."],
    emoji: "🗺️",
    syllables: "ex-plore",
    distractorGroup: "actions",
  },
  {
    word: "pack",
    pos: "verb",
    kidMeaning: "To put things into a bag or box.",
    examples: ["She packs her clothes.", "He packs for the trip."],
    emoji: "🧳",
    syllables: "pack",
    distractorGroup: "actions",
  },
  {
    word: "unpack",
    pos: "verb",
    kidMeaning: "To take things out of a bag or box.",
    examples: ["She unpacks her bag.", "He unpacks his suitcase."],
    emoji: "📦",
    syllables: "un-pack",
    distractorGroup: "actions",
  },
  {
    word: "load",
    pos: "verb",
    kidMeaning: "To put things onto a vehicle.",
    examples: ["She loads the boxes.", "He loads the van."],
    emoji: "📦",
    syllables: "load",
    distractorGroup: "actions",
  },
  {
    word: "unload",
    pos: "verb",
    kidMeaning: "To take things off a vehicle.",
    examples: ["She unloads the car.", "He unloads the boxes."],
    emoji: "📦",
    syllables: "un-load",
    distractorGroup: "actions",
  },
  {
    word: "deliver",
    pos: "verb",
    kidMeaning: "To bring something to someone.",
    examples: ["She delivers the package.", "He delivers newspapers."],
    emoji: "📦",
    syllables: "de-liv-er",
    distractorGroup: "actions",
  },
  {
    word: "receive",
    pos: "verb",
    kidMeaning: "To get something given to you.",
    examples: ["She receives a gift.", "He receives the package."],
    emoji: "📦",
    syllables: "re-ceive",
    distractorGroup: "actions",
  },
  {
    word: "loud",
    pos: "adjective",
    kidMeaning: "Making a lot of noise.",
    examples: ["The music is very loud.", "He has a loud voice."],
    emoji: "🔊",
    syllables: "loud",
    distractorGroup: "quality",
  },
  {
    word: "peaceful",
    pos: "adjective",
    kidMeaning: "Calm and quiet.",
    examples: ["The park is peaceful.", "She feels peaceful."],
    emoji: "☮️",
    syllables: "peace-ful",
    distractorGroup: "quality",
  },
  {
    word: "empty",
    pos: "adjective",
    kidMeaning: "Having nothing inside.",
    examples: ["The bag is empty.", "The room is empty."],
    emoji: "📭",
    syllables: "emp-ty",
    distractorGroup: "quality",
  },
  {
    word: "full",
    pos: "adjective",
    kidMeaning: "Filled with as much as possible.",
    examples: ["The cup is full of water.", "Her day is full."],
    emoji: "🪣",
    syllables: "full",
    distractorGroup: "quality",
  },
  {
    word: "energetic",
    pos: "adjective",
    kidMeaning: "Full of energy and activity.",
    examples: ["He is very energetic.", "The energetic dog runs fast."],
    emoji: "⚡",
    syllables: "en-er-get-ic",
    distractorGroup: "manner",
  },
  {
    word: "gloomy",
    pos: "adjective",
    kidMeaning: "Dark and sad.",
    examples: ["The weather is gloomy.", "His gloomy mood improves."],
    emoji: "⛅",
    syllables: "gloom-y",
    distractorGroup: "feelings",
  },
  {
    word: "helpful",
    pos: "adjective",
    kidMeaning: "Giving help or being useful.",
    examples: ["She is very helpful.", "A helpful student aids others."],
    emoji: "🤝",
    syllables: "help-ful",
    distractorGroup: "manner",
  },
  {
    word: "selfish",
    pos: "adjective",
    kidMeaning: "Only thinking of yourself.",
    examples: ["He is selfish with his toys.", "The selfish boy refuses to share."],
    emoji: "😤",
    syllables: "self-ish",
    distractorGroup: "manner",
  },
  {
    word: "generous",
    pos: "adjective",
    kidMeaning: "Willing to give and share.",
    examples: ["She is very generous.", "The generous man gives gifts."],
    emoji: "🎁",
    syllables: "gen-er-ous",
    distractorGroup: "manner",
  },
  {
    word: "loyal",
    pos: "adjective",
    kidMeaning: "Staying close to someone you care for.",
    examples: ["He is loyal to his friends.", "Her loyal dog follows her everywhere."],
    emoji: "🐕",
    syllables: "loy-al",
    distractorGroup: "manner",
  },
  {
    word: "patient",
    pos: "adjective",
    kidMeaning: "Able to wait calmly.",
    examples: ["She is patient with her siblings.", "The patient teacher helps all students."],
    emoji: "⏳",
    syllables: "pa-tient",
    distractorGroup: "manner",
  },
  {
    word: "impatient",
    pos: "adjective",
    kidMeaning: "Not able to wait calmly.",
    examples: ["He is impatient for lunch.", "The impatient child taps his foot."],
    emoji: "⏱️",
    syllables: "im-pa-tient",
    distractorGroup: "manner",
  },
  {
    word: "practical",
    pos: "adjective",
    kidMeaning: "Good for everyday use.",
    examples: ["She gives practical advice.", "Practical clothing is best for hiking."],
    emoji: "🔧",
    syllables: "prac-ti-cal",
    distractorGroup: "quality",
  },
  {
    word: "ungrateful",
    pos: "adjective",
    kidMeaning: "Not feeling or showing thanks.",
    examples: ["He is ungrateful for help.", "The ungrateful child complains."],
    emoji: "😠",
    syllables: "un-grate-ful",
    distractorGroup: "feelings",
  },
  {
    word: "humble",
    pos: "adjective",
    kidMeaning: "Not proud or boastful.",
    examples: ["He is humble about his success.", "She remains humble despite winning."],
    emoji: "🙏",
    syllables: "hum-ble",
    distractorGroup: "manner",
  },
  {
    word: "responsible",
    pos: "adjective",
    kidMeaning: "Able to do the right thing.",
    examples: ["She is responsible for the plants.", "The responsible student completes homework."],
    emoji: "✓",
    syllables: "re-spon-si-ble",
    distractorGroup: "manner",
  },
  {
    word: "flexible",
    pos: "adjective",
    kidMeaning: "Able to bend or change.",
    examples: ["She is flexible in her approach.", "The flexible rope bends easily."],
    emoji: "🤸",
    syllables: "flex-i-ble",
    distractorGroup: "quality",
  },
  {
    word: "rigid",
    pos: "adjective",
    kidMeaning: "Stiff and unable to bend.",
    examples: ["The rigid stick does not bend.", "His rigid rules never change."],
    emoji: "📏",
    syllables: "rig-id",
    distractorGroup: "quality",
  },
  {
    word: "comfortable",
    pos: "adjective",
    kidMeaning: "Feeling nice and good.",
    examples: ["The chair is comfortable.", "She feels comfortable with her friends."],
    emoji: "🛋️",
    syllables: "com-fort-a-ble",
    distractorGroup: "quality",
  },
  {
    word: "temporary",
    pos: "adjective",
    kidMeaning: "Lasting for a short time only.",
    examples: ["The temporary bridge closes soon.", "She takes a temporary job."],
    emoji: "⏱️",
    syllables: "tem-po-rar-y",
    distractorGroup: "time",
  },
  {
    word: "permanent",
    pos: "adjective",
    kidMeaning: "Lasting forever or for a long time.",
    examples: ["He makes a permanent move.", "The permanent mark stays on the wall."],
    emoji: "♾️",
    syllables: "per-ma-nent",
    distractorGroup: "time",
  },
  {
    word: "prompt",
    pos: "adjective",
    kidMeaning: "Done without delay.",
    examples: ["She gives a prompt reply.", "His prompt arrival surprises everyone."],
    emoji: "⚡",
    syllables: "prompt",
    distractorGroup: "manner",
  },
  {
    word: "early",
    pos: "adjective",
    kidMeaning: "Before the expected time.",
    examples: ["She arrives early.", "She goes for a walk early in the morning."],
    emoji: "🌅",
    syllables: "ear-ly",
    distractorGroup: "time",
  },
  {
    word: "late",
    pos: "adjective",
    kidMeaning: "After the expected time.",
    examples: ["He arrives late to school.", "They have a late dinner."],
    emoji: "🌙",
    syllables: "late",
    distractorGroup: "time",
  },
  {
    word: "distant",
    pos: "adjective",
    kidMeaning: "Far away from something.",
    examples: ["The mountain is distant.", "Her relative lives in a distant country."],
    emoji: "📏",
    syllables: "dis-tant",
    distractorGroup: "position",
  },
  {
    word: "shallow",
    pos: "adjective",
    kidMeaning: "Not deep.",
    examples: ["The pool is shallow.", "She walks in shallow water."],
    emoji: "🏊",
    syllables: "shal-low",
    distractorGroup: "quality",
  },
  {
    word: "deep",
    pos: "adjective",
    kidMeaning: "Extending far down.",
    examples: ["The ocean is very deep.", "He digs a deep hole."],
    emoji: "🌊",
    syllables: "deep",
    distractorGroup: "quality",
  },
  {
    word: "steep",
    pos: "adjective",
    kidMeaning: "Rising at a sharp angle.",
    examples: ["The hill is very steep.", "She climbs the steep stairs."],
    emoji: "⛰️",
    syllables: "steep",
    distractorGroup: "quality",
  },
  {
    word: "dim",
    pos: "adjective",
    kidMeaning: "Not bright; not giving much light.",
    examples: ["The room is very dim.", "The dim bulb flickers."],
    emoji: "💡",
    syllables: "dim",
    distractorGroup: "quality",
  },
  {
    word: "clear",
    pos: "adjective",
    kidMeaning: "Easy to see through or understand.",
    examples: ["The water is very clear.", "Her instructions are clear."],
    emoji: "👀",
    syllables: "clear",
    distractorGroup: "quality",
  },
  {
    word: "sunny",
    pos: "adjective",
    kidMeaning: "Full of sunshine.",
    examples: ["The sunny day is perfect.", "She enjoys sunny weather."],
    emoji: "☀️",
    syllables: "sun-ny",
    distractorGroup: "weather",
  },
  {
    word: "rainy",
    pos: "adjective",
    kidMeaning: "Having lots of rain.",
    examples: ["The rainy day makes her sad.", "He plays in the rainy weather."],
    emoji: "🌧️",
    syllables: "rain-y",
    distractorGroup: "weather",
  },
  {
    word: "windy",
    pos: "adjective",
    kidMeaning: "Having lots of wind.",
    examples: ["The windy day blows hard.", "She flies her kite in windy weather."],
    emoji: "💨",
    syllables: "wind-y",
    distractorGroup: "weather",
  },
  {
    word: "warm",
    pos: "adjective",
    kidMeaning: "Having or giving heat.",
    examples: ["The weather is very warm.", "She wraps in a warm blanket."],
    emoji: "🔥",
    syllables: "warm",
    distractorGroup: "quality",
  },
  {
    word: "cool",
    pos: "adjective",
    kidMeaning: "Pleasantly cold.",
    examples: ["The cool breeze feels nice.", "He takes a cool drink."],
    emoji: "🧊",
    syllables: "cool",
    distractorGroup: "quality",
  },
  {
    word: "thick",
    pos: "adjective",
    kidMeaning: "Having great distance through.",
    examples: ["The wall is very thick.", "He wears a thick sweater."],
    emoji: "📏",
    syllables: "thick",
    distractorGroup: "quality",
  },
  {
    word: "thin",
    pos: "adjective",
    kidMeaning: "Having small distance through.",
    examples: ["The paper is very thin.", "She wears thin socks."],
    emoji: "📄",
    syllables: "thin",
    distractorGroup: "quality",
  },
  {
    word: "tall",
    pos: "adjective",
    kidMeaning: "Having great height.",
    examples: ["The building is very tall.", "He is a tall boy."],
    emoji: "📏",
    syllables: "tall",
    distractorGroup: "size",
  },
  {
    word: "light",
    pos: "adjective",
    kidMeaning: "Of little weight or not heavy.",
    examples: ["The feather is very light.", "She carries light bags."],
    emoji: "🪶",
    syllables: "light",
    distractorGroup: "quality",
  },
  {
    word: "modern",
    pos: "adjective",
    kidMeaning: "Of recent times or now.",
    examples: ["The modern building is tall.", "She likes modern music."],
    emoji: "🏢",
    syllables: "mod-ern",
    distractorGroup: "time",
  },
  {
    word: "sprint",
    pos: "verb",
    kidMeaning: "To run very fast over a short distance.",
    examples: ["She sprints to the finish line.", "He sprints across the field."],
    emoji: "🏃",
    syllables: "sprint",
    distractorGroup: "actions",
  },
  {
    word: "wander",
    pos: "verb",
    kidMeaning: "To walk with no fixed destination.",
    examples: ["She wanders through the market.", "He wanders the streets."],
    emoji: "🗺️",
    syllables: "wan-der",
    distractorGroup: "actions",
  },
  {
    word: "inspect",
    pos: "verb",
    kidMeaning: "To look carefully at something.",
    examples: ["She inspects the building.", "He inspects the car for damage."],
    emoji: "🔍",
    syllables: "in-spect",
    distractorGroup: "actions",
  },
  {
    word: "observe",
    pos: "verb",
    kidMeaning: "To watch or notice something.",
    examples: ["She observes the animals.", "He observes the rules."],
    emoji: "👀",
    syllables: "ob-serve",
    distractorGroup: "actions",
  },
  {
    word: "flatten",
    pos: "verb",
    kidMeaning: "To make something flat.",
    examples: ["She flattens the dough.", "He flattens the boxes."],
    emoji: "📏",
    syllables: "flat-ten",
    distractorGroup: "actions",
  },
  {
    word: "crumple",
    pos: "verb",
    kidMeaning: "To crush something into a ball.",
    examples: ["She crumples the paper.", "He crumples his shirt."],
    emoji: "📄",
    syllables: "crum-ple",
    distractorGroup: "actions",
  },
  {
    word: "squeeze",
    pos: "verb",
    kidMeaning: "To press or compress.",
    examples: ["She squeezes the sponge.", "He squeezes the juice from the fruit."],
    emoji: "🍋",
    syllables: "squeeze",
    distractorGroup: "actions",
  },
  {
    word: "stretch",
    pos: "verb",
    kidMeaning: "To make something longer or wider.",
    examples: ["She stretches the fabric.", "He stretches before exercise."],
    emoji: "🤸",
    syllables: "stretch",
    distractorGroup: "actions",
  },
  {
    word: "unfold",
    pos: "verb",
    kidMeaning: "To open something that was folded.",
    examples: ["She unfolds the map.", "He unfolds his chair."],
    emoji: "📝",
    syllables: "un-fold",
    distractorGroup: "actions",
  },
  {
    word: "roll",
    pos: "verb",
    kidMeaning: "To turn over and over.",
    examples: ["She rolls the ball.", "He rolls down the hill."],
    emoji: "⚽",
    syllables: "roll",
    distractorGroup: "actions",
  },
  {
    word: "slide",
    pos: "verb",
    kidMeaning: "To move smoothly over a surface.",
    examples: ["She slides on the ice.", "He slides down the slope."],
    emoji: "🛷",
    syllables: "slide",
    distractorGroup: "actions",
  },
  {
    word: "stumble",
    pos: "verb",
    kidMeaning: "To almost fall while walking.",
    examples: ["She stumbles over a stone.", "He stumbles in the dark."],
    emoji: "🚶",
    syllables: "stum-ble",
    distractorGroup: "actions",
  },
  {
    word: "trip",
    pos: "verb",
    kidMeaning: "To lose your footing and fall.",
    examples: ["She trips on the stairs.", "He trips over the mat."],
    emoji: "🚶",
    syllables: "trip",
    distractorGroup: "actions",
  },
  {
    word: "slip",
    pos: "verb",
    kidMeaning: "To slide by mistake.",
    examples: ["She slips on the floor.", "He slips on the wet ground."],
    emoji: "🪨",
    syllables: "slip",
    distractorGroup: "actions",
  },
  {
    word: "zigzag",
    pos: "verb",
    kidMeaning: "To move in a side to side pattern.",
    examples: ["She zigzags through the crowd.", "He zigzags down the hill."],
    emoji: "⚡",
    syllables: "zig-zag",
    distractorGroup: "actions",
  },
  {
    word: "hover",
    pos: "verb",
    kidMeaning: "To hang in the air.",
    examples: ["The helicopter hovers over the building.", "The bird hovers before landing."],
    emoji: "🚁",
    syllables: "hov-er",
    distractorGroup: "actions",
  },
  {
    word: "toddler",
    pos: "noun",
    kidMeaning: "A very young child learning to walk.",
    examples: ["The toddler learns to walk.", "She plays with the toddler."],
    emoji: "👶",
    syllables: "tod-dler",
    distractorGroup: "people",
  },
  {
    word: "elderly",
    pos: "adjective",
    kidMeaning: "Very old in age.",
    examples: ["The elderly man walks slowly.", "She helps elderly people."],
    emoji: "👴",
    syllables: "eld-erly",
    distractorGroup: "people",
  },
  {
    word: "twin",
    pos: "noun",
    kidMeaning: "One of two children born at the same time.",
    examples: ["He is a twin with his brother.", "The twins look the same."],
    emoji: "👯",
    syllables: "twin",
    distractorGroup: "people",
  },
  {
    word: "grandparent",
    pos: "noun",
    kidMeaning: "The parent of your parent.",
    examples: ["She visits her grandparent every week.", "My grandparent tells me stories."],
    emoji: "👵",
    syllables: "grand-par-ent",
    distractorGroup: "family",
  },
  {
    word: "crowd",
    pos: "noun",
    kidMeaning: "A large group of people together.",
    examples: ["A large crowd gathers at the market.", "She pushes through the crowd."],
    emoji: "👥",
    syllables: "crowd",
    distractorGroup: "people",
  },
  {
    word: "cyclist",
    pos: "noun",
    kidMeaning: "A person who rides a bicycle.",
    examples: ["The cyclist rides fast down the road.", "She is a skilled cyclist."],
    emoji: "🚴",
    syllables: "cy-clist",
    distractorGroup: "people",
  },
  {
    word: "tourist",
    pos: "noun",
    kidMeaning: "A person visiting a place for pleasure.",
    examples: ["The tourist takes many pictures.", "They are tourists visiting the city."],
    emoji: "📷",
    syllables: "tour-ist",
    distractorGroup: "people",
  },
  {
    word: "visitor",
    pos: "noun",
    kidMeaning: "A person who comes to see someone.",
    examples: ["We welcome the visitor to our home.", "He is a frequent visitor."],
    emoji: "🤝",
    syllables: "vis-i-tor",
    distractorGroup: "people",
  },
  {
    word: "owner",
    pos: "noun",
    kidMeaning: "A person who possesses something.",
    examples: ["The owner of the shop is friendly.", "She is the owner of the cat."],
    emoji: "🏠",
    syllables: "own-er",
    distractorGroup: "people",
  },
  {
    word: "boss",
    pos: "noun",
    kidMeaning: "A person in charge of workers.",
    examples: ["My boss gives me work to do.", "The boss is very strict."],
    emoji: "👔",
    syllables: "boss",
    distractorGroup: "people",
  },
  {
    word: "staff",
    pos: "noun",
    kidMeaning: "All the workers in a place.",
    examples: ["She is part of the staff.", "He joins the hotel staff."],
    emoji: "👨‍💼",
    syllables: "staff",
    distractorGroup: "people",
  },
  {
    word: "cleaner",
    pos: "noun",
    kidMeaning: "A person who makes things clean.",
    examples: ["The cleaner sweeps the floor.", "She works as a cleaner."],
    emoji: "🧹",
    syllables: "clean-er",
    distractorGroup: "people",
  },
  {
    word: "postman",
    pos: "noun",
    kidMeaning: "A person who delivers letters.",
    examples: ["The postman brings letters to our house.", "She sees the postman every day."],
    emoji: "📬",
    syllables: "post-man",
    distractorGroup: "people",
  },
  {
    word: "mechanic",
    pos: "noun",
    kidMeaning: "A person who fixes machines or cars.",
    examples: ["The mechanic fixes the broken car.", "She is a skilled mechanic."],
    emoji: "🔧",
    syllables: "me-chan-ic",
    distractorGroup: "people",
  },
  {
    word: "vet",
    pos: "noun",
    kidMeaning: "A doctor for animals.",
    examples: ["The vet checks the sick dog.", "She takes her cat to the vet."],
    emoji: "🐾",
    syllables: "vet",
    distractorGroup: "people",
  },
  {
    word: "lifeguard",
    pos: "noun",
    kidMeaning: "A person who watches swimmers for safety.",
    examples: ["The lifeguard sits by the pool.", "She works as a lifeguard."],
    emoji: "🏖️",
    syllables: "life-guard",
    distractorGroup: "people",
  },
  {
    word: "salesman",
    pos: "noun",
    kidMeaning: "A person who sells things.",
    examples: ["The salesman shows the customer the shirt.", "He works as a salesman in a shop."],
    emoji: "🛒",
    syllables: "sales-man",
    distractorGroup: "people",
  },
  {
    word: "neighbourhood",
    pos: "noun",
    kidMeaning: "The area around where you live.",
    examples: ["She knows many people in her neighbourhood.", "My neighbourhood is very quiet."],
    emoji: "🏘️",
    syllables: "neigh-bour-hood",
    distractorGroup: "places",
  },
  {
    word: "estate",
    pos: "noun",
    kidMeaning: "A large area of land with buildings.",
    examples: ["They live in a large housing estate.", "The estate has many trees."],
    emoji: "🏘️",
    syllables: "es-tate",
    distractorGroup: "places",
  },
  {
    word: "storey",
    pos: "noun",
    kidMeaning: "A level or floor of a building.",
    examples: ["The building has ten storeys.", "They live on the third storey."],
    emoji: "🏢",
    syllables: "sto-rey",
    distractorGroup: "places",
  },
  {
    word: "staircase",
    pos: "noun",
    kidMeaning: "Steps that go up or down between floors.",
    examples: ["She walks down the staircase carefully.", "The staircase is made of wood."],
    emoji: "🪜",
    syllables: "stair-case",
    distractorGroup: "places",
  },
  {
    word: "rooftop",
    pos: "noun",
    kidMeaning: "The top surface of a building.",
    examples: ["We play on the rooftop.", "The rooftop has a nice view."],
    emoji: "🏠",
    syllables: "roof-top",
    distractorGroup: "places",
  },
  {
    word: "carpark",
    pos: "noun",
    kidMeaning: "A place where cars are left.",
    examples: ["She parks her car in the carpark.", "The carpark is very busy."],
    emoji: "🅿️",
    syllables: "car-park",
    distractorGroup: "places",
  },
  {
    word: "crossing",
    pos: "noun",
    kidMeaning: "A place to safely cross a road.",
    examples: ["She waits at the crossing for the light.", "Use the crossing to cross safely."],
    emoji: "🚸",
    syllables: "cross-ing",
    distractorGroup: "places",
  },
  {
    word: "junction",
    pos: "noun",
    kidMeaning: "A place where roads or paths meet.",
    examples: ["The junction is very busy with cars.", "Turn right at the junction."],
    emoji: "🛣️",
    syllables: "junc-tion",
    distractorGroup: "places",
  },
  {
    word: "roundabout",
    pos: "noun",
    kidMeaning: "A circular place where roads meet.",
    examples: ["The car goes round the roundabout.", "There is a roundabout at this junction."],
    emoji: "🔄",
    syllables: "round-a-about",
    distractorGroup: "places",
  },
  {
    word: "footpath",
    pos: "noun",
    kidMeaning: "A path for people to walk on.",
    examples: ["We walk on the footpath.", "The footpath is beside the road."],
    emoji: "🚶",
    syllables: "foot-path",
    distractorGroup: "places",
  },
  {
    word: "kerb",
    pos: "noun",
    kidMeaning: "The edge of a path beside a road.",
    examples: ["The ball rolls to the kerb.", "She sits on the kerb."],
    emoji: "🪨",
    syllables: "kerb",
    distractorGroup: "places",
  },
  {
    word: "drain",
    pos: "noun",
    kidMeaning: "A pipe or hole for water to flow out.",
    examples: ["The drain takes the water away.", "Water flows down the drain."],
    emoji: "🚰",
    syllables: "drain",
    distractorGroup: "places",
  },
  {
    word: "lamppost",
    pos: "noun",
    kidMeaning: "A tall pole with a light at the top.",
    examples: ["The lamppost lights the street.", "We meet by the lamppost."],
    emoji: "💡",
    syllables: "lamp-post",
    distractorGroup: "places",
  },
  {
    word: "signboard",
    pos: "noun",
    kidMeaning: "A board with writing to give information.",
    examples: ["The signboard shows the shop name.", "She reads the signboard."],
    emoji: "🪧",
    syllables: "sign-board",
    distractorGroup: "places",
  },
  {
    word: "shophouse",
    pos: "noun",
    kidMeaning: "A building with a shop below and home above.",
    examples: ["They live in a shophouse.", "The shophouse is very old."],
    emoji: "🏪",
    syllables: "shop-house",
    distractorGroup: "places",
  },
  {
    word: "kiosk",
    pos: "noun",
    kidMeaning: "A small shop or stand for selling things.",
    examples: ["She buys a drink at the kiosk.", "The kiosk sells newspapers."],
    emoji: "🎪",
    syllables: "ki-osk",
    distractorGroup: "places",
  },
  {
    word: "warehouse",
    pos: "noun",
    kidMeaning: "A large building for storing goods.",
    examples: ["The warehouse stores many boxes.", "Goods are sent from the warehouse."],
    emoji: "🏭",
    syllables: "ware-house",
    distractorGroup: "places",
  },
  {
    word: "bookshop",
    pos: "noun",
    kidMeaning: "A shop that sells books.",
    examples: ["She buys a book at the bookshop.", "The bookshop has many shelves."],
    emoji: "📚",
    syllables: "book-shop",
    distractorGroup: "places",
  },
  {
    word: "jetty",
    pos: "noun",
    kidMeaning: "A path of stone going into the water.",
    examples: ["The boat leaves from the jetty.", "They fish from the jetty."],
    emoji: "⚓",
    syllables: "jet-ty",
    distractorGroup: "places",
  },
  {
    word: "pier",
    pos: "noun",
    kidMeaning: "A structure built into the water for boats.",
    examples: ["The ship is at the pier.", "People walk on the pier."],
    emoji: "⛴️",
    syllables: "pier",
    distractorGroup: "places",
  },
  {
    word: "interchange",
    pos: "noun",
    kidMeaning: "A place where people change transport.",
    examples: ["The bus interchange is busy.", "She changes buses at the interchange."],
    emoji: "🚌",
    syllables: "in-ter-change",
    distractorGroup: "places",
  },
  {
    word: "terminal",
    pos: "noun",
    kidMeaning: "A building where transport stops.",
    examples: ["The bus terminal is large.", "They meet at the airport terminal."],
    emoji: "✈️",
    syllables: "ter-mi-nal",
    distractorGroup: "places",
  },
  {
    word: "detour",
    pos: "noun",
    kidMeaning: "A different way to go because the usual way is blocked.",
    examples: ["The road is closed so we take a detour.", "The detour makes the trip longer."],
    emoji: "🛣️",
    syllables: "de-tour",
    distractorGroup: "travel",
  },
  {
    word: "traffic",
    pos: "noun",
    kidMeaning: "Many cars and vehicles on the road.",
    examples: ["The traffic is very heavy.", "There is much traffic at rush hour."],
    emoji: "🚗",
    syllables: "traf-fic",
    distractorGroup: "travel",
  },
  {
    word: "jam",
    pos: "noun",
    kidMeaning: "A place where traffic is stuck and moving slowly.",
    examples: ["We are stuck in a traffic jam.", "The jam lasts for two hours."],
    emoji: "🚦",
    syllables: "jam",
    distractorGroup: "travel",
  },
  {
    word: "honk",
    pos: "verb",
    kidMeaning: "To make a loud noise with a car horn.",
    examples: ["The driver honks the horn.", "She honks at the slow car."],
    emoji: "📯",
    syllables: "honk",
    distractorGroup: "actions",
  },
  {
    word: "overtake",
    pos: "verb",
    kidMeaning: "To pass another moving vehicle.",
    examples: ["The car overtakes the bus.", "He overtakes the slow cyclist."],
    emoji: "🚗",
    syllables: "o-ver-take",
    distractorGroup: "actions",
  },
  {
    word: "reverse",
    pos: "verb",
    kidMeaning: "To go backward.",
    examples: ["She reverses the car into the space.", "The car reverses out of the driveway."],
    emoji: "⬅️",
    syllables: "re-verse",
    distractorGroup: "actions",
  },
  {
    word: "alight",
    pos: "verb",
    kidMeaning: "To get off a vehicle.",
    examples: ["He alights from the bus.", "She alights at the next stop."],
    emoji: "🚌",
    syllables: "a-light",
    distractorGroup: "actions",
  },
  {
    word: "cancel",
    pos: "verb",
    kidMeaning: "To say something will not happen.",
    examples: ["The teacher cancels the trip.", "They cancel the meeting."],
    emoji: "❌",
    syllables: "can-cel",
    distractorGroup: "actions",
  },
  {
    word: "arrival",
    pos: "noun",
    kidMeaning: "When someone or something comes to a place.",
    examples: ["The arrival of the bus is delayed.", "His arrival is at three o'clock."],
    emoji: "🚌",
    syllables: "ar-riv-al",
    distractorGroup: "travel",
  },
  {
    word: "departure",
    pos: "noun",
    kidMeaning: "When someone or something leaves a place.",
    examples: ["The departure time is at nine.", "The departure is delayed by one hour."],
    emoji: "✈️",
    syllables: "de-par-ture",
    distractorGroup: "travel",
  },
  {
    word: "seatbelt",
    pos: "noun",
    kidMeaning: "A strap to keep you safe in a car.",
    examples: ["She wears her seatbelt in the car.", "Always fasten your seatbelt."],
    emoji: "🔐",
    syllables: "seat-belt",
    distractorGroup: "objects",
  },
  {
    word: "helmet",
    pos: "noun",
    kidMeaning: "A hard hat to protect your head.",
    examples: ["He wears a helmet on his bike.", "The helmet keeps you safe."],
    emoji: "🪖",
    syllables: "hel-met",
    distractorGroup: "objects",
  },
  {
    word: "pedal",
    pos: "noun",
    kidMeaning: "A part of a bike you push with your foot.",
    examples: ["She pushes the pedal on her bike.", "The pedal moves the wheel."],
    emoji: "🚴",
    syllables: "ped-al",
    distractorGroup: "objects",
  },
  {
    word: "tyre",
    pos: "noun",
    kidMeaning: "A round rubber part of a wheel.",
    examples: ["The tyre is flat.", "She pumps air into the tyre."],
    emoji: "🛞",
    syllables: "tyre",
    distractorGroup: "objects",
  },
  {
    word: "puncture",
    pos: "noun",
    kidMeaning: "A small hole in a tyre.",
    examples: ["The bike has a puncture.", "A nail causes a puncture."],
    emoji: "🔨",
    syllables: "punc-ture",
    distractorGroup: "objects",
  },
  {
    word: "voucher",
    pos: "noun",
    kidMeaning: "A paper or card to get a discount.",
    examples: ["She uses a voucher to buy shoes.", "The voucher saves her money."],
    emoji: "🎟️",
    syllables: "vouch-er",
    distractorGroup: "shopping",
  },
  {
    word: "coupon",
    pos: "noun",
    kidMeaning: "A piece of paper for a discount.",
    examples: ["He cuts out a coupon from a magazine.", "The coupon gives a discount."],
    emoji: "✂️",
    syllables: "cou-pon",
    distractorGroup: "shopping",
  },
  {
    word: "counter",
    pos: "noun",
    kidMeaning: "A high table where shop work happens.",
    examples: ["The cashier stands behind the counter.", "She pays at the counter."],
    emoji: "🏪",
    syllables: "coun-ter",
    distractorGroup: "objects",
  },
  {
    word: "label",
    pos: "noun",
    kidMeaning: "A piece of paper with information on it.",
    examples: ["The label shows the price.", "She reads the label on the box."],
    emoji: "🏷️",
    syllables: "la-bel",
    distractorGroup: "objects",
  },
  {
    word: "barcode",
    pos: "noun",
    kidMeaning: "Black lines that show information to a machine.",
    examples: ["The barcode scans the price.", "She scans the barcode at the shop."],
    emoji: "📊",
    syllables: "bar-code",
    distractorGroup: "objects",
  },
  {
    word: "brand",
    pos: "noun",
    kidMeaning: "The name of a company that makes things.",
    examples: ["She likes this brand of shoes.", "The brand is very popular."],
    emoji: "🏷️",
    syllables: "brand",
    distractorGroup: "objects",
  },
  {
    word: "purchase",
    pos: "noun",
    kidMeaning: "Something you buy.",
    examples: ["She makes a purchase at the shop.", "His purchase costs twenty dollars."],
    emoji: "💳",
    syllables: "pur-chase",
    distractorGroup: "objects",
  },
  {
    word: "waste",
    pos: "noun",
    kidMeaning: "Rubbish or something not used well.",
    examples: ["Waste goes in the bin.", "Do not waste your money."],
    emoji: "♻️",
    syllables: "waste",
    distractorGroup: "objects",
  },
  {
    word: "savings",
    pos: "noun",
    kidMeaning: "Money kept for later use.",
    examples: ["She puts money in her savings.", "His savings are in the bank."],
    emoji: "🏦",
    syllables: "sav-ings",
    distractorGroup: "objects",
  },
  {
    word: "allowance",
    pos: "noun",
    kidMeaning: "Money given to you regularly.",
    examples: ["She gets an allowance every week.", "His allowance is used to buy toys."],
    emoji: "💰",
    syllables: "al-low-ance",
    distractorGroup: "objects",
  },
  {
    word: "pricey",
    pos: "adjective",
    kidMeaning: "Costing a lot of money.",
    examples: ["The shoes are very pricey.", "This restaurant is pricey."],
    emoji: "💸",
    syllables: "pric-ey",
    distractorGroup: "qualities",
  },
  {
    word: "owe",
    pos: "verb",
    kidMeaning: "To need to pay money to someone.",
    examples: ["She owes ten dollars to her friend.", "I owe you a thank you."],
    emoji: "💳",
    syllables: "owe",
    distractorGroup: "actions",
  },
  {
    word: "donate",
    pos: "verb",
    kidMeaning: "To give something to help people.",
    examples: ["They donate money to the school.", "She donates her old toys."],
    emoji: "🤝",
    syllables: "do-nate",
    distractorGroup: "actions",
  },
  {
    word: "charity",
    pos: "noun",
    kidMeaning: "A group that gives help to poor people.",
    examples: ["The charity helps poor people.", "She gives money to charity."],
    emoji: "❤️",
    syllables: "char-i-ty",
    distractorGroup: "objects",
  },
  {
    word: "weekday",
    pos: "noun",
    kidMeaning: "A day that is not Saturday or Sunday.",
    examples: ["Weekday mornings are busy.", "School is open on weekdays."],
    emoji: "📅",
    syllables: "week-day",
    distractorGroup: "time",
  },
  {
    word: "daily",
    pos: "adverb",
    kidMeaning: "Every day.",
    examples: ["She reads daily.", "The bus runs daily."],
    emoji: "📅",
    syllables: "dai-ly",
    distractorGroup: "time",
  },
  {
    word: "hourly",
    pos: "adverb",
    kidMeaning: "Every hour.",
    examples: ["The bus comes hourly.", "She checks hourly for news."],
    emoji: "🕐",
    syllables: "hour-ly",
    distractorGroup: "time",
  },
  {
    word: "overnight",
    pos: "adverb",
    kidMeaning: "During the night or very quickly.",
    examples: ["She stays overnight at her friend's house.", "The package arrives overnight."],
    emoji: "🌙",
    syllables: "o-ver-night",
    distractorGroup: "time",
  },
  {
    word: "appointment",
    pos: "noun",
    kidMeaning: "A planned time to meet someone.",
    examples: ["She has a doctor's appointment.", "The appointment is at three."],
    emoji: "📋",
    syllables: "ap-point-ment",
    distractorGroup: "objects",
  },
  {
    word: "errand",
    pos: "noun",
    kidMeaning: "A small trip to do a job.",
    examples: ["She runs an errand at the shop.", "His errands take one hour."],
    emoji: "🏃",
    syllables: "er-rand",
    distractorGroup: "actions",
  },
  {
    word: "chore",
    pos: "noun",
    kidMeaning: "A job that must be done at home.",
    examples: ["Washing dishes is her chore.", "He does his chores after school."],
    emoji: "🧹",
    syllables: "chore",
    distractorGroup: "actions",
  },
  {
    word: "reminder",
    pos: "noun",
    kidMeaning: "Something that helps you remember.",
    examples: ["The alarm is a reminder to go out.", "She sets a reminder on her phone."],
    emoji: "🔔",
    syllables: "re-mind-er",
    distractorGroup: "objects",
  },
  {
    word: "snooze",
    pos: "verb",
    kidMeaning: "To sleep for a short time.",
    examples: ["He snoozes for ten more minutes.", "She snoozes before getting up."],
    emoji: "😴",
    syllables: "snooze",
    distractorGroup: "actions",
  },
  {
    word: "nap",
    pos: "noun",
    kidMeaning: "A short time of sleep.",
    examples: ["She takes a nap after lunch.", "The baby sleeps during the nap."],
    emoji: "😴",
    syllables: "nap",
    distractorGroup: "actions",
  },
  {
    word: "curfew",
    pos: "noun",
    kidMeaning: "A time when you must be home.",
    examples: ["The curfew is at nine o'clock.", "She must be home by the curfew."],
    emoji: "⏰",
    syllables: "cur-few",
    distractorGroup: "objects",
  },
  {
    word: "festival",
    pos: "noun",
    kidMeaning: "A day or time of celebration.",
    examples: ["They celebrate the festival together.", "The festival has many events."],
    emoji: "🎉",
    syllables: "fes-ti-val",
    distractorGroup: "objects",
  },
  {
    word: "ceremony",
    pos: "noun",
    kidMeaning: "A formal event with special activities.",
    examples: ["The ceremony takes one hour.", "They attend the school ceremony."],
    emoji: "🎩",
    syllables: "cer-e-mo-ny",
    distractorGroup: "objects",
  },
  {
    word: "anniversary",
    pos: "noun",
    kidMeaning: "The date each year when something special happened.",
    examples: ["It is her birthday anniversary.", "They celebrate their anniversary."],
    emoji: "🎂",
    syllables: "an-ni-ver-sa-ry",
    distractorGroup: "objects",
  },
  {
    word: "chat",
    pos: "noun",
    kidMeaning: "A friendly talk between people.",
    examples: ["They have a chat after school.", "She enjoys a chat with friends."],
    emoji: "💬",
    syllables: "chat",
    distractorGroup: "actions",
  },
  {
    word: "gossip",
    pos: "noun",
    kidMeaning: "Talk about other people's lives.",
    examples: ["They gossip about their classmates.", "She spreads gossip to her friends."],
    emoji: "🗣️",
    syllables: "gos-sip",
    distractorGroup: "actions",
  },
  {
    word: "forgive",
    pos: "verb",
    kidMeaning: "To stop being angry at someone.",
    examples: ["She forgives him for his mistake.", "He asks her to forgive him."],
    emoji: "🤝",
    syllables: "for-give",
    distractorGroup: "actions",
  },
  {
    word: "remind",
    pos: "verb",
    kidMeaning: "To make someone remember.",
    examples: ["She reminds him to do his homework.", "Please remind me to call him."],
    emoji: "🔔",
    syllables: "re-mind",
    distractorGroup: "actions",
  },
  {
    word: "obey",
    pos: "verb",
    kidMeaning: "To do what someone asks.",
    examples: ["The child obeys the teacher.", "She obeys her parent's rules."],
    emoji: "👂",
    syllables: "o-bey",
    distractorGroup: "actions",
  },
  {
    word: "disobey",
    pos: "verb",
    kidMeaning: "To not do what someone asks.",
    examples: ["He disobeys the teacher.", "She disobeys her parent's rules."],
    emoji: "🙅",
    syllables: "dis-o-bey",
    distractorGroup: "actions",
  },
  {
    word: "misbehave",
    pos: "verb",
    kidMeaning: "To act badly.",
    examples: ["He misbehaves in class.", "She misbehaves at the restaurant."],
    emoji: "🚫",
    syllables: "mis-be-have",
    distractorGroup: "actions",
  },
  {
    word: "fetch",
    pos: "verb",
    kidMeaning: "To go and get something.",
    examples: ["She fetches water from the well.", "He fetches his bag from school."],
    emoji: "🏃",
    syllables: "fetch",
    distractorGroup: "actions",
  },
  {
    word: "pass",
    pos: "verb",
    kidMeaning: "To give something to someone.",
    examples: ["She passes the ball to him.", "He passes the letter to his mother."],
    emoji: "🤝",
    syllables: "pass",
    distractorGroup: "actions",
  },
  {
    word: "return",
    pos: "verb",
    kidMeaning: "To bring something back.",
    examples: ["She returns the book to the library.", "He returns home from school."],
    emoji: "🔄",
    syllables: "re-turn",
    distractorGroup: "actions",
  },
  {
    word: "swap",
    pos: "verb",
    kidMeaning: "To give something and get something else.",
    examples: ["They swap toys at playtime.", "She swaps her lunch with her friend."],
    emoji: "🔄",
    syllables: "swap",
    distractorGroup: "actions",
  },
  {
    word: "reserve",
    pos: "verb",
    kidMeaning: "To save something for later use.",
    examples: ["She reserves a seat at the cinema.", "He reserves a table at the restaurant."],
    emoji: "📖",
    syllables: "re-serve",
    distractorGroup: "actions",
  },
  {
    word: "apologise",
    pos: "verb",
    kidMeaning: "To say sorry to someone.",
    examples: ["He apologises for being late.", "She apologises for her mistake."],
    emoji: "🙏",
    syllables: "a-pol-o-gise",
    distractorGroup: "actions",
  },
  {
    word: "thank",
    pos: "verb",
    kidMeaning: "To show thanks to someone.",
    examples: ["She thanks him for his help.", "He thanks the teacher."],
    emoji: "🙏",
    syllables: "thank",
    distractorGroup: "actions",
  },
  {
    word: "queue",
    pos: "noun",
    kidMeaning: "A line of people waiting.",
    examples: ["They stand in a queue at the shop.", "The queue is very long."],
    emoji: "👥",
    syllables: "queue",
    distractorGroup: "objects",
  },
  {
    word: "commuter",
    pos: "noun",
    kidMeaning: "A person who travels to work every day.",
    examples: ["The commuter takes the bus to work.", "She is a daily commuter."],
    emoji: "🚌",
    syllables: "com-mut-er",
    distractorGroup: "people",
  },
];
