import type { Word } from "../words";

export const band6: Word[] = [
  {
    word: "embarrassed",
    pos: "adjective",
    kidMeaning: "Feeling shy or ashamed in front of others.",
    examples: ["She was embarrassed when she tripped in class.", "He felt embarrassed about making a silly mistake."],
    emoji: "😳",
    syllables: "em-bar-rassed",
    distractorGroup: "feelings",
  },
  {
    word: "relieved",
    pos: "adjective",
    kidMeaning: "Feeling happy because worry or pain stops.",
    examples: ["She felt relieved when the test was finally over.", "He was relieved to hear his friend was safe."],
    emoji: "😌",
    syllables: "re-lieved",
    distractorGroup: "feelings",
  },
  {
    word: "jealous",
    pos: "adjective",
    kidMeaning: "Feeling unhappy because someone else has something you want.",
    examples: ["She felt jealous when her friend won the prize.", "He was jealous of his brother's new toy."],
    emoji: "😒",
    syllables: "jeal-ous",
    distractorGroup: "feelings",
  },
  {
    word: "guilty",
    pos: "adjective",
    kidMeaning: "Feeling bad because you did something wrong.",
    examples: ["She felt guilty after lying to her mother.", "He looked guilty when caught stealing the biscuit."],
    emoji: "😔",
    syllables: "guil-ty",
    distractorGroup: "feelings",
  },
  {
    word: "delighted",
    pos: "adjective",
    kidMeaning: "Feeling very happy and pleased about something.",
    examples: ["She was delighted to receive a gift from her grandmother.", "He looked delighted when he won the game."],
    emoji: "😄",
    syllables: "de-light-ed",
    distractorGroup: "feelings",
  },
  {
    word: "frightened",
    pos: "adjective",
    kidMeaning: "Feeling very scared or afraid of something.",
    examples: ["She was frightened by the loud thunder.", "The child was frightened of the dark."],
    emoji: "😨",
    syllables: "fright-ened",
    distractorGroup: "feelings",
  },
  {
    word: "furious",
    pos: "adjective",
    kidMeaning: "Very angry about something.",
    examples: ["She was furious when someone broke her pencil.", "He looked furious after losing the match."],
    emoji: "😠",
    syllables: "fu-ri-ous",
    distractorGroup: "feelings",
  },
  {
    word: "miserable",
    pos: "adjective",
    kidMeaning: "Feeling very unhappy or sad.",
    examples: ["She felt miserable after her friend moved away.", "He looked miserable sitting alone at lunch."],
    emoji: "😢",
    syllables: "mis-er-a-ble",
    distractorGroup: "feelings",
  },
  {
    word: "homesick",
    pos: "adjective",
    kidMeaning: "Missing home when you are away from it.",
    examples: ["She felt homesick during the school camp.", "He got homesick after sleeping at his cousin's house."],
    emoji: "🏠",
    syllables: "home-sick",
    distractorGroup: "feelings",
  },
  {
    word: "content",
    pos: "adjective",
    kidMeaning: "Feeling satisfied and at peace.",
    examples: ["She felt content reading her favourite book.", "He looked content playing in the garden."],
    emoji: "😌",
    syllables: "con-tent",
    distractorGroup: "feelings",
  },
  {
    word: "ashamed",
    pos: "adjective",
    kidMeaning: "Feeling bad or shameful about what you did.",
    examples: ["She felt ashamed after being mean to someone.", "He was ashamed when caught cheating."],
    emoji: "😔",
    syllables: "a-shamed",
    distractorGroup: "feelings",
  },
  {
    word: "confused",
    pos: "adjective",
    kidMeaning: "Unable to understand.",
    examples: ["She felt confused by the difficult question.", "He looked confused when reading the instructions."],
    emoji: "🤔",
    syllables: "con-fused",
    distractorGroup: "feelings",
  },
  {
    word: "surprised",
    pos: "adjective",
    kidMeaning: "Feeling shocked because something unexpected happened.",
    examples: ["She was surprised to see a gift on her desk.", "He looked surprised when he saw the rainbow."],
    emoji: "😲",
    syllables: "sur-prised",
    distractorGroup: "feelings",
  },
  {
    word: "stubborn",
    pos: "adjective",
    kidMeaning: "Not willing to change your mind.",
    examples: ["She was stubborn and refused to say sorry.", "He is stubborn when he wants something."],
    emoji: "🚫",
    syllables: "stub-born",
    distractorGroup: "character",
  },
  {
    word: "greedy",
    pos: "adjective",
    kidMeaning: "Wanting too much of something for yourself.",
    examples: ["She looked greedy when taking all the food.", "He was greedy and wanted the biggest piece."],
    emoji: "🍽️",
    syllables: "gree-dy",
    distractorGroup: "character",
  },
  {
    word: "cheeky",
    pos: "adjective",
    kidMeaning: "Playfully rude or impolite.",
    examples: ["She gave her teacher a cheeky smile.", "He was cheeky and made a funny joke."],
    emoji: "😏",
    syllables: "chee-ky",
    distractorGroup: "character",
  },
  {
    word: "timid",
    pos: "adjective",
    kidMeaning: "Easily scared; not confident.",
    examples: ["She was too timid to raise her hand.", "He seemed timid when meeting new people."],
    emoji: "😳",
    syllables: "tim-id",
    distractorGroup: "character",
  },
  {
    word: "kind",
    pos: "adjective",
    kidMeaning: "Showing care and being nice to others.",
    examples: ["She was kind and helped an older person cross the road.", "He is kind to all his friends."],
    emoji: "💚",
    syllables: "kind",
    distractorGroup: "character",
  },
  {
    word: "cruel",
    pos: "adjective",
    kidMeaning: "Being mean and causing harm to others.",
    examples: ["She was cruel to exclude her classmate.", "He acted cruelly when teasing the younger child."],
    emoji: "😈",
    syllables: "cruel",
    distractorGroup: "character",
  },
  {
    word: "bossy",
    pos: "adjective",
    kidMeaning: "Always telling others what to do.",
    examples: ["She was bossy and wanted to lead the game.", "He acted bossy during the group work."],
    emoji: "📢",
    syllables: "boss-y",
    distractorGroup: "character",
  },
  {
    word: "arrogant",
    pos: "adjective",
    kidMeaning: "Too proud of yourself; thinking you are better than others.",
    examples: ["She was arrogant and looked down on others.", "He spoke in an arrogant tone."],
    emoji: "😏",
    syllables: "ar-ro-gant",
    distractorGroup: "character",
  },
  {
    word: "thoughtful",
    pos: "adjective",
    kidMeaning: "Thinking about others' feelings and needs.",
    examples: ["She was thoughtful and brought flowers to visit her friend.", "He showed thoughtfulness by helping without being asked."],
    emoji: "💭",
    syllables: "thought-ful",
    distractorGroup: "character",
  },
  {
    word: "creep",
    pos: "verb",
    kidMeaning: "To move slowly and quietly.",
    examples: ["She crept up the stairs to surprise her friend.", "He crept closer to see what was happening."],
    emoji: "🚶",
    syllables: "creep",
    distractorGroup: "action",
  },
  {
    word: "dash",
    pos: "verb",
    kidMeaning: "To run very fast.",
    examples: ["She dashed to catch the ball.", "He dashed across the field to score a goal."],
    emoji: "🏃",
    syllables: "dash",
    distractorGroup: "action",
  },
  {
    word: "gasp",
    pos: "verb",
    kidMeaning: "To suddenly breathe in sharply with surprise.",
    examples: ["She gasped when she saw the surprise party.", "He gasped at the sudden loud noise."],
    emoji: "😲",
    syllables: "gasp",
    distractorGroup: "action",
  },
  {
    word: "mutter",
    pos: "verb",
    kidMeaning: "To speak quietly and unclearly.",
    examples: ["She muttered something under her breath.", "He muttered a complaint as he left the room."],
    emoji: "🤐",
    syllables: "mut-ter",
    distractorGroup: "action",
  },
  {
    word: "giggle",
    pos: "verb",
    kidMeaning: "To laugh in a light, nervous way.",
    examples: ["She giggled at the funny joke.", "He giggled when tickled by his younger sister."],
    emoji: "😄",
    syllables: "gig-gle",
    distractorGroup: "action",
  },
  {
    word: "sob",
    pos: "verb",
    kidMeaning: "To cry with short, loud breaths.",
    examples: ["She sobbed after seeing the sad film.", "He sobbed when he could not find his lost toy."],
    emoji: "😭",
    syllables: "sob",
    distractorGroup: "action",
  },
  {
    word: "stagger",
    pos: "verb",
    kidMeaning: "To walk unsteadily, as if about to fall.",
    examples: ["She staggered under the weight of the heavy bag.", "He staggered backwards after the push."],
    emoji: "🚶",
    syllables: "stag-ger",
    distractorGroup: "action",
  },
  {
    word: "peep",
    pos: "verb",
    kidMeaning: "To look quickly at something, often secretly.",
    examples: ["She peeped through the door to see the surprise.", "He peeped at the answer sheet to cheat."],
    emoji: "👀",
    syllables: "peep",
    distractorGroup: "action",
  },
  {
    word: "pounce",
    pos: "verb",
    kidMeaning: "To jump on something suddenly and forcefully.",
    examples: ["The cat pounced on the mouse.", "She pounced on the opportunity to win the game."],
    emoji: "🐱",
    syllables: "pounce",
    distractorGroup: "action",
  },
  {
    word: "crouch",
    pos: "verb",
    kidMeaning: "To bend low and stay close to the ground.",
    examples: ["She crouched behind the bush to hide.", "He crouched down to pick up the coin."],
    emoji: "🤐",
    syllables: "crouch",
    distractorGroup: "action",
  },
  {
    word: "hug",
    pos: "verb",
    kidMeaning: "To put your arms around someone to show love.",
    examples: ["She hugged her mother when she arrived home.", "He hugged his friend tightly."],
    emoji: "🤗",
    syllables: "hug",
    distractorGroup: "action",
  },
  {
    word: "yell",
    pos: "verb",
    kidMeaning: "To shout loudly.",
    examples: ["She yelled to call her friend from far away.", "He yelled in pain when he stubbed his toe."],
    emoji: "📢",
    syllables: "yell",
    distractorGroup: "action",
  },
  {
    word: "scream",
    pos: "verb",
    kidMeaning: "To cry out loudly in fear or pain.",
    examples: ["She screamed when she saw the spider.", "He screamed as he went down the slide."],
    emoji: "😱",
    syllables: "scream",
    distractorGroup: "action",
  },
  {
    word: "whip",
    pos: "verb",
    kidMeaning: "To move something quickly with a sudden motion.",
    examples: ["She whipped around to see who was calling.", "He whipped the towel playfully."],
    emoji: "⚡",
    syllables: "whip",
    distractorGroup: "action",
  },
  {
    word: "spin",
    pos: "verb",
    kidMeaning: "To turn around quickly.",
    examples: ["She will spin in a circle until dizzy.", "He will spin the top and watch it turn."],
    emoji: "🌀",
    syllables: "spin",
    distractorGroup: "action",
  },
  {
    word: "twist",
    pos: "verb",
    kidMeaning: "To turn something around its centre.",
    examples: ["She twisted the lid to open the jar.", "He twisted his body to see behind him."],
    emoji: "🔄",
    syllables: "twist",
    distractorGroup: "action",
  },
  {
    word: "poke",
    pos: "verb",
    kidMeaning: "To push something with your finger or a pointed object.",
    examples: ["She poked the bubble wrap playfully.", "He poked his friend in the ribs to wake him up."],
    emoji: "👆",
    syllables: "poke",
    distractorGroup: "action",
  },
  {
    word: "nudge",
    pos: "verb",
    kidMeaning: "To push someone gently with your elbow.",
    examples: ["She nudged her friend to get his attention.", "He nudged the door open with his shoulder."],
    emoji: "👉",
    syllables: "nudge",
    distractorGroup: "action",
  },
  {
    word: "bump",
    pos: "verb",
    kidMeaning: "To hit something lightly.",
    examples: ["She bumped into the door by accident.", "He bumped his head on the low ceiling."],
    emoji: "💥",
    syllables: "bump",
    distractorGroup: "action",
  },
  {
    word: "collide",
    pos: "verb",
    kidMeaning: "To crash into something with force.",
    examples: ["The two cars collided at the intersection.", "She collided with a person while running."],
    emoji: "💥",
    syllables: "col-lide",
    distractorGroup: "action",
  },
  {
    word: "bounce",
    pos: "verb",
    kidMeaning: "To spring back after hitting a surface.",
    examples: ["The ball bounced across the court.", "She bounced on the bed happily."],
    emoji: "⛹️",
    syllables: "bounce",
    distractorGroup: "action",
  },
  {
    word: "hop",
    pos: "verb",
    kidMeaning: "To jump on one leg or bounce up and down.",
    examples: ["She hopped on one foot in the playground.", "The rabbit hopped across the garden."],
    emoji: "🐰",
    syllables: "hop",
    distractorGroup: "action",
  },
  {
    word: "jump",
    pos: "verb",
    kidMeaning: "To push yourself off the ground with force.",
    examples: ["She jumped over the puddle.", "He jumped up with joy when he heard the good news."],
    emoji: "🤸",
    syllables: "jump",
    distractorGroup: "action",
  },
  {
    word: "swim",
    pos: "verb",
    kidMeaning: "To move through water using your arms and legs.",
    examples: ["She will swim in the pool fast.", "He can swim very well now."],
    emoji: "🏊",
    syllables: "swim",
    distractorGroup: "action",
  },
  {
    word: "dive",
    pos: "verb",
    kidMeaning: "To plunge into water headfirst.",
    examples: ["She dived into the pool from the diving board.", "He dived to catch the falling ball."],
    emoji: "🤿",
    syllables: "dive",
    distractorGroup: "action",
  },
  {
    word: "drag",
    pos: "verb",
    kidMeaning: "To pull something along the ground.",
    examples: ["She dragged her suitcase up the stairs.", "He dragged his feet when walking slowly."],
    emoji: "🚧",
    syllables: "drag",
    distractorGroup: "action",
  },
  {
    word: "snatch",
    pos: "verb",
    kidMeaning: "To grab something quickly and roughly.",
    examples: ["She snatched the toy away from her brother.", "He snatched the last piece of cake."],
    emoji: "⚡",
    syllables: "snatch",
    distractorGroup: "action",
  },
  {
    word: "flick",
    pos: "verb",
    kidMeaning: "To move something quickly with a light motion.",
    examples: ["She flicked the switch to turn on the light.", "He flicked water at his friend playfully."],
    emoji: "⚡",
    syllables: "flick",
    distractorGroup: "action",
  },
  {
    word: "sway",
    pos: "verb",
    kidMeaning: "To move back and forth gently.",
    examples: ["The trees swayed in the wind.", "She swayed to the music while dancing."],
    emoji: "🌊",
    syllables: "sway",
    distractorGroup: "action",
  },
  {
    word: "glide",
    pos: "verb",
    kidMeaning: "To move smoothly and easily.",
    examples: ["The skater glided across the ice.", "She glided down the stairs gracefully."],
    emoji: "✨",
    syllables: "glide",
    distractorGroup: "action",
  },
  {
    word: "reply",
    pos: "verb",
    kidMeaning: "To answer someone when they speak to you.",
    examples: ["She replied to his question honestly.", "He replied with a smile to her greeting."],
    emoji: "💬",
    syllables: "re-ply",
    distractorGroup: "saying",
  },
  {
    word: "insist",
    pos: "verb",
    kidMeaning: "To say something firmly and not change your mind.",
    examples: ["She insisted that she did not break the vase.", "He insisted on finishing his work before playing."],
    emoji: "📢",
    syllables: "in-sist",
    distractorGroup: "saying",
  },
  {
    word: "complain",
    pos: "verb",
    kidMeaning: "To say that you are unhappy about something.",
    examples: ["She complained about the cold weather.", "He complained that the homework was too difficult."],
    emoji: "😤",
    syllables: "com-plain",
    distractorGroup: "saying",
  },
  {
    word: "warn",
    pos: "verb",
    kidMeaning: "To tell someone about a danger or problem.",
    examples: ["She warned him about the icy path.", "He warned the children not to go near the cliff."],
    emoji: "⚠️",
    syllables: "warn",
    distractorGroup: "saying",
  },
  {
    word: "exclaim",
    pos: "verb",
    kidMeaning: "To say something loudly and with strong emotion.",
    examples: ["She exclaimed with delight at the surprise.", "He exclaimed in pain when he touched the hot stove."],
    emoji: "😲",
    syllables: "ex-claim",
    distractorGroup: "saying",
  },
  {
    word: "stammer",
    pos: "verb",
    kidMeaning: "To speak with difficulty, repeating sounds.",
    examples: ["She stammered when nervous while speaking.", "He stammered as he told his story."],
    emoji: "😳",
    syllables: "stam-mer",
    distractorGroup: "saying",
  },
  {
    word: "tease",
    pos: "verb",
    kidMeaning: "To make fun of someone in a playful way.",
    examples: ["She teased her brother about his new glasses.", "He teased his friend about being slow."],
    emoji: "😏",
    syllables: "tease",
    distractorGroup: "saying",
  },
  {
    word: "moan",
    pos: "verb",
    kidMeaning: "To make a low sound of pain or sadness.",
    examples: ["She moaned when she had a headache.", "He moaned about the unfair decision."],
    emoji: "😞",
    syllables: "moan",
    distractorGroup: "saying",
  },
  {
    word: "groan",
    pos: "verb",
    kidMeaning: "To make a deep sound showing pain or tiredness.",
    examples: ["She groaned when waking up early.", "He groaned under the weight of the heavy box."],
    emoji: "😫",
    syllables: "groan",
    distractorGroup: "saying",
  },
  {
    word: "growl",
    pos: "verb",
    kidMeaning: "To make a deep angry sound.",
    examples: ["The dog growled at the stranger.", "She growled in annoyance when interrupted."],
    emoji: "😠",
    syllables: "growl",
    distractorGroup: "saying",
  },
  {
    word: "hiss",
    pos: "verb",
    kidMeaning: "To make a sharp sound like a snake.",
    examples: ["The cat hissed at the new kitten.", "She hissed a warning to be quiet."],
    emoji: "🐍",
    syllables: "hiss",
    distractorGroup: "saying",
  },
  {
    word: "sigh",
    pos: "verb",
    kidMeaning: "To breathe out heavily, showing sadness or tiredness.",
    examples: ["She sighed with relief when the test ended.", "He sighed deeply, worried about his marks."],
    emoji: "😔",
    syllables: "sigh",
    distractorGroup: "saying",
  },
  {
    word: "snort",
    pos: "verb",
    kidMeaning: "To make a sharp sound through your nose.",
    examples: ["He snorted with laughter at the joke.", "She snorted in disbelief at the story."],
    emoji: "😒",
    syllables: "snort",
    distractorGroup: "saying",
  },
  {
    word: "grumble",
    pos: "verb",
    kidMeaning: "To complain in a quiet, unhappy way.",
    examples: ["She grumbled about having to do chores.", "He grumbled while doing his homework."],
    emoji: "😤",
    syllables: "grum-ble",
    distractorGroup: "saying",
  },
  {
    word: "murmur",
    pos: "verb",
    kidMeaning: "To speak in a soft, unclear way.",
    examples: ["She murmured her thanks quietly.", "He murmured agreement from the back of the class."],
    emoji: "🤐",
    syllables: "mur-mur",
    distractorGroup: "saying",
  },
  {
    word: "mumble",
    pos: "verb",
    kidMeaning: "To speak unclearly, making it hard to understand.",
    examples: ["She mumbled an excuse when late.", "He mumbled something under his breath."],
    emoji: "🤐",
    syllables: "mum-ble",
    distractorGroup: "saying",
  },
  {
    word: "chant",
    pos: "verb",
    kidMeaning: "To sing or shout the same words repeatedly.",
    examples: ["They chanted their team's name at the match.", "The crowd chanted together loudly."],
    emoji: "🎵",
    syllables: "chant",
    distractorGroup: "saying",
  },
  {
    word: "cheer",
    pos: "verb",
    kidMeaning: "To shout for joy or to support someone.",
    examples: ["She cheered when her team won the match.", "They cheered loudly for the players."],
    emoji: "📢",
    syllables: "cheer",
    distractorGroup: "saying",
  },
  {
    word: "boo",
    pos: "verb",
    kidMeaning: "To make a sound to show disapproval or to scare someone.",
    examples: ["The audience booed the losing team.", "He booed to scare his sister."],
    emoji: "👻",
    syllables: "boo",
    distractorGroup: "saying",
  },
  {
    word: "hoot",
    pos: "verb",
    kidMeaning: "To make a loud sound like an owl.",
    examples: ["The owl hooted at night in the forest.", "She hooted with laughter at the funny moment."],
    emoji: "🦉",
    syllables: "hoot",
    distractorGroup: "saying",
  },
  {
    word: "squeak",
    pos: "verb",
    kidMeaning: "To make a high, thin sound.",
    examples: ["The door squeaked when opened.", "She squeaked with excitement at the gift."],
    emoji: "🐭",
    syllables: "squeak",
    distractorGroup: "saying",
  },
  {
    word: "screech",
    pos: "verb",
    kidMeaning: "To make a loud, harsh, high sound.",
    examples: ["The brakes screeched as the car stopped.", "She screeched with laughter at the joke."],
    emoji: "😲",
    syllables: "screech",
    distractorGroup: "saying",
  },
  {
    word: "realise",
    pos: "verb",
    kidMeaning: "To understand or become aware of something.",
    examples: ["She realised she had made a big mistake.", "He realised the truth when she told him."],
    emoji: "💡",
    syllables: "re-al-ise",
    distractorGroup: "thinking",
    confusedWith: "realize (American spelling)",
  },
  {
    word: "decide",
    pos: "verb",
    kidMeaning: "To make up your mind about something.",
    examples: ["She decided to join the football team.", "He decided to tell the truth."],
    emoji: "✅",
    syllables: "de-cide",
    distractorGroup: "thinking",
  },
  {
    word: "imagine",
    pos: "verb",
    kidMeaning: "To picture something in your mind.",
    examples: ["She imagined living in a fairy tale castle.", "He imagined what it would be like to be famous."],
    emoji: "🧠",
    syllables: "i-mag-ine",
    distractorGroup: "thinking",
  },
  {
    word: "remember",
    pos: "verb",
    kidMeaning: "To recall something from your memory.",
    examples: ["She remembered the day they first became friends.", "He tried to remember the answer to the question."],
    emoji: "💭",
    syllables: "re-mem-ber",
    distractorGroup: "thinking",
  },
  {
    word: "forget",
    pos: "verb",
    kidMeaning: "To fail to remember something.",
    examples: ["She forgot to bring her homework to school.", "He could not forget the sad moment."],
    emoji: "😕",
    syllables: "for-get",
    distractorGroup: "thinking",
  },
  {
    word: "doubt",
    pos: "verb",
    kidMeaning: "To have questions about whether something is true.",
    examples: ["She doubted his excuse for being late.", "He doubted he could win the race."],
    emoji: "🤨",
    syllables: "doubt",
    distractorGroup: "thinking",
  },
  {
    word: "recognise",
    pos: "verb",
    kidMeaning: "To identify or know someone you have seen before.",
    examples: ["She recognised her friend from far away.", "He recognised the voice immediately."],
    emoji: "👁️",
    syllables: "rec-og-nise",
    distractorGroup: "thinking",
    confusedWith: "recognize (American spelling)",
  },
  {
    word: "notice",
    pos: "verb",
    kidMeaning: "To see or observe something.",
    examples: ["She noticed a small scratch on the desk.", "He noticed that someone was missing."],
    emoji: "👀",
    syllables: "no-tice",
    distractorGroup: "thinking",
  },
  {
    word: "ponder",
    pos: "verb",
    kidMeaning: "To think deeply about something.",
    examples: ["She pondered the difficult question.", "He pondered what he should do next."],
    emoji: "🤔",
    syllables: "pon-der",
    distractorGroup: "thinking",
  },
  {
    word: "daydream",
    pos: "verb",
    kidMeaning: "To think about pleasant things while awake.",
    examples: ["She daydreamed about her holiday.", "He daydreamed during the boring lesson."],
    emoji: "😴",
    syllables: "day-dream",
    distractorGroup: "thinking",
  },
  {
    word: "villain",
    pos: "noun",
    kidMeaning: "The bad character in a story.",
    examples: ["The villain tried to stop the hero.", "She acted as the villain in the school play."],
    emoji: "😈",
    syllables: "vil-lain",
    distractorGroup: "story",
  },
  {
    word: "hero",
    pos: "noun",
    kidMeaning: "The main good character in a story.",
    examples: ["The hero defeated the evil wizard.", "He was the hero who saved the day."],
    emoji: "🦸",
    syllables: "he-ro",
    distractorGroup: "story",
  },
  {
    word: "clue",
    pos: "noun",
    kidMeaning: "Information that helps solve a mystery.",
    examples: ["She found an important clue in the room.", "The detective looked for clues at the scene."],
    emoji: "🔍",
    syllables: "clue",
    distractorGroup: "story",
  },
  {
    word: "treasure",
    pos: "noun",
    kidMeaning: "Valuable things, often hidden and sought.",
    examples: ["They searched for buried treasure on the island.", "The treasure was hidden in a secret place."],
    emoji: "💎",
    syllables: "treas-ure",
    distractorGroup: "story",
  },
  {
    word: "trap",
    pos: "noun",
    kidMeaning: "Something set to catch or harm someone.",
    examples: ["The hunter set a trap for the animal.", "It was a trap to catch the villain."],
    emoji: "⚠️",
    syllables: "trap",
    distractorGroup: "story",
  },
  {
    word: "castle",
    pos: "noun",
    kidMeaning: "A large stone building where kings and queens live.",
    examples: ["The princess lived in a beautiful castle.", "The knight defended the castle."],
    emoji: "🏰",
    syllables: "cas-tle",
    distractorGroup: "story",
  },
  {
    word: "secret",
    pos: "noun",
    kidMeaning: "Something hidden that not many people know.",
    examples: ["She kept the secret safe from everyone.", "He discovered a secret passage."],
    emoji: "🤐",
    syllables: "se-cret",
    distractorGroup: "story",
  },
  {
    word: "mystery",
    pos: "noun",
    kidMeaning: "Something strange or puzzling that needs to be solved.",
    examples: ["The mystery of the missing ring confused everyone.", "She loved reading mystery stories."],
    emoji: "🔍",
    syllables: "mys-ter-y",
    distractorGroup: "story",
  },
  {
    word: "adventure",
    pos: "noun",
    kidMeaning: "An exciting and dangerous journey or experience.",
    examples: ["They had an amazing adventure in the jungle.", "She dreamed of going on an adventure."],
    emoji: "🗺️",
    syllables: "ad-ven-ture",
    distractorGroup: "story",
  },
  {
    word: "quest",
    pos: "noun",
    kidMeaning: "A long journey to find or achieve something.",
    examples: ["The knight went on a quest to find the ring.", "Their quest for treasure was challenging."],
    emoji: "⚔️",
    syllables: "quest",
    distractorGroup: "story",
  },
  {
    word: "dragon",
    pos: "noun",
    kidMeaning: "A large mythical creature that can breathe fire.",
    examples: ["The brave knight fought the dragon.", "A friendly dragon appears in her story."],
    emoji: "🐉",
    syllables: "drag-on",
    distractorGroup: "story",
  },
  {
    word: "monster",
    pos: "noun",
    kidMeaning: "A scary creature, often imaginary.",
    examples: ["The monster lived under the child's bed.", "He was not afraid of monsters."],
    emoji: "👹",
    syllables: "mon-ster",
    distractorGroup: "story",
  },
  {
    word: "wizard",
    pos: "noun",
    kidMeaning: "A person with magical powers in stories.",
    examples: ["The wizard cast a spell on the castle.", "She wanted to become a wizard like Harry Potter."],
    emoji: "🧙",
    syllables: "wiz-ard",
    distractorGroup: "story",
  },
  {
    word: "witch",
    pos: "noun",
    kidMeaning: "A woman with magical powers.",
    examples: ["The witch lived in the dark forest.", "She dressed as a witch for Halloween."],
    emoji: "🧙‍♀️",
    syllables: "witch",
    distractorGroup: "story",
  },
  {
    word: "knight",
    pos: "noun",
    kidMeaning: "A warrior in armour who serves a king.",
    examples: ["The knight rode on a horse.", "She dreamed of being a brave knight."],
    emoji: "⚔️",
    syllables: "knight",
    distractorGroup: "story",
  },
  {
    word: "sword",
    pos: "noun",
    kidMeaning: "A weapon with a long blade.",
    examples: ["The knight drew his sword in battle.", "She held the sword with both hands."],
    emoji: "⚔️",
    syllables: "sword",
    distractorGroup: "story",
  },
  {
    word: "magic",
    pos: "noun",
    kidMeaning: "Mysterious powers that can do impossible things.",
    examples: ["The wizard used magic to defeat the monster.", "She believed in magic and fairy tales."],
    emoji: "✨",
    syllables: "mag-ic",
    distractorGroup: "story",
  },
  {
    word: "spell",
    pos: "noun",
    kidMeaning: "Words or actions that create magic.",
    examples: ["The wizard cast a spell on the enemy.", "She learned a new spell in the story."],
    emoji: "🪄",
    syllables: "spell",
    distractorGroup: "story",
  },
  {
    word: "enchanted",
    pos: "adjective",
    kidMeaning: "Affected by magic; magical.",
    examples: ["She wandered through an enchanted forest.", "The enchanted castle was hidden from view."],
    emoji: "✨",
    syllables: "en-chant-ed",
    distractorGroup: "story",
  },
  {
    word: "curse",
    pos: "noun",
    kidMeaning: "Bad magic that brings harm or bad luck.",
    examples: ["The witch placed a curse on the princess.", "A curse made him sleep for a hundred years."],
    emoji: "😈",
    syllables: "curse",
    distractorGroup: "story",
  },
  {
    word: "ally",
    pos: "noun",
    kidMeaning: "Someone who works with you against an enemy.",
    examples: ["She gained an important ally in the battle.", "He considered the warrior his trusted ally."],
    emoji: "🤝",
    syllables: "al-ly",
    distractorGroup: "story",
  },
  {
    word: "crown",
    pos: "noun",
    kidMeaning: "A decorated ring worn on the head by a ruler.",
    examples: ["The king wore a golden crown.", "She was crowned with a beautiful crown."],
    emoji: "👑",
    syllables: "crown",
    distractorGroup: "story",
  },
  {
    word: "throne",
    pos: "noun",
    kidMeaning: "The special chair where a king or queen sits.",
    examples: ["The king sat on his throne proudly.", "She inherited the throne from her father."],
    emoji: "🪑",
    syllables: "throne",
    distractorGroup: "story",
  },
  {
    word: "suddenly",
    pos: "adverb",
    kidMeaning: "All at once; happening without warning.",
    examples: ["The lights suddenly went out.", "She suddenly remembered where she left her keys."],
    emoji: "⚡",
    syllables: "sud-den-ly",
    distractorGroup: "manner",
  },
  {
    word: "carefully",
    pos: "adverb",
    kidMeaning: "With great attention; being cautious.",
    examples: ["She carefully placed the egg on the table.", "He walked carefully on the icy path."],
    emoji: "👁️",
    syllables: "care-ful-ly",
    distractorGroup: "manner",
  },
  {
    word: "eagerly",
    pos: "adverb",
    kidMeaning: "With enthusiasm and desire.",
    examples: ["She eagerly opened the gift.", "He eagerly awaited the start of the game."],
    emoji: "🤩",
    syllables: "ea-ger-ly",
    distractorGroup: "manner",
  },
  {
    word: "silently",
    pos: "adverb",
    kidMeaning: "Without making any sound.",
    examples: ["She silently crept into the room.", "He silently closed the door behind him."],
    emoji: "🤐",
    syllables: "si-lent-ly",
    distractorGroup: "manner",
  },
  {
    word: "bravely",
    pos: "adverb",
    kidMeaning: "With courage; without fear.",
    examples: ["She bravely faced her fear of heights.", "He bravely stood up to the bully."],
    emoji: "💪",
    syllables: "brave-ly",
    distractorGroup: "manner",
  },
  {
    word: "gently",
    pos: "adverb",
    kidMeaning: "With softness and care.",
    examples: ["She gently touched the butterfly.", "He spoke gently to calm the scared child."],
    emoji: "🌸",
    syllables: "gent-ly",
    distractorGroup: "manner",
  },
  {
    word: "reluctantly",
    pos: "adverb",
    kidMeaning: "Not wanting to do it.",
    examples: ["She reluctantly went to bed.", "He reluctantly admitted his mistake."],
    emoji: "😒",
    syllables: "re-luc-tant-ly",
    distractorGroup: "manner",
  },
  {
    word: "cautiously",
    pos: "adverb",
    kidMeaning: "Very carefully; watching for danger.",
    examples: ["She cautiously approached the strange animal.", "He cautiously entered the dark room."],
    emoji: "⚠️",
    syllables: "cau-tious-ly",
    distractorGroup: "manner",
  },
  {
    word: "quickly",
    pos: "adverb",
    kidMeaning: "At high speed; fast.",
    examples: ["She quickly ran to answer the door.", "He quickly finished his meal."],
    emoji: "💨",
    syllables: "quick-ly",
    distractorGroup: "manner",
  },
  {
    word: "slowly",
    pos: "adverb",
    kidMeaning: "At low speed; taking a long time.",
    examples: ["She slowly climbed the stairs.", "He walked slowly to get his balance."],
    emoji: "🐢",
    syllables: "slow-ly",
    distractorGroup: "manner",
  },
  {
    word: "badly",
    pos: "adverb",
    kidMeaning: "In a poor or negative way.",
    examples: ["She played badly in the match.", "He badly wanted to win the competition."],
    emoji: "😞",
    syllables: "bad-ly",
    distractorGroup: "manner",
  },
  {
    word: "well",
    pos: "adverb",
    kidMeaning: "In a good way.",
    examples: ["She played well at the concert.", "He did well on his exam."],
    emoji: "✅",
    syllables: "well",
    distractorGroup: "manner",
  },
  {
    word: "happily",
    pos: "adverb",
    kidMeaning: "In a pleased and joyful way.",
    examples: ["She happily skipped to school.", "He happily accepted the invitation."],
    emoji: "😊",
    syllables: "hap-pi-ly",
    distractorGroup: "manner",
  },
  {
    word: "sadly",
    pos: "adverb",
    kidMeaning: "In an unhappy or sorrowful way.",
    examples: ["She sadly watched her friend leave.", "He sadly shook his head at the news."],
    emoji: "😢",
    syllables: "sad-ly",
    distractorGroup: "manner",
  },
  {
    word: "angrily",
    pos: "adverb",
    kidMeaning: "In a furious or enraged manner.",
    examples: ["She angrily slammed the door.", "He angrily refused the offer."],
    emoji: "😠",
    syllables: "an-gri-ly",
    distractorGroup: "manner",
  },
  {
    word: "calmly",
    pos: "adverb",
    kidMeaning: "In a peaceful and relaxed way.",
    examples: ["She calmly explained her plan.", "He calmly waited for his turn."],
    emoji: "😌",
    syllables: "calm-ly",
    distractorGroup: "manner",
  },
  {
    word: "nervously",
    pos: "adverb",
    kidMeaning: "With worry or anxiety.",
    examples: ["She nervously awaited the test results.", "He nervously tapped his fingers."],
    emoji: "😰",
    syllables: "nerv-ous-ly",
    distractorGroup: "manner",
  },
  {
    word: "confidently",
    pos: "adverb",
    kidMeaning: "With assurance and belief in yourself.",
    examples: ["She confidently answered the question.", "He walked confidently into the room."],
    emoji: "💪",
    syllables: "con-fi-dent-ly",
    distractorGroup: "manner",
  },
  {
    word: "honestly",
    pos: "adverb",
    kidMeaning: "In a truthful way; being sincere.",
    examples: ["She honestly told the truth.", "He honestly did not know the answer."],
    emoji: "✅",
    syllables: "hon-est-ly",
    distractorGroup: "manner",
  },
  {
    word: "loudly",
    pos: "adverb",
    kidMeaning: "With a loud sound or voice.",
    examples: ["She loudly cheered for her team.", "He laughed loudly at the joke."],
    emoji: "📢",
    syllables: "loud-ly",
    distractorGroup: "manner",
  },
  {
    word: "softly",
    pos: "adverb",
    kidMeaning: "With little sound; quietly.",
    examples: ["She spoke softly so as not to wake the baby.", "He softly sang the lullaby."],
    emoji: "🤐",
    syllables: "soft-ly",
    distractorGroup: "manner",
  },
  {
    word: "roughly",
    pos: "adverb",
    kidMeaning: "In a harsh or violent way.",
    examples: ["He roughly pushed past her.", "She roughly grabbed the toy."],
    emoji: "💢",
    syllables: "rough-ly",
    distractorGroup: "manner",
  },
  {
    word: "smoothly",
    pos: "adverb",
    kidMeaning: "Without bumps or problems.",
    examples: ["The plan went smoothly without problems.", "She smoothly glided across the ice."],
    emoji: "✨",
    syllables: "smooth-ly",
    distractorGroup: "manner",
  },
  {
    word: "awkwardly",
    pos: "adverb",
    kidMeaning: "In a clumsy or not smooth way.",
    examples: ["She awkwardly stumbled over her words.", "He awkwardly tripped and fell."],
    emoji: "😅",
    syllables: "awk-ward-ly",
    distractorGroup: "manner",
  },
  {
    word: "gracefully",
    pos: "adverb",
    kidMeaning: "In a beautiful and elegant way.",
    examples: ["She gracefully danced across the stage.", "The swan gracefully glided on the water."],
    emoji: "✨",
    syllables: "grace-ful-ly",
    distractorGroup: "manner",
  },
  {
    word: "fiercely",
    pos: "adverb",
    kidMeaning: "In a strong and intense way.",
    examples: ["She fiercely defended her friend.", "The lion fiercely roared at the intruder."],
    emoji: "🦁",
    syllables: "fierce-ly",
    distractorGroup: "manner",
  },
  {
    word: "playfully",
    pos: "adverb",
    kidMeaning: "In a fun and light-hearted way.",
    examples: ["She playfully nudged her brother.", "He playfully teased her about her mistake."],
    emoji: "🎮",
    syllables: "play-ful-ly",
    distractorGroup: "manner",
  },
  {
    word: "seriously",
    pos: "adverb",
    kidMeaning: "In an earnest and solemn way.",
    examples: ["She seriously considered the problem.", "He seriously meant what he said."],
    emoji: "😑",
    syllables: "se-ri-ous-ly",
    distractorGroup: "manner",
  },
  {
    word: "secretly",
    pos: "adverb",
    kidMeaning: "In a hidden or private way; not openly.",
    examples: ["She secretly wished for his forgiveness.", "He secretly liked her all along."],
    emoji: "🤐",
    syllables: "se-cret-ly",
    distractorGroup: "manner",
  },
  {
    word: "openly",
    pos: "adverb",
    kidMeaning: "Without hiding; in public.",
    examples: ["She openly admitted her fear.", "He openly expressed his opinion."],
    emoji: "📢",
    syllables: "o-pen-ly",
    distractorGroup: "manner",
  },
  {
    word: "constantly",
    pos: "adverb",
    kidMeaning: "All the time; repeatedly.",
    examples: ["She constantly checked her phone.", "He constantly worried about his marks."],
    emoji: "🔄",
    syllables: "con-stant-ly",
    distractorGroup: "manner",
  },
  {
    word: "frequently",
    pos: "adverb",
    kidMeaning: "Often; many times.",
    examples: ["She frequently visits the library.", "He frequently goes to the park."],
    emoji: "🔄",
    syllables: "fre-quent-ly",
    distractorGroup: "manner",
  },
  {
    word: "rarely",
    pos: "adverb",
    kidMeaning: "Not often; seldom.",
    examples: ["She rarely complains about anything.", "He rarely misses school."],
    emoji: "🟣",
    syllables: "rare-ly",
    distractorGroup: "manner",
  },
  {
    word: "eventually",
    pos: "adverb",
    kidMeaning: "After a long time; finally.",
    examples: ["She eventually found what she was looking for.", "He eventually admitted the truth."],
    emoji: "⏳",
    syllables: "e-ven-tu-al-ly",
    distractorGroup: "manner",
  },
  {
    word: "immediately",
    pos: "adverb",
    kidMeaning: "Right away; without delay.",
    examples: ["She immediately answered the phone.", "He immediately understood the instructions."],
    emoji: "⚡",
    syllables: "im-me-di-ate-ly",
    distractorGroup: "manner",
  },
  {
    word: "determined",
    pos: "adjective",
    kidMeaning: "Having a strong decision to do something.",
    examples: ["She looked determined to win the race.", "He was determined to finish his project."],
    emoji: "💪",
    syllables: "de-ter-mined",
    distractorGroup: "feelings",
  },
  {
    word: "hopeful",
    pos: "adjective",
    kidMeaning: "Believing something good will happen.",
    examples: ["She felt hopeful about the future.", "He remained hopeful despite the setback."],
    emoji: "🌟",
    syllables: "hope-ful",
    distractorGroup: "feelings",
  },
  {
    word: "hopeless",
    pos: "adjective",
    kidMeaning: "Believing nothing good will happen.",
    examples: ["She felt hopeless after failing the test.", "He sounded hopeless about his chances."],
    emoji: "😞",
    syllables: "hope-less",
    distractorGroup: "feelings",
  },
  {
    word: "sceptical",
    pos: "adjective",
    kidMeaning: "Not believing something without proof.",
    examples: ["She was sceptical about the ghost story.", "He sounded sceptical of the plan."],
    emoji: "🤨",
    syllables: "scep-ti-cal",
    distractorGroup: "feelings",
  },
  {
    word: "suspicious",
    pos: "adjective",
    kidMeaning: "Thinking someone might be doing something wrong.",
    examples: ["She became suspicious of his sudden kindness.", "He looked suspicious at the strange offer."],
    emoji: "🤨",
    syllables: "sus-pi-cious",
    distractorGroup: "feelings",
  },
  {
    word: "resentful",
    pos: "adjective",
    kidMeaning: "Feeling bitter or angry about something.",
    examples: ["She felt resentful after being left out.", "He was resentful of the unfair treatment."],
    emoji: "😠",
    syllables: "re-sent-ful",
    distractorGroup: "feelings",
  },
  {
    word: "regretful",
    pos: "adjective",
    kidMeaning: "Feeling sorry about something you did.",
    examples: ["She looked regretful about her harsh words.", "He was regretful for his mistake."],
    emoji: "😔",
    syllables: "re-gret-ful",
    distractorGroup: "feelings",
  },
  {
    word: "independent",
    pos: "adjective",
    kidMeaning: "Able to do things without help from others.",
    examples: ["She was independent and solved the problem alone.", "He acted independently without asking."],
    emoji: "💪",
    syllables: "in-de-pend-ent",
    distractorGroup: "character",
  },
  {
    word: "dependent",
    pos: "adjective",
    kidMeaning: "Needing help from others.",
    examples: ["The young child was dependent on his mother.", "She seemed dependent on her friend's approval."],
    emoji: "🤝",
    syllables: "de-pend-ent",
    distractorGroup: "character",
  },
  {
    word: "flee",
    pos: "verb",
    kidMeaning: "To run away from danger.",
    examples: ["She fled from the burning house.", "He fled when he saw the angry dog."],
    emoji: "🏃",
    syllables: "flee",
    distractorGroup: "action",
  },
  {
    word: "release",
    pos: "verb",
    kidMeaning: "To let something go free.",
    examples: ["She released the bird from its cage.", "He released his grip on the toy."],
    emoji: "🦅",
    syllables: "re-lease",
    distractorGroup: "action",
  },
  {
    word: "escape",
    pos: "verb",
    kidMeaning: "To get away from a place or situation.",
    examples: ["She escaped from the locked room.", "He managed to escape from trouble."],
    emoji: "🏃",
    syllables: "es-cape",
    distractorGroup: "action",
  },
  {
    word: "lean",
    pos: "verb",
    kidMeaning: "To bend your body to one side.",
    examples: ["She leaned against the wall.", "He leaned forward to listen carefully."],
    emoji: "🚶",
    syllables: "lean",
    distractorGroup: "action",
  },
  {
    word: "relax",
    pos: "verb",
    kidMeaning: "To rest and become calm.",
    examples: ["She relaxed in the sun.", "He relaxed on the beach."],
    emoji: "😌",
    syllables: "re-lax",
    distractorGroup: "action",
  },
  {
    word: "tense",
    pos: "verb",
    kidMeaning: "To tighten your muscles.",
    examples: ["She tensed up before the test.", "He tensed when hearing the noise."],
    emoji: "😰",
    syllables: "tense",
    distractorGroup: "action",
  },
  {
    word: "hold",
    pos: "verb",
    kidMeaning: "To keep something in your hand.",
    examples: ["She will hold the baby safe.", "He will hold the rope tightly."],
    emoji: "🤲",
    syllables: "hold",
    distractorGroup: "action",
  },
  {
    word: "knock",
    pos: "verb",
    kidMeaning: "To hit a door to get someone's attention.",
    examples: ["She knocked on the door loudly.", "He knocked three times."],
    emoji: "🚪",
    syllables: "knock",
    distractorGroup: "action",
  },
  {
    word: "tap",
    pos: "verb",
    kidMeaning: "To hit lightly and quickly.",
    examples: ["She tapped on the window to signal.", "He tapped the desk with his pencil."],
    emoji: "👆",
    syllables: "tap",
    distractorGroup: "action",
  },
  {
    word: "strike",
    pos: "verb",
    kidMeaning: "To hit someone or something with force.",
    examples: ["She will strike the ball hard.", "He can strike the ball well."],
    emoji: "⚡",
    syllables: "strike",
    distractorGroup: "action",
  },
  {
    word: "swallow",
    pos: "verb",
    kidMeaning: "To take food down your throat.",
    examples: ["She swallowed the medicine quickly.", "He swallowed hard and said nothing."],
    emoji: "😌",
    syllables: "swal-low",
    distractorGroup: "action",
  },
  {
    word: "spit",
    pos: "verb",
    kidMeaning: "To force liquid from your mouth.",
    examples: ["He spit out the bad-tasting food.", "She spit the seeds into the bin."],
    emoji: "😛",
    syllables: "spit",
    distractorGroup: "action",
  },
  {
    word: "suck",
    pos: "verb",
    kidMeaning: "To draw in liquid or air.",
    examples: ["She sucked on the lollipop.", "He sucked in his cheeks."],
    emoji: "😋",
    syllables: "suck",
    distractorGroup: "action",
  },
  {
    word: "blow",
    pos: "verb",
    kidMeaning: "To force air from your mouth.",
    examples: ["She will blow out the candles.", "He will blow into the whistle."],
    emoji: "💨",
    syllables: "blow",
    distractorGroup: "action",
  },
  {
    word: "itch",
    pos: "verb",
    kidMeaning: "To have a itch on your skin.",
    examples: ["She itched her arm where the mosquito bit her.", "He itched his nose."],
    emoji: "😤",
    syllables: "itch",
    distractorGroup: "action",
  },
  {
    word: "ghost",
    pos: "noun",
    kidMeaning: "The spirit of a dead person.",
    examples: ["The ghost haunted the old castle.", "She did not believe in ghosts."],
    emoji: "👻",
    syllables: "ghost",
    distractorGroup: "story",
  },
  {
    word: "spirit",
    pos: "noun",
    kidMeaning: "A being without a body.",
    examples: ["The spirit of Christmas brought joy.", "He believed in forest spirits."],
    emoji: "👻",
    syllables: "spir-it",
    distractorGroup: "story",
  },
  {
    word: "invisible",
    pos: "adjective",
    kidMeaning: "Not able to be seen.",
    examples: ["The invisible cloak made him disappear.", "She felt invisible when ignored."],
    emoji: "👁️",
    syllables: "in-vis-i-ble",
    distractorGroup: "story",
  },
  {
    word: "potion",
    pos: "noun",
    kidMeaning: "It is a drink with magic.",
    examples: ["The witch mixed a potion to heal the wound.", "He drank the magic potion."],
    emoji: "🧪",
    syllables: "po-tion",
    distractorGroup: "story",
  },
  {
    word: "wand",
    pos: "noun",
    kidMeaning: "A stick used to cast spells in magic.",
    examples: ["The wizard waved his wand.", "She held the magic wand carefully."],
    emoji: "🪄",
    syllables: "wand",
    distractorGroup: "story",
  },
  {
    word: "scroll",
    pos: "noun",
    kidMeaning: "An old piece of paper rolled up.",
    examples: ["The ancient scroll held secrets.", "She unrolled the magical scroll."],
    emoji: "📜",
    syllables: "scroll",
    distractorGroup: "story",
  },
  {
    word: "riddle",
    pos: "noun",
    kidMeaning: "A tricky puzzle or question.",
    examples: ["She solved the riddle correctly.", "He could not answer the sphinx's riddle."],
    emoji: "🧩",
    syllables: "rid-dle",
    distractorGroup: "story",
  },
  {
    word: "tale",
    pos: "noun",
    kidMeaning: "A story, especially an old or magical one.",
    examples: ["Grandmother told an old fairy tale.", "He loved adventure tales."],
    emoji: "📖",
    syllables: "tale",
    distractorGroup: "story",
  },
  {
    word: "creature",
    pos: "noun",
    kidMeaning: "A living being or animal.",
    examples: ["The creature emerged from the water.", "He studied strange creatures in the forest."],
    emoji: "🦁",
    syllables: "crea-ture",
    distractorGroup: "story",
  },
  {
    word: "angel",
    pos: "noun",
    kidMeaning: "A good being with wings.",
    examples: ["The angel watched over her.", "He prayed to the angel for help."],
    emoji: "😇",
    syllables: "an-gel",
    distractorGroup: "story",
  },
  {
    word: "demon",
    pos: "noun",
    kidMeaning: "An evil spirit or creature.",
    examples: ["The demon tried to stop the hero.", "She feared the demon in the story."],
    emoji: "😈",
    syllables: "de-mon",
    distractorGroup: "story",
  },
  {
    word: "elf",
    pos: "noun",
    kidMeaning: "A magical small creature from fairy tales.",
    examples: ["The elf danced in the moonlight.", "An elf danced with fairies."],
    emoji: "🧝",
    syllables: "elf",
    distractorGroup: "story",
  },
  {
    word: "fairy",
    pos: "noun",
    kidMeaning: "A magical tiny being with wings.",
    examples: ["The fairy godmother helped Cinderella.", "He wished to meet a real fairy."],
    emoji: "🧚",
    syllables: "fair-y",
    distractorGroup: "story",
  },
  {
    word: "troll",
    pos: "noun",
    kidMeaning: "An ugly giant creature in fairy tales.",
    examples: ["The troll lived under the bridge.", "She was afraid of the fierce troll."],
    emoji: "👹",
    syllables: "troll",
    distractorGroup: "story",
  },
  {
    word: "goblin",
    pos: "noun",
    kidMeaning: "A small mischievous creature.",
    examples: ["The goblins stole the treasure.", "He fought off the goblin army."],
    emoji: "👹",
    syllables: "gob-lin",
    distractorGroup: "story",
  },
  {
    word: "ogre",
    pos: "noun",
    kidMeaning: "A large brutal giant in stories.",
    examples: ["The ogre guarded the princess.", "She was terrified of the ugly ogre."],
    emoji: "👹",
    syllables: "o-gre",
    distractorGroup: "story",
  },
  {
    word: "mermaid",
    pos: "noun",
    kidMeaning: "A mythical creature half-woman, half-fish.",
    examples: ["The mermaid sang beautifully.", "He saw a mermaid in the ocean."],
    emoji: "🧜‍♀️",
    syllables: "mer-maid",
    distractorGroup: "story",
  },
  {
    word: "unicorn",
    pos: "noun",
    kidMeaning: "A horse with a single horn.",
    examples: ["The unicorn pranced in the meadow.", "She dreamed of riding a unicorn."],
    emoji: "🦄",
    syllables: "u-ni-corn",
    distractorGroup: "story",
  },
  {
    word: "charm",
    pos: "noun",
    kidMeaning: "An object or words with magical power.",
    examples: ["The charm protected her from evil.", "She wore a lucky charm."],
    emoji: "✨",
    syllables: "charm",
    distractorGroup: "story",
  },
  {
    word: "stutter",
    pos: "verb",
    kidMeaning: "To speak with repeated sounds.",
    examples: ["She stuttered nervously during the presentation.", "He stuttered when trying to explain."],
    emoji: "😳",
    syllables: "stut-ter",
    distractorGroup: "saying",
  },
  {
    word: "announce",
    pos: "verb",
    kidMeaning: "To tell people something important.",
    examples: ["She announced the winner loudly.", "He announced his arrival."],
    emoji: "📢",
    syllables: "an-nounce",
    distractorGroup: "saying",
  },
  {
    word: "declare",
    pos: "verb",
    kidMeaning: "To state something firmly.",
    examples: ["She declared war on the enemy.", "He declared his love openly."],
    emoji: "📢",
    syllables: "de-clare",
    distractorGroup: "saying",
  },
  {
    word: "deny",
    pos: "verb",
    kidMeaning: "To say something is not true.",
    examples: ["She denied taking the money.", "He denied seeing the accident."],
    emoji: "🚫",
    syllables: "de-ny",
    distractorGroup: "saying",
  },
  {
    word: "promise",
    pos: "verb",
    kidMeaning: "To say you will definitely do something.",
    examples: ["She promised to be on time.", "He promised to help her."],
    emoji: "🤝",
    syllables: "prom-ise",
    distractorGroup: "saying",
  },
  {
    word: "swear",
    pos: "verb",
    kidMeaning: "To make a solemn promise.",
    examples: ["He will swear to tell the truth.", "She will swear an oath."],
    emoji: "🙋",
    syllables: "swear",
    distractorGroup: "saying",
  },
  {
    word: "praise",
    pos: "verb",
    kidMeaning: "To say nice things about someone.",
    examples: ["The teacher praised her excellent work.", "He praised his friend's bravery."],
    emoji: "👏",
    syllables: "praise",
    distractorGroup: "saying",
  },
  {
    word: "process",
    pos: "verb",
    kidMeaning: "To think through information.",
    examples: ["She took time to process the news.", "He processed what she said."],
    emoji: "⚙️",
    syllables: "pro-cess",
    distractorGroup: "thinking",
  },
  {
    word: "anxious",
    pos: "adjective",
    kidMeaning: "Feeling worried or uneasy.",
    examples: ["She felt anxious before the competition.", "He was anxious about the results."],
    emoji: "😰",
    syllables: "anx-ious",
    distractorGroup: "feelings",
  },
  {
    word: "panicked",
    pos: "adjective",
    kidMeaning: "Sudden fear that makes you act carelessly.",
    examples: ["She panicked when she saw the spider.", "He looked panicked during the fire drill."],
    emoji: "😱",
    syllables: "pan-icked",
    distractorGroup: "feelings",
  },
  {
    word: "courageous",
    pos: "adjective",
    kidMeaning: "Very brave and fearless.",
    examples: ["She was courageous to stand up for her friend.", "He showed courageous actions."],
    emoji: "💪",
    syllables: "cour-a-geous",
    distractorGroup: "character",
  },
  {
    word: "cowardly",
    pos: "adjective",
    kidMeaning: "Showing fear; not brave.",
    examples: ["He was cowardly and ran away.", "She called his behaviour cowardly."],
    emoji: "😰",
    syllables: "cow-ard-ly",
    distractorGroup: "character",
  },
  {
    word: "modest",
    pos: "adjective",
    kidMeaning: "Not boasting; simple and humble.",
    examples: ["She was modest about her achievement.", "He had modest ambitions."],
    emoji: "🙏",
    syllables: "mod-est",
    distractorGroup: "character",
  },
  {
    word: "lair",
    pos: "noun",
    kidMeaning: "A secret hideout or den.",
    examples: ["The villain retreated to his secret lair.", "She found the dragon's lair."],
    emoji: "🐉",
    syllables: "lair",
    distractorGroup: "story",
  },
  {
    word: "hideout",
    pos: "noun",
    kidMeaning: "A place where someone hides.",
    examples: ["The bandits found their hideout.", "He discovered the secret hideout."],
    emoji: "🏠",
    syllables: "hide-out",
    distractorGroup: "story",
  },
  {
    word: "defeat",
    pos: "noun",
    kidMeaning: "A loss or failure.",
    examples: ["The defeat was hard to accept.", "She refused to accept defeat."],
    emoji: "😞",
    syllables: "de-feat",
    distractorGroup: "story",
  },
  {
    word: "retreat",
    pos: "noun",
    kidMeaning: "A place to go for safety or rest.",
    examples: ["The cabin was a peaceful retreat.", "He needed a quiet retreat from the city."],
    emoji: "🏠",
    syllables: "re-treat",
    distractorGroup: "story",
  },
  {
    word: "traitor",
    pos: "noun",
    kidMeaning: "Someone who betrays others.",
    examples: ["The traitor revealed the secret location.", "She was revealed as the traitor."],
    emoji: "🚫",
    syllables: "trai-tor",
    distractorGroup: "story",
  },
  {
    word: "outlaw",
    pos: "noun",
    kidMeaning: "A person who breaks the law and is pursued.",
    examples: ["The outlaw lived in hiding.", "Many outlaws were famous long ago."],
    emoji: "🤠",
    syllables: "out-law",
    distractorGroup: "story",
  },
  {
    word: "rebel",
    pos: "noun",
    kidMeaning: "Someone who fights against authority.",
    examples: ["The rebel fought for freedom.", "He was a rebel against unfair rules."],
    emoji: "✊",
    syllables: "reb-el",
    distractorGroup: "story",
  },
  {
    word: "champion",
    pos: "noun",
    kidMeaning: "The winner of a competition.",
    examples: ["She was the chess champion.", "He defended his champion title."],
    emoji: "🏆",
    syllables: "cham-pi-on",
    distractorGroup: "story",
  },
  {
    word: "uneasy",
    pos: "adjective",
    kidMeaning: "Feeling worried.",
    examples: ["She felt uneasy about the dark forest.", "He seemed uneasy before the performance."],
    emoji: "😟",
    syllables: "eas-y",
    distractorGroup: "feelings",
  },
  {
    word: "thrilled",
    pos: "adjective",
    kidMeaning: "Very excited and happy.",
    examples: ["She was thrilled to win the prize.", "He looked thrilled about the big surprise."],
    emoji: "🎉",
    syllables: "thrilled",
    distractorGroup: "feelings",
  },
  {
    word: "cross",
    pos: "adjective",
    kidMeaning: "Annoyed or angry.",
    examples: ["She looked cross when interrupted.", "He was cross about the broken toy."],
    emoji: "😠",
    syllables: "cross",
    distractorGroup: "feelings",
  },
  {
    word: "restless",
    pos: "adjective",
    kidMeaning: "Unable to stay still or calm.",
    examples: ["The restless child could not sit down.", "She felt restless before her trip."],
    emoji: "😤",
    syllables: "rest-less",
    distractorGroup: "feelings",
  },
  {
    word: "weary",
    pos: "adjective",
    kidMeaning: "Very tired.",
    examples: ["She felt weary after the long journey.", "He was weary from working hard all day."],
    emoji: "😴",
    syllables: "wea-ry",
    distractorGroup: "feelings",
  },
  {
    word: "bitter",
    pos: "adjective",
    kidMeaning: "Feeling angry and unhappy.",
    examples: ["She felt bitter about the unfair loss.", "He had a bitter tone in his voice."],
    emoji: "😤",
    syllables: "bit-ter",
    distractorGroup: "feelings",
  },
  {
    word: "tender",
    pos: "adjective",
    kidMeaning: "Soft and gentle easily hurt.",
    examples: ["She had tender feelings for him.", "His tender heart made him cry easily."],
    emoji: "💕",
    syllables: "ten-der",
    distractorGroup: "feelings",
  },
  {
    word: "fussy",
    pos: "adjective",
    kidMeaning: "Particular about small details.",
    examples: ["He was fussy about his food.", "She was fussy about cleanliness."],
    emoji: "😕",
    syllables: "fuss-y",
    distractorGroup: "character",
  },
  {
    word: "sensible",
    pos: "adjective",
    kidMeaning: "Showing good sense.",
    examples: ["She made a sensible choice.", "He was sensible about safety."],
    emoji: "👍",
    syllables: "sens-i-ble",
    distractorGroup: "character",
  },
  {
    word: "obedient",
    pos: "adjective",
    kidMeaning: "Following rules and orders.",
    examples: ["The obedient child listened well.", "She was obedient to her parents."],
    emoji: "😊",
    syllables: "o-be-di-ent",
    distractorGroup: "character",
  },
  {
    word: "boastful",
    pos: "adjective",
    kidMeaning: "Talking too much about yourself.",
    examples: ["He was boastful about his skills.", "She did not like his boastful behaviour."],
    emoji: "🤐",
    syllables: "boast-ful",
    distractorGroup: "character",
  },
  {
    word: "moody",
    pos: "adjective",
    kidMeaning: "Having changing moods quickly.",
    examples: ["He was moody and hard to please.", "She seemed moody today."],
    emoji: "😠",
    syllables: "mood-y",
    distractorGroup: "character",
  },
  {
    word: "witty",
    pos: "adjective",
    kidMeaning: "Clever and funny.",
    examples: ["She made a witty remark.", "He had a witty sense of humour."],
    emoji: "😄",
    syllables: "wit-ty",
    distractorGroup: "character",
  },
  {
    word: "dishonest",
    pos: "adjective",
    kidMeaning: "Not truthful.",
    examples: ["His dishonest answer upset her.", "She could not trust his dishonest ways."],
    emoji: "🚫",
    syllables: "dis-hon-est",
    distractorGroup: "character",
  },
  {
    word: "sincere",
    pos: "adjective",
    kidMeaning: "Honest and genuine.",
    examples: ["She gave a sincere apology.", "He was sincere about his feelings."],
    emoji: "💯",
    syllables: "sin-cere",
    distractorGroup: "character",
  },
  {
    word: "reliable",
    pos: "adjective",
    kidMeaning: "Can be trusted to help.",
    examples: ["He was a reliable friend.", "She was reliable with her responsibilities."],
    emoji: "✅",
    syllables: "re-li-a-ble",
    distractorGroup: "character",
  },
  {
    word: "grumpy",
    pos: "adjective",
    kidMeaning: "Bad-tempered and unhappy.",
    examples: ["He was grumpy in the morning.", "She seemed grumpy all day."],
    emoji: "😠",
    syllables: "grum-py",
    distractorGroup: "character",
  },
  {
    word: "scurry",
    pos: "verb",
    kidMeaning: "To run quickly with short steps.",
    examples: ["The mouse scurried across the floor.", "She scurried away from the danger."],
    emoji: "🐭",
    syllables: "scur-ry",
    distractorGroup: "action",
  },
  {
    word: "tiptoe",
    pos: "verb",
    kidMeaning: "To walk quietly on toes.",
    examples: ["He tiptoed up the stairs.", "She tiptoed past the sleeping cat."],
    emoji: "🚶",
    syllables: "tip-toe",
    distractorGroup: "action",
  },
  {
    word: "hurl",
    pos: "verb",
    kidMeaning: "To throw something with force.",
    examples: ["He hurled the ball far away.", "She hurled the rock at the wall."],
    emoji: "⚡",
    syllables: "hurl",
    distractorGroup: "action",
  },
  {
    word: "clutch",
    pos: "verb",
    kidMeaning: "To hold something tightly.",
    examples: ["She clutched her toy hard.", "He clutched the rope for safety."],
    emoji: "✊",
    syllables: "clutch",
    distractorGroup: "action",
  },
  {
    word: "fumble",
    pos: "verb",
    kidMeaning: "To handle in an awkward way.",
    examples: ["He fumbled with the keys.", "She fumbled the catch in the game."],
    emoji: "😅",
    syllables: "fum-ble",
    distractorGroup: "action",
  },
  {
    word: "flinch",
    pos: "verb",
    kidMeaning: "To move back suddenly.",
    examples: ["He flinched at the loud noise.", "She flinched when touched suddenly."],
    emoji: "😰",
    syllables: "flinch",
    distractorGroup: "action",
  },
  {
    word: "wriggle",
    pos: "verb",
    kidMeaning: "To twist and turn.",
    examples: ["The worm wriggled in the soil.", "She wriggled to get free."],
    emoji: "🪱",
    syllables: "wrig-gle",
    distractorGroup: "action",
  },
  {
    word: "lurch",
    pos: "verb",
    kidMeaning: "To move suddenly or unsteadily.",
    examples: ["The ship lurched in the storm.", "He lurched forward suddenly."],
    emoji: "⛴️",
    syllables: "lurch",
    distractorGroup: "action",
  },
  {
    word: "scamper",
    pos: "verb",
    kidMeaning: "To run quickly.",
    examples: ["The squirrel scampered up the tree.", "They scampered away laughing loudly."],
    emoji: "🐿️",
    syllables: "scam-per",
    distractorGroup: "action",
  },
  {
    word: "snap",
    pos: "verb",
    kidMeaning: "To speak in an angry sharp way.",
    examples: ["She snapped at him rudely.", "He snapped when frustrated."],
    emoji: "😠",
    syllables: "snap",
    distractorGroup: "saying",
  },
  {
    word: "plead",
    pos: "verb",
    kidMeaning: "To ask with strong feeling.",
    examples: ["She pleaded for another chance.", "He pleaded with her for help."],
    emoji: "🙏",
    syllables: "plead",
    distractorGroup: "saying",
  },
  {
    word: "chuckle",
    pos: "verb",
    kidMeaning: "To laugh softly.",
    examples: ["He chuckled at the funny joke.", "She chuckled at the silly story."],
    emoji: "😄",
    syllables: "chuck-le",
    distractorGroup: "saying",
  },
  {
    word: "sneer",
    pos: "verb",
    kidMeaning: "To smile in a mean way.",
    examples: ["He sneered at the losers.", "She sneered at his poor try."],
    emoji: "😒",
    syllables: "sneer",
    distractorGroup: "saying",
  },
  {
    word: "whine",
    pos: "verb",
    kidMeaning: "To complain in an annoying way.",
    examples: ["The child whined about bedtime.", "She whined about unfair treatment."],
    emoji: "😩",
    syllables: "whine",
    distractorGroup: "saying",
  },
  {
    word: "taunt",
    pos: "verb",
    kidMeaning: "To make fun of to challenge.",
    examples: ["He taunted her about losing.", "She taunted him boldly."],
    emoji: "😠",
    syllables: "taunt",
    distractorGroup: "saying",
  },
  {
    word: "scold",
    pos: "verb",
    kidMeaning: "To tell someone off.",
    examples: ["She scolded the child.", "He scolded them for being late."],
    emoji: "😠",
    syllables: "scold",
    distractorGroup: "saying",
  },
  {
    word: "guess",
    pos: "verb",
    kidMeaning: "To try to answer without knowing.",
    examples: ["She guessed the answer was five.", "He guessed what was inside."],
    emoji: "🤔",
    syllables: "guess",
    distractorGroup: "thinking",
  },
  {
    word: "expect",
    pos: "verb",
    kidMeaning: "To think something will happen.",
    examples: ["She expected him to arrive soon.", "He expected rain today."],
    emoji: "💭",
    syllables: "ex-pect",
    distractorGroup: "thinking",
  },
  {
    word: "recall",
    pos: "verb",
    kidMeaning: "To remember something.",
    examples: ["She recalled the happy day.", "He recalled the story clearly."],
    emoji: "💭",
    syllables: "re-call",
    distractorGroup: "thinking",
  },
  {
    word: "hesitate",
    pos: "verb",
    kidMeaning: "To pause because unsure.",
    examples: ["She hesitated before answering.", "He hesitated at the edge."],
    emoji: "⏸️",
    syllables: "hes-i-tate",
    distractorGroup: "thinking",
  },
  {
    word: "rescue",
    pos: "noun",
    kidMeaning: "Saving someone from danger.",
    examples: ["The rescue came just in time.", "She was grateful for the rescue."],
    emoji: "🆘",
    syllables: "res-cue",
    distractorGroup: "story",
  },
  {
    word: "disguise",
    pos: "noun",
    kidMeaning: "Outfit to hide who you really are.",
    examples: ["She wore a disguise to the party.", "His disguise fooled everyone."],
    emoji: "🎭",
    syllables: "dis-guise",
    distractorGroup: "story",
  },
  {
    word: "footprint",
    pos: "noun",
    kidMeaning: "The mark left by a foot.",
    examples: ["She found a footprint in sand.", "He followed the footprint trail."],
    emoji: "👣",
    syllables: "foot-print",
    distractorGroup: "story",
  },
  {
    word: "signal",
    pos: "noun",
    kidMeaning: "A sign to communicate.",
    examples: ["She gave a signal to start.", "He understood the signal."],
    emoji: "🚩",
    syllables: "sig-nal",
    distractorGroup: "story",
  },
  {
    word: "reward",
    pos: "noun",
    kidMeaning: "A prize for doing good.",
    examples: ["She received a reward for honesty.", "He wanted the reward badly."],
    emoji: "🏆",
    syllables: "re-ward",
    distractorGroup: "story",
  },
  {
    word: "punishment",
    pos: "noun",
    kidMeaning: "Something bad for wrongdoing.",
    examples: ["His punishment was severe.", "She accepted her punishment."],
    emoji: "⚖️",
    syllables: "pun-ish-ment",
    distractorGroup: "story",
  },
  {
    word: "weapon",
    pos: "noun",
    kidMeaning: "A tool used to fight.",
    examples: ["He carried a weapon for safety.", "The weapon was sharp."],
    emoji: "⚔️",
    syllables: "weap-on",
    distractorGroup: "story",
  },
  {
    word: "victory",
    pos: "noun",
    kidMeaning: "A win or success.",
    examples: ["Their victory was celebrated.", "She enjoyed the victory."],
    emoji: "🥇",
    syllables: "vic-tor-y",
    distractorGroup: "story",
  },
  {
    word: "passage",
    pos: "noun",
    kidMeaning: "A way or path through.",
    examples: ["The passage was narrow.", "She found a passage."],
    emoji: "🛤️",
    syllables: "pass-age",
    distractorGroup: "story",
  },
  {
    word: "hastily",
    pos: "adverb",
    kidMeaning: "In a quick and hurried way.",
    examples: ["She hastily packed her bag.", "He hastily left the room."],
    emoji: "💨",
    syllables: "has-ti-ly",
    distractorGroup: "manner",
  },
  {
    word: "proudly",
    pos: "adverb",
    kidMeaning: "With pride and confidence.",
    examples: ["She proudly showed her work.", "He proudly wore his medal."],
    emoji: "😊",
    syllables: "proud-ly",
    distractorGroup: "manner",
  },
  {
    word: "sheepishly",
    pos: "adverb",
    kidMeaning: "In an embarrassed way.",
    examples: ["She sheepishly admitted the truth.", "He sheepishly smiled back."],
    emoji: "😳",
    syllables: "sheep-ish-ly",
    distractorGroup: "manner",
  },
  {
    word: "wearily",
    pos: "adverb",
    kidMeaning: "In a tired way.",
    examples: ["She wearily walked to school.", "He wearily sat down hard."],
    emoji: "😴",
    syllables: "wear-i-ly",
    distractorGroup: "manner",
  },
  {
    word: "firmly",
    pos: "adverb",
    kidMeaning: "In a strong and fixed way.",
    examples: ["She firmly held his hand.", "He spoke firmly and clearly."],
    emoji: "💪",
    syllables: "firm-ly",
    distractorGroup: "manner",
  },
  {
    word: "politely",
    pos: "adverb",
    kidMeaning: "With good manners.",
    examples: ["She politely asked for help.", "He politely excused himself now."],
    emoji: "😊",
    syllables: "po-lite-ly",
    distractorGroup: "manner",
  },
  {
    word: "harshly",
    pos: "adverb",
    kidMeaning: "In a cruel or severe way.",
    examples: ["She spoke harshly to him.", "He treated her harshly."],
    emoji: "😠",
    syllables: "harsh-ly",
    distractorGroup: "manner",
  },
  {
    word: "warmly",
    pos: "adverb",
    kidMeaning: "In a friendly and kind way.",
    examples: ["She warmly welcomed them all.", "He smiled warmly at her."],
    emoji: "🤍",
    syllables: "warm-ly",
    distractorGroup: "manner",
  },
  {
    word: "wildly",
    pos: "adverb",
    kidMeaning: "In a crazy or wild way.",
    examples: ["She danced wildly at the party.", "He ran wildly through the field."],
    emoji: "🎉",
    syllables: "wild-ly",
    distractorGroup: "manner",
  },
  {
    word: "freely",
    pos: "adverb",
    kidMeaning: "Without limits or control.",
    examples: ["She spoke freely about her feelings.", "He roamed freely in the forest."],
    emoji: "🦅",
    syllables: "free-ly",
    distractorGroup: "manner",
  },
  {
    word: "swiftly",
    pos: "adverb",
    kidMeaning: "In a quick and smooth way.",
    examples: ["She swiftly moved across the ice.", "He swiftly caught the ball."],
    emoji: "⚡",
    syllables: "swift-ly",
    distractorGroup: "manner",
  },
  {
    word: "bluntly",
    pos: "adverb",
    kidMeaning: "Speaking directly and honestly.",
    examples: ["She bluntly told the truth.", "He bluntly refused the offer."],
    emoji: "💯",
    syllables: "blunt-ly",
    distractorGroup: "manner",
  },
];
