import type { Word } from "../words";

export const band3: Word[] = [
  {
    word: "science",
    pos: "noun",
    kidMeaning: "Study of nature and how things work.",
    examples: ["She learns science at school.", "Science helps us understand the world."],
    emoji: "🔬",
    syllables: "sci-ence",
    distractorGroup: "subjects",
  },
  {
    word: "weather",
    pos: "noun",
    kidMeaning: "Condition of the air and sky.",
    examples: ["The weather is sunny today.", "Bad weather stops the game."],
    emoji: "🌤️",
    syllables: "weath-er",
    distractorGroup: "nature",
  },
  {
    word: "sunshine",
    pos: "noun",
    kidMeaning: "Light and heat from the sun.",
    examples: ["She enjoys sunshine in the park.", "Sunshine makes plants grow."],
    emoji: "☀️",
    syllables: "sun-shine",
    distractorGroup: "nature",
  },
  {
    word: "shadow",
    pos: "noun",
    kidMeaning: "Dark area when light is blocked.",
    examples: ["The shadow moves when the sun moves.", "She sits in the shadow."],
    emoji: "🌑",
    syllables: "shad-ow",
    distractorGroup: "nature",
  },
  {
    word: "leaf",
    pos: "noun",
    kidMeaning: "Green part of a plant.",
    examples: ["The tree has many green leaves.", "Leaves change colour in autumn."],
    emoji: "🍃",
    syllables: "leaf",
    distractorGroup: "plants",
  },
  {
    word: "grass",
    pos: "noun",
    kidMeaning: "Green plant covering field.",
    examples: ["The grass is soft and green.", "Cows eat grass."],
    emoji: "🌿",
    syllables: "grass",
    distractorGroup: "plants",
  },
  {
    word: "insect",
    pos: "noun",
    kidMeaning: "Small animal with six legs.",
    examples: ["She sees an insect on the flower.", "Insects have antennae."],
    emoji: "🦋",
    syllables: "in-sect",
    distractorGroup: "animals",
  },
  {
    word: "butterfly",
    pos: "noun",
    kidMeaning: "Insect with coloured wings.",
    examples: ["Butterflies land on flowers.", "She catches butterflies in the garden."],
    emoji: "🦋",
    syllables: "but-ter-fly",
    distractorGroup: "animals",
  },
  {
    word: "plane",
    pos: "noun",
    kidMeaning: "Vehicle that flies.",
    examples: ["She rides the plane to the country.", "The plane lands at the airport."],
    emoji: "✈️",
    syllables: "plane",
    distractorGroup: "transport",
  },
  {
    word: "bedroom",
    pos: "noun",
    kidMeaning: "Room for sleeping.",
    examples: ["She sleeps in the bedroom.", "The bedroom has a big bed."],
    emoji: "🛏️",
    syllables: "bed-room",
    distractorGroup: "places",
  },
  {
    word: "bathroom",
    pos: "noun",
    kidMeaning: "Room to wash yourself.",
    examples: ["She washes her hands in the bathroom.", "The bathroom is clean."],
    emoji: "🚿",
    syllables: "bath-room",
    distractorGroup: "places",
  },
  {
    word: "tower",
    pos: "noun",
    kidMeaning: "Very tall structure.",
    examples: ["The tower reaches the clouds.", "She visits the tower."],
    emoji: "🏰",
    syllables: "tow-er",
    distractorGroup: "places",
  },
  {
    word: "ice",
    pos: "noun",
    kidMeaning: "Frozen water.",
    examples: ["She slides on ice.", "Ice cream has ice in it."],
    emoji: "🧊",
    syllables: "ice",
    distractorGroup: "nature",
  },
  {
    word: "sky",
    pos: "noun",
    kidMeaning: "Space above us.",
    examples: ["The sky is blue today.", "She looks at the sky at night."],
    emoji: "🌌",
    syllables: "sky",
    distractorGroup: "nature",
  },
  {
    word: "team",
    pos: "noun",
    kidMeaning: "Group of people.",
    examples: ["She is on the football team.", "The team wins the match."],
    emoji: "👥",
    syllables: "team",
    distractorGroup: "groups",
  },
  {
    word: "prepare",
    pos: "verb",
    kidMeaning: "Get ready.",
    examples: ["She prepares the food.", "He prepares for the exam."],
    emoji: "🍳",
    syllables: "pre-pare",
    distractorGroup: "actions",
  },
  {
    word: "enjoy",
    pos: "verb",
    kidMeaning: "Have fun.",
    examples: ["She enjoys the movie.", "He enjoys the party."],
    emoji: "😊",
    syllables: "en-joy",
    distractorGroup: "feelings",
  },
  {
    word: "understand",
    pos: "verb",
    kidMeaning: "Know the meaning.",
    examples: ["She understands the lesson.", "He understands the rules."],
    emoji: "💭",
    syllables: "un-der-stand",
    distractorGroup: "actions",
  },
  {
    word: "practice",
    pos: "verb",
    kidMeaning: "Do many times.",
    examples: ["She practises the piano.", "He practises maths."],
    emoji: "🎯",
    syllables: "prac-tice",
    distractorGroup: "actions",
  },
  {
    word: "provide",
    pos: "verb",
    kidMeaning: "Give supply.",
    examples: ["She provides food.", "He provides help."],
    emoji: "🤝",
    syllables: "pro-vide",
    distractorGroup: "actions",
  },
  {
    word: "decrease",
    pos: "verb",
    kidMeaning: "Make smaller.",
    examples: ["She decreases the light.", "He decreases the distance."],
    emoji: "📉",
    syllables: "de-crease",
    distractorGroup: "actions",
  },
  {
    word: "improve",
    pos: "verb",
    kidMeaning: "Make better.",
    examples: ["She improves her skill.", "He improves the design."],
    emoji: "⬆️",
    syllables: "im-prove",
    distractorGroup: "actions",
  },
  {
    word: "suggest",
    pos: "verb",
    kidMeaning: "Give an idea.",
    examples: ["She suggests the game.", "He suggests the park."],
    emoji: "💡",
    syllables: "sug-gest",
    distractorGroup: "actions",
  },
  {
    word: "request",
    pos: "verb",
    kidMeaning: "Ask politely.",
    examples: ["She requests water.", "He requests help."],
    emoji: "🙏",
    syllables: "re-quest",
    distractorGroup: "actions",
  },
  {
    word: "remain",
    pos: "verb",
    kidMeaning: "Stay in place.",
    examples: ["She remains at home.", "He remains silent."],
    emoji: "🧍",
    syllables: "re-main",
    distractorGroup: "actions",
  },
  {
    word: "support",
    pos: "verb",
    kidMeaning: "Help someone.",
    examples: ["She supports her friend.", "He supports his team."],
    emoji: "🤝",
    syllables: "sup-port",
    distractorGroup: "actions",
  },
  {
    word: "update",
    pos: "verb",
    kidMeaning: "Make new.",
    examples: ["She updates the list.", "He updates the software."],
    emoji: "🔄",
    syllables: "up-date",
    distractorGroup: "actions",
  },
  {
    word: "visit",
    pos: "verb",
    kidMeaning: "Go see someone.",
    examples: ["She visits her friend.", "He visits the museum."],
    emoji: "🚪",
    syllables: "vis-it",
    distractorGroup: "actions",
  },
  {
    word: "welcome",
    pos: "verb",
    kidMeaning: "Greet nicely.",
    examples: ["She welcomes the guest.", "He welcomes the team."],
    emoji: "👋",
    syllables: "wel-come",
    distractorGroup: "actions",
  },
  {
    word: "wonder",
    pos: "verb",
    kidMeaning: "Think about.",
    examples: ["She wonders what will happen.", "He wonders if it is true."],
    emoji: "🤔",
    syllables: "won-der",
    distractorGroup: "actions",
  },
  {
    word: "worry",
    pos: "verb",
    kidMeaning: "Feel afraid.",
    examples: ["She worries about the exam.", "He worries about his mum."],
    emoji: "😟",
    syllables: "wor-ry",
    distractorGroup: "feelings",
  },
  {
    word: "zoom",
    pos: "verb",
    kidMeaning: "Move very fast.",
    examples: ["She zooms in on the photo.", "He zooms past in a car."],
    emoji: "💨",
    syllables: "zoom",
    distractorGroup: "actions",
  },
  {
    word: "myself",
    pos: "pronoun",
    kidMeaning: "Me alone.",
    examples: ["I do it myself.", "I tell myself secrets."],
    emoji: "🙋",
    syllables: "my-self",
    distractorGroup: "pronouns",
  },
  {
    word: "yourself",
    pos: "pronoun",
    kidMeaning: "You alone.",
    examples: ["You do it yourself.", "You tell yourself stories."],
    emoji: "🙋",
    syllables: "your-self",
    distractorGroup: "pronouns",
  },
  {
    word: "himself",
    pos: "pronoun",
    kidMeaning: "Him alone.",
    examples: ["He does it himself.", "He tells himself secrets."],
    emoji: "🙋",
    syllables: "him-self",
    distractorGroup: "pronouns",
  },
  {
    word: "herself",
    pos: "pronoun",
    kidMeaning: "Her alone.",
    examples: ["She does it herself.", "She tells herself secrets."],
    emoji: "🙋",
    syllables: "her-self",
    distractorGroup: "pronouns",
  },
  {
    word: "themselves",
    pos: "pronoun",
    kidMeaning: "Them alone.",
    examples: ["They do it themselves.", "They tell themselves stories."],
    emoji: "🙋",
    syllables: "them-selves",
    distractorGroup: "pronouns",
  },
  {
    word: "desk",
    pos: "noun",
    kidMeaning: "Table for work.",
    examples: ["She works at the desk.", "The desk has a computer."],
    emoji: "🖥️",
    syllables: "desk",
    distractorGroup: "objects",
  },
  {
    word: "telephone",
    pos: "noun",
    kidMeaning: "Machine for talking far.",
    examples: ["She talks on the telephone.", "The telephone rings loud."],
    emoji: "☎️",
    syllables: "tel-e-phone",
    distractorGroup: "objects",
  },
  {
    word: "computer",
    pos: "noun",
    kidMeaning: "Machine for work.",
    examples: ["He uses a computer.", "The computer is very fast."],
    emoji: "💻",
    syllables: "com-pu-ter",
    distractorGroup: "objects",
  },
  {
    word: "camera",
    pos: "noun",
    kidMeaning: "Machine for taking photos.",
    examples: ["She takes a photo with a camera.", "The camera is very good."],
    emoji: "📷",
    syllables: "cam-er-a",
    distractorGroup: "objects",
  },
  {
    word: "sofa",
    pos: "noun",
    kidMeaning: "Furniture to sit on.",
    examples: ["He sits on the sofa.", "The sofa is very comfortable."],
    emoji: "🛋️",
    syllables: "so-fa",
    distractorGroup: "objects",
  },
  {
    word: "lamp",
    pos: "noun",
    kidMeaning: "Thing that gives light.",
    examples: ["She turns on the lamp.", "The lamp shines brightly."],
    emoji: "💡",
    syllables: "lamp",
    distractorGroup: "objects",
  },
  {
    word: "box",
    pos: "noun",
    kidMeaning: "Container for things.",
    examples: ["She puts a toy in the box.", "The box is empty."],
    emoji: "📦",
    syllables: "box",
    distractorGroup: "objects",
  },
  {
    word: "bag",
    pos: "noun",
    kidMeaning: "Container you carry.",
    examples: ["He carries a bag.", "The bag has many things."],
    emoji: "👜",
    syllables: "bag",
    distractorGroup: "objects",
  },
  {
    word: "hat",
    pos: "noun",
    kidMeaning: "Thing you wear on head.",
    examples: ["She wears a hat.", "The hat is warm."],
    emoji: "🎩",
    syllables: "hat",
    distractorGroup: "objects",
  },
  {
    word: "shoe",
    pos: "noun",
    kidMeaning: "Thing on foot.",
    examples: ["He puts on his shoes.", "The shoe is big."],
    emoji: "👟",
    syllables: "shoe",
    distractorGroup: "objects",
  },
  {
    word: "dress",
    pos: "noun",
    kidMeaning: "Thing to wear.",
    examples: ["She wears a dress.", "The dress is beautiful."],
    emoji: "👗",
    syllables: "dress",
    distractorGroup: "objects",
  },
  {
    word: "coat",
    pos: "noun",
    kidMeaning: "Thing to keep warm.",
    examples: ["He wears a coat.", "The coat is thick."],
    emoji: "🧥",
    syllables: "coat",
    distractorGroup: "objects",
  },
  {
    word: "orange",
    pos: "noun",
    kidMeaning: "Orange fruit.",
    examples: ["He eats an orange.", "Oranges have vitamin C."],
    emoji: "🍊",
    syllables: "or-ange",
    distractorGroup: "food",
  },
  {
    word: "banana",
    pos: "noun",
    kidMeaning: "Yellow fruit.",
    examples: ["She peels a banana.", "Bananas are very good."],
    emoji: "🍌",
    syllables: "ba-nan-a",
    distractorGroup: "food",
  },
  {
    word: "cow",
    pos: "noun",
    kidMeaning: "Animal for milk.",
    examples: ["She milks the cow.", "Cows live on farms."],
    emoji: "🐄",
    syllables: "cow",
    distractorGroup: "animals",
  },
  {
    word: "pig",
    pos: "noun",
    kidMeaning: "Animal on a farm.",
    examples: ["He feeds the pig.", "Pigs are very fat."],
    emoji: "🐷",
    syllables: "pig",
    distractorGroup: "animals",
  },
  {
    word: "sheep",
    pos: "noun",
    kidMeaning: "Animal with wool.",
    examples: ["She has a sheep.", "Sheep give wool."],
    emoji: "🐑",
    syllables: "sheep",
    distractorGroup: "animals",
  },
  {
    word: "horse",
    pos: "noun",
    kidMeaning: "Animal you ride.",
    examples: ["He rides a horse.", "Horses are very fast."],
    emoji: "🐴",
    syllables: "horse",
    distractorGroup: "animals",
  },
  {
    word: "store",
    pos: "noun",
    kidMeaning: "Place for buying things.",
    examples: ["He goes to the store.", "Stores sell many things."],
    emoji: "🛍️",
    syllables: "store",
    distractorGroup: "places",
  },
  {
    word: "movie",
    pos: "noun",
    kidMeaning: "Film to watch.",
    examples: ["He watches a movie.", "Movies are good."],
    emoji: "🎬",
    syllables: "mov-ie",
    distractorGroup: "art",
  },
  {
    word: "party",
    pos: "noun",
    kidMeaning: "Celebration time.",
    examples: ["She goes to the party.", "Parties are fun."],
    emoji: "🎉",
    syllables: "par-ty",
    distractorGroup: "events",
  },
  {
    word: "holiday",
    pos: "noun",
    kidMeaning: "Day with no work.",
    examples: ["He has a holiday.", "Holidays are good."],
    emoji: "🎄",
    syllables: "hol-i-day",
    distractorGroup: "events",
  },
  {
    word: "birthday",
    pos: "noun",
    kidMeaning: "Day you were born.",
    examples: ["She has a birthday.", "Birthdays have cake."],
    emoji: "🎂",
    syllables: "birth-day",
    distractorGroup: "events",
  },
  {
    word: "wedding",
    pos: "noun",
    kidMeaning: "Day of marriage.",
    examples: ["He goes to a wedding.", "Weddings are nice."],
    emoji: "💍",
    syllables: "wed-ding",
    distractorGroup: "events",
  },
  {
    word: "winter",
    pos: "noun",
    kidMeaning: "Cold season.",
    examples: ["She likes winter.", "Winter has snow."],
    emoji: "❄️",
    syllables: "win-ter",
    distractorGroup: "time",
  },
  {
    word: "summer",
    pos: "noun",
    kidMeaning: "Hot season.",
    examples: ["He likes summer.", "Summer is very hot."],
    emoji: "☀️",
    syllables: "sum-mer",
    distractorGroup: "time",
  },
  {
    word: "spring",
    pos: "noun",
    kidMeaning: "Warm season.",
    examples: ["She likes spring.", "Spring has flowers."],
    emoji: "🌸",
    syllables: "spring",
    distractorGroup: "time",
  },
  {
    word: "autumn",
    pos: "noun",
    kidMeaning: "Season before winter.",
    examples: ["He likes autumn.", "Autumn has red leaves."],
    emoji: "🍂",
    syllables: "au-tumn",
    distractorGroup: "time",
  },
  {
    word: "grandmother",
    pos: "noun",
    kidMeaning: "Mother of a parent.",
    examples: ["She visits her grandmother.", "Grandmothers tell stories."],
    emoji: "👵",
    syllables: "grand-moth-er",
    distractorGroup: "people",
  },
  {
    word: "grandfather",
    pos: "noun",
    kidMeaning: "Father of a parent.",
    examples: ["He visits his grandfather.", "Grandfathers are old."],
    emoji: "👴",
    syllables: "grand-fath-er",
    distractorGroup: "people",
  },
  {
    word: "uncle",
    pos: "noun",
    kidMeaning: "Brother of a parent.",
    examples: ["She visits her uncle.", "Uncles work at banks."],
    emoji: "👨",
    syllables: "un-cle",
    distractorGroup: "people",
  },
  {
    word: "aunt",
    pos: "noun",
    kidMeaning: "Sister of a parent.",
    examples: ["He visits his aunt.", "Aunts are very kind."],
    emoji: "👩",
    syllables: "aunt",
    distractorGroup: "people",
  },
  {
    word: "teenager",
    pos: "noun",
    kidMeaning: "Young person 13-19.",
    examples: ["The teenager studies hard.", "Teenagers like music."],
    emoji: "👦",
    syllables: "teen-ag-er",
    distractorGroup: "people",
  },
  {
    word: "young",
    pos: "adjective",
    kidMeaning: "Not old.",
    examples: ["The young girl is smart.", "Young people have energy."],
    emoji: "👧",
    syllables: "young",
    distractorGroup: "age",
  },
  {
    word: "police",
    pos: "noun",
    kidMeaning: "The people who keep everyone safe.",
    examples: ["The police helps.", "Police are brave."],
    emoji: "👮",
    syllables: "po-lice",
    distractorGroup: "people",
  },
  {
    word: "chef",
    pos: "noun",
    kidMeaning: "Person who cooks food.",
    examples: ["The chef is very good.", "Chefs make delicious food."],
    emoji: "👨",
    syllables: "chef",
    distractorGroup: "people",
  },
  {
    word: "manual",
    pos: "noun",
    kidMeaning: "Instruction book or guide",
    examples: ["She reads the manual.", "The manual explains everything."],
    emoji: "📖",
    syllables: "man-u-al",
    distractorGroup: "school",
  },
  {
    word: "sailor",
    pos: "noun",
    kidMeaning: "Person who works on ships.",
    examples: ["The sailor navigates the ship.", "Sailors work hard at sea."],
    emoji: "⛵",
    syllables: "sail-or",
    distractorGroup: "people",
  },
  {
    word: "builder",
    pos: "noun",
    kidMeaning: "Person who builds houses.",
    examples: ["The builder builds fast.", "Builders are strong."],
    emoji: "👷",
    syllables: "build-er",
    distractorGroup: "people",
  },
  {
    word: "singer",
    pos: "noun",
    kidMeaning: "Person who sings songs.",
    examples: ["The singer has a nice voice.", "Singers are famous."],
    emoji: "🎤",
    syllables: "sing-er",
    distractorGroup: "people",
  },
  {
    word: "dancer",
    pos: "noun",
    kidMeaning: "Person who dances.",
    examples: ["The dancer moves beautifully.", "Dancers are graceful."],
    emoji: "💃",
    syllables: "danc-er",
    distractorGroup: "people",
  },
  {
    word: "judge",
    pos: "noun",
    kidMeaning: "Person in a court.",
    examples: ["The judge makes decisions.", "Judges are wise."],
    emoji: "👨",
    syllables: "judge",
    distractorGroup: "people",
  },
  {
    word: "lawyer",
    pos: "noun",
    kidMeaning: "Person who gives legal help.",
    examples: ["The lawyer helps her.", "Lawyers are smart."],
    emoji: "👨",
    syllables: "law-yer",
    distractorGroup: "people",
  },
  {
    word: "dentist",
    pos: "noun",
    kidMeaning: "Person who cares for teeth.",
    examples: ["The dentist checks teeth.", "Dentists are good."],
    emoji: "👨",
    syllables: "den-tist",
    distractorGroup: "people",
  },
  {
    word: "pharmacist",
    pos: "noun",
    kidMeaning: "Person who gives medicine.",
    examples: ["The pharmacist gives pills.", "Pharmacists are careful."],
    emoji: "💊",
    syllables: "phar-ma-cist",
    distractorGroup: "people",
  },
  {
    word: "checklist",
    pos: "noun",
    kidMeaning: "List of things to check or do",
    examples: ["She uses a checklist for homework.", "The checklist is organised."],
    emoji: "✓",
    syllables: "check-list",
    distractorGroup: "school",
  },
  {
    word: "tailor",
    pos: "noun",
    kidMeaning: "Person who makes clothes.",
    examples: ["The tailor fixed my shirt.", "A tailor makes custom clothes."],
    emoji: "👗",
    syllables: "tail-or",
    distractorGroup: "people",
  },
  {
    word: "hairdresser",
    pos: "noun",
    kidMeaning: "Person who cuts hair.",
    examples: ["The hairdresser cuts hair.", "Hairdressers are good."],
    emoji: "✂️",
    syllables: "hair-dress-er",
    distractorGroup: "people",
  },
  {
    word: "bartender",
    pos: "noun",
    kidMeaning: "Person who makes drinks.",
    examples: ["The bartender makes drinks.", "Bartenders are friendly."],
    emoji: "🍸",
    syllables: "bar-tend-er",
    distractorGroup: "people",
  },
  {
    word: "security",
    pos: "noun",
    kidMeaning: "Being safe from danger or harm.",
    examples: ["The security of the school comes first.", "Security guards check every bag."],
    emoji: "🔒",
    syllables: "se-cur-i-ty",
    distractorGroup: "people",
  },
  {
    word: "secretary",
    pos: "noun",
    kidMeaning: "Person who helps the boss.",
    examples: ["The secretary helps the boss.", "Secretaries are organised."],
    emoji: "📋",
    syllables: "sec-re-tar-y",
    distractorGroup: "people",
  },
  {
    word: "manager",
    pos: "noun",
    kidMeaning: "Person who leads a team.",
    examples: ["The manager leads the team.", "Managers are smart."],
    emoji: "👨",
    syllables: "man-ag-er",
    distractorGroup: "people",
  },
  {
    word: "director",
    pos: "noun",
    kidMeaning: "Person who directs films.",
    examples: ["The director makes films.", "Directors are creative."],
    emoji: "🎬",
    syllables: "di-rec-tor",
    distractorGroup: "people",
  },
  {
    word: "president",
    pos: "noun",
    kidMeaning: "Leader of a country.",
    examples: ["The president leads the country.", "Presidents are important."],
    emoji: "👑",
    syllables: "pres-i-dent",
    distractorGroup: "people",
  },
  {
    word: "king",
    pos: "noun",
    kidMeaning: "Male ruler.",
    examples: ["The king rules the kingdom.", "Kings are powerful."],
    emoji: "👑",
    syllables: "king",
    distractorGroup: "people",
  },
  {
    word: "queen",
    pos: "noun",
    kidMeaning: "Female ruler.",
    examples: ["The queen rules the kingdom.", "Queens are beautiful."],
    emoji: "👑",
    syllables: "queen",
    distractorGroup: "people",
  },
  {
    word: "prince",
    pos: "noun",
    kidMeaning: "Son of a king.",
    examples: ["The prince is handsome.", "Princes live in palaces."],
    emoji: "🤴",
    syllables: "prince",
    distractorGroup: "people",
  },
  {
    word: "princess",
    pos: "noun",
    kidMeaning: "Daughter of a king.",
    examples: ["The princess is beautiful.", "Princesses wear crowns."],
    emoji: "👸",
    syllables: "prin-cess",
    distractorGroup: "people",
  },
  {
    word: "astronaut",
    pos: "noun",
    kidMeaning: "Person who goes to space.",
    examples: ["The astronaut flies to the moon.", "Astronauts are brave."],
    emoji: "👨",
    syllables: "as-tro-naut",
    distractorGroup: "people",
  },
  {
    word: "poet",
    pos: "noun",
    kidMeaning: "Person who writes poems.",
    examples: ["The poet writes beautiful words.", "Poets are sensitive."],
    emoji: "📖",
    syllables: "po-et",
    distractorGroup: "people",
  },
  {
    word: "creator",
    pos: "noun",
    kidMeaning: "Person who makes or builds things.",
    examples: ["The creator draws well.", "She is a talented creator."],
    emoji: "📷",
    syllables: "pho-tog-ra-pher",
    distractorGroup: "people",
  },
  {
    word: "composer",
    pos: "noun",
    kidMeaning: "Person who writes music.",
    examples: ["The composer writes songs.", "Composers are creative."],
    emoji: "🎵",
    syllables: "com-pos-er",
    distractorGroup: "people",
  },
  {
    word: "athlete",
    pos: "noun",
    kidMeaning: "Person who does sports.",
    examples: ["The athlete trains hard.", "Athletes are strong."],
    emoji: "🏃",
    syllables: "ath-lete",
    distractorGroup: "people",
  },
  {
    word: "trainer",
    pos: "noun",
    kidMeaning: "Person who teaches exercise.",
    examples: ["The trainer helps with fitness.", "Trainers are strict."],
    emoji: "🏋️",
    syllables: "train-er",
    distractorGroup: "people",
  },
  {
    word: "counsellor",
    pos: "noun",
    kidMeaning: "Person who gives advice.",
    examples: ["The counsellor helps her.", "Counsellors are patient."],
    emoji: "👨",
    syllables: "coun-sel-lor",
    distractorGroup: "people",
  },
  {
    word: "tutorial",
    pos: "noun",
    kidMeaning: "Lesson showing how to do something",
    examples: ["He watches the tutorial.", "The tutorial is helpful."],
    emoji: "🎓",
    syllables: "tu-tor-i-al",
    distractorGroup: "school",
  },
  {
    word: "fisherman",
    pos: "noun",
    kidMeaning: "Person who catches fish.",
    examples: ["The fisherman caught a big fish.", "Fishermen work near the water."],
    emoji: "🎣",
    syllables: "fish-er-man",
    distractorGroup: "people",
  },
  {
    word: "hunter",
    pos: "noun",
    kidMeaning: "Person who hunts animals.",
    examples: ["The hunter hunts deer.", "Hunters are brave."],
    emoji: "🏹",
    syllables: "hunt-er",
    distractorGroup: "people",
  },
  {
    word: "miner",
    pos: "noun",
    kidMeaning: "Person who digs in mines.",
    examples: ["The miner digs coal.", "Miners are strong."],
    emoji: "⛏️",
    syllables: "min-er",
    distractorGroup: "people",
  },
  {
    word: "carpenter",
    pos: "noun",
    kidMeaning: "Person who makes wood things.",
    examples: ["The carpenter makes tables.", "Carpenters are skilled."],
    emoji: "🔨",
    syllables: "car-pent-er",
    distractorGroup: "people",
  },
  {
    word: "electrician",
    pos: "noun",
    kidMeaning: "Person who fixes electricity.",
    examples: ["The electrician fixes wires.", "Electricians are smart."],
    emoji: "⚡",
    syllables: "e-lec-tri-cian",
    distractorGroup: "people",
  },
  {
    word: "plumber",
    pos: "noun",
    kidMeaning: "Person who fixes water pipes.",
    examples: ["The plumber fixes pipes.", "Plumbers are helpful."],
    emoji: "🚰",
    syllables: "plumb-er",
    distractorGroup: "people",
  },
  {
    word: "gardener",
    pos: "noun",
    kidMeaning: "Person who cares for gardens.",
    examples: ["The gardener plants flowers.", "Gardeners are patient."],
    emoji: "🌻",
    syllables: "gard-en-er",
    distractorGroup: "people",
  },
  {
    word: "decorator",
    pos: "noun",
    kidMeaning: "Person who decorates places.",
    examples: ["The decorator decorates the room.", "Decorators are artistic."],
    emoji: "🎨",
    syllables: "dec-o-rat-or",
    distractorGroup: "people",
  },
  {
    word: "architect",
    pos: "noun",
    kidMeaning: "Person who designs buildings.",
    examples: ["The architect designs houses.", "Architects are creative."],
    emoji: "🏢",
    syllables: "ar-chi-tect",
    distractorGroup: "people",
  },
  {
    word: "chemist",
    pos: "noun",
    kidMeaning: "Person who studies chemistry.",
    examples: ["The chemist does experiments.", "Chemists are careful."],
    emoji: "🧪",
    syllables: "chem-ist",
    distractorGroup: "people",
  },
  {
    word: "historian",
    pos: "noun",
    kidMeaning: "Person who studies history.",
    examples: ["The historian studies the past.", "Historians are knowledgeable."],
    emoji: "📖",
    syllables: "his-to-ri-an",
    distractorGroup: "people",
  },
  {
    word: "accountant",
    pos: "noun",
    kidMeaning: "Person who keeps numbers.",
    examples: ["The accountant keeps accounts.", "Accountants are careful."],
    emoji: "💼",
    syllables: "ac-count-ant",
    distractorGroup: "people",
  },
  {
    word: "banker",
    pos: "noun",
    kidMeaning: "Person who works at a bank.",
    examples: ["The banker helps with money.", "Bankers are professional."],
    emoji: "🏦",
    syllables: "bank-er",
    distractorGroup: "people",
  },
  {
    word: "businessman",
    pos: "noun",
    kidMeaning: "Person who does business.",
    examples: ["The businessman makes deals.", "Businessmen are busy."],
    emoji: "💼",
    syllables: "bus-i-ness-man",
    distractorGroup: "people",
  },
  {
    word: "dealer",
    pos: "noun",
    kidMeaning: "Person who sells things.",
    examples: ["The dealer sells cars.", "Dealers are friendly."],
    emoji: "🚗",
    syllables: "deal-er",
    distractorGroup: "people",
  },
  {
    word: "trader",
    pos: "noun",
    kidMeaning: "Person who trades things.",
    examples: ["The trader trades goods.", "Traders are smart."],
    emoji: "💼",
    syllables: "trad-er",
    distractorGroup: "people",
  },
  {
    word: "smuggler",
    pos: "noun",
    kidMeaning: "Person who moves illegal things.",
    examples: ["The smuggler breaks the law.", "Smugglers are sneaky."],
    emoji: "🚫",
    syllables: "smug-gler",
    distractorGroup: "people",
  },
  {
    word: "thief",
    pos: "noun",
    kidMeaning: "Person who steals things.",
    examples: ["The thief steals money.", "Thieves are sneaky."],
    emoji: "🚨",
    syllables: "thief",
    distractorGroup: "people",
  },
  {
    word: "pirate",
    pos: "noun",
    kidMeaning: "Person who attacks ships.",
    examples: ["The pirate attacks ships.", "Pirates are dangerous."],
    emoji: "🏴‍☠️",
    syllables: "pi-rate",
    distractorGroup: "people",
  },
  {
    word: "witness",
    pos: "noun",
    kidMeaning: "Person who sees a crime.",
    examples: ["The witness tells the police.", "Witnesses are scared."],
    emoji: "👁️",
    syllables: "wit-ness",
    distractorGroup: "people",
  },
  {
    word: "dictionary",
    pos: "noun",
    kidMeaning: "Book that shows word meanings.",
    examples: ["She looks up a word in the dictionary.", "Dictionaries help you learn new words."],
    emoji: "📖",
    syllables: "dic-tion-ar-y",
    distractorGroup: "objects",
  },
  {
    word: "essay",
    pos: "noun",
    kidMeaning: "Piece of writing about one idea.",
    examples: ["She writes an essay about trees.", "The essay is very good."],
    emoji: "✏️",
    syllables: "es-say",
    distractorGroup: "activities",
  },
  {
    word: "poem",
    pos: "noun",
    kidMeaning: "Special writing with rhyme and feeling.",
    examples: ["He reads a poem in class.", "The poem is very beautiful."],
    emoji: "📖",
    syllables: "po-em",
    distractorGroup: "activities",
  },
  {
    word: "rhyme",
    pos: "noun",
    kidMeaning: "Word that sounds like another word.",
    examples: ["Cat and mat rhyme.", "She finds rhymes in poems."],
    emoji: "🎵",
    syllables: "rhyme",
    distractorGroup: "language",
  },
  {
    word: "vowel",
    pos: "noun",
    kidMeaning: "Letter a, e, i, o, u.",
    examples: ["The vowel is in the word apple.", "Vowels are important for speaking."],
    emoji: "ABC",
    syllables: "vow-el",
    distractorGroup: "language",
  },
  {
    word: "consonant",
    pos: "noun",
    kidMeaning: "Letter that is not a vowel.",
    examples: ["B and c are consonants.", "Most letters are consonants."],
    emoji: "ABC",
    syllables: "con-so-nant",
    distractorGroup: "language",
  },
  {
    word: "syllable",
    pos: "noun",
    kidMeaning: "Part of a word you say.",
    examples: ["The word cat has one syllable.", "She counts syllables in words."],
    emoji: "🔤",
    syllables: "syl-la-ble",
    distractorGroup: "language",
  },
  {
    word: "sentence",
    pos: "noun",
    kidMeaning: "Group of words with meaning.",
    examples: ["She writes a complete sentence.", "The sentence has a subject."],
    emoji: "📝",
    syllables: "sen-tence",
    distractorGroup: "language",
  },
  {
    word: "paragraph",
    pos: "noun",
    kidMeaning: "Group of sentences about one idea.",
    examples: ["The paragraph is about animals.", "She writes three paragraphs."],
    emoji: "📄",
    syllables: "par-a-graph",
    distractorGroup: "language",
  },
  {
    word: "punctuation",
    pos: "noun",
    kidMeaning: "Sign like period and comma.",
    examples: ["Punctuation marks sentences.", "She adds punctuation to her writing."],
    emoji: "◦",
    syllables: "punc-tu-a-tion",
    distractorGroup: "language",
  },
  {
    word: "comma",
    pos: "noun",
    kidMeaning: "Mark (,) that separates things.",
    examples: ["Put a comma between words.", "She puts a comma in the sentence."],
    emoji: "⌣",
    syllables: "com-ma",
    distractorGroup: "language",
  },
  {
    word: "period",
    pos: "noun",
    kidMeaning: "Mark (.) at the end of a sentence.",
    examples: ["Every sentence ends with a period.", "She writes a period at the end."],
    emoji: "⭕",
    syllables: "pe-ri-od",
    distractorGroup: "language",
  },
  {
    word: "exclamation",
    pos: "noun",
    kidMeaning: "Loud cry or shout mark.",
    examples: ["Exclamations show big feelings.", "She writes an exclamation mark."],
    emoji: "◦",
    syllables: "ex-cla-ma-tion",
    distractorGroup: "language",
  },
  {
    word: "revise",
    pos: "verb",
    kidMeaning: "Study again to remember.",
    examples: ["She revises for the test.", "He revises the chapter."],
    emoji: "📚",
    syllables: "re-vise",
    distractorGroup: "actions",
  },
  {
    word: "memorise",
    pos: "verb",
    kidMeaning: "Remember by heart.",
    examples: ["She memorises the poem.", "He memorises vocabulary words."],
    emoji: "🧠",
    syllables: "mem-o-rise",
    distractorGroup: "actions",
  },
  {
    word: "recite",
    pos: "verb",
    kidMeaning: "Say words that you memorise.",
    examples: ["She recites the poem.", "They recite the alphabet together."],
    emoji: "🎤",
    syllables: "re-cite",
    distractorGroup: "actions",
  },
  {
    word: "debate",
    pos: "verb",
    kidMeaning: "Argue and discuss an idea.",
    examples: ["The student debates the topic.", "They debate in class."],
    emoji: "💬",
    syllables: "de-bate",
    distractorGroup: "actions",
  },
  {
    word: "concert",
    pos: "noun",
    kidMeaning: "A show with music and singers.",
    examples: ["We watch a concert together.", "The concert is very fun."],
    emoji: "🎤",
    syllables: "pres-en-ta-tion",
    distractorGroup: "activities",
  },
  {
    word: "lecture",
    pos: "noun",
    kidMeaning: "Teacher talks to many students.",
    examples: ["The professor gives a lecture.", "She listens to the lecture."],
    emoji: "👨",
    syllables: "lec-ture",
    distractorGroup: "activities",
  },
  {
    word: "chapter",
    pos: "noun",
    kidMeaning: "Part of a book.",
    examples: ["The book has ten chapters.", "She reads chapter five."],
    emoji: "📖",
    syllables: "chap-ter",
    distractorGroup: "objects",
  },
  {
    word: "margin",
    pos: "noun",
    kidMeaning: "Empty space at side of page.",
    examples: ["Write in the margin.", "Leave margins when you write."],
    emoji: "📄",
    syllables: "mar-gin",
    distractorGroup: "objects",
  },
  {
    word: "highlight",
    pos: "verb",
    kidMeaning: "Mark important words with colour.",
    examples: ["She highlights key words.", "He highlights the important part."],
    emoji: "🖍️",
    syllables: "high-light",
    distractorGroup: "actions",
  },
  {
    word: "underline",
    pos: "verb",
    kidMeaning: "Draw a line under a word.",
    examples: ["She underlines new vocabulary.", "He underlines the answer."],
    emoji: "✏️",
    syllables: "un-der-line",
    distractorGroup: "actions",
  },
  {
    word: "erase",
    pos: "verb",
    kidMeaning: "Remove writing with a rubber.",
    examples: ["She erases her mistake.", "He erases the pencil mark."],
    emoji: "🧹",
    syllables: "e-rase",
    distractorGroup: "actions",
  },
  {
    word: "sketch",
    pos: "verb",
    kidMeaning: "Draw quickly and simply.",
    examples: ["She sketches the flower.", "He sketches what he sees."],
    emoji: "🎨",
    syllables: "sketch",
    distractorGroup: "actions",
  },
  {
    word: "crayon",
    pos: "noun",
    kidMeaning: "Stick of colour for drawing.",
    examples: ["She colours with crayons.", "The crayon is soft."],
    emoji: "🖍️",
    syllables: "cray-on",
    distractorGroup: "objects",
  },
  {
    word: "charcoal",
    pos: "noun",
    kidMeaning: "Dark stick for drawing and shading.",
    examples: ["She draws with charcoal.", "Charcoal makes dark lines."],
    emoji: "🖤",
    syllables: "char-coal",
    distractorGroup: "objects",
  },
  {
    word: "locker",
    pos: "noun",
    kidMeaning: "Small cupboard at school.",
    examples: ["She keeps books in the locker.", "The locker has a lock."],
    emoji: "🔓",
    syllables: "lock-er",
    distractorGroup: "places",
  },
  {
    word: "bell",
    pos: "noun",
    kidMeaning: "Metal thing that rings loud.",
    examples: ["The bell rings for the start of class.", "She hears the bell."],
    emoji: "🔔",
    syllables: "bell",
    distractorGroup: "objects",
  },
  {
    word: "recess",
    pos: "noun",
    kidMeaning: "Time to play and rest at school.",
    examples: ["The children play at recess.", "Recess is fun time."],
    emoji: "🎮",
    syllables: "re-cess",
    distractorGroup: "time",
  },
  {
    word: "laboratory",
    pos: "noun",
    kidMeaning: "Place for science experiments.",
    examples: ["They do experiments in the laboratory.", "The laboratory has tools."],
    emoji: "🔬",
    syllables: "lab-o-ra-tor-y",
    distractorGroup: "places",
  },
  {
    word: "gymnasium",
    pos: "noun",
    kidMeaning: "Room for exercise and sports.",
    examples: ["They play basketball in the gymnasium.", "The gymnasium is big."],
    emoji: "🏋️",
    syllables: "gym-na-si-um",
    distractorGroup: "places",
  },
  {
    word: "wardrobe",
    pos: "noun",
    kidMeaning: "Large cabinet for clothes.",
    examples: ["She hangs a dress in the wardrobe.", "The wardrobe has many clothes."],
    emoji: "👗",
    syllables: "ward-robe",
    distractorGroup: "objects",
  },
  {
    word: "drawer",
    pos: "noun",
    kidMeaning: "Box part that pulls out.",
    examples: ["She opens the drawer.", "Socks are in the drawer."],
    emoji: "🗄️",
    syllables: "draw-er",
    distractorGroup: "objects",
  },
  {
    word: "mattress",
    pos: "noun",
    kidMeaning: "Soft thing on a bed.",
    examples: ["The mattress is comfortable.", "She sleeps on the mattress."],
    emoji: "🛏️",
    syllables: "mat-tress",
    distractorGroup: "objects",
  },
  {
    word: "carpet",
    pos: "noun",
    kidMeaning: "Cloth cover for floor.",
    examples: ["She walks on the carpet.", "The carpet is soft."],
    emoji: "🟫",
    syllables: "car-pet",
    distractorGroup: "objects",
  },
  {
    word: "rug",
    pos: "noun",
    kidMeaning: "Small cloth on floor.",
    examples: ["The rug is colourful.", "She puts a rug in the room."],
    emoji: "🟫",
    syllables: "rug",
    distractorGroup: "objects",
  },
  {
    word: "painting",
    pos: "noun",
    kidMeaning: "Picture painted on canvas.",
    examples: ["The painting is beautiful.", "She hangs the painting on the wall."],
    emoji: "🎨",
    syllables: "paint-ing",
    distractorGroup: "objects",
  },
  {
    word: "vase",
    pos: "noun",
    kidMeaning: "Container for flowers.",
    examples: ["She puts flowers in the vase.", "The vase is fragile."],
    emoji: "🌸",
    syllables: "vase",
    distractorGroup: "objects",
  },
  {
    word: "utensil",
    pos: "noun",
    kidMeaning: "Tool for cooking or eating.",
    examples: ["Kitchen utensils are useful.", "She uses utensils to eat."],
    emoji: "🍴",
    syllables: "u-ten-sil",
    distractorGroup: "objects",
  },
  {
    word: "cutlery",
    pos: "noun",
    kidMeaning: "Knife, fork, spoon for eating.",
    examples: ["She sets the cutlery.", "The cutlery is clean."],
    emoji: "🍴",
    syllables: "cut-ler-y",
    distractorGroup: "objects",
  },
  {
    word: "spoon",
    pos: "noun",
    kidMeaning: "Eating tool with a cup part.",
    examples: ["She eats soup with a spoon.", "The spoon is silver."],
    emoji: "🥄",
    syllables: "spoon",
    distractorGroup: "objects",
  },
  {
    word: "fork",
    pos: "noun",
    kidMeaning: "Eating tool with points.",
    examples: ["She uses a fork to eat.", "The fork has four points."],
    emoji: "🍴",
    syllables: "fork",
    distractorGroup: "objects",
  },
  {
    word: "knife",
    pos: "noun",
    kidMeaning: "Sharp tool for cutting.",
    examples: ["She cuts with a knife.", "The knife is sharp."],
    emoji: "🔪",
    syllables: "knife",
    distractorGroup: "objects",
  },
  {
    word: "plate",
    pos: "noun",
    kidMeaning: "Flat dish for food.",
    examples: ["She puts food on the plate.", "The plate is clean."],
    emoji: "🍽️",
    syllables: "plate",
    distractorGroup: "objects",
  },
  {
    word: "bowl",
    pos: "noun",
    kidMeaning: "Round dish for soup.",
    examples: ["She eats rice in the bowl.", "The bowl is deep."],
    emoji: "🥣",
    syllables: "bowl",
    distractorGroup: "objects",
  },
  {
    word: "mug",
    pos: "noun",
    kidMeaning: "Cup with a handle.",
    examples: ["She drinks tea in the mug.", "The mug is warm."],
    emoji: "☕",
    syllables: "mug",
    distractorGroup: "objects",
  },
  {
    word: "jug",
    pos: "noun",
    kidMeaning: "Container with a handle.",
    examples: ["She pours water from the jug.", "The jug is full."],
    emoji: "🫖",
    syllables: "jug",
    distractorGroup: "objects",
  },
  {
    word: "dustpan",
    pos: "noun",
    kidMeaning: "Pan for sweeping dust.",
    examples: ["She uses a dustpan to collect dust.", "The dustpan is near the broom."],
    emoji: "🧹",
    syllables: "dust-pan",
    distractorGroup: "objects",
  },
  {
    word: "mop",
    pos: "noun",
    kidMeaning: "Tool for washing the floor.",
    examples: ["She cleans the floor with a mop.", "The mop is wet."],
    emoji: "🧼",
    syllables: "mop",
    distractorGroup: "objects",
  },
  {
    word: "scrub",
    pos: "verb",
    kidMeaning: "Wash hard and rough.",
    examples: ["She scrubs the floor.", "He scrubs his hands clean."],
    emoji: "🧹",
    syllables: "scrub",
    distractorGroup: "actions",
  },
  {
    word: "rinse",
    pos: "verb",
    kidMeaning: "Wash with clean water.",
    examples: ["She rinses the plate.", "He rinses his mouth."],
    emoji: "💧",
    syllables: "rinse",
    distractorGroup: "actions",
  },
  {
    word: "wring",
    pos: "verb",
    kidMeaning: "Squeeze water out.",
    examples: ["She wrings the cloth.", "He wrings the mop dry."],
    emoji: "💧",
    syllables: "wring",
    distractorGroup: "actions",
  },
  {
    word: "sweep",
    pos: "verb",
    kidMeaning: "Clean the floor with a broom.",
    examples: ["She sweeps the floor.", "He sweeps away the dust."],
    emoji: "🧹",
    syllables: "sweep",
    distractorGroup: "actions",
  },
  {
    word: "vacuum",
    pos: "verb",
    kidMeaning: "Clean with a vacuum machine.",
    examples: ["She vacuums the carpet.", "He vacuums the room."],
    emoji: "🧹",
    syllables: "vac-u-um",
    distractorGroup: "actions",
  },
  {
    word: "decorate",
    pos: "verb",
    kidMeaning: "Make beautiful with things.",
    examples: ["She decorates the room.", "He decorates the cake."],
    emoji: "🎨",
    syllables: "dec-o-rate",
    distractorGroup: "actions",
  },
  {
    word: "polish",
    pos: "verb",
    kidMeaning: "Make shiny and smooth.",
    examples: ["She polishes the shoe.", "He polishes the floor."],
    emoji: "✨",
    syllables: "pol-ish",
    distractorGroup: "actions",
  },
  {
    word: "niece",
    pos: "noun",
    kidMeaning: "Daughter of your brother.",
    examples: ["She is my niece.", "My niece is very cute."],
    emoji: "👧",
    syllables: "niece",
    distractorGroup: "people",
  },
  {
    word: "nephew",
    pos: "noun",
    kidMeaning: "Son of your brother.",
    examples: ["He is my nephew.", "My nephew likes to play."],
    emoji: "👦",
    syllables: "neph-ew",
    distractorGroup: "people",
  },
  {
    word: "ancestor",
    pos: "noun",
    kidMeaning: "Family member long ago.",
    examples: ["Her ancestors came from China.", "Ancestors are family history."],
    emoji: "👴",
    syllables: "an-ces-tor",
    distractorGroup: "people",
  },
  {
    word: "stepmother",
    pos: "noun",
    kidMeaning: "Mother by marriage, not birth.",
    examples: ["She is my stepmother.", "My stepmother is kind."],
    emoji: "👩",
    syllables: "step-moth-er",
    distractorGroup: "people",
  },
  {
    word: "stepfather",
    pos: "noun",
    kidMeaning: "Father by marriage, not birth.",
    examples: ["He is my stepfather.", "My stepfather helps me."],
    emoji: "👨",
    syllables: "step-fath-er",
    distractorGroup: "people",
  },
  {
    word: "stepsister",
    pos: "noun",
    kidMeaning: "Sister by marriage, not blood.",
    examples: ["She is my stepsister.", "My stepsister likes books."],
    emoji: "👧",
    syllables: "step-sis-ter",
    distractorGroup: "people",
  },
  {
    word: "stepbrother",
    pos: "noun",
    kidMeaning: "Brother by marriage, not blood.",
    examples: ["He is my stepbrother.", "My stepbrother likes games."],
    emoji: "👦",
    syllables: "step-broth-er",
    distractorGroup: "people",
  },
  {
    word: "tradition",
    pos: "noun",
    kidMeaning: "Way a family does things long time.",
    examples: ["Celebrating with family is a tradition.", "This tradition is old."],
    emoji: "🎏",
    syllables: "tra-di-tion",
    distractorGroup: "abstract",
  },
  {
    word: "surgeon",
    pos: "noun",
    kidMeaning: "Doctor who does operations.",
    examples: ["The surgeon helps the patient.", "She wants to be a surgeon."],
    emoji: "👨",
    syllables: "sur-geon",
    distractorGroup: "people",
  },
  {
    word: "therapist",
    pos: "noun",
    kidMeaning: "Person who helps people feel better.",
    examples: ["The therapist helps her feel happy.", "He goes to a therapist."],
    emoji: "👨",
    syllables: "ther-a-pist",
    distractorGroup: "people",
  },
  {
    word: "guidebook",
    pos: "noun",
    kidMeaning: "Book that tells you what to do",
    examples: ["He reads the guidebook.", "The guidebook is helpful."],
    emoji: "📖",
    syllables: "guide-book",
    distractorGroup: "school",
  },
  {
    word: "conductor",
    pos: "noun",
    kidMeaning: "Person who leads music or buses.",
    examples: ["The conductor leads the orchestra.", "A conductor directs the band."],
    emoji: "🚌",
    syllables: "con-duc-tor",
    distractorGroup: "people",
  },
  {
    word: "clerk",
    pos: "noun",
    kidMeaning: "Person who helps in an office.",
    examples: ["The clerk helps with papers.", "He works as a clerk."],
    emoji: "📋",
    syllables: "clerk",
    distractorGroup: "people",
  },
  {
    word: "courier",
    pos: "noun",
    kidMeaning: "Person who delivers packages.",
    examples: ["The courier brings packages.", "She works as a courier."],
    emoji: "📦",
    syllables: "cour-i-er",
    distractorGroup: "people",
  },
  {
    word: "pamphlet",
    pos: "noun",
    kidMeaning: "Small booklet with information",
    examples: ["She reads the pamphlet.", "The pamphlet has useful tips."],
    emoji: "📄",
    syllables: "pam-phlet",
    distractorGroup: "school",
  },
  {
    word: "firefighter",
    pos: "noun",
    kidMeaning: "Person who puts out fires.",
    examples: ["The firefighter puts out fires.", "She is a brave firefighter."],
    emoji: "🚒",
    syllables: "fire-fight-er",
    distractorGroup: "people",
  },
  {
    word: "paramedic",
    pos: "noun",
    kidMeaning: "Person who helps people at accidents.",
    examples: ["The paramedic helps the hurt person.", "He is a paramedic."],
    emoji: "🚒",
    syllables: "par-a-med-ic",
    distractorGroup: "people",
  },
  {
    word: "umpire",
    pos: "noun",
    kidMeaning: "Person who watches games and makes rules.",
    examples: ["The umpire makes decisions.", "He is an umpire of the game."],
    emoji: "👨",
    syllables: "um-pire",
    distractorGroup: "people",
  },
  {
    word: "spectator",
    pos: "noun",
    kidMeaning: "Person who watches events.",
    examples: ["The spectator claps for the player.", "She is a spectator at the game."],
    emoji: "👀",
    syllables: "spec-ta-tor",
    distractorGroup: "people",
  },
  {
    word: "audience",
    pos: "noun",
    kidMeaning: "People who watch a show.",
    examples: ["The audience claps at the end.", "Large audiences come."],
    emoji: "👥",
    syllables: "au-di-ence",
    distractorGroup: "groups",
  },
  {
    word: "tricycle",
    pos: "noun",
    kidMeaning: "Three-wheel vehicle.",
    examples: ["He rides a tricycle.", "The tricycle has a seat."],
    emoji: "🛺",
    syllables: "tri-cy-cle",
    distractorGroup: "transport",
  },
  {
    word: "yacht",
    pos: "noun",
    kidMeaning: "Fancy boat for fun.",
    examples: ["He sails in a yacht.", "The yacht is beautiful."],
    emoji: "⛵",
    syllables: "yacht",
    distractorGroup: "transport",
  },
  {
    word: "submarine",
    pos: "noun",
    kidMeaning: "Boat that goes under water.",
    examples: ["The submarine goes deep.", "She sees a submarine in the museum."],
    emoji: "🚢",
    syllables: "sub-ma-rine",
    distractorGroup: "transport",
  },
  {
    word: "pedestrian",
    pos: "noun",
    kidMeaning: "Person who walks on the road.",
    examples: ["Pedestrians cross the road.", "He is a pedestrian."],
    emoji: "🚶",
    syllables: "pe-des-tri-an",
    distractorGroup: "people",
  },
  {
    word: "fare",
    pos: "noun",
    kidMeaning: "Money to ride transport.",
    examples: ["She pays the fare for the bus.", "The fare is expensive."],
    emoji: "💰",
    syllables: "fare",
    distractorGroup: "abstract",
  },
  {
    word: "accelerate",
    pos: "verb",
    kidMeaning: "Make a vehicle go faster.",
    examples: ["He accelerates the car.", "The car accelerates quickly."],
    emoji: "⚡",
    syllables: "ac-cel-er-ate",
    distractorGroup: "actions",
  },
  {
    word: "trouser",
    pos: "noun",
    kidMeaning: "Long cloth on the leg.",
    examples: ["He wears trousers.", "The trouser is long."],
    emoji: "👖",
    syllables: "trou-ser",
    distractorGroup: "objects",
  },
  {
    word: "jeans",
    pos: "noun",
    kidMeaning: "Thick cloth trouser.",
    examples: ["She wears jeans.", "The jeans are blue."],
    emoji: "👖",
    syllables: "jeans",
    distractorGroup: "objects",
  },
  {
    word: "skirt",
    pos: "noun",
    kidMeaning: "Cloth on the leg for girls.",
    examples: ["She wears a skirt.", "The skirt is pink."],
    emoji: "👗",
    syllables: "skirt",
    distractorGroup: "objects",
  },
  {
    word: "blouse",
    pos: "noun",
    kidMeaning: "Shirt for girls.",
    examples: ["She wears a blouse.", "The blouse is pretty."],
    emoji: "👚",
    syllables: "blouse",
    distractorGroup: "objects",
  },
  {
    word: "jumper",
    pos: "noun",
    kidMeaning: "Warm cloth for the body.",
    examples: ["She wears a jumper in winter.", "The jumper is warm."],
    emoji: "🧶",
    syllables: "jump-er",
    distractorGroup: "objects",
  },
  {
    word: "cardigan",
    pos: "noun",
    kidMeaning: "Cloth with buttons.",
    examples: ["She wears a cardigan.", "The cardigan is cosy."],
    emoji: "🧥",
    syllables: "car-di-gan",
    distractorGroup: "objects",
  },
  {
    word: "blazer",
    pos: "noun",
    kidMeaning: "Formal jacket.",
    examples: ["He wears a blazer.", "The blazer is smart."],
    emoji: "🧥",
    syllables: "blaz-er",
    distractorGroup: "objects",
  },
  {
    word: "raincoat",
    pos: "noun",
    kidMeaning: "Cloth for rain.",
    examples: ["She wears a raincoat.", "The raincoat is yellow."],
    emoji: "🧥",
    syllables: "rain-coat",
    distractorGroup: "objects",
  },
  {
    word: "overall",
    pos: "noun",
    kidMeaning: "Cloth that covers everything.",
    examples: ["She wears overalls for work.", "The overall is blue."],
    emoji: "🧥",
    syllables: "o-ver-all",
    distractorGroup: "objects",
  },
  {
    word: "apron",
    pos: "noun",
    kidMeaning: "Cloth that protects clothes.",
    examples: ["She wears an apron to cook.", "The apron has a pocket."],
    emoji: "👕",
    syllables: "a-pron",
    distractorGroup: "objects",
  },
  {
    word: "glove",
    pos: "noun",
    kidMeaning: "Cloth that covers the hand.",
    examples: ["She wears gloves in winter.", "The glove is warm."],
    emoji: "🧤",
    syllables: "glove",
    distractorGroup: "objects",
  },
  {
    word: "mitten",
    pos: "noun",
    kidMeaning: "Cloth that covers hand and finger.",
    examples: ["He wears mittens.", "The mitten is soft."],
    emoji: "🧤",
    syllables: "mit-ten",
    distractorGroup: "objects",
  },
  {
    word: "scarf",
    pos: "noun",
    kidMeaning: "Cloth around the neck.",
    examples: ["She wears a scarf.", "The scarf is warm."],
    emoji: "🧣",
    syllables: "scarf",
    distractorGroup: "objects",
  },
  {
    word: "worksheet",
    pos: "noun",
    kidMeaning: "Paper with exercises to do",
    examples: ["She completes the worksheet in class.", "The worksheet has many questions."],
    emoji: "📝",
    syllables: "work-sheet",
    distractorGroup: "school",
  },
  {
    word: "highlighter",
    pos: "noun",
    kidMeaning: "Marker that highlights text",
    examples: ["She highlights key words.", "The highlighter is yellow."],
    emoji: "🖍️",
    syllables: "high-light-er",
    distractorGroup: "school",
  },
  {
    word: "classroom",
    pos: "noun",
    kidMeaning: "Room where students learn",
    examples: ["She learns in the classroom.", "The classroom has desks."],
    emoji: "🏫",
    syllables: "class-room",
    distractorGroup: "school",
  },
  {
    word: "pupil",
    pos: "noun",
    kidMeaning: "Student at school",
    examples: ["The pupil learns quickly.", "She is a good pupil."],
    emoji: "👧",
    syllables: "pu-pil",
    distractorGroup: "school",
  },
  {
    word: "lesson",
    pos: "noun",
    kidMeaning: "Class teaching time",
    examples: ["The lesson is about maths.", "She listens to the lesson."],
    emoji: "📖",
    syllables: "les-son",
    distractorGroup: "school",
  },
  {
    word: "assignment",
    pos: "noun",
    kidMeaning: "Work given to do",
    examples: ["She finishes her assignment.", "The assignment is long."],
    emoji: "📋",
    syllables: "as-sign-ment",
    distractorGroup: "school",
  },
  {
    word: "test",
    pos: "noun",
    kidMeaning: "Check of what you know",
    examples: ["He takes a test tomorrow.", "The test is hard."],
    emoji: "✏️",
    syllables: "test",
    distractorGroup: "school",
  },
  {
    word: "quiz",
    pos: "noun",
    kidMeaning: "Quick test with questions",
    examples: ["They have a quiz Friday.", "The quiz is short."],
    emoji: "❓",
    syllables: "quiz",
    distractorGroup: "school",
  },
  {
    word: "calendar",
    pos: "noun",
    kidMeaning: "Chart showing days and months",
    examples: ["She marks the date on the calendar.", "The calendar hangs on the wall."],
    emoji: "📅",
    syllables: "cal-en-dar",
    distractorGroup: "school",
  },
  {
    word: "medal",
    pos: "noun",
    kidMeaning: "Metal prize for winning",
    examples: ["She wins a gold medal.", "He wears his medal proudly."],
    emoji: "🥇",
    syllables: "med-al",
    distractorGroup: "school",
  },
  {
    word: "trophy",
    pos: "noun",
    kidMeaning: "Prize cup for winning",
    examples: ["She holds the trophy.", "The trophy is shiny."],
    emoji: "🏆",
    syllables: "tro-phy",
    distractorGroup: "school",
  },
  {
    word: "breaktime",
    pos: "noun",
    kidMeaning: "Time to rest between lessons",
    examples: ["Breaktime is at ten o'clock.", "She eats at breaktime."],
    emoji: "⏰",
    syllables: "break-time",
    distractorGroup: "school",
  },
  {
    word: "lunchtime",
    pos: "noun",
    kidMeaning: "Time to eat lunch",
    examples: ["Lunchtime is at noon.", "They eat in the canteen at lunchtime."],
    emoji: "🍽️",
    syllables: "lunch-time",
    distractorGroup: "school",
  },
  {
    word: "semester",
    pos: "noun",
    kidMeaning: "Half of a school year",
    examples: ["The first semester ends soon.", "She works hard each semester."],
    emoji: "📅",
    syllables: "se-mes-ter",
    distractorGroup: "school",
  },
  {
    word: "term",
    pos: "noun",
    kidMeaning: "Period of school year",
    examples: ["The term ends in July.", "There are three terms per year."],
    emoji: "📅",
    syllables: "term",
    distractorGroup: "school",
  },
  {
    word: "report",
    pos: "noun",
    kidMeaning: "Paper with your marks",
    examples: ["He gets a report card.", "The report shows good grades."],
    emoji: "📄",
    syllables: "re-port",
    distractorGroup: "school",
  },
  {
    word: "discipline",
    pos: "noun",
    kidMeaning: "Punishment for bad behaviour",
    examples: ["He faces discipline for bad behaviour.", "Discipline helps learning."],
    emoji: "🚫",
    syllables: "dis-ci-pline",
    distractorGroup: "school",
  },
  {
    word: "bedtime",
    pos: "noun",
    kidMeaning: "Time to go to bed",
    examples: ["Her bedtime is nine o'clock.", "Bedtime is early on school nights."],
    emoji: "🛏️",
    syllables: "bed-time",
    distractorGroup: "home",
  },
  {
    word: "breakfast",
    pos: "noun",
    kidMeaning: "First meal of the day",
    examples: ["She eats breakfast.", "Breakfast is important."],
    emoji: "🍳",
    syllables: "break-fast",
    distractorGroup: "home",
  },
  {
    word: "dinner",
    pos: "noun",
    kidMeaning: "Big meal in evening",
    examples: ["He eats dinner at six.", "Dinner is delicious."],
    emoji: "🍽️",
    syllables: "din-ner",
    distractorGroup: "home",
  },
  {
    word: "supper",
    pos: "noun",
    kidMeaning: "Light meal before bed",
    examples: ["She has supper at eight.", "Supper is quick."],
    emoji: "🍲",
    syllables: "sup-per",
    distractorGroup: "home",
  },
  {
    word: "lunch",
    pos: "noun",
    kidMeaning: "Meal in the middle of day",
    examples: ["He eats lunch at school.", "Lunch is tasty."],
    emoji: "🥪",
    syllables: "lunch",
    distractorGroup: "home",
  },
  {
    word: "recipe",
    pos: "noun",
    kidMeaning: "How to cook food and make meals",
    examples: ["She follows the recipe.", "The recipe has ten steps."],
    emoji: "📖",
    syllables: "rec-i-pe",
    distractorGroup: "home",
  },
  {
    word: "ingredient",
    pos: "noun",
    kidMeaning: "Things you put in food",
    examples: ["Flour is an ingredient.", "She has all the ingredients."],
    emoji: "🥘",
    syllables: "in-gred-i-ent",
    distractorGroup: "home",
  },
  {
    word: "crockery",
    pos: "noun",
    kidMeaning: "Plates and cups",
    examples: ["The crockery is white.", "She washes the crockery."],
    emoji: "🍽️",
    syllables: "crock-er-y",
    distractorGroup: "home",
  },
  {
    word: "dishwasher",
    pos: "noun",
    kidMeaning: "Machine for washing dishes",
    examples: ["She puts dishes in the dishwasher.", "The dishwasher runs at night."],
    emoji: "🍽️",
    syllables: "dish-wash-er",
    distractorGroup: "home",
  },
  {
    word: "pantry",
    pos: "noun",
    kidMeaning: "Small room for storing food",
    examples: ["She looks in the pantry.", "The pantry has flour."],
    emoji: "🥫",
    syllables: "pant-ry",
    distractorGroup: "home",
  },
  {
    word: "cellar",
    pos: "noun",
    kidMeaning: "Room underground in a house",
    examples: ["He stores things in the cellar.", "The cellar is cold."],
    emoji: "🏠",
    syllables: "cel-lar",
    distractorGroup: "home",
  },
  {
    word: "attic",
    pos: "noun",
    kidMeaning: "Room at top of house",
    examples: ["She plays in the attic.", "The attic is dusty."],
    emoji: "🏠",
    syllables: "at-tic",
    distractorGroup: "home",
  },
  {
    word: "hallway",
    pos: "noun",
    kidMeaning: "Passage connecting rooms",
    examples: ["She walks down the hallway.", "The hallway is long."],
    emoji: "🚪",
    syllables: "hall-way",
    distractorGroup: "home",
  },
  {
    word: "lobby",
    pos: "noun",
    kidMeaning: "Entrance hall of building",
    examples: ["They wait in the lobby.", "The lobby is bright."],
    emoji: "🏢",
    syllables: "lob-by",
    distractorGroup: "home",
  },
  {
    word: "furniture",
    pos: "noun",
    kidMeaning: "Things like chairs and tables",
    examples: ["The furniture is wooden.", "She buys new furniture."],
    emoji: "🪑",
    syllables: "fur-ni-ture",
    distractorGroup: "home",
  },
  {
    word: "dresser",
    pos: "noun",
    kidMeaning: "Furniture with drawers",
    examples: ["She puts clothes in the dresser.", "The dresser is tall."],
    emoji: "🪑",
    syllables: "dress-er",
    distractorGroup: "home",
  },
  {
    word: "bookshelf",
    pos: "noun",
    kidMeaning: "Shelf for holding books",
    examples: ["His bookshelf is full.", "She arranges the bookshelf."],
    emoji: "📚",
    syllables: "book-shelf",
    distractorGroup: "home",
  },
  {
    word: "headboard",
    pos: "noun",
    kidMeaning: "Back of a bed",
    examples: ["The headboard is padded.", "She leans on the headboard."],
    emoji: "🛏️",
    syllables: "head-board",
    distractorGroup: "home",
  },
  {
    word: "footboard",
    pos: "noun",
    kidMeaning: "End of a bed",
    examples: ["The footboard is wooden.", "She sits on the footboard."],
    emoji: "🛏️",
    syllables: "foot-board",
    distractorGroup: "home",
  },
  {
    word: "bedframe",
    pos: "noun",
    kidMeaning: "Structure supporting mattress",
    examples: ["The bedframe is metal.", "She makes the bedframe."],
    emoji: "🛏️",
    syllables: "bed-frame",
    distractorGroup: "home",
  },
  {
    word: "duvet",
    pos: "noun",
    kidMeaning: "Thick cover on a bed",
    examples: ["He sleeps under a duvet.", "The duvet is warm."],
    emoji: "🛏️",
    syllables: "du-vet",
    distractorGroup: "home",
  },
  {
    word: "canopy",
    pos: "noun",
    kidMeaning: "Cloth covering top of bed",
    examples: ["The canopy is purple.", "She climbs under the canopy."],
    emoji: "🛏️",
    syllables: "can-o-py",
    distractorGroup: "home",
  },
  {
    word: "playpen",
    pos: "noun",
    kidMeaning: "Enclosed area for baby to play",
    examples: ["She puts the baby in the playpen.", "The playpen is safe."],
    emoji: "👶",
    syllables: "play-pen",
    distractorGroup: "home",
  },
  {
    word: "highchair",
    pos: "noun",
    kidMeaning: "Chair with table for baby",
    examples: ["The baby sits in the highchair.", "The highchair has a tray."],
    emoji: "👶",
    syllables: "high-chair",
    distractorGroup: "home",
  },
  {
    word: "swing",
    pos: "noun",
    kidMeaning: "Hanging seat for fun",
    examples: ["She plays on the swing.", "The swing goes high."],
    emoji: "🛝",
    syllables: "swing",
    distractorGroup: "home",
  },
  {
    word: "seesaw",
    pos: "noun",
    kidMeaning: "Board that goes up and down",
    examples: ["They play on the seesaw.", "The seesaw bounces."],
    emoji: "🪝",
    syllables: "see-saw",
    distractorGroup: "home",
  },
  {
    word: "trampoline",
    pos: "noun",
    kidMeaning: "Canvas that bounces",
    examples: ["He jumps on the trampoline.", "The trampoline is fun."],
    emoji: "🎪",
    syllables: "tram-po-line",
    distractorGroup: "home",
  },
  {
    word: "toolbox",
    pos: "noun",
    kidMeaning: "Container for tools",
    examples: ["He opens the toolbox.", "The toolbox is full."],
    emoji: "🔧",
    syllables: "tool-box",
    distractorGroup: "home",
  },
  {
    word: "hammer",
    pos: "noun",
    kidMeaning: "Tool to hit nails",
    examples: ["He uses a hammer.", "The hammer is heavy."],
    emoji: "🔨",
    syllables: "ham-mer",
    distractorGroup: "home",
  },
  {
    word: "screwdriver",
    pos: "noun",
    kidMeaning: "Tool to turn screws",
    examples: ["She uses a screwdriver.", "The screwdriver is small."],
    emoji: "🔧",
    syllables: "screw-driv-er",
    distractorGroup: "home",
  },
  {
    word: "nail",
    pos: "noun",
    kidMeaning: "Metal pin for fastening",
    examples: ["She hammers the nail.", "The nail is sharp."],
    emoji: "🔨",
    syllables: "nail",
    distractorGroup: "home",
  },
  {
    word: "screw",
    pos: "noun",
    kidMeaning: "Spiral metal fastener",
    examples: ["He turns the screw.", "The screw is tight."],
    emoji: "🔧",
    syllables: "screw",
    distractorGroup: "home",
  },
  {
    word: "bolt",
    pos: "noun",
    kidMeaning: "Metal fastener with nut",
    examples: ["She tightens the bolt.", "The bolt is strong."],
    emoji: "🔧",
    syllables: "bolt",
    distractorGroup: "home",
  },
  {
    word: "nut",
    pos: "noun",
    kidMeaning: "Small metal piece for bolt",
    examples: ["He twists the nut.", "The nut is small."],
    emoji: "🔩",
    syllables: "nut",
    distractorGroup: "home",
  },
  {
    word: "washer",
    pos: "noun",
    kidMeaning: "Machine that washes clothes",
    examples: ["She puts clothes in the washer.", "The washer is clean."],
    emoji: "🧺",
    syllables: "wash-er",
    distractorGroup: "home",
  },
  {
    word: "dryer",
    pos: "noun",
    kidMeaning: "Machine that dries clothes",
    examples: ["He puts clothes in the dryer.", "The dryer is warm."],
    emoji: "🧺",
    syllables: "dry-er",
    distractorGroup: "home",
  },
  {
    word: "clothesline",
    pos: "noun",
    kidMeaning: "Rope for hanging wet clothes",
    examples: ["She hangs clothes on the clothesline.", "The clothesline is full."],
    emoji: "🧺",
    syllables: "clothes-line",
    distractorGroup: "home",
  },
  {
    word: "garment",
    pos: "noun",
    kidMeaning: "Piece of clothing",
    examples: ["The garment is clean.", "She folds the garment."],
    emoji: "👗",
    syllables: "gar-ment",
    distractorGroup: "home",
  },
  {
    word: "outfit",
    pos: "noun",
    kidMeaning: "Set of clothes worn together",
    examples: ["She wears a nice outfit.", "The outfit is colorful."],
    emoji: "👗",
    syllables: "out-fit",
    distractorGroup: "home",
  },
  {
    word: "necktie",
    pos: "noun",
    kidMeaning: "Cloth worn around neck",
    examples: ["He wears a necktie.", "The necktie is striped."],
    emoji: "👔",
    syllables: "neck-tie",
    distractorGroup: "home",
  },
  {
    word: "bowtie",
    pos: "noun",
    kidMeaning: "Formal tie in bow shape",
    examples: ["He wears a bowtie.", "The bowtie is red."],
    emoji: "🎀",
    syllables: "bow-tie",
    distractorGroup: "home",
  },
  {
    word: "shoelace",
    pos: "noun",
    kidMeaning: "String that ties a shoe",
    examples: ["He ties his shoelace.", "The shoelace is long."],
    emoji: "👞",
    syllables: "shoe-lace",
    distractorGroup: "home",
  },
  {
    word: "slipper",
    pos: "noun",
    kidMeaning: "Soft shoe to wear indoors",
    examples: ["She wears slippers at home.", "Slippers are cosy."],
    emoji: "🩴",
    syllables: "slip-per",
    distractorGroup: "home",
  },
  {
    word: "knit",
    pos: "verb",
    kidMeaning: "Make cloth with needles and yarn",
    examples: ["She knits a sweater.", "He knits a scarf."],
    emoji: "🧶",
    syllables: "knit",
    distractorGroup: "hobby",
  },
  {
    word: "embroider",
    pos: "verb",
    kidMeaning: "Sew pictures with thread",
    examples: ["She embroiders a picture.", "He embroiders flowers."],
    emoji: "🧵",
    syllables: "em-broid-er",
    distractorGroup: "hobby",
  },
  {
    word: "weave",
    pos: "verb",
    kidMeaning: "Cross threads to make cloth",
    examples: ["She weaves at the loom.", "He weaves baskets."],
    emoji: "🧶",
    syllables: "weave",
    distractorGroup: "hobby",
  },
  {
    word: "quilt",
    pos: "noun",
    kidMeaning: "Patchwork blanket",
    examples: ["She makes a quilt.", "The quilt is pretty."],
    emoji: "🧣",
    syllables: "quilt",
    distractorGroup: "hobby",
  },
  {
    word: "patchwork",
    pos: "noun",
    kidMeaning: "Cloth made from many pieces",
    examples: ["She does patchwork.", "The patchwork is beautiful."],
    emoji: "🧵",
    syllables: "patch-work",
    distractorGroup: "hobby",
  },
  {
    word: "collage",
    pos: "noun",
    kidMeaning: "Picture made from many pieces",
    examples: ["She makes a collage.", "The collage is colorful."],
    emoji: "🎨",
    syllables: "col-lage",
    distractorGroup: "hobby",
  },
  {
    word: "scrapbook",
    pos: "noun",
    kidMeaning: "Book for saving pictures",
    examples: ["She keeps a scrapbook.", "The scrapbook has memories."],
    emoji: "📖",
    syllables: "scrap-book",
    distractorGroup: "hobby",
  },
  {
    word: "lego",
    pos: "noun",
    kidMeaning: "Plastic bricks for building",
    examples: ["He plays with lego.", "The lego is colorful."],
    emoji: "🧱",
    syllables: "le-go",
    distractorGroup: "hobby",
  },
  {
    word: "dollhouse",
    pos: "noun",
    kidMeaning: "Miniature house for dolls",
    examples: ["She plays with a dollhouse.", "The dollhouse is detailed."],
    emoji: "🏠",
    syllables: "doll-house",
    distractorGroup: "hobby",
  },
  {
    word: "boardgame",
    pos: "noun",
    kidMeaning: "Game played on board",
    examples: ["They play a boardgame.", "The boardgame is fun."],
    emoji: "🎲",
    syllables: "board-game",
    distractorGroup: "hobby",
  },
  {
    word: "dice",
    pos: "noun",
    kidMeaning: "Small cubes with numbers",
    examples: ["She rolls the dice.", "The dice are fair."],
    emoji: "🎲",
    syllables: "dice",
    distractorGroup: "hobby",
  },
  {
    word: "deck",
    pos: "noun",
    kidMeaning: "Set of playing cards",
    examples: ["He has a deck of cards.", "The deck is complete."],
    emoji: "🃏",
    syllables: "deck",
    distractorGroup: "hobby",
  },
  {
    word: "checker",
    pos: "noun",
    kidMeaning: "Game piece in checkers",
    examples: ["She moves a checker.", "The checker is red."],
    emoji: "🔴",
    syllables: "check-er",
    distractorGroup: "hobby",
  },
  {
    word: "dartboard",
    pos: "noun",
    kidMeaning: "Target for throwing darts",
    examples: ["He throws at the dartboard.", "The dartboard is round."],
    emoji: "🎯",
    syllables: "dart-board",
    distractorGroup: "hobby",
  },
  {
    word: "dart",
    pos: "noun",
    kidMeaning: "Pointed thing to throw",
    examples: ["She throws a dart.", "The dart is sharp."],
    emoji: "🎯",
    syllables: "dart",
    distractorGroup: "hobby",
  },
  {
    word: "archery",
    pos: "noun",
    kidMeaning: "Sport of shooting arrows",
    examples: ["He does archery.", "Archery is fun."],
    emoji: "🏹",
    syllables: "arch-er-y",
    distractorGroup: "hobby",
  },
  {
    word: "bowstring",
    pos: "noun",
    kidMeaning: "String on a bow",
    examples: ["She pulls the bowstring.", "The bowstring is tight."],
    emoji: "🏹",
    syllables: "bow-string",
    distractorGroup: "hobby",
  },
  {
    word: "racket",
    pos: "noun",
    kidMeaning: "Bat for hitting ball",
    examples: ["She holds a racket.", "The racket is strong."],
    emoji: "🎾",
    syllables: "rack-et",
    distractorGroup: "hobby",
  },
  {
    word: "paddle",
    pos: "noun",
    kidMeaning: "Short bat for games",
    examples: ["He uses a paddle.", "The paddle is wooden."],
    emoji: "🏸",
    syllables: "pad-dle",
    distractorGroup: "hobby",
  },
  {
    word: "pogo-stick",
    pos: "noun",
    kidMeaning: "Toy to jump on",
    examples: ["She bounces on a pogo-stick.", "The pogo-stick is fun."],
    emoji: "🎪",
    syllables: "po-go-stick",
    distractorGroup: "hobby",
  },
  {
    word: "skates",
    pos: "noun",
    kidMeaning: "Shoes with wheels for sliding.",
    examples: ["She wears skates.", "Skates are fun."],
    emoji: "⛸️",
    syllables: "roll-er-blades",
    distractorGroup: "hobby",
  },
  {
    word: "tent",
    pos: "noun",
    kidMeaning: "Canvas shelter for camping",
    examples: ["They sleep in a tent.", "The tent is waterproof."],
    emoji: "⛺",
    syllables: "tent",
    distractorGroup: "hobby",
  },
  {
    word: "campfire",
    pos: "noun",
    kidMeaning: "Fire for warmth outside",
    examples: ["They sit around the campfire.", "The campfire is warm."],
    emoji: "🔥",
    syllables: "camp-fire",
    distractorGroup: "hobby",
  },
  {
    word: "bedroll",
    pos: "noun",
    kidMeaning: "A soft roll for sleeping outside.",
    examples: ["He sleeps in a bedroll.", "The bedroll is warm."],
    emoji: "🛏️",
    syllables: "sleep-ing-bag",
    distractorGroup: "hobby",
  },
  {
    word: "thermos",
    pos: "noun",
    kidMeaning: "Container to keep drinks hot",
    examples: ["She pours from the thermos.", "The thermos keeps it warm."],
    emoji: "🫖",
    syllables: "ther-mos",
    distractorGroup: "hobby",
  },
  {
    word: "flask",
    pos: "noun",
    kidMeaning: "Container for hot liquid",
    examples: ["He carries a flask.", "The flask is full."],
    emoji: "🫖",
    syllables: "flask",
    distractorGroup: "hobby",
  },
  {
    word: "lantern",
    pos: "noun",
    kidMeaning: "Light you carry outside",
    examples: ["She carries a lantern.", "The lantern glows."],
    emoji: "🏮",
    syllables: "lant-ern",
    distractorGroup: "hobby",
  },
  {
    word: "telescope",
    pos: "noun",
    kidMeaning: "Tool to see stars and planets",
    examples: ["He uses a telescope.", "The telescope is powerful."],
    emoji: "🔭",
    syllables: "tel-e-scope",
    distractorGroup: "hobby",
  },
  {
    word: "microscope",
    pos: "noun",
    kidMeaning: "Tool to see tiny things",
    examples: ["She uses a microscope.", "The microscope is powerful."],
    emoji: "🔬",
    syllables: "mi-cro-scope",
    distractorGroup: "hobby",
  },
  {
    word: "clipboard",
    pos: "noun",
    kidMeaning: "Board with clip to hold paper",
    examples: ["She writes on a clipboard.", "The clipboard holds the papers."],
    emoji: "📋",
    syllables: "clip-board",
    distractorGroup: "school",
  },
  {
    word: "bookcase",
    pos: "noun",
    kidMeaning: "Shelf furniture for books",
    examples: ["She puts books in the bookcase.", "The bookcase is tall."],
    emoji: "📚",
    syllables: "book-case",
    distractorGroup: "home",
  },
  {
    word: "daycare",
    pos: "noun",
    kidMeaning: "Care for young children while parents work.",
    examples: ["She goes to daycare.", "Daycare is fun."],
    emoji: "🏠",
    syllables: "day-care",
    distractorGroup: "school",
  },
  {
    word: "torch",
    pos: "noun",
    kidMeaning: "Light you carry in hand",
    examples: ["He carries a torch.", "The torch is bright."],
    emoji: "🔦",
    syllables: "torch",
    distractorGroup: "home",
  },
];
