import type { Word } from "../words";

/**
 * Band 7 — work, money, media, measurement and civic life.
 * The "wider world" band: jobs and workplaces, buying and selling, news and
 * devices, maths/measuring vocabulary, and how a town is run. Themes are kept
 * clear of bands 1-6 (everyday, people/places, school/home, general, nature,
 * feelings) so words are not taught twice.
 */
export const band7: Word[] = [
  {
    word: "accomplish",
    pos: "verb",
    level: 6,
    kidMeaning: "To finish something you set out to do.",
    examples: ["She worked hard to accomplish her goal.", "They accomplished the task before lunch."],
    emoji: "🏁",
    syllables: "ac-com-plish",
    distractorGroup: "work",
  },
  {
    word: "account",
    pos: "noun",
    level: 5,
    kidMeaning: "A place where a bank keeps your money.",
    examples: ["Mum put the money into her bank account.", "He opened an account at the bank."],
    emoji: "🏦",
    syllables: "ac-count",
    distractorGroup: "money",
  },
  {
    word: "achieve",
    pos: "verb",
    level: 4,
    kidMeaning: "To reach a goal after trying hard.",
    examples: ["She achieved top marks in maths.", "You can achieve a lot with practice."],
    emoji: "🎯",
    syllables: "a-chieve",
    distractorGroup: "work",
  },
  {
    word: "addition",
    pos: "noun",
    level: 5,
    kidMeaning: "Adding numbers to find the total.",
    examples: ["We learnt addition in maths today.", "Addition is easier than division."],
    emoji: "➕",
    syllables: "ad-di-tion",
    distractorGroup: "maths",
  },
  {
    word: "address",
    pos: "noun",
    level: 2,
    kidMeaning: "The place where a person lives.",
    examples: ["Write your address on the envelope.", "She wrote the wrong address on the parcel."],
    emoji: "📮",
    syllables: "ad-dress",
    distractorGroup: "post",
  },
  {
    word: "advertisement",
    pos: "noun",
    level: 6,
    kidMeaning: "A notice that asks you to buy something.",
    examples: ["The advertisement showed a shiny new toy.", "She saw an advertisement for cheap shoes."],
    emoji: "📢",
    syllables: "ad-ver-tise-ment",
    distractorGroup: "media",
  },
  {
    word: "advice",
    pos: "noun",
    level: 3,
    kidMeaning: "Helpful words about what you should do.",
    examples: ["Dad gave me good advice about school.", "She asked her teacher for advice."],
    emoji: "💬",
    syllables: "ad-vice",
    confusedWith: "advise",
    spellingTip: "advice with c is the thing you get; advise with s is the doing word",
    distractorGroup: "talking",
  },
  {
    word: "agenda",
    pos: "noun",
    level: 5,
    kidMeaning: "A list of things to talk about.",
    examples: ["Sports day was first on the agenda.", "She wrote the agenda for the meeting."],
    emoji: "📋",
    syllables: "a-gen-da",
    distractorGroup: "work",
  },
  {
    word: "agent",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who does jobs for others.",
    examples: ["The travel agent booked our flight.", "An agent sold the house for them."],
    emoji: "🕴",
    syllables: "a-gent",
    distractorGroup: "jobs",
  },
  {
    word: "agreement",
    pos: "noun",
    level: 5,
    kidMeaning: "When people say yes to the same plan.",
    examples: ["They shook hands to show their agreement.", "The two sides reached an agreement."],
    emoji: "🤝",
    syllables: "a-gree-ment",
    distractorGroup: "talking",
  },
  {
    word: "aisle",
    pos: "noun",
    level: 4,
    kidMeaning: "A path between rows of shelves or seats.",
    examples: ["The rice is in the third aisle.", "She walked down the aisle to her seat."],
    emoji: "🛒",
    syllables: "aisle",
    spellingTip: "silent s in ai-sle",
    distractorGroup: "shopping",
  },
  {
    word: "album",
    pos: "noun",
    level: 4,
    kidMeaning: "A book or set for photos or songs.",
    examples: ["She put the photos in an album.", "His new album has ten songs."],
    emoji: "📔",
    syllables: "al-bum",
    distractorGroup: "media",
  },
  {
    word: "alert",
    pos: "adjective",
    level: 4,
    kidMeaning: "Awake and watching very closely.",
    examples: ["The guard stayed alert all night.", "A good driver is alert on the road."],
    emoji: "👀",
    syllables: "a-lert",
    distractorGroup: "qualities",
  },
  {
    word: "ambulance",
    pos: "noun",
    level: 4,
    kidMeaning: "A van that rushes sick people to hospital.",
    examples: ["The ambulance raced to the accident.", "An ambulance took her to hospital."],
    emoji: "🚑",
    syllables: "am-bu-lance",
    distractorGroup: "emergency",
  },
  {
    word: "analyse",
    pos: "verb",
    level: 6,
    kidMeaning: "To look at something bit by bit.",
    examples: ["Scientists analyse the water for germs.", "We analysed our test results in class."],
    emoji: "🔬",
    syllables: "an-a-lyse",
    spellingTip: "British ending is -yse, not -yze",
    distractorGroup: "thinking",
  },
  {
    word: "angle",
    pos: "noun",
    level: 4,
    kidMeaning: "The corner where two lines meet.",
    examples: ["Measure the angle with a protractor.", "A square has four equal angles."],
    emoji: "📐",
    syllables: "an-gle",
    distractorGroup: "maths",
  },
  {
    word: "announcement",
    pos: "noun",
    level: 6,
    kidMeaning: "A message that tells everyone some news.",
    examples: ["The teacher made an announcement about the trip.", "An announcement said the bus was late."],
    emoji: "📣",
    syllables: "an-nounce-ment",
    distractorGroup: "media",
  },
  {
    word: "annual",
    pos: "adjective",
    level: 5,
    kidMeaning: "Happening one time in each year.",
    examples: ["The annual concert is in November.", "Sports day is an annual event."],
    emoji: "📅",
    syllables: "an-nu-al",
    distractorGroup: "time",
  },
  {
    word: "app",
    pos: "noun",
    level: 4,
    kidMeaning: "A small tool you tap on a phone.",
    examples: ["She opened the maths app on the tablet.", "This app helps you learn new words."],
    emoji: "📱",
    syllables: "app",
    distractorGroup: "technology",
  },
  {
    word: "application",
    pos: "noun",
    level: 6,
    kidMeaning: "A form asking to join or get something.",
    examples: ["Dad filled in an application for a new job.", "Her application to the club was accepted."],
    emoji: "📝",
    syllables: "ap-pli-ca-tion",
    distractorGroup: "work",
  },
  {
    word: "apprentice",
    pos: "noun",
    level: 6,
    kidMeaning: "A young worker learning a trade.",
    examples: ["The apprentice watched the carpenter closely.", "He works as an apprentice at the garage."],
    emoji: "🔨",
    syllables: "ap-pren-tice",
    distractorGroup: "jobs",
  },
  {
    word: "approve",
    pos: "verb",
    level: 5,
    kidMeaning: "To say that something is good enough.",
    examples: ["The teacher approved our plan.", "Mum approves of my new friends."],
    emoji: "👍",
    syllables: "ap-prove",
    distractorGroup: "thinking",
  },
  {
    word: "approximate",
    pos: "adjective",
    level: 6,
    kidMeaning: "Close to right, but not exact.",
    examples: ["The approximate price is thirty dollars.", "She gave an approximate answer."],
    emoji: "🔢",
    syllables: "ap-prox-i-mate",
    distractorGroup: "maths",
  },
  {
    word: "argument",
    pos: "noun",
    level: 5,
    kidMeaning: "An angry talk between people who disagree.",
    examples: ["They had an argument about the game.", "The argument ended with a sorry."],
    emoji: "😠",
    syllables: "ar-gu-ment",
    distractorGroup: "talking",
  },
  {
    word: "article",
    pos: "noun",
    level: 5,
    kidMeaning: "A piece of writing in a paper.",
    examples: ["She enjoyed an article about pandas.", "The article explained why bees matter."],
    emoji: "📰",
    syllables: "ar-ti-cle",
    distractorGroup: "media",
  },
  {
    word: "assemble",
    pos: "verb",
    level: 6,
    kidMeaning: "To put the parts together.",
    examples: ["Dad assembled the new shelf.", "We assemble in the hall each morning."],
    emoji: "🔧",
    syllables: "as-sem-ble",
    distractorGroup: "making",
  },
  {
    word: "assist",
    pos: "verb",
    level: 4,
    kidMeaning: "To help someone with a job.",
    examples: ["She assisted the teacher with the books.", "A nurse assists the doctor."],
    emoji: "🙌",
    syllables: "as-sist",
    distractorGroup: "work",
  },
  {
    word: "association",
    pos: "noun",
    level: 6,
    kidMeaning: "A group of people who share a hobby.",
    examples: ["He joined the football association.", "The association meets every month."],
    emoji: "👥",
    syllables: "as-so-ci-a-tion",
    distractorGroup: "community",
  },
  {
    word: "assume",
    pos: "verb",
    level: 4,
    kidMeaning: "To think it is true without checking.",
    examples: ["Do not assume the shop is open.", "She assumed the bus would be late."],
    emoji: "🤔",
    syllables: "as-sume",
    distractorGroup: "thinking",
  },
  {
    word: "auction",
    pos: "noun",
    level: 5,
    kidMeaning: "A sale where the highest offer wins.",
    examples: ["The old bike was sold at an auction.", "They raised money with an auction."],
    emoji: "🔨",
    syllables: "auc-tion",
    distractorGroup: "money",
  },
  {
    word: "audio",
    pos: "noun",
    level: 5,
    kidMeaning: "Sound that comes out of a device.",
    examples: ["The audio was too soft to hear.", "Turn up the audio on the video."],
    emoji: "🔊",
    syllables: "au-di-o",
    distractorGroup: "technology",
  },
  {
    word: "average",
    pos: "noun",
    level: 5,
    kidMeaning: "The middle amount when you share out.",
    examples: ["The average score was sixty marks.", "She reads an average of two books weekly."],
    emoji: "📊",
    syllables: "av-er-age",
    distractorGroup: "maths",
  },
  {
    word: "banknote",
    pos: "noun",
    level: 3,
    kidMeaning: "Paper money that you spend in shops.",
    examples: ["He folded the banknote into his wallet.", "A fifty-dollar banknote fell on the floor."],
    emoji: "💵",
    syllables: "bank-note",
    distractorGroup: "money",
  },
  {
    word: "barber",
    pos: "noun",
    level: 5,
    kidMeaning: "A person whose job is cutting hair.",
    examples: ["The barber cut my hair very short.", "Dad goes to the barber each month."],
    emoji: "💈",
    syllables: "bar-ber",
    distractorGroup: "jobs",
  },
  {
    word: "basket",
    pos: "noun",
    level: 4,
    kidMeaning: "A container with a handle for carrying.",
    examples: ["She put the fruit in a basket.", "His shopping basket was full."],
    emoji: "🧺",
    syllables: "bas-ket",
    distractorGroup: "shopping",
  },
  {
    word: "battery",
    pos: "noun",
    level: 5,
    kidMeaning: "A part that stores power for a device.",
    examples: ["The battery in my torch is flat.", "Charge the battery before the trip."],
    emoji: "🔋",
    syllables: "bat-ter-y",
    distractorGroup: "technology",
  },
  {
    word: "blade",
    pos: "noun",
    level: 3,
    kidMeaning: "The sharp, flat part that cuts.",
    examples: ["The blade of the knife was shiny.", "Be careful, because the blade is sharp."],
    emoji: "🔪",
    syllables: "blade",
    distractorGroup: "tools",
  },
  {
    word: "blog",
    pos: "noun",
    level: 5,
    kidMeaning: "A diary that people read online.",
    examples: ["She writes a blog about cooking.", "His blog has photos of his trips."],
    emoji: "💻",
    syllables: "blog",
    distractorGroup: "media",
  },
  {
    word: "broadcast",
    pos: "verb",
    level: 5,
    kidMeaning: "To send a show to many people.",
    examples: ["The match was broadcast on television.", "They broadcast the news at six."],
    emoji: "📡",
    syllables: "broad-cast",
    distractorGroup: "media",
  },
  {
    word: "brochure",
    pos: "noun",
    level: 6,
    kidMeaning: "A thin book that shows what is sold.",
    examples: ["The travel brochure showed sunny beaches.", "She kept a brochure about the museum."],
    emoji: "📑",
    syllables: "bro-chure",
    spellingTip: "-chure sounds like 'sher'",
    distractorGroup: "media",
  },
  {
    word: "browse",
    pos: "verb",
    level: 6,
    kidMeaning: "To look through things without hurrying.",
    examples: ["We browsed the shelves in the bookshop.", "He likes to browse for new games."],
    emoji: "🔎",
    syllables: "browse",
    distractorGroup: "shopping",
  },
  {
    word: "button",
    pos: "noun",
    level: 3,
    kidMeaning: "A small part you press or do up.",
    examples: ["He pressed the button to call the lift.", "A button fell off my school shirt."],
    emoji: "🔘",
    syllables: "but-ton",
    distractorGroup: "technology",
  },
  {
    word: "cable",
    pos: "noun",
    level: 4,
    kidMeaning: "A thick wire that carries power.",
    examples: ["The cable joins the screen to the laptop.", "A cable ran under the road."],
    emoji: "🔌",
    syllables: "ca-ble",
    distractorGroup: "technology",
  },
  {
    word: "calculator",
    pos: "noun",
    level: 6,
    kidMeaning: "A small machine that works out sums.",
    examples: ["She checked her answer on a calculator.", "The calculator showed the total at once."],
    emoji: "🧮",
    syllables: "cal-cu-la-tor",
    distractorGroup: "maths",
  },
  {
    word: "campaign",
    pos: "noun",
    level: 4,
    kidMeaning: "A plan of actions to reach one goal.",
    examples: ["The school ran a campaign to save water.", "Their campaign asked people to recycle."],
    emoji: "📣",
    syllables: "cam-paign",
    spellingTip: "silent g in cam-paign",
    distractorGroup: "community",
  },
  {
    word: "capacity",
    pos: "noun",
    level: 6,
    kidMeaning: "How much a thing can hold.",
    examples: ["The bottle has a capacity of one litre.", "The hall was filled to capacity."],
    emoji: "🥤",
    syllables: "ca-pac-i-ty",
    distractorGroup: "measuring",
  },
  {
    word: "caption",
    pos: "noun",
    level: 6,
    kidMeaning: "The words printed under a picture.",
    examples: ["The caption told us where the photo was taken.", "She wrote a funny caption for the drawing."],
    emoji: "🖼",
    syllables: "cap-tion",
    distractorGroup: "media",
  },
  {
    word: "career",
    pos: "noun",
    level: 5,
    kidMeaning: "The kind of work you do for years.",
    examples: ["She wants a career as a vet.", "His career in nursing lasted thirty years."],
    emoji: "💼",
    syllables: "ca-reer",
    distractorGroup: "work",
  },
  {
    word: "certificate",
    pos: "noun",
    level: 6,
    kidMeaning: "A paper that shows what you did.",
    examples: ["She won a certificate for good reading.", "The swimming certificate hangs on his wall."],
    emoji: "🏅",
    syllables: "cer-tif-i-cate",
    distractorGroup: "school",
  },
  {
    word: "championship",
    pos: "noun",
    level: 6,
    kidMeaning: "A big contest to find the best team.",
    examples: ["Our school won the netball championship.", "The championship is held every June."],
    emoji: "🏆",
    syllables: "cham-pi-on-ship",
    distractorGroup: "sport",
  },
  {
    word: "charger",
    pos: "noun",
    level: 6,
    kidMeaning: "A lead that fills a battery again.",
    examples: ["I left my charger at my cousin's house.", "Plug the charger into the wall."],
    emoji: "🔌",
    syllables: "char-ger",
    distractorGroup: "technology",
  },
  {
    word: "cheque",
    pos: "noun",
    level: 4,
    kidMeaning: "A slip of paper that pays money.",
    examples: ["Dad wrote a cheque for the school fees.", "The cheque was posted to the shop."],
    emoji: "🧾",
    syllables: "cheque",
    spellingTip: "British spelling ends in -que",
    distractorGroup: "money",
  },
  {
    word: "citizen",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who belongs to a country.",
    examples: ["Every citizen can vote when grown up.", "She became a citizen of Singapore."],
    emoji: "🪪",
    syllables: "cit-i-zen",
    distractorGroup: "civic",
  },
  {
    word: "claim",
    pos: "verb",
    level: 5,
    kidMeaning: "To say something is true or yours.",
    examples: ["He claimed that he had finished first.", "She went to claim her lost bag."],
    emoji: "🙋",
    syllables: "claim",
    distractorGroup: "talking",
  },
  {
    word: "column",
    pos: "noun",
    level: 4,
    kidMeaning: "A line of things going down.",
    examples: ["Add up the numbers in this column.", "The column of names filled the page."],
    emoji: "📊",
    syllables: "col-umn",
    spellingTip: "silent n at the end of col-umn",
    distractorGroup: "maths",
  },
  {
    word: "comparison",
    pos: "noun",
    level: 6,
    kidMeaning: "Looking at how two things differ.",
    examples: ["We made a comparison of the two books.", "The comparison showed the red car was faster."],
    emoji: "⚖",
    syllables: "com-par-i-son",
    distractorGroup: "thinking",
  },
  {
    word: "competitor",
    pos: "noun",
    level: 6,
    kidMeaning: "A person trying to win against you.",
    examples: ["Each competitor wore a number.", "The last competitor crossed the line."],
    emoji: "🏃",
    syllables: "com-pet-i-tor",
    distractorGroup: "sport",
  },
  {
    word: "conclude",
    pos: "verb",
    level: 6,
    kidMeaning: "To decide after looking at the facts.",
    examples: ["We concluded that the plant needed sun.", "She concluded her talk with a joke."],
    emoji: "🧠",
    syllables: "con-clude",
    distractorGroup: "thinking",
  },
  {
    word: "confidence",
    pos: "noun",
    level: 5,
    kidMeaning: "The feeling that you can do it.",
    examples: ["Practice gave her confidence in maths.", "He spoke with confidence in front of the class."],
    emoji: "😎",
    syllables: "con-fi-dence",
    distractorGroup: "qualities",
  },
  {
    word: "consequence",
    pos: "noun",
    level: 6,
    kidMeaning: "What happens because of what you did.",
    examples: ["Being late had a consequence: he missed the bus.", "One consequence of rain is muddy shoes."],
    emoji: "➡",
    syllables: "con-se-quence",
    distractorGroup: "thinking",
  },
  {
    word: "construct",
    pos: "verb",
    level: 6,
    kidMeaning: "To build something from many parts.",
    examples: ["They constructed a bridge over the canal.", "We construct model houses in art class."],
    emoji: "🏗",
    syllables: "con-struct",
    distractorGroup: "making",
  },
  {
    word: "contrast",
    pos: "noun",
    level: 6,
    kidMeaning: "A clear difference between two things.",
    examples: ["There is a contrast between town and farm.", "The contrast in colour makes the sign clear."],
    emoji: "🎨",
    syllables: "con-trast",
    distractorGroup: "thinking",
  },
  {
    word: "council",
    pos: "noun",
    level: 4,
    kidMeaning: "A group chosen to run a town.",
    examples: ["The council fixed the broken street lamp.", "She spoke to the town council about litter."],
    emoji: "🏛",
    syllables: "coun-cil",
    distractorGroup: "civic",
  },
  {
    word: "crew",
    pos: "noun",
    level: 2,
    kidMeaning: "A team who work on a ship.",
    examples: ["The crew waved from the deck.", "A crew of six sailed the boat."],
    emoji: "⛵",
    syllables: "crew",
    distractorGroup: "work",
  },
  {
    word: "cube",
    pos: "noun",
    level: 4,
    kidMeaning: "A solid shape with six square sides.",
    examples: ["He dropped an ice cube into the glass.", "The box is shaped like a cube."],
    emoji: "🧊",
    syllables: "cube",
    distractorGroup: "maths",
  },
  {
    word: "currency",
    pos: "noun",
    level: 6,
    kidMeaning: "The kind of money a country uses.",
    examples: ["The currency in Japan is the yen.", "We changed our currency at the airport."],
    emoji: "💱",
    syllables: "cur-ren-cy",
    distractorGroup: "money",
  },
  {
    word: "curve",
    pos: "noun",
    level: 4,
    kidMeaning: "A line that bends smoothly.",
    examples: ["The road makes a wide curve here.", "She drew a curve under the words."],
    emoji: "➰",
    syllables: "curve",
    distractorGroup: "maths",
  },
  {
    word: "custom",
    pos: "noun",
    level: 5,
    kidMeaning: "Something people always do here.",
    examples: ["It is a custom to give red packets.", "The custom of bowing shows respect."],
    emoji: "🎎",
    syllables: "cus-tom",
    distractorGroup: "community",
  },
  {
    word: "cylinder",
    pos: "noun",
    level: 6,
    kidMeaning: "A shape that looks like a round tin.",
    examples: ["A drink can is a cylinder.", "She drew a cylinder in her maths book."],
    emoji: "🥫",
    syllables: "cyl-in-der",
    distractorGroup: "maths",
  },
  {
    word: "debt",
    pos: "noun",
    level: 5,
    kidMeaning: "Money that you must pay back.",
    examples: ["He paid off his debt to his brother.", "The shop had a large debt."],
    emoji: "💸",
    syllables: "debt",
    spellingTip: "silent b in de-bt",
    distractorGroup: "money",
  },
  {
    word: "decimal",
    pos: "noun",
    level: 6,
    kidMeaning: "A number with a dot in it.",
    examples: ["Write one half as the decimal 0.5.", "We learnt about decimal points today."],
    emoji: "🔢",
    syllables: "dec-i-mal",
    distractorGroup: "maths",
  },
  {
    word: "define",
    pos: "verb",
    level: 5,
    kidMeaning: "To say what a word means.",
    examples: ["Can you define the word 'brave'?", "The teacher defined each new word."],
    emoji: "📖",
    syllables: "de-fine",
    distractorGroup: "thinking",
  },
  {
    word: "delivery",
    pos: "noun",
    level: 5,
    kidMeaning: "Bringing goods to someone's door.",
    examples: ["The delivery came before lunch.", "We waited for the delivery of the new bed."],
    emoji: "📦",
    syllables: "de-liv-er-y",
    distractorGroup: "shopping",
  },
  {
    word: "deposit",
    pos: "noun",
    level: 6,
    kidMeaning: "Money paid now to keep something.",
    examples: ["They paid a deposit for the hall.", "The deposit was ten dollars."],
    emoji: "💰",
    syllables: "de-pos-it",
    distractorGroup: "money",
  },
  {
    word: "depot",
    pos: "noun",
    level: 5,
    kidMeaning: "A place where buses or goods are kept.",
    examples: ["The buses sleep at the depot at night.", "Lorries load boxes at the depot."],
    emoji: "🚌",
    syllables: "de-pot",
    spellingTip: "the t is silent: 'dep-oh'",
    distractorGroup: "work",
  },
  {
    word: "design",
    pos: "noun",
    level: 3,
    kidMeaning: "A plan or drawing of how to make it.",
    examples: ["Her design for the poster won.", "The design of the chair looks clever."],
    emoji: "✏",
    syllables: "de-sign",
    spellingTip: "silent g in de-sign",
    distractorGroup: "making",
  },
  {
    word: "designer",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who plans how things look.",
    examples: ["The designer chose bright blue for the kit.", "She hopes to be a game designer."],
    emoji: "🎨",
    syllables: "de-sign-er",
    distractorGroup: "jobs",
  },
  {
    word: "detective",
    pos: "noun",
    level: 3,
    kidMeaning: "A person who works out who did it.",
    examples: ["The detective found a muddy footprint.", "A detective asked the neighbours questions."],
    emoji: "🕵",
    syllables: "de-tec-tive",
    distractorGroup: "jobs",
  },
  {
    word: "develop",
    pos: "verb",
    level: 5,
    kidMeaning: "To grow or get better slowly.",
    examples: ["Plants develop roots before leaves.", "She developed a love of reading."],
    emoji: "🌱",
    syllables: "de-vel-op",
    distractorGroup: "change",
  },
  {
    word: "device",
    pos: "noun",
    level: 3,
    kidMeaning: "A tool or machine made for one job.",
    examples: ["A phone is a handy device.", "This device measures how hot it is."],
    emoji: "📲",
    syllables: "de-vice",
    distractorGroup: "technology",
  },
  {
    word: "diagonal",
    pos: "adjective",
    level: 6,
    kidMeaning: "Going slanted from corner to corner.",
    examples: ["She drew a diagonal line across the square.", "The stripes on his tie are diagonal."],
    emoji: "📐",
    syllables: "di-ag-o-nal",
    distractorGroup: "maths",
  },
  {
    word: "diagram",
    pos: "noun",
    level: 6,
    kidMeaning: "A simple drawing that explains something.",
    examples: ["The diagram showed the parts of a flower.", "Copy the diagram into your book."],
    emoji: "📈",
    syllables: "di-a-gram",
    distractorGroup: "school",
  },
  {
    word: "digit",
    pos: "noun",
    level: 6,
    kidMeaning: "Any one of the numbers from 0 to 9.",
    examples: ["The number 47 has two digits.", "Write the last digit of your phone number."],
    emoji: "🔢",
    syllables: "dig-it",
    distractorGroup: "maths",
  },
  {
    word: "digital",
    pos: "adjective",
    level: 6,
    kidMeaning: "Shown in numbers, or done by computer.",
    examples: ["A digital clock shows the time in numbers.", "She keeps her photos in a digital album."],
    emoji: "🖥",
    syllables: "dig-i-tal",
    distractorGroup: "technology",
  },
  {
    word: "discuss",
    pos: "verb",
    level: 3,
    kidMeaning: "To talk about something with others.",
    examples: ["We discussed the story in class.", "Let us discuss where to go on Sunday."],
    emoji: "🗣",
    syllables: "dis-cuss",
    distractorGroup: "talking",
  },
  {
    word: "distribute",
    pos: "verb",
    level: 6,
    kidMeaning: "To give things out to many people.",
    examples: ["She distributed the books to each group.", "Helpers distribute food to the families."],
    emoji: "🤲",
    syllables: "dis-trib-ute",
    distractorGroup: "work",
  },
  {
    word: "division",
    pos: "noun",
    level: 5,
    kidMeaning: "Sharing a number into equal groups.",
    examples: ["We did division sums all morning.", "Division is the opposite of times."],
    emoji: "➗",
    syllables: "di-vi-sion",
    distractorGroup: "maths",
  },
  {
    word: "document",
    pos: "noun",
    level: 5,
    kidMeaning: "A paper or file with facts on it.",
    examples: ["Dad signed the document for the bank.", "She saved the document on her laptop."],
    emoji: "📄",
    syllables: "doc-u-ment",
    distractorGroup: "work",
  },
  {
    word: "donation",
    pos: "noun",
    level: 6,
    kidMeaning: "Money or goods given to help others.",
    examples: ["Our class made a donation to the shelter.", "Every donation buys food for a family."],
    emoji: "🎁",
    syllables: "do-na-tion",
    distractorGroup: "community",
  },
  {
    word: "download",
    pos: "verb",
    level: 5,
    kidMeaning: "To pull a file onto your device.",
    examples: ["She downloaded the song for the concert.", "You can download the book tonight."],
    emoji: "⬇",
    syllables: "down-load",
    distractorGroup: "technology",
  },
  {
    word: "dozen",
    pos: "noun",
    level: 3,
    kidMeaning: "A group of twelve things.",
    examples: ["Mum bought a dozen eggs.", "He ate half a dozen biscuits."],
    emoji: "🥚",
    syllables: "doz-en",
    distractorGroup: "measuring",
  },
  {
    word: "duration",
    pos: "noun",
    level: 6,
    kidMeaning: "How long something goes on for.",
    examples: ["The duration of the film was two hours.", "Sit still for the duration of the test."],
    emoji: "⏳",
    syllables: "du-ra-tion",
    distractorGroup: "time",
  },
  {
    word: "earnings",
    pos: "noun",
    level: 6,
    kidMeaning: "The money you get for working.",
    examples: ["He saved his earnings from the stall.", "Her earnings paid for the trip."],
    emoji: "💵",
    syllables: "earn-ings",
    distractorGroup: "money",
  },
  {
    word: "edition",
    pos: "noun",
    level: 6,
    kidMeaning: "One printing of a book or paper.",
    examples: ["The new edition has extra pictures.", "She keeps the first edition on her shelf."],
    emoji: "📚",
    syllables: "e-di-tion",
    distractorGroup: "media",
  },
  {
    word: "editor",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who checks and fixes writing.",
    examples: ["The editor found three spelling mistakes.", "She wrote to the editor of the paper."],
    emoji: "✏",
    syllables: "ed-i-tor",
    distractorGroup: "jobs",
  },
  {
    word: "election",
    pos: "noun",
    level: 5,
    kidMeaning: "A time when people vote to choose.",
    examples: ["The class held an election for monitor.", "He won the election by two votes."],
    emoji: "🗳",
    syllables: "e-lec-tion",
    distractorGroup: "civic",
  },
  {
    word: "email",
    pos: "noun",
    level: 4,
    kidMeaning: "A letter you send by computer.",
    examples: ["Mum sent an email to my teacher.", "He opened the email on his phone."],
    emoji: "📧",
    syllables: "e-mail",
    distractorGroup: "technology",
  },
  {
    word: "emergency",
    pos: "noun",
    level: 5,
    kidMeaning: "A sudden problem that needs help now.",
    examples: ["Call for help in an emergency.", "The fire was a real emergency."],
    emoji: "🚨",
    syllables: "e-mer-gen-cy",
    distractorGroup: "emergency",
  },
  {
    word: "employ",
    pos: "verb",
    level: 5,
    kidMeaning: "To pay someone to do work.",
    examples: ["The bakery employs six people.", "They employed a cleaner for the office."],
    emoji: "💼",
    syllables: "em-ploy",
    distractorGroup: "work",
  },
  {
    word: "employer",
    pos: "noun",
    level: 6,
    kidMeaning: "The person who pays you to work.",
    examples: ["Her employer gave her a day off.", "The employer thanked all the staff."],
    emoji: "👔",
    syllables: "em-ploy-er",
    distractorGroup: "work",
  },
  {
    word: "employment",
    pos: "noun",
    level: 6,
    kidMeaning: "Having a job that pays you.",
    examples: ["He found employment at the bakery.", "Employment helps a family pay bills."],
    emoji: "🏢",
    syllables: "em-ploy-ment",
    distractorGroup: "work",
  },
  {
    word: "equation",
    pos: "noun",
    level: 6,
    kidMeaning: "A maths sentence with an equals sign.",
    examples: ["Solve the equation 5 + x = 9.", "She wrote the equation on the board."],
    emoji: "🟰",
    syllables: "e-qua-tion",
    distractorGroup: "maths",
  },
  {
    word: "equipment",
    pos: "noun",
    level: 4,
    kidMeaning: "The tools you need for a job.",
    examples: ["The camping equipment filled the boot.", "Sports equipment is kept in the store room."],
    emoji: "🧰",
    syllables: "e-quip-ment",
    distractorGroup: "tools",
  },
  {
    word: "era",
    pos: "noun",
    level: 4,
    kidMeaning: "A long period of time in history.",
    examples: ["Dinosaurs lived in an era long ago.", "That song is from another era."],
    emoji: "🏺",
    syllables: "e-ra",
    distractorGroup: "time",
  },
  {
    word: "error",
    pos: "noun",
    level: 4,
    kidMeaning: "A mistake in what you did.",
    examples: ["There was one error in her sums.", "The error made the answer wrong."],
    emoji: "❌",
    syllables: "er-ror",
    distractorGroup: "school",
  },
  {
    word: "escalator",
    pos: "noun",
    level: 6,
    kidMeaning: "Moving stairs that carry you up.",
    examples: ["We rode the escalator to the top floor.", "Hold the rail on the escalator."],
    emoji: "🛗",
    syllables: "es-ca-la-tor",
    distractorGroup: "places",
  },
  {
    word: "estimate",
    pos: "verb",
    level: 6,
    kidMeaning: "To guess a number in a careful way.",
    examples: ["Estimate how many sweets are in the jar.", "She estimated the trip would take an hour."],
    emoji: "🤔",
    syllables: "es-ti-mate",
    distractorGroup: "maths",
  },
  {
    word: "evidence",
    pos: "noun",
    level: 5,
    kidMeaning: "Facts that show something is true.",
    examples: ["Muddy prints were evidence of a fox.", "She had no evidence for her claim."],
    emoji: "🔍",
    syllables: "ev-i-dence",
    distractorGroup: "thinking",
  },
  {
    word: "examine",
    pos: "verb",
    level: 6,
    kidMeaning: "To look at something very closely.",
    examples: ["The vet examined the puppy's paw.", "We examine leaves under a lens."],
    emoji: "🔬",
    syllables: "ex-am-ine",
    distractorGroup: "thinking",
  },
  {
    word: "exit",
    pos: "noun",
    level: 3,
    kidMeaning: "The way out of a place.",
    examples: ["The exit is beside the lift.", "A green sign marks the fire exit."],
    emoji: "🚪",
    syllables: "ex-it",
    distractorGroup: "places",
  },
  {
    word: "expense",
    pos: "noun",
    level: 5,
    kidMeaning: "Money that you have to spend.",
    examples: ["Petrol is a big expense for drivers.", "The trip was worth the expense."],
    emoji: "💸",
    syllables: "ex-pense",
    distractorGroup: "money",
  },
  {
    word: "experienced",
    pos: "adjective",
    level: 5,
    kidMeaning: "Having done a thing many times before.",
    examples: ["An experienced nurse helped the new one.", "She is an experienced swimmer."],
    emoji: "🎖",
    syllables: "ex-pe-ri-enced",
    distractorGroup: "qualities",
  },
  {
    word: "expert",
    pos: "noun",
    level: 3,
    kidMeaning: "A person who knows a subject well.",
    examples: ["An expert on bees spoke to our class.", "She is an expert at chess."],
    emoji: "🧑‍🏫",
    syllables: "ex-pert",
    distractorGroup: "jobs",
  },
  {
    word: "expertise",
    pos: "noun",
    level: 6,
    kidMeaning: "Deep skill that comes from practice.",
    examples: ["His expertise with wood built the shed.", "We need her expertise in maths."],
    emoji: "🛠",
    syllables: "ex-per-tise",
    distractorGroup: "work",
  },
  {
    word: "export",
    pos: "verb",
    level: 6,
    kidMeaning: "To sell goods to another country.",
    examples: ["Our country exports ships and chips.", "They export fruit by aeroplane."],
    emoji: "🚢",
    syllables: "ex-port",
    distractorGroup: "trade",
  },
  {
    word: "express",
    pos: "verb",
    level: 4,
    kidMeaning: "To show what you think or feel.",
    examples: ["She expressed her thanks in a card.", "Paint lets him express his feelings."],
    emoji: "🗨",
    syllables: "ex-press",
    distractorGroup: "talking",
  },
  {
    word: "extend",
    pos: "verb",
    level: 5,
    kidMeaning: "To make something longer or bigger.",
    examples: ["They extended the school hall.", "The teacher extended our time by five minutes."],
    emoji: "📏",
    syllables: "ex-tend",
    distractorGroup: "change",
  },
  {
    word: "factor",
    pos: "noun",
    level: 5,
    kidMeaning: "One thing that helps cause a result.",
    examples: ["Rain was a factor in the wet pitch.", "Sleep is one factor in doing well."],
    emoji: "🧩",
    syllables: "fac-tor",
    distractorGroup: "thinking",
  },
  {
    word: "fee",
    pos: "noun",
    level: 4,
    kidMeaning: "Money you pay to use something.",
    examples: ["The club fee is five dollars a month.", "Dad paid the fee for my swimming lessons."],
    emoji: "💲",
    syllables: "fee",
    distractorGroup: "money",
  },
  {
    word: "file",
    pos: "noun",
    level: 2,
    kidMeaning: "A set of papers or work kept together.",
    examples: ["She saved the file on the computer.", "The file holds all his drawings."],
    emoji: "🗂",
    syllables: "file",
    distractorGroup: "work",
  },
  {
    word: "folder",
    pos: "noun",
    level: 4,
    kidMeaning: "A cover that holds papers or files.",
    examples: ["Put your worksheets in the blue folder.", "The folder was full of old photos."],
    emoji: "📁",
    syllables: "fold-er",
    distractorGroup: "school",
  },
  {
    word: "form",
    pos: "noun",
    level: 3,
    kidMeaning: "A paper with blanks you fill in.",
    examples: ["Mum filled in the form for the trip.", "Sign your name at the end of the form."],
    emoji: "🧾",
    syllables: "form",
    distractorGroup: "work",
  },
  {
    word: "formula",
    pos: "noun",
    level: 5,
    kidMeaning: "A short rule for working something out.",
    examples: ["The formula for area is length times width.", "He wrote the formula in his notebook."],
    emoji: "🧪",
    syllables: "for-mu-la",
    distractorGroup: "maths",
  },
  {
    word: "fraction",
    pos: "noun",
    level: 6,
    kidMeaning: "A part of a whole, like one half.",
    examples: ["A quarter is a fraction of a cake.", "We shaded the fraction on the grid."],
    emoji: "🍕",
    syllables: "frac-tion",
    distractorGroup: "maths",
  },
  {
    word: "frequency",
    pos: "noun",
    level: 6,
    kidMeaning: "How often something happens over time.",
    examples: ["The frequency of buses drops at night.", "We counted the frequency of each colour."],
    emoji: "🔁",
    syllables: "fre-quen-cy",
    distractorGroup: "measuring",
  },
  {
    word: "fundraiser",
    pos: "noun",
    level: 6,
    kidMeaning: "An event held to collect money.",
    examples: ["The cake sale was a fundraiser for the library.", "Our fundraiser raised two hundred dollars."],
    emoji: "🎪",
    syllables: "fund-rais-er",
    distractorGroup: "community",
  },
  {
    word: "garage",
    pos: "noun",
    level: 3,
    kidMeaning: "A place where cars are kept or fixed.",
    examples: ["The car is in the garage.", "A man at the garage mended our tyre."],
    emoji: "🚗",
    syllables: "ga-rage",
    distractorGroup: "places",
  },
  {
    word: "government",
    pos: "noun",
    level: 4,
    kidMeaning: "The people who run a country.",
    examples: ["The government built a new hospital.", "Our government makes the laws."],
    emoji: "🏛",
    syllables: "gov-ern-ment",
    spellingTip: "don't forget the n: gov-ern-ment",
    distractorGroup: "civic",
  },
  {
    word: "graph",
    pos: "noun",
    level: 5,
    kidMeaning: "A picture that shows numbers as bars.",
    examples: ["The graph showed rain for each month.", "She drew a graph of the class results."],
    emoji: "📊",
    syllables: "graph",
    distractorGroup: "maths",
  },
  {
    word: "guard",
    pos: "noun",
    level: 2,
    kidMeaning: "A person who keeps a place safe.",
    examples: ["The guard checked our bags at the gate.", "A guard stood by the museum door."],
    emoji: "💂",
    syllables: "guard",
    distractorGroup: "jobs",
  },
  {
    word: "guideline",
    pos: "noun",
    level: 3,
    kidMeaning: "A rule that shows the best way.",
    examples: ["The guideline says to write in blue ink.", "Follow the safety guideline in the lab."],
    emoji: "📋",
    syllables: "guide-line",
    distractorGroup: "rules",
  },
  {
    word: "headline",
    pos: "noun",
    level: 6,
    kidMeaning: "The big words at the top of news.",
    examples: ["The headline said the team had won.", "She looked only at the headline."],
    emoji: "📰",
    syllables: "head-line",
    distractorGroup: "media",
  },
  {
    word: "headphones",
    pos: "noun",
    level: 6,
    kidMeaning: "Small speakers you wear on your ears.",
    examples: ["He listened with headphones on the bus.", "Her headphones were tangled again."],
    emoji: "🎧",
    syllables: "head-phones",
    distractorGroup: "technology",
  },
  {
    word: "heritage",
    pos: "noun",
    level: 6,
    kidMeaning: "Old things a country keeps and values.",
    examples: ["The shophouses are part of our heritage.", "A heritage trail shows old buildings."],
    emoji: "🏯",
    syllables: "her-i-tage",
    distractorGroup: "community",
  },
  {
    word: "horizontal",
    pos: "adjective",
    level: 6,
    kidMeaning: "Lying flat, going from side to side.",
    examples: ["She drew a horizontal line across the page.", "The shelf must be horizontal, not slanted."],
    emoji: "➖",
    syllables: "hor-i-zon-tal",
    distractorGroup: "maths",
  },
  {
    word: "impact",
    pos: "noun",
    level: 4,
    kidMeaning: "The strong effect one thing has.",
    examples: ["Litter has a bad impact on the sea.", "Her kind words had a big impact."],
    emoji: "💥",
    syllables: "im-pact",
    distractorGroup: "thinking",
  },
  {
    word: "import",
    pos: "verb",
    level: 5,
    kidMeaning: "To bring in goods from another country.",
    examples: ["We import apples from New Zealand.", "The shop imports toys by ship."],
    emoji: "🛳",
    syllables: "im-port",
    distractorGroup: "trade",
  },
  {
    word: "income",
    pos: "noun",
    level: 5,
    kidMeaning: "The money that comes in each month.",
    examples: ["Her income pays for food and rent.", "The stall gives him a small income."],
    emoji: "💰",
    syllables: "in-come",
    distractorGroup: "money",
  },
  {
    word: "influence",
    pos: "verb",
    level: 5,
    kidMeaning: "To change how someone thinks or acts.",
    examples: ["Her sister influenced her to read more.", "Friends often influence what we wear."],
    emoji: "🧲",
    syllables: "in-flu-ence",
    distractorGroup: "thinking",
  },
  {
    word: "inspector",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who checks that things are right.",
    examples: ["The inspector looked at every bus.", "A food inspector visited the stall."],
    emoji: "🔎",
    syllables: "in-spec-tor",
    distractorGroup: "jobs",
  },
  {
    word: "install",
    pos: "verb",
    level: 5,
    kidMeaning: "To put a thing in and get it working.",
    examples: ["They installed a fan in the classroom.", "Dad installed the new app for me."],
    emoji: "🔧",
    syllables: "in-stall",
    distractorGroup: "making",
  },
  {
    word: "instruction",
    pos: "noun",
    level: 6,
    kidMeaning: "A step that tells you what to do.",
    examples: ["Read every instruction before you start.", "The last instruction says to check your work."],
    emoji: "📜",
    syllables: "in-struc-tion",
    distractorGroup: "rules",
  },
  {
    word: "insurance",
    pos: "noun",
    level: 5,
    kidMeaning: "Money paid so you are helped if hurt.",
    examples: ["The car insurance paid for the repairs.", "Travel insurance covers lost bags."],
    emoji: "🛡",
    syllables: "in-sur-ance",
    distractorGroup: "money",
  },
  {
    word: "intend",
    pos: "verb",
    level: 4,
    kidMeaning: "To plan to do something.",
    examples: ["I intend to finish my book tonight.", "She intended to say sorry."],
    emoji: "🎯",
    syllables: "in-tend",
    distractorGroup: "thinking",
  },
  {
    word: "intention",
    pos: "noun",
    level: 6,
    kidMeaning: "What you mean to do.",
    examples: ["His intention was to help, not to hurt.", "She had no intention of being late."],
    emoji: "💭",
    syllables: "in-ten-tion",
    distractorGroup: "thinking",
  },
  {
    word: "internet",
    pos: "noun",
    level: 4,
    kidMeaning: "The network that joins computers everywhere.",
    examples: ["She looked up the answer on the internet.", "The internet was slow last night."],
    emoji: "🌐",
    syllables: "in-ter-net",
    distractorGroup: "technology",
  },
  {
    word: "interpret",
    pos: "verb",
    level: 6,
    kidMeaning: "To work out what something means.",
    examples: ["He interpreted the map for us.", "She interprets the words for her grandmother."],
    emoji: "🗺",
    syllables: "in-ter-pret",
    distractorGroup: "thinking",
  },
  {
    word: "interview",
    pos: "noun",
    level: 4,
    kidMeaning: "A meeting where you answer questions.",
    examples: ["Dad has a job interview on Monday.", "The interview lasted twenty minutes."],
    emoji: "🎤",
    syllables: "in-ter-view",
    distractorGroup: "work",
  },
  {
    word: "invoice",
    pos: "noun",
    level: 6,
    kidMeaning: "A note that lists what you owe.",
    examples: ["The shop sent an invoice for the chairs.", "She checked the invoice for mistakes."],
    emoji: "🧾",
    syllables: "in-voice",
    distractorGroup: "money",
  },
  {
    word: "jeweller",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who makes or sells rings.",
    examples: ["The jeweller mended Mum's chain.", "A jeweller polished the silver ring."],
    emoji: "💍",
    syllables: "jew-el-ler",
    spellingTip: "British spelling has two l's",
    distractorGroup: "jobs",
  },
  {
    word: "journalist",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who writes the news.",
    examples: ["The journalist asked the mayor questions.", "She wants to be a journalist."],
    emoji: "🗞",
    syllables: "jour-nal-ist",
    distractorGroup: "jobs",
  },
  {
    word: "judgement",
    pos: "noun",
    level: 6,
    kidMeaning: "A careful choice about what is right.",
    examples: ["The referee made a fair judgement.", "Use your own judgement about the weather."],
    emoji: "⚖",
    syllables: "judge-ment",
    spellingTip: "British spelling keeps the e: judge-ment",
    distractorGroup: "thinking",
  },
  {
    word: "justify",
    pos: "verb",
    level: 6,
    kidMeaning: "To give good reasons for what you did.",
    examples: ["She justified her answer with a rule.", "He could not justify being rude."],
    emoji: "🗯",
    syllables: "jus-ti-fy",
    distractorGroup: "thinking",
  },
  {
    word: "keyboard",
    pos: "noun",
    level: 5,
    kidMeaning: "The set of keys you type on.",
    examples: ["Her keyboard has a sticky letter e.", "He types on the keyboard with two fingers."],
    emoji: "⌨",
    syllables: "key-board",
    distractorGroup: "technology",
  },
  {
    word: "labourer",
    pos: "noun",
    level: 5,
    kidMeaning: "A worker who does hard body work.",
    examples: ["The labourer carried bricks all day.", "A labourer dug the deep hole."],
    emoji: "👷",
    syllables: "la-bour-er",
    spellingTip: "British spelling: la-bour, with u",
    distractorGroup: "jobs",
  },
  {
    word: "landmark",
    pos: "noun",
    level: 5,
    kidMeaning: "A famous thing that helps you find places.",
    examples: ["The tall tower is a landmark in town.", "We met by the landmark near the park."],
    emoji: "🗼",
    syllables: "land-mark",
    distractorGroup: "places",
  },
  {
    word: "laptop",
    pos: "noun",
    level: 4,
    kidMeaning: "A small computer you can carry.",
    examples: ["She did her project on the laptop.", "The laptop fits inside my bag."],
    emoji: "💻",
    syllables: "lap-top",
    distractorGroup: "technology",
  },
  {
    word: "laundry",
    pos: "noun",
    level: 3,
    kidMeaning: "Clothes and sheets that need washing.",
    examples: ["The laundry basket was full.", "She hung the laundry on the line."],
    emoji: "🧺",
    syllables: "laun-dry",
    distractorGroup: "home",
  },
  {
    word: "law",
    pos: "noun",
    level: 3,
    kidMeaning: "A rule that everyone in a country obeys.",
    examples: ["It is against the law to drop litter.", "The new law keeps roads safer."],
    emoji: "⚖",
    syllables: "law",
    distractorGroup: "civic",
  },
  {
    word: "leaflet",
    pos: "noun",
    level: 6,
    kidMeaning: "A small printed sheet that tells you things.",
    examples: ["A leaflet about the fair came today.", "She handed a leaflet to each parent."],
    emoji: "📃",
    syllables: "leaf-let",
    distractorGroup: "media",
  },
  {
    word: "lever",
    pos: "noun",
    level: 5,
    kidMeaning: "A bar you push to move something.",
    examples: ["He pulled the lever to start the ride.", "A lever lifts the heavy lid."],
    emoji: "🎚",
    syllables: "le-ver",
    distractorGroup: "tools",
  },
  {
    word: "librarian",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who looks after a library.",
    examples: ["The librarian found the book for me.", "Ask the librarian where the atlas is."],
    emoji: "📚",
    syllables: "li-brar-i-an",
    distractorGroup: "jobs",
  },
  {
    word: "licence",
    pos: "noun",
    level: 6,
    kidMeaning: "A paper that lets you do something.",
    examples: ["Dad showed his driving licence.", "You need a licence to keep that dog."],
    emoji: "🪪",
    syllables: "li-cence",
    spellingTip: "British noun ends in -ce; the verb is license",
    distractorGroup: "civic",
  },
  {
    word: "loan",
    pos: "noun",
    level: 3,
    kidMeaning: "Money you borrow and pay back later.",
    examples: ["The bank gave them a loan for the flat.", "He asked for a small loan from his uncle."],
    emoji: "🏦",
    syllables: "loan",
    distractorGroup: "money",
  },
  {
    word: "logic",
    pos: "noun",
    level: 5,
    kidMeaning: "Clear thinking that makes good sense.",
    examples: ["Her logic showed why the plan would fail.", "Use logic to solve the puzzle."],
    emoji: "🧠",
    syllables: "log-ic",
    distractorGroup: "thinking",
  },
  {
    word: "loss",
    pos: "noun",
    level: 3,
    kidMeaning: "When you no longer have something.",
    examples: ["The loss of his dog made him sad.", "The shop had a loss this month."],
    emoji: "📉",
    syllables: "loss",
    distractorGroup: "money",
  },
  {
    word: "machine",
    pos: "noun",
    level: 2,
    kidMeaning: "A thing with parts that does work.",
    examples: ["The washing machine hummed all morning.", "A machine prints the tickets."],
    emoji: "⚙",
    syllables: "ma-chine",
    spellingTip: "ch sounds like 'sh' in ma-chine",
    distractorGroup: "technology",
  },
  {
    word: "magazine",
    pos: "noun",
    level: 5,
    kidMeaning: "A thin book with news and pictures.",
    examples: ["She borrowed a magazine about horses.", "The magazine comes out every week."],
    emoji: "📖",
    syllables: "mag-a-zine",
    distractorGroup: "media",
  },
  {
    word: "maintain",
    pos: "verb",
    level: 4,
    kidMeaning: "To keep something working well.",
    examples: ["He maintains his bike with oil.", "They maintained the garden all year."],
    emoji: "🛠",
    syllables: "main-tain",
    distractorGroup: "work",
  },
  {
    word: "manufacture",
    pos: "verb",
    level: 6,
    kidMeaning: "To make goods in a factory.",
    examples: ["That plant manufactures bottles.", "They manufactured toys for many shops."],
    emoji: "🏭",
    syllables: "man-u-fac-ture",
    distractorGroup: "making",
  },
  {
    word: "material",
    pos: "noun",
    level: 5,
    kidMeaning: "The stuff a thing is made from.",
    examples: ["Wood is a strong material.", "She chose soft material for the bag."],
    emoji: "🧵",
    syllables: "ma-te-ri-al",
    distractorGroup: "making",
  },
  {
    word: "measurement",
    pos: "noun",
    level: 6,
    kidMeaning: "The size or amount you have found.",
    examples: ["Write the measurement in centimetres.", "His measurement of the room was wrong."],
    emoji: "📏",
    syllables: "meas-ure-ment",
    distractorGroup: "measuring",
  },
  {
    word: "media",
    pos: "noun",
    level: 5,
    kidMeaning: "News shown on papers, radio and screens.",
    examples: ["The media told the story all week.", "Social media spreads news quickly."],
    emoji: "📺",
    syllables: "me-di-a",
    distractorGroup: "media",
  },
  {
    word: "member",
    pos: "noun",
    level: 3,
    kidMeaning: "A person who belongs to a group.",
    examples: ["She is a member of the chess club.", "Every member pays a small fee."],
    emoji: "🧑",
    syllables: "mem-ber",
    distractorGroup: "community",
  },
  {
    word: "membership",
    pos: "noun",
    level: 6,
    kidMeaning: "Being part of a club or group.",
    examples: ["His membership of the gym ends in May.", "Membership costs two dollars a year."],
    emoji: "🎟",
    syllables: "mem-ber-ship",
    distractorGroup: "community",
  },
  {
    word: "memo",
    pos: "noun",
    level: 5,
    kidMeaning: "A short note that reminds people.",
    examples: ["The memo said the meeting had moved.", "She pinned the memo to the board."],
    emoji: "🗒",
    syllables: "mem-o",
    distractorGroup: "work",
  },
  {
    word: "merchant",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who buys and sells goods.",
    examples: ["The merchant sold silk and spices.", "A merchant came to the market by boat."],
    emoji: "⛵",
    syllables: "mer-chant",
    distractorGroup: "trade",
  },
  {
    word: "message",
    pos: "noun",
    level: 2,
    kidMeaning: "Words you send to another person.",
    examples: ["She left a message on the fridge.", "His message said he was on the way."],
    emoji: "💬",
    syllables: "mes-sage",
    distractorGroup: "talking",
  },
  {
    word: "microphone",
    pos: "noun",
    level: 6,
    kidMeaning: "A tool that makes your voice louder.",
    examples: ["He spoke into the microphone on stage.", "The microphone squeaked loudly."],
    emoji: "🎙",
    syllables: "mi-cro-phone",
    distractorGroup: "technology",
  },
  {
    word: "minister",
    pos: "noun",
    level: 4,
    kidMeaning: "A leader who runs part of a country.",
    examples: ["The minister opened the new school.", "A minister spoke about clean water."],
    emoji: "🏛",
    syllables: "min-is-ter",
    distractorGroup: "civic",
  },
  {
    word: "model",
    pos: "noun",
    level: 3,
    kidMeaning: "A small copy of a bigger thing.",
    examples: ["He built a model of a plane.", "The model of the town filled the table."],
    emoji: "🛩",
    syllables: "mod-el",
    distractorGroup: "making",
  },
  {
    word: "monitor",
    pos: "verb",
    level: 5,
    kidMeaning: "To watch and check something over time.",
    examples: ["Nurses monitor his heartbeat.", "We monitored the plant's growth each day."],
    emoji: "🖥",
    syllables: "mon-i-tor",
    distractorGroup: "work",
  },
  {
    word: "monument",
    pos: "noun",
    level: 5,
    kidMeaning: "A statue built to remember someone.",
    examples: ["The monument stands in the square.", "Flowers were left at the monument."],
    emoji: "🗿",
    syllables: "mon-u-ment",
    distractorGroup: "places",
  },
  {
    word: "motor",
    pos: "noun",
    level: 4,
    kidMeaning: "The part that makes a machine move.",
    examples: ["The boat's motor started with a roar.", "A tiny motor spins the fan."],
    emoji: "⚙",
    syllables: "mo-tor",
    distractorGroup: "technology",
  },
  {
    word: "multiplication",
    pos: "noun",
    level: 6,
    kidMeaning: "Timesing numbers to find the total.",
    examples: ["We learnt multiplication by threes.", "The multiplication table is on the wall."],
    emoji: "✖",
    syllables: "mul-ti-pli-ca-tion",
    distractorGroup: "maths",
  },
  {
    word: "needle",
    pos: "noun",
    level: 4,
    kidMeaning: "A thin sharp tool used for sewing.",
    examples: ["She threaded the needle carefully.", "The needle pricked his finger."],
    emoji: "🪡",
    syllables: "nee-dle",
    distractorGroup: "tools",
  },
  {
    word: "network",
    pos: "noun",
    level: 4,
    kidMeaning: "Lines or people joined to each other.",
    examples: ["The bus network covers the whole island.", "Our computers share one network."],
    emoji: "🌐",
    syllables: "net-work",
    distractorGroup: "technology",
  },
  {
    word: "newspaper",
    pos: "noun",
    level: 5,
    kidMeaning: "Printed sheets that carry the daily news.",
    examples: ["Grandpa reads the newspaper each morning.", "Her photo was in the newspaper."],
    emoji: "📰",
    syllables: "news-pa-per",
    distractorGroup: "media",
  },
  {
    word: "notification",
    pos: "noun",
    level: 6,
    kidMeaning: "A short alert that tells you news.",
    examples: ["A notification popped up on the screen.", "She turned off every notification at night."],
    emoji: "🔔",
    syllables: "no-ti-fi-ca-tion",
    distractorGroup: "technology",
  },
  {
    word: "obtain",
    pos: "verb",
    level: 5,
    kidMeaning: "To get something you wanted.",
    examples: ["She obtained a ticket for the show.", "You can obtain a form at the office."],
    emoji: "🎫",
    syllables: "ob-tain",
    distractorGroup: "work",
  },
  {
    word: "occupation",
    pos: "noun",
    level: 6,
    kidMeaning: "The job a person does.",
    examples: ["Write your parent's occupation on the form.", "Her occupation is teaching."],
    emoji: "💼",
    syllables: "oc-cu-pa-tion",
    distractorGroup: "work",
  },
  {
    word: "officer",
    pos: "noun",
    level: 3,
    kidMeaning: "A person with a job of keeping order.",
    examples: ["A police officer helped us cross.", "The officer wrote down what happened."],
    emoji: "👮",
    syllables: "of-fi-cer",
    distractorGroup: "jobs",
  },
  {
    word: "online",
    pos: "adjective",
    level: 4,
    kidMeaning: "Joined to the internet by a device.",
    examples: ["She bought the shoes online.", "Our online lesson starts at nine."],
    emoji: "🌐",
    syllables: "on-line",
    distractorGroup: "technology",
  },
  {
    word: "operate",
    pos: "verb",
    level: 5,
    kidMeaning: "To make a machine do its work.",
    examples: ["He operates the lift in the flats.", "She learnt to operate the printer."],
    emoji: "🎛",
    syllables: "op-er-ate",
    distractorGroup: "work",
  },
  {
    word: "operator",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who works a machine.",
    examples: ["The crane operator waved to us.", "An operator answered the phone."],
    emoji: "🏗",
    syllables: "op-er-a-tor",
    distractorGroup: "jobs",
  },
  {
    word: "opponent",
    pos: "noun",
    level: 5,
    kidMeaning: "The person you play against.",
    examples: ["Her opponent served the ball hard.", "He shook hands with his opponent."],
    emoji: "🏓",
    syllables: "op-po-nent",
    distractorGroup: "sport",
  },
  {
    word: "order",
    pos: "noun",
    level: 2,
    kidMeaning: "A request asking for goods to come.",
    examples: ["The order of books arrived today.", "She placed an order for six chairs."],
    emoji: "📦",
    syllables: "or-der",
    distractorGroup: "shopping",
  },
  {
    word: "organisation",
    pos: "noun",
    level: 6,
    kidMeaning: "A group set up to do work.",
    examples: ["The organisation plants trees in towns.", "She works for a charity organisation."],
    emoji: "🏢",
    syllables: "or-gan-i-sa-tion",
    spellingTip: "British spelling uses s, not z",
    distractorGroup: "community",
  },
  {
    word: "overtime",
    pos: "noun",
    level: 6,
    kidMeaning: "Extra hours worked after normal time.",
    examples: ["Dad worked overtime to finish the job.", "The overtime pay bought her a bike."],
    emoji: "🕗",
    syllables: "o-ver-time",
    distractorGroup: "work",
  },
  {
    word: "package",
    pos: "noun",
    level: 4,
    kidMeaning: "Something wrapped up to be sent.",
    examples: ["A package came for my sister.", "She tied string around the package."],
    emoji: "📦",
    syllables: "pack-age",
    distractorGroup: "post",
  },
  {
    word: "pair",
    pos: "noun",
    level: 2,
    kidMeaning: "Two things that go together.",
    examples: ["She bought a pair of shoes.", "A pair of socks was on the line."],
    emoji: "👟",
    syllables: "pair",
    distractorGroup: "measuring",
  },
  {
    word: "parade",
    pos: "noun",
    level: 4,
    kidMeaning: "A march of people through the streets.",
    examples: ["We watched the parade on National Day.", "The parade began with drums."],
    emoji: "🎺",
    syllables: "pa-rade",
    distractorGroup: "community",
  },
  {
    word: "parallel",
    pos: "adjective",
    level: 6,
    kidMeaning: "Side by side and never meeting.",
    examples: ["Draw two parallel lines.", "The railway tracks stay parallel."],
    emoji: "🛤",
    syllables: "par-al-lel",
    distractorGroup: "maths",
  },
  {
    word: "parcel",
    pos: "noun",
    level: 5,
    kidMeaning: "A wrapped box sent by post.",
    examples: ["The parcel came with red tape on it.", "She carried the parcel to the door."],
    emoji: "🎁",
    syllables: "par-cel",
    distractorGroup: "post",
  },
  {
    word: "participate",
    pos: "verb",
    level: 6,
    kidMeaning: "To join in and take part.",
    examples: ["Everyone can participate in the race.", "She participated in the singing contest."],
    emoji: "🙋",
    syllables: "par-tic-i-pate",
    distractorGroup: "community",
  },
  {
    word: "passport",
    pos: "noun",
    level: 4,
    kidMeaning: "A small book that lets you travel abroad.",
    examples: ["He showed his passport at the airport.", "Her passport photo looks funny."],
    emoji: "🛂",
    syllables: "pass-port",
    distractorGroup: "travel",
  },
  {
    word: "password",
    pos: "noun",
    level: 5,
    kidMeaning: "A secret word that unlocks something.",
    examples: ["Do not tell anyone your password.", "She changed the password last week."],
    emoji: "🔑",
    syllables: "pass-word",
    distractorGroup: "technology",
  },
  {
    word: "pension",
    pos: "noun",
    level: 5,
    kidMeaning: "Money paid to people who have retired.",
    examples: ["Grandma lives on her pension.", "His pension arrives every month."],
    emoji: "👵",
    syllables: "pen-sion",
    distractorGroup: "money",
  },
  {
    word: "percentage",
    pos: "noun",
    level: 6,
    kidMeaning: "A part of a hundred, written with %.",
    examples: ["A large percentage of the class walks to school.", "She scored a percentage of eighty."],
    emoji: "💯",
    syllables: "per-cent-age",
    distractorGroup: "maths",
  },
  {
    word: "perform",
    pos: "verb",
    level: 4,
    kidMeaning: "To sing or act in front of people.",
    examples: ["They performed a play for the parents.", "She performs on stage every year."],
    emoji: "🎭",
    syllables: "per-form",
    distractorGroup: "arts",
  },
  {
    word: "permit",
    pos: "noun",
    level: 5,
    kidMeaning: "A paper that allows you to do something.",
    examples: ["You need a permit to park here.", "The permit lasts for one year."],
    emoji: "🎫",
    syllables: "per-mit",
    distractorGroup: "civic",
  },
  {
    word: "petition",
    pos: "noun",
    level: 6,
    kidMeaning: "A paper many people sign to ask for change.",
    examples: ["They signed a petition to save the trees.", "The petition had five hundred names."],
    emoji: "✍",
    syllables: "pe-ti-tion",
    distractorGroup: "civic",
  },
  {
    word: "photo",
    pos: "noun",
    level: 3,
    kidMeaning: "A picture taken with a camera.",
    examples: ["She framed the photo of her cat.", "A photo of the class hangs in the hall."],
    emoji: "📷",
    syllables: "pho-to",
    distractorGroup: "media",
  },
  {
    word: "photographer",
    pos: "noun",
    level: 6,
    kidMeaning: "A person whose job is taking pictures.",
    examples: ["The photographer asked us to smile.", "A photographer came to the wedding."],
    emoji: "📸",
    syllables: "pho-tog-ra-pher",
    distractorGroup: "jobs",
  },
  {
    word: "pipe",
    pos: "noun",
    level: 3,
    kidMeaning: "A tube that carries water or gas.",
    examples: ["Water ran out of the broken pipe.", "The pipe under the sink leaks."],
    emoji: "🚰",
    syllables: "pipe",
    distractorGroup: "tools",
  },
  {
    word: "podcast",
    pos: "noun",
    level: 6,
    kidMeaning: "A talk show you listen to online.",
    examples: ["Dad listens to a podcast while driving.", "The podcast is about space."],
    emoji: "🎧",
    syllables: "pod-cast",
    distractorGroup: "media",
  },
  {
    word: "population",
    pos: "noun",
    level: 6,
    kidMeaning: "How many people live in a place.",
    examples: ["The population of our town is growing.", "China has a huge population."],
    emoji: "👨‍👩‍👧",
    syllables: "pop-u-la-tion",
    distractorGroup: "civic",
  },
  {
    word: "poster",
    pos: "noun",
    level: 4,
    kidMeaning: "A big printed sheet put on a wall.",
    examples: ["Our poster told everyone about the fair.", "She painted a poster for the play."],
    emoji: "🖼",
    syllables: "post-er",
    distractorGroup: "media",
  },
  {
    word: "presenter",
    pos: "noun",
    level: 3,
    kidMeaning: "A person who talks on a show.",
    examples: ["The presenter welcomed the singers.", "A presenter announced the winners."],
    emoji: "🎤",
    syllables: "pre-sent-er",
    distractorGroup: "jobs",
  },
  {
    word: "pressure",
    pos: "noun",
    level: 3,
    kidMeaning: "A hard press on something, or a worry.",
    examples: ["The pressure of the water burst the pipe.", "He felt pressure before the test."],
    emoji: "🌡",
    syllables: "pres-sure",
    distractorGroup: "science",
  },
  {
    word: "print",
    pos: "verb",
    level: 3,
    kidMeaning: "To put words on paper with a machine.",
    examples: ["The school prints the timetable each term.", "She printed her project last night."],
    emoji: "🖨",
    syllables: "print",
    distractorGroup: "making",
  },
  {
    word: "printer",
    pos: "noun",
    level: 4,
    kidMeaning: "A machine that puts words on paper.",
    examples: ["The printer ran out of ink.", "He fixed the jammed printer."],
    emoji: "🖨",
    syllables: "print-er",
    distractorGroup: "technology",
  },
  {
    word: "profession",
    pos: "noun",
    level: 5,
    kidMeaning: "A job that needs long training.",
    examples: ["Nursing is a caring profession.", "She joined the teaching profession."],
    emoji: "🩺",
    syllables: "pro-fes-sion",
    distractorGroup: "work",
  },
  {
    word: "professional",
    pos: "adjective",
    level: 6,
    kidMeaning: "Trained and paid to do a job well.",
    examples: ["A professional coach trained the team.", "His work looks neat and professional."],
    emoji: "👔",
    syllables: "pro-fes-sion-al",
    distractorGroup: "qualities",
  },
  {
    word: "profile",
    pos: "noun",
    level: 5,
    kidMeaning: "A short set of facts about someone.",
    examples: ["Her profile lists her hobbies.", "The magazine printed a profile of the singer."],
    emoji: "👤",
    syllables: "pro-file",
    distractorGroup: "media",
  },
  {
    word: "profit",
    pos: "noun",
    level: 4,
    kidMeaning: "Money left after you pay your costs.",
    examples: ["The stall made a small profit.", "All the profit went to charity."],
    emoji: "📈",
    syllables: "prof-it",
    distractorGroup: "money",
  },
  {
    word: "project",
    pos: "noun",
    level: 2,
    kidMeaning: "A piece of work that takes many days.",
    examples: ["Our science project is about rain.", "She finished the project on Sunday."],
    emoji: "📔",
    syllables: "proj-ect",
    distractorGroup: "school",
  },
  {
    word: "promotion",
    pos: "noun",
    level: 5,
    kidMeaning: "Moving up to a better job.",
    examples: ["Mum got a promotion at work.", "His promotion means more pay."],
    emoji: "⬆",
    syllables: "pro-mo-tion",
    distractorGroup: "work",
  },
  {
    word: "propose",
    pos: "verb",
    level: 5,
    kidMeaning: "To put forward an idea for others.",
    examples: ["She proposed a bake sale.", "He proposes that we start earlier."],
    emoji: "💡",
    syllables: "pro-pose",
    distractorGroup: "thinking",
  },
  {
    word: "protest",
    pos: "verb",
    level: 5,
    kidMeaning: "To say loudly that something is wrong.",
    examples: ["The pupils protested about the litter.", "She protested when he pushed in."],
    emoji: "✊",
    syllables: "pro-test",
    distractorGroup: "civic",
  },
  {
    word: "publish",
    pos: "verb",
    level: 5,
    kidMeaning: "To print a book for people to read.",
    examples: ["They published her poem in the paper.", "The school publishes a magazine."],
    emoji: "📘",
    syllables: "pub-lish",
    distractorGroup: "media",
  },
  {
    word: "publisher",
    pos: "noun",
    level: 6,
    kidMeaning: "A company that prints and sells books.",
    examples: ["The publisher sent the book to shops.", "She wrote to a publisher about her story."],
    emoji: "🏢",
    syllables: "pub-lish-er",
    distractorGroup: "media",
  },
  {
    word: "qualification",
    pos: "noun",
    level: 6,
    kidMeaning: "Proof that you have passed your training.",
    examples: ["She has a qualification in first aid.", "The job needs one qualification."],
    emoji: "🎓",
    syllables: "qual-i-fi-ca-tion",
    distractorGroup: "work",
  },
  {
    word: "qualified",
    pos: "adjective",
    level: 6,
    kidMeaning: "Trained and allowed to do a job.",
    examples: ["A qualified nurse checked his arm.", "She is qualified to teach swimming."],
    emoji: "🎓",
    syllables: "qual-i-fied",
    distractorGroup: "qualities",
  },
  {
    word: "reception",
    pos: "noun",
    level: 4,
    kidMeaning: "The desk where visitors are greeted.",
    examples: ["Wait at reception for your name.", "The reception was busy this morning."],
    emoji: "🛎",
    syllables: "re-cep-tion",
    distractorGroup: "places",
  },
  {
    word: "receptionist",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who greets visitors at a desk.",
    examples: ["The receptionist took our names.", "A receptionist answered the phone politely."],
    emoji: "💁",
    syllables: "re-cep-tion-ist",
    distractorGroup: "jobs",
  },
  {
    word: "recommend",
    pos: "verb",
    level: 5,
    kidMeaning: "To tell someone that a thing is good.",
    examples: ["I recommend this book to my friends.", "The doctor recommended more sleep."],
    emoji: "👍",
    syllables: "rec-om-mend",
    spellingTip: "one c, two m's: rec-om-mend",
    distractorGroup: "talking",
  },
  {
    word: "rectangle",
    pos: "noun",
    level: 6,
    kidMeaning: "A shape with four sides and square corners.",
    examples: ["The door is shaped like a rectangle.", "She drew a long rectangle."],
    emoji: "▭",
    syllables: "rec-tan-gle",
    distractorGroup: "maths",
  },
  {
    word: "reference",
    pos: "noun",
    level: 5,
    kidMeaning: "A note showing where facts came from.",
    examples: ["She added a reference to the website.", "The reference is at the end of the page."],
    emoji: "🔖",
    syllables: "ref-er-ence",
    distractorGroup: "school",
  },
  {
    word: "regard",
    pos: "verb",
    level: 5,
    kidMeaning: "To think of someone in a certain way.",
    examples: ["We regard her as the best speller.", "He regarded the plan as silly."],
    emoji: "🤔",
    syllables: "re-gard",
    distractorGroup: "thinking",
  },
  {
    word: "relationship",
    pos: "noun",
    level: 4,
    kidMeaning: "The way two people get on together.",
    examples: ["She has a close relationship with her gran.", "Their relationship began at school."],
    emoji: "🤝",
    syllables: "re-la-tion-ship",
    distractorGroup: "community",
  },
  {
    word: "remark",
    pos: "noun",
    level: 5,
    kidMeaning: "A short thing that someone says.",
    examples: ["His remark made everyone laugh.", "She made a kind remark about my work."],
    emoji: "💬",
    syllables: "re-mark",
    distractorGroup: "talking",
  },
  {
    word: "rent",
    pos: "noun",
    level: 3,
    kidMeaning: "Money paid each month for a home.",
    examples: ["They pay rent on the first day.", "The rent went up this year."],
    emoji: "🏠",
    syllables: "rent",
    distractorGroup: "money",
  },
  {
    word: "reporter",
    pos: "noun",
    level: 3,
    kidMeaning: "A person who tells the news.",
    examples: ["A reporter spoke to the winning team.", "The reporter wrote about the flood."],
    emoji: "🎙",
    syllables: "re-port-er",
    distractorGroup: "jobs",
  },
  {
    word: "represent",
    pos: "verb",
    level: 5,
    kidMeaning: "To speak or stand for a group.",
    examples: ["She represents our class at assembly.", "Two pupils represented the school."],
    emoji: "🏅",
    syllables: "rep-re-sent",
    distractorGroup: "community",
  },
  {
    word: "researcher",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who studies to find new facts.",
    examples: ["The researcher counted the birds each week.", "A researcher tested the water."],
    emoji: "🔬",
    syllables: "re-search-er",
    distractorGroup: "jobs",
  },
  {
    word: "response",
    pos: "noun",
    level: 4,
    kidMeaning: "The answer or reaction you give.",
    examples: ["Her response to the letter was quick.", "There was no response to my knock."],
    emoji: "↩",
    syllables: "re-sponse",
    distractorGroup: "talking",
  },
  {
    word: "responsibility",
    pos: "noun",
    level: 6,
    kidMeaning: "A job that you must take care of.",
    examples: ["Feeding the cat is my responsibility.", "She takes responsibility for the keys."],
    emoji: "🧑‍🍼",
    syllables: "re-spon-si-bil-i-ty",
    distractorGroup: "qualities",
  },
  {
    word: "retail",
    pos: "noun",
    level: 5,
    kidMeaning: "Selling goods to people in shops.",
    examples: ["She works in retail at the mall.", "Retail is busy before the holidays."],
    emoji: "🏬",
    syllables: "re-tail",
    distractorGroup: "trade",
  },
  {
    word: "retire",
    pos: "verb",
    level: 4,
    kidMeaning: "To stop working when you are old.",
    examples: ["Grandpa retired at sixty.", "She will retire next year."],
    emoji: "🧓",
    syllables: "re-tire",
    distractorGroup: "work",
  },
  {
    word: "retirement",
    pos: "noun",
    level: 6,
    kidMeaning: "The years after you stop working.",
    examples: ["He grows plants in his retirement.", "Her retirement starts in June."],
    emoji: "🌴",
    syllables: "re-tire-ment",
    distractorGroup: "work",
  },
  {
    word: "review",
    pos: "noun",
    level: 4,
    kidMeaning: "A report saying if something is good.",
    examples: ["Her review of the film was kind.", "The book got a good review."],
    emoji: "⭐",
    syllables: "re-view",
    distractorGroup: "media",
  },
  {
    word: "robot",
    pos: "noun",
    level: 4,
    kidMeaning: "A machine that can do jobs by itself.",
    examples: ["The robot swept the whole floor.", "He built a robot from a kit."],
    emoji: "🤖",
    syllables: "ro-bot",
    distractorGroup: "technology",
  },
  {
    word: "safety",
    pos: "noun",
    level: 3,
    kidMeaning: "Being kept away from harm.",
    examples: ["Wear a helmet for safety.", "Road safety is taught in school."],
    emoji: "🦺",
    syllables: "safe-ty",
    distractorGroup: "rules",
  },
  {
    word: "salary",
    pos: "noun",
    level: 5,
    kidMeaning: "The money paid to a worker monthly.",
    examples: ["Her salary pays for the flat.", "He saves part of his salary."],
    emoji: "💷",
    syllables: "sal-a-ry",
    distractorGroup: "money",
  },
  {
    word: "salon",
    pos: "noun",
    level: 4,
    kidMeaning: "A shop where hair is washed and cut.",
    examples: ["Mum went to the salon on Saturday.", "The salon smells of shampoo."],
    emoji: "💇",
    syllables: "sa-lon",
    distractorGroup: "places",
  },
  {
    word: "sample",
    pos: "noun",
    level: 4,
    kidMeaning: "A small part that shows the whole.",
    examples: ["She tried a sample of the new juice.", "The sample of soil went to the lab."],
    emoji: "🧪",
    syllables: "sam-ple",
    distractorGroup: "science",
  },
  {
    word: "scanner",
    pos: "noun",
    level: 5,
    kidMeaning: "A machine that copies pages onto a screen.",
    examples: ["The scanner copied her drawing.", "He fed the letter into the scanner."],
    emoji: "🖨",
    syllables: "scan-ner",
    distractorGroup: "technology",
  },
  {
    word: "screen",
    pos: "noun",
    level: 3,
    kidMeaning: "The flat part where pictures appear.",
    examples: ["The screen went black suddenly.", "She wiped the dusty screen."],
    emoji: "🖥",
    syllables: "screen",
    distractorGroup: "technology",
  },
  {
    word: "sculptor",
    pos: "noun",
    level: 6,
    kidMeaning: "An artist who shapes stone or clay.",
    examples: ["The sculptor carved a lion.", "A sculptor made the statue in the park."],
    emoji: "🗿",
    syllables: "sculp-tor",
    distractorGroup: "arts",
  },
  {
    word: "service",
    pos: "noun",
    level: 3,
    kidMeaning: "Help or work done for other people.",
    examples: ["The bus service starts at six.", "Her service to the club lasted ten years."],
    emoji: "🛎",
    syllables: "ser-vice",
    distractorGroup: "work",
  },
  {
    word: "shelter",
    pos: "noun",
    level: 3,
    kidMeaning: "A place that keeps you safe and dry.",
    examples: ["They waited in the bus shelter.", "The dog shelter takes in strays."],
    emoji: "⛺",
    syllables: "shel-ter",
    distractorGroup: "places",
  },
  {
    word: "shift",
    pos: "noun",
    level: 3,
    kidMeaning: "The hours a worker works that day.",
    examples: ["Her shift ends at ten at night.", "He swapped his shift with a friend."],
    emoji: "🕘",
    syllables: "shift",
    distractorGroup: "work",
  },
  {
    word: "signature",
    pos: "noun",
    level: 5,
    kidMeaning: "Your own name written by you.",
    examples: ["Mum put her signature on the form.", "His signature is hard to read."],
    emoji: "✒",
    syllables: "sig-na-ture",
    distractorGroup: "work",
  },
  {
    word: "similarity",
    pos: "noun",
    level: 6,
    kidMeaning: "A way that two things are alike.",
    examples: ["There is a similarity between the twins.", "We listed every similarity we found."],
    emoji: "👯",
    syllables: "sim-i-lar-i-ty",
    distractorGroup: "thinking",
  },
  {
    word: "society",
    pos: "noun",
    level: 5,
    kidMeaning: "All the people living together in a place.",
    examples: ["Rules help society run smoothly.", "Kind acts make society better."],
    emoji: "🏘",
    syllables: "so-ci-e-ty",
    distractorGroup: "civic",
  },
  {
    word: "software",
    pos: "noun",
    level: 5,
    kidMeaning: "The set of tools that runs a computer.",
    examples: ["New software made the laptop faster.", "The software checks your spelling."],
    emoji: "💽",
    syllables: "soft-ware",
    distractorGroup: "technology",
  },
  {
    word: "speaker",
    pos: "noun",
    level: 2,
    kidMeaning: "A box that sound comes out of.",
    examples: ["The speaker played music in the hall.", "One speaker was too loud."],
    emoji: "🔈",
    syllables: "speak-er",
    distractorGroup: "technology",
  },
  {
    word: "square",
    pos: "noun",
    level: 2,
    kidMeaning: "A shape with four sides the same.",
    examples: ["He cut the paper into a square.", "Each square on the board is white."],
    emoji: "⬜",
    syllables: "square",
    distractorGroup: "maths",
  },
  {
    word: "stamp",
    pos: "noun",
    level: 4,
    kidMeaning: "A small sticker that pays for post.",
    examples: ["She stuck a stamp on the letter.", "The stamp had a bird on it."],
    emoji: "📬",
    syllables: "stamp",
    distractorGroup: "post",
  },
  {
    word: "subtitle",
    pos: "noun",
    level: 6,
    kidMeaning: "Words on screen showing what is said.",
    examples: ["The subtitle helped her follow the film.", "Turn on the subtitle if it is soft."],
    emoji: "💬",
    syllables: "sub-ti-tle",
    distractorGroup: "media",
  },
  {
    word: "subtract",
    pos: "verb",
    level: 6,
    kidMeaning: "To take one number away from another.",
    examples: ["Subtract four from ten to get six.", "She subtracted the wrong number."],
    emoji: "➖",
    syllables: "sub-tract",
    distractorGroup: "maths",
  },
  {
    word: "subtraction",
    pos: "noun",
    level: 6,
    kidMeaning: "Taking one number away from another.",
    examples: ["We had a subtraction test today.", "Subtraction is the opposite of adding."],
    emoji: "➖",
    syllables: "sub-trac-tion",
    distractorGroup: "maths",
  },
  {
    word: "summarise",
    pos: "verb",
    level: 6,
    kidMeaning: "To tell the main points in few words.",
    examples: ["Can you summarise the story for us?", "She summarised the report in one page."],
    emoji: "📝",
    syllables: "sum-ma-rise",
    spellingTip: "British spelling uses s, not z",
    distractorGroup: "thinking",
  },
  {
    word: "supervisor",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who checks other people's work.",
    examples: ["The supervisor praised the whole team.", "Ask your supervisor before you leave."],
    emoji: "👔",
    syllables: "su-per-vi-sor",
    distractorGroup: "jobs",
  },
  {
    word: "supplier",
    pos: "noun",
    level: 4,
    kidMeaning: "A firm that sends goods to shops.",
    examples: ["The supplier delivered the flour late.", "Our supplier sells fresh eggs."],
    emoji: "🚚",
    syllables: "sup-pli-er",
    distractorGroup: "trade",
  },
  {
    word: "survey",
    pos: "noun",
    level: 4,
    kidMeaning: "A set of questions asked to many people.",
    examples: ["Our survey asked about favourite fruit.", "The survey showed most pupils walk."],
    emoji: "📋",
    syllables: "sur-vey",
    distractorGroup: "school",
  },
  {
    word: "survive",
    pos: "verb",
    level: 3,
    kidMeaning: "To stay alive through something hard.",
    examples: ["The plant survived the dry month.", "All the birds survived the storm."],
    emoji: "🌵",
    syllables: "sur-vive",
    distractorGroup: "science",
  },
  {
    word: "switch",
    pos: "noun",
    level: 2,
    kidMeaning: "The part you flick to turn power on.",
    examples: ["The light switch is by the door.", "He flicked the switch and the fan spun."],
    emoji: "🔛",
    syllables: "switch",
    distractorGroup: "technology",
  },
  {
    word: "symmetry",
    pos: "noun",
    level: 6,
    kidMeaning: "When both halves match each other.",
    examples: ["A butterfly's wings show symmetry.", "Fold the shape to test its symmetry."],
    emoji: "🦋",
    syllables: "sym-me-try",
    distractorGroup: "maths",
  },
  {
    word: "tablet",
    pos: "noun",
    level: 5,
    kidMeaning: "A flat computer you touch with a finger.",
    examples: ["She enjoyed a story on the tablet.", "The tablet needs charging again."],
    emoji: "📱",
    syllables: "tab-let",
    distractorGroup: "technology",
  },
  {
    word: "tax",
    pos: "noun",
    level: 5,
    kidMeaning: "Money paid to help run the country.",
    examples: ["Shops add a tax to the price.", "The tax pays for roads and schools."],
    emoji: "🧾",
    syllables: "tax",
    distractorGroup: "money",
  },
  {
    word: "teammate",
    pos: "noun",
    level: 6,
    kidMeaning: "Someone who plays on your team.",
    examples: ["Her teammate passed the ball to her.", "He cheered for his teammate."],
    emoji: "⚽",
    syllables: "team-mate",
    distractorGroup: "sport",
  },
  {
    word: "teamwork",
    pos: "noun",
    level: 6,
    kidMeaning: "People working well together on one job.",
    examples: ["Good teamwork won them the match.", "Teamwork made the job quick."],
    emoji: "🤝",
    syllables: "team-work",
    distractorGroup: "qualities",
  },
  {
    word: "technician",
    pos: "noun",
    level: 6,
    kidMeaning: "A person trained to fix machines.",
    examples: ["The technician mended the printer.", "A technician checked the school fans."],
    emoji: "🔧",
    syllables: "tech-ni-cian",
    distractorGroup: "jobs",
  },
  {
    word: "temperature",
    pos: "noun",
    level: 6,
    kidMeaning: "How hot or cold something is.",
    examples: ["The nurse took his temperature.", "The temperature drops at night."],
    emoji: "🌡",
    syllables: "tem-per-a-ture",
    distractorGroup: "measuring",
  },
  {
    word: "thread",
    pos: "noun",
    level: 4,
    kidMeaning: "A thin string used for sewing.",
    examples: ["She pulled the thread through the cloth.", "A loose thread hung from his sleeve."],
    emoji: "🧵",
    syllables: "thread",
    distractorGroup: "tools",
  },
  {
    word: "timber",
    pos: "noun",
    level: 5,
    kidMeaning: "Wood that is ready for building.",
    examples: ["The shed is made of timber.", "They stacked the timber by the wall."],
    emoji: "🪵",
    syllables: "tim-ber",
    distractorGroup: "making",
  },
  {
    word: "tonne",
    pos: "noun",
    level: 6,
    kidMeaning: "A very heavy weight of one thousand kilos.",
    examples: ["The lorry carried a tonne of sand.", "An elephant can weigh over a tonne."],
    emoji: "🐘",
    syllables: "tonne",
    spellingTip: "British spelling ends in -nne",
    distractorGroup: "measuring",
  },
  {
    word: "tournament",
    pos: "noun",
    level: 6,
    kidMeaning: "A series of games to find a winner.",
    examples: ["Our school joined the chess tournament.", "The tournament lasts three days."],
    emoji: "🏆",
    syllables: "tour-na-ment",
    distractorGroup: "sport",
  },
  {
    word: "training",
    pos: "noun",
    level: 2,
    kidMeaning: "Lessons that teach you to do a job.",
    examples: ["The training lasted six weeks.", "She had training in first aid."],
    emoji: "🏋",
    syllables: "train-ing",
    distractorGroup: "work",
  },
  {
    word: "transaction",
    pos: "noun",
    level: 6,
    kidMeaning: "One act of buying or paying.",
    examples: ["The transaction took only a minute.", "Each transaction shows on the slip."],
    emoji: "💳",
    syllables: "trans-ac-tion",
    distractorGroup: "money",
  },
  {
    word: "translator",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who turns words into another tongue.",
    examples: ["The translator helped the visitors.", "A translator wrote the story in Malay."],
    emoji: "🗣",
    syllables: "trans-la-tor",
    distractorGroup: "jobs",
  },
  {
    word: "transport",
    pos: "noun",
    level: 4,
    kidMeaning: "Ways of carrying people or goods.",
    examples: ["Public transport takes us to town.", "Transport by ship is slower."],
    emoji: "🚌",
    syllables: "trans-port",
    distractorGroup: "travel",
  },
  {
    word: "triple",
    pos: "adjective",
    level: 5,
    kidMeaning: "Three times as much as before.",
    examples: ["He ate a triple scoop of ice cream.", "The prize was triple the usual amount."],
    emoji: "3️⃣",
    syllables: "tri-ple",
    distractorGroup: "measuring",
  },
  {
    word: "tutor",
    pos: "noun",
    level: 5,
    kidMeaning: "A teacher who helps one pupil.",
    examples: ["Her maths tutor comes on Tuesday.", "The tutor explained the sum again."],
    emoji: "🧑‍🏫",
    syllables: "tu-tor",
    distractorGroup: "jobs",
  },
  {
    word: "uniform",
    pos: "noun",
    level: 4,
    kidMeaning: "The same clothes worn by one group.",
    examples: ["Our school uniform is blue and white.", "He ironed his uniform for Monday."],
    emoji: "👕",
    syllables: "u-ni-form",
    distractorGroup: "school",
  },
  {
    word: "upload",
    pos: "verb",
    level: 6,
    kidMeaning: "To send a file to the internet.",
    examples: ["She uploaded the photo to the class page.", "Please upload your work by Friday."],
    emoji: "⬆",
    syllables: "up-load",
    distractorGroup: "technology",
  },
  {
    word: "useless",
    pos: "adjective",
    level: 4,
    kidMeaning: "Not able to help at all.",
    examples: ["A broken pen is useless.", "The torch was useless without a battery."],
    emoji: "🚯",
    syllables: "use-less",
    distractorGroup: "qualities",
  },
  {
    word: "vertical",
    pos: "adjective",
    level: 6,
    kidMeaning: "Standing straight up and down.",
    examples: ["The flagpole is vertical.", "She drew a vertical line down the page."],
    emoji: "⬆",
    syllables: "ver-ti-cal",
    distractorGroup: "maths",
  },
  {
    word: "video",
    pos: "noun",
    level: 4,
    kidMeaning: "Moving pictures you watch on a screen.",
    examples: ["We watched a video about volcanoes.", "Her video shows the puppy playing."],
    emoji: "📹",
    syllables: "vid-e-o",
    distractorGroup: "media",
  },
  {
    word: "viewer",
    pos: "noun",
    level: 3,
    kidMeaning: "A person watching a show.",
    examples: ["Every viewer clapped at the end.", "The show has a million viewers."],
    emoji: "📺",
    syllables: "view-er",
    distractorGroup: "media",
  },
  {
    word: "viewpoint",
    pos: "noun",
    level: 6,
    kidMeaning: "The way one person sees a thing.",
    examples: ["From her viewpoint, the rule is fair.", "He explained his viewpoint calmly."],
    emoji: "👁",
    syllables: "view-point",
    distractorGroup: "thinking",
  },
  {
    word: "volume",
    pos: "noun",
    level: 4,
    kidMeaning: "How loud a sound is.",
    examples: ["Turn the volume down, please.", "The volume was so high it hurt."],
    emoji: "🔊",
    syllables: "vol-ume",
    distractorGroup: "measuring",
  },
  {
    word: "vote",
    pos: "verb",
    level: 5,
    kidMeaning: "To choose by putting up a hand.",
    examples: ["We voted for the class monitor.", "She votes for the blue team."],
    emoji: "🗳",
    syllables: "vote",
    distractorGroup: "civic",
  },
  {
    word: "wages",
    pos: "noun",
    level: 5,
    kidMeaning: "Money paid each week for work.",
    examples: ["He spent his wages on food.", "Her wages went up in June."],
    emoji: "💵",
    syllables: "wa-ges",
    distractorGroup: "money",
  },
  {
    word: "weakness",
    pos: "noun",
    level: 5,
    kidMeaning: "The part you are not good at.",
    examples: ["Spelling is his weakness.", "She turned her weakness into a strength."],
    emoji: "📉",
    syllables: "weak-ness",
    distractorGroup: "qualities",
  },
  {
    word: "website",
    pos: "noun",
    level: 4,
    kidMeaning: "A set of pages you visit online.",
    examples: ["The school website lists the holidays.", "She found the recipe on a website."],
    emoji: "🌐",
    syllables: "web-site",
    distractorGroup: "technology",
  },
  {
    word: "wholesale",
    pos: "adjective",
    level: 6,
    kidMeaning: "Sold in big amounts to shops.",
    examples: ["The wholesale price is much lower.", "They buy rice at a wholesale market."],
    emoji: "🏪",
    syllables: "whole-sale",
    distractorGroup: "trade",
  },
  {
    word: "wire",
    pos: "noun",
    level: 3,
    kidMeaning: "A thin metal thread that bends.",
    examples: ["The wire carries power to the lamp.", "He twisted the wire into a hook."],
    emoji: "🪢",
    syllables: "wire",
    distractorGroup: "tools",
  },
  {
    word: "wireless",
    pos: "adjective",
    level: 6,
    kidMeaning: "Working without any wires at all.",
    examples: ["The wireless mouse needs a battery.", "Our printer is wireless."],
    emoji: "📶",
    syllables: "wire-less",
    distractorGroup: "technology",
  },
];
