import type { Word } from "../words";

export const band3: Word[] = [
  {
    word: "science",
    pos: "noun",
    level: 3,
    kidMeaning: "The study of nature and how things work.",
    examples: ["She learns science at school.", "Science helps us understand the world."],
    emoji: "🔬",
    syllables: "sci-ence",
    distractorGroup: "subjects",
  },
  {
    word: "weather",
    pos: "noun",
    level: 2,
    kidMeaning: "How warm, wet or windy the air is.",
    examples: ["The weather is sunny today.", "Bad weather stops the game."],
    emoji: "🌤️",
    syllables: "weath-er",
    distractorGroup: "nature",
  },
  {
    word: "sunshine",
    pos: "noun",
    level: 4,
    kidMeaning: "The light and heat that come from the sun.",
    examples: ["She enjoys sunshine in the park.", "Sunshine makes plants grow."],
    emoji: "☀️",
    syllables: "sun-shine",
    distractorGroup: "nature",
  },
  {
    word: "shadow",
    pos: "noun",
    level: 3,
    kidMeaning: "The dark shape made when light is blocked.",
    examples: ["The shadow moves when the sun moves.", "She sits in the shadow."],
    emoji: "🌑",
    syllables: "shad-ow",
    distractorGroup: "nature",
  },
  {
    word: "leaf",
    pos: "noun",
    level: 2,
    kidMeaning: "A flat green part that grows on a plant.",
    examples: ["The tree has many green leaves.", "Leaves change colour in autumn."],
    emoji: "🍃",
    syllables: "leaf",
    distractorGroup: "plants",
  },
  {
    word: "grass",
    pos: "noun",
    level: 1,
    kidMeaning: "A green plant that covers fields and lawns.",
    examples: ["The grass is soft and green.", "Cows eat grass."],
    emoji: "🌿",
    syllables: "grass",
    distractorGroup: "plants",
  },
  {
    word: "insect",
    pos: "noun",
    level: 4,
    kidMeaning: "A small animal with six legs.",
    examples: ["She sees an insect on the flower.", "Insects have antennae."],
    emoji: "🦋",
    syllables: "in-sect",
    distractorGroup: "animals",
  },
  {
    word: "butterfly",
    pos: "noun",
    level: 5,
    kidMeaning: "An insect with large, bright, patterned wings.",
    examples: ["Butterflies land on flowers.", "She catches butterflies in the garden."],
    emoji: "🦋",
    syllables: "but-ter-fly",
    distractorGroup: "animals",
  },
  {
    word: "plane",
    pos: "noun",
    level: 1,
    kidMeaning: "A machine with wings that flies in the sky.",
    examples: ["She rides the plane to the country.", "The plane lands at the airport."],
    emoji: "✈️",
    syllables: "plane",
    distractorGroup: "transport",
  },
  {
    word: "bedroom",
    pos: "noun",
    level: 3,
    kidMeaning: "The room where you sleep at night.",
    examples: ["She sleeps in the bedroom.", "The bedroom has a big bed."],
    emoji: "🛏️",
    syllables: "bed-room",
    distractorGroup: "places",
  },
  {
    word: "bathroom",
    pos: "noun",
    level: 2,
    kidMeaning: "The room where you wash and use the toilet.",
    examples: ["She washes her hands in the bathroom.", "The bathroom is clean."],
    emoji: "🚿",
    syllables: "bath-room",
    distractorGroup: "places",
  },
  {
    word: "tower",
    pos: "noun",
    level: 3,
    kidMeaning: "A building that is very tall and narrow.",
    examples: ["The tower reaches the clouds.", "She visits the tower."],
    emoji: "🏰",
    syllables: "tow-er",
    distractorGroup: "places",
  },
  {
    word: "ice",
    pos: "noun",
    level: 1,
    kidMeaning: "Water that has frozen hard and cold.",
    examples: ["She slides on ice.", "Ice cream has ice in it."],
    emoji: "🧊",
    syllables: "ice",
    distractorGroup: "nature",
  },
  {
    word: "sky",
    pos: "noun",
    level: 1,
    kidMeaning: "The wide space above you in the air.",
    examples: ["The sky is blue today.", "She looks at the sky at night."],
    emoji: "🌌",
    syllables: "sky",
    distractorGroup: "nature",
  },
  {
    word: "team",
    pos: "noun",
    level: 1,
    kidMeaning: "A group of people who play or work together.",
    examples: ["She is on the football team.", "The team wins the match."],
    emoji: "👥",
    syllables: "team",
    distractorGroup: "groups",
  },
  {
    word: "prepare",
    pos: "verb",
    level: 3,
    kidMeaning: "To get something ready before you need it.",
    examples: ["She prepares the food.", "He prepares for the exam."],
    emoji: "🍳",
    syllables: "pre-pare",
    distractorGroup: "actions",
  },
  {
    word: "enjoy",
    pos: "verb",
    level: 2,
    kidMeaning: "To get pleasure from something you do.",
    examples: ["She enjoys the movie.", "He enjoys the party."],
    emoji: "😊",
    syllables: "en-joy",
    distractorGroup: "feelings",
  },
  {
    word: "understand",
    pos: "verb",
    level: 2,
    kidMeaning: "To know what something means.",
    examples: ["She understands the lesson.", "He understands the rules."],
    emoji: "💭",
    syllables: "un-der-stand",
    distractorGroup: "actions",
  },
  {
    word: "practice",
    pos: "verb",
    level: 3,
    kidMeaning: "To do something again and again to improve.",
    examples: ["She practises the piano.", "He practises maths."],
    emoji: "🎯",
    syllables: "prac-tice",
    distractorGroup: "actions",
  },
  {
    word: "provide",
    pos: "verb",
    level: 4,
    kidMeaning: "To give people the things they need.",
    examples: ["She provides food.", "He provides help."],
    emoji: "🤝",
    syllables: "pro-vide",
    distractorGroup: "actions",
  },
  {
    word: "decrease",
    pos: "verb",
    level: 6,
    kidMeaning: "To become smaller or fewer in number.",
    examples: ["She decreases the light.", "He decreases the distance."],
    emoji: "📉",
    syllables: "de-crease",
    distractorGroup: "actions",
  },
  {
    word: "improve",
    pos: "verb",
    level: 4,
    kidMeaning: "To make something better than it was.",
    examples: ["She improves her skill.", "He improves the design."],
    emoji: "⬆️",
    syllables: "im-prove",
    distractorGroup: "actions",
  },
  {
    word: "suggest",
    pos: "verb",
    level: 3,
    kidMeaning: "To offer an idea for others to consider.",
    examples: ["She suggests the game.", "He suggests the park."],
    emoji: "💡",
    syllables: "sug-gest",
    distractorGroup: "actions",
  },
  {
    word: "request",
    pos: "verb",
    level: 4,
    kidMeaning: "To ask politely for something you want.",
    examples: ["She requests water.", "He requests help."],
    emoji: "🙏",
    syllables: "re-quest",
    distractorGroup: "actions",
  },
  {
    word: "remain",
    pos: "verb",
    level: 3,
    kidMeaning: "To stay in the same place or state.",
    examples: ["She remains at home.", "He remains silent."],
    emoji: "🧍",
    syllables: "re-main",
    distractorGroup: "actions",
  },
  {
    word: "support",
    pos: "verb",
    level: 2,
    kidMeaning: "To help someone, or hold something up.",
    examples: ["She supports her friend.", "He supports his team."],
    emoji: "🤝",
    syllables: "sup-port",
    distractorGroup: "actions",
  },
  {
    word: "update",
    pos: "verb",
    level: 5,
    kidMeaning: "To add the newest information to something.",
    examples: ["She updates the list.", "He updates the software."],
    emoji: "🔄",
    syllables: "up-date",
    distractorGroup: "actions",
  },
  {
    word: "visit",
    pos: "verb",
    level: 2,
    kidMeaning: "To go and spend time with someone.",
    examples: ["She visits her friend.", "He visits the museum."],
    emoji: "🚪",
    syllables: "vis-it",
    distractorGroup: "actions",
  },
  {
    word: "welcome",
    pos: "verb",
    level: 2,
    kidMeaning: "To greet someone in a kind, friendly way.",
    examples: ["She welcomes the guest.", "He welcomes the team."],
    emoji: "👋",
    syllables: "wel-come",
    distractorGroup: "actions",
  },
  {
    word: "wonder",
    pos: "verb",
    level: 2,
    kidMeaning: "To think about something you are unsure of.",
    examples: ["She wonders what will happen.", "He wonders if it is true."],
    emoji: "🤔",
    syllables: "won-der",
    distractorGroup: "actions",
  },
  {
    word: "worry",
    pos: "verb",
    level: 1,
    kidMeaning: "To feel afraid that something bad may happen.",
    examples: ["She worries about the exam.", "He worries about his mum."],
    emoji: "😟",
    syllables: "wor-ry",
    distractorGroup: "feelings",
  },
  {
    word: "zoom",
    pos: "verb",
    level: 4,
    kidMeaning: "To move very fast with a loud hum.",
    examples: ["She zooms in on the photo.", "He zooms past in a car."],
    emoji: "💨",
    syllables: "zoom",
    distractorGroup: "actions",
  },
  {
    word: "myself",
    pos: "pronoun",
    level: 1,
    kidMeaning: "My own self, and nobody else.",
    examples: ["I do it myself.", "I tell myself secrets."],
    emoji: "🙋",
    syllables: "my-self",
    distractorGroup: "pronouns",
  },
  {
    word: "yourself",
    pos: "pronoun",
    level: 1,
    kidMeaning: "Your own self, and nobody else.",
    examples: ["You do it yourself.", "You tell yourself stories."],
    emoji: "🙋",
    syllables: "your-self",
    distractorGroup: "pronouns",
  },
  {
    word: "himself",
    pos: "pronoun",
    level: 2,
    kidMeaning: "His own self, and nobody else.",
    examples: ["He does it himself.", "He tells himself secrets."],
    emoji: "🙋",
    syllables: "him-self",
    distractorGroup: "pronouns",
  },
  {
    word: "herself",
    pos: "pronoun",
    level: 3,
    kidMeaning: "Her own self, and nobody else.",
    examples: ["She does it herself.", "She tells herself secrets."],
    emoji: "🙋",
    syllables: "her-self",
    distractorGroup: "pronouns",
  },
  {
    word: "themselves",
    pos: "pronoun",
    level: 3,
    kidMeaning: "Their own selves, and nobody else.",
    examples: ["They do it themselves.", "They tell themselves stories."],
    emoji: "🙋",
    syllables: "them-selves",
    distractorGroup: "pronouns",
  },
  {
    word: "desk",
    pos: "noun",
    level: 2,
    kidMeaning: "A table you sit at to write.",
    examples: ["She works at the desk.", "The desk has a computer."],
    emoji: "🖥️",
    syllables: "desk",
    distractorGroup: "objects",
  },
  {
    word: "telephone",
    pos: "noun",
    level: 4,
    kidMeaning: "A machine for talking to faraway people.",
    examples: ["She talks on the telephone.", "The telephone rings loud."],
    emoji: "☎️",
    syllables: "tel-e-phone",
    distractorGroup: "objects",
  },
  {
    word: "computer",
    pos: "noun",
    level: 3,
    kidMeaning: "A machine that stores and works with information.",
    examples: ["He uses a computer.", "The computer is very fast."],
    emoji: "💻",
    syllables: "com-pu-ter",
    distractorGroup: "objects",
  },
  {
    word: "camera",
    pos: "noun",
    level: 2,
    kidMeaning: "A device for taking photos and films.",
    examples: ["She takes a photo with a camera.", "The camera is very good."],
    emoji: "📷",
    syllables: "cam-er-a",
    distractorGroup: "objects",
  },
  {
    word: "sofa",
    pos: "noun",
    level: 4,
    kidMeaning: "A long soft seat for two or more.",
    examples: ["He sits on the sofa.", "The sofa is very comfortable."],
    emoji: "🛋️",
    syllables: "so-fa",
    distractorGroup: "objects",
  },
  {
    word: "lamp",
    pos: "noun",
    level: 3,
    kidMeaning: "A device that gives light in a room.",
    examples: ["She turns on the lamp.", "The lamp shines brightly."],
    emoji: "💡",
    syllables: "lamp",
    distractorGroup: "objects",
  },
  {
    word: "box",
    pos: "noun",
    level: 1,
    kidMeaning: "A container with straight sides for holding things.",
    examples: ["She puts a toy in the box.", "The box is empty."],
    emoji: "📦",
    syllables: "box",
    distractorGroup: "objects",
  },
  {
    word: "bag",
    pos: "noun",
    level: 1,
    kidMeaning: "A soft container you carry things in.",
    examples: ["He carries a bag.", "The bag has many things."],
    emoji: "👜",
    syllables: "bag",
    distractorGroup: "objects",
  },
  {
    word: "hat",
    pos: "noun",
    level: 2,
    kidMeaning: "A covering that you wear on your head.",
    examples: ["She wears a hat.", "The hat is warm."],
    emoji: "🎩",
    syllables: "hat",
    distractorGroup: "objects",
  },
  {
    word: "shoe",
    pos: "noun",
    level: 2,
    kidMeaning: "A covering that you wear on your foot.",
    examples: ["He puts on his shoes.", "The shoe is big."],
    emoji: "👟",
    syllables: "shoe",
    distractorGroup: "objects",
  },
  {
    word: "dress",
    pos: "noun",
    level: 1,
    kidMeaning: "A piece of clothing with a joined skirt.",
    examples: ["She wears a dress.", "The dress is beautiful."],
    emoji: "👗",
    syllables: "dress",
    distractorGroup: "objects",
  },
  {
    word: "coat",
    pos: "noun",
    level: 2,
    kidMeaning: "A warm piece of clothing worn outdoors.",
    examples: ["He wears a coat.", "The coat is thick."],
    emoji: "🧥",
    syllables: "coat",
    distractorGroup: "objects",
  },
  {
    word: "orange",
    pos: "noun",
    level: 1,
    kidMeaning: "A round, sweet, juicy fruit with thick skin.",
    examples: ["He eats an orange.", "Oranges have vitamin C."],
    emoji: "🍊",
    syllables: "or-ange",
    distractorGroup: "food",
  },
  {
    word: "banana",
    pos: "noun",
    level: 4,
    kidMeaning: "A long, curved fruit with soft yellow skin.",
    examples: ["She peels a banana.", "Bananas are very good."],
    emoji: "🍌",
    syllables: "ba-nan-a",
    distractorGroup: "food",
  },
  {
    word: "cow",
    pos: "noun",
    level: 2,
    kidMeaning: "A large farm animal that gives milk.",
    examples: ["She milks the cow.", "Cows live on farms."],
    emoji: "🐄",
    syllables: "cow",
    distractorGroup: "animals",
  },
  {
    word: "pig",
    pos: "noun",
    level: 2,
    kidMeaning: "A fat farm animal with a curly tail.",
    examples: ["He feeds the pig.", "Pigs are very fat."],
    emoji: "🐷",
    syllables: "pig",
    distractorGroup: "animals",
  },
  {
    word: "sheep",
    pos: "noun",
    level: 2,
    kidMeaning: "A farm animal with thick woolly fur.",
    examples: ["She has a sheep.", "Sheep give wool."],
    emoji: "🐑",
    syllables: "sheep",
    distractorGroup: "animals",
  },
  {
    word: "horse",
    pos: "noun",
    level: 1,
    kidMeaning: "A large animal that people ride.",
    examples: ["He rides a horse.", "Horses are very fast."],
    emoji: "🐴",
    syllables: "horse",
    distractorGroup: "animals",
  },
  {
    word: "store",
    pos: "noun",
    level: 1,
    kidMeaning: "A place where things are sold.",
    examples: ["He goes to the store.", "Stores sell many things."],
    emoji: "🛍️",
    syllables: "store",
    distractorGroup: "places",
  },
  {
    word: "movie",
    pos: "noun",
    level: 2,
    kidMeaning: "A story told in moving pictures.",
    examples: ["He watches a movie.", "Movies are good."],
    emoji: "🎬",
    syllables: "mov-ie",
    distractorGroup: "art",
  },
  {
    word: "party",
    pos: "noun",
    level: 1,
    kidMeaning: "A happy gathering with food and games.",
    examples: ["She goes to the party.", "Parties are fun."],
    emoji: "🎉",
    syllables: "par-ty",
    distractorGroup: "events",
  },
  {
    word: "holiday",
    pos: "noun",
    level: 4,
    kidMeaning: "A special day when nobody goes to work.",
    examples: ["He has a holiday.", "Holidays are good."],
    emoji: "🎄",
    syllables: "hol-i-day",
    distractorGroup: "events",
  },
  {
    word: "birthday",
    pos: "noun",
    level: 2,
    kidMeaning: "The day of the year you were born.",
    examples: ["She has a birthday.", "Birthdays have cake."],
    emoji: "🎂",
    syllables: "birth-day",
    distractorGroup: "events",
  },
  {
    word: "wedding",
    pos: "noun",
    level: 2,
    kidMeaning: "The day when two people get married.",
    examples: ["He goes to a wedding.", "Weddings are nice."],
    emoji: "💍",
    syllables: "wed-ding",
    distractorGroup: "events",
  },
  {
    word: "winter",
    pos: "noun",
    level: 3,
    kidMeaning: "The coldest season of the year.",
    examples: ["She likes winter.", "Winter has snow."],
    emoji: "❄️",
    syllables: "win-ter",
    distractorGroup: "time",
  },
  {
    word: "summer",
    pos: "noun",
    level: 2,
    kidMeaning: "The hottest season of the year.",
    examples: ["He likes summer.", "Summer is very hot."],
    emoji: "☀️",
    syllables: "sum-mer",
    distractorGroup: "time",
  },
  {
    word: "spring",
    pos: "noun",
    level: 2,
    kidMeaning: "The season when plants start to grow.",
    examples: ["She likes spring.", "Spring has flowers."],
    emoji: "🌸",
    syllables: "spring",
    distractorGroup: "time",
  },
  {
    word: "autumn",
    pos: "noun",
    level: 4,
    kidMeaning: "The season when leaves fall from trees.",
    examples: ["He likes autumn.", "Autumn has red leaves."],
    emoji: "🍂",
    syllables: "au-tumn",
    distractorGroup: "time",
  },
  {
    word: "grandmother",
    pos: "noun",
    level: 5,
    kidMeaning: "The mother of your mother or father.",
    examples: ["She visits her grandmother.", "Grandmothers tell stories."],
    emoji: "👵",
    syllables: "grand-moth-er",
    distractorGroup: "people",
  },
  {
    word: "grandfather",
    pos: "noun",
    level: 4,
    kidMeaning: "The father of your mother or father.",
    examples: ["He visits his grandfather.", "Grandfathers are old."],
    emoji: "👴",
    syllables: "grand-fath-er",
    distractorGroup: "people",
  },
  {
    word: "uncle",
    pos: "noun",
    level: 2,
    kidMeaning: "The brother of your mother or father.",
    examples: ["She visits her uncle.", "Uncles work at banks."],
    emoji: "👨",
    syllables: "un-cle",
    distractorGroup: "people",
  },
  {
    word: "aunt",
    pos: "noun",
    level: 2,
    kidMeaning: "The sister of your mother or father.",
    examples: ["He visits his aunt.", "Aunts are very kind."],
    emoji: "👩",
    syllables: "aunt",
    distractorGroup: "people",
  },
  {
    word: "teenager",
    pos: "noun",
    level: 5,
    kidMeaning: "A person aged between thirteen and nineteen.",
    examples: ["The teenager studies hard.", "Teenagers like music."],
    emoji: "👦",
    syllables: "teen-ag-er",
    distractorGroup: "people",
  },
  {
    word: "young",
    pos: "adjective",
    level: 1,
    kidMeaning: "In the early part of your life.",
    examples: ["The young girl is smart.", "Young people have energy."],
    emoji: "👧",
    syllables: "young",
    distractorGroup: "age",
  },
  {
    word: "police",
    pos: "noun",
    level: 1,
    kidMeaning: "The people who keep everyone safe.",
    examples: ["The police helps.", "Police are brave."],
    emoji: "👮",
    syllables: "po-lice",
    distractorGroup: "people",
  },
  {
    word: "chef",
    pos: "noun",
    level: 2,
    kidMeaning: "A cook in charge of a kitchen.",
    examples: ["The chef is very good.", "Chefs make delicious food."],
    emoji: "👨",
    syllables: "chef",
    distractorGroup: "people",
  },
  {
    word: "manual",
    pos: "noun",
    level: 5,
    kidMeaning: "A book that tells you how to do something.",
    examples: ["She reads the manual.", "The manual explains everything."],
    emoji: "📖",
    syllables: "man-u-al",
    distractorGroup: "school",
  },
  {
    word: "sailor",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who works on a ship.",
    examples: ["The sailor navigates the ship.", "Sailors work hard at sea."],
    emoji: "⛵",
    syllables: "sail-or",
    distractorGroup: "people",
  },
  {
    word: "builder",
    pos: "noun",
    level: 3,
    kidMeaning: "A person whose job is building houses.",
    examples: ["The builder builds fast.", "Builders are strong."],
    emoji: "👷",
    syllables: "build-er",
    distractorGroup: "people",
  },
  {
    word: "singer",
    pos: "noun",
    level: 2,
    kidMeaning: "A person who sings songs for others.",
    examples: ["The singer has a nice voice.", "Singers are famous."],
    emoji: "🎤",
    syllables: "sing-er",
    distractorGroup: "people",
  },
  {
    word: "dancer",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who dances, often on a stage.",
    examples: ["The dancer moves beautifully.", "Dancers are graceful."],
    emoji: "💃",
    syllables: "danc-er",
    distractorGroup: "people",
  },
  {
    word: "judge",
    pos: "noun",
    level: 3,
    kidMeaning: "The person who decides things in a court.",
    examples: ["The judge makes decisions.", "Judges are wise."],
    emoji: "👨",
    syllables: "judge",
    distractorGroup: "people",
  },
  {
    word: "lawyer",
    pos: "noun",
    level: 2,
    kidMeaning: "A person whose job is helping with laws.",
    examples: ["The lawyer helps her.", "Lawyers are smart."],
    emoji: "👨",
    syllables: "law-yer",
    distractorGroup: "people",
  },
  {
    word: "dentist",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who looks after your teeth.",
    examples: ["The dentist checks teeth.", "Dentists are good."],
    emoji: "👨",
    syllables: "den-tist",
    distractorGroup: "people",
  },
  {
    word: "pharmacist",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who prepares and sells medicines.",
    examples: ["The pharmacist gives pills.", "Pharmacists are careful."],
    emoji: "💊",
    syllables: "phar-ma-cist",
    distractorGroup: "people",
  },
  {
    word: "checklist",
    pos: "noun",
    level: 6,
    kidMeaning: "A list of things you tick off.",
    examples: ["She uses a checklist for homework.", "The checklist is organised."],
    emoji: "✓",
    syllables: "check-list",
    distractorGroup: "school",
  },
  {
    word: "tailor",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who makes and mends clothes.",
    examples: ["The tailor fixed my shirt.", "A tailor makes custom clothes."],
    emoji: "👗",
    syllables: "tail-or",
    distractorGroup: "people",
  },
  {
    word: "hairdresser",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who cuts and styles hair.",
    examples: ["The hairdresser cuts hair.", "Hairdressers are good."],
    emoji: "✂️",
    syllables: "hair-dress-er",
    distractorGroup: "people",
  },
  {
    word: "bartender",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who serves drinks at a bar.",
    examples: ["The bartender makes drinks.", "Bartenders are friendly."],
    emoji: "🍸",
    syllables: "bar-tend-er",
    distractorGroup: "people",
  },
  {
    word: "security",
    pos: "noun",
    level: 4,
    kidMeaning: "Being safe from danger or harm.",
    examples: ["The security of the school comes first.", "Security guards check every bag."],
    emoji: "🔒",
    syllables: "se-cur-i-ty",
    distractorGroup: "people",
  },
  {
    word: "secretary",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who keeps records and writes letters.",
    examples: ["The secretary helps the boss.", "Secretaries are organised."],
    emoji: "📋",
    syllables: "sec-re-tar-y",
    distractorGroup: "people",
  },
  {
    word: "manager",
    pos: "noun",
    level: 4,
    kidMeaning: "A person in charge of a business.",
    examples: ["The manager leads the team.", "Managers are smart."],
    emoji: "👨",
    syllables: "man-ag-er",
    distractorGroup: "people",
  },
  {
    word: "director",
    pos: "noun",
    level: 3,
    kidMeaning: "The person in charge of making a film.",
    examples: ["The director makes films.", "Directors are creative."],
    emoji: "🎬",
    syllables: "di-rec-tor",
    distractorGroup: "people",
  },
  {
    word: "president",
    pos: "noun",
    level: 3,
    kidMeaning: "The leader of a country or a club.",
    examples: ["The president leads the country.", "Presidents are important."],
    emoji: "👑",
    syllables: "pres-i-dent",
    distractorGroup: "people",
  },
  {
    word: "king",
    pos: "noun",
    level: 1,
    kidMeaning: "A man who rules a country.",
    examples: ["The king rules the kingdom.", "Kings are powerful."],
    emoji: "👑",
    syllables: "king",
    distractorGroup: "people",
  },
  {
    word: "queen",
    pos: "noun",
    level: 2,
    kidMeaning: "A woman who rules a country.",
    examples: ["The queen rules the kingdom.", "Queens are beautiful."],
    emoji: "👑",
    syllables: "queen",
    distractorGroup: "people",
  },
  {
    word: "prince",
    pos: "noun",
    level: 2,
    kidMeaning: "The son of a king or queen.",
    examples: ["The prince is handsome.", "Princes live in palaces."],
    emoji: "🤴",
    syllables: "prince",
    distractorGroup: "people",
  },
  {
    word: "princess",
    pos: "noun",
    level: 3,
    kidMeaning: "The daughter of a king or queen.",
    examples: ["The princess is beautiful.", "Princesses wear crowns."],
    emoji: "👸",
    syllables: "prin-cess",
    distractorGroup: "people",
  },
  {
    word: "astronaut",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who travels into space.",
    examples: ["The astronaut flies to the moon.", "Astronauts are brave."],
    emoji: "👨",
    syllables: "as-tro-naut",
    distractorGroup: "people",
  },
  {
    word: "poet",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who writes poems for others.",
    examples: ["The poet writes beautiful words.", "Poets are sensitive."],
    emoji: "📖",
    syllables: "po-et",
    distractorGroup: "people",
  },
  {
    word: "creator",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who makes or invents things.",
    examples: ["The creator draws well.", "She is a talented creator."],
    emoji: "📷",
    syllables: "pho-tog-ra-pher",
    distractorGroup: "people",
  },
  {
    word: "composer",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who writes music for others.",
    examples: ["The composer writes songs.", "Composers are creative."],
    emoji: "🎵",
    syllables: "com-pos-er",
    distractorGroup: "people",
  },
  {
    word: "athlete",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who is good at sport.",
    examples: ["The athlete trains hard.", "Athletes are strong."],
    emoji: "🏃",
    syllables: "ath-lete",
    distractorGroup: "people",
  },
  {
    word: "trainer",
    pos: "noun",
    level: 2,
    kidMeaning: "A person who teaches a sport or skill.",
    examples: ["The trainer helps with fitness.", "Trainers are strict."],
    emoji: "🏋️",
    syllables: "train-er",
    distractorGroup: "people",
  },
  {
    word: "counsellor",
    pos: "noun",
    level: 6,
    kidMeaning: "A person trained to listen and give advice.",
    examples: ["The counsellor helps her.", "Counsellors are patient."],
    emoji: "👨",
    syllables: "coun-sel-lor",
    distractorGroup: "people",
  },
  {
    word: "tutorial",
    pos: "noun",
    level: 6,
    kidMeaning: "A lesson that shows you how to do something.",
    examples: ["He watches the tutorial.", "The tutorial is helpful."],
    emoji: "🎓",
    syllables: "tu-tor-i-al",
    distractorGroup: "school",
  },
  {
    word: "fisherman",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who catches fish for a living.",
    examples: ["The fisherman caught a big fish.", "Fishermen work near the water."],
    emoji: "🎣",
    syllables: "fish-er-man",
    distractorGroup: "people",
  },
  {
    word: "hunter",
    pos: "noun",
    level: 3,
    kidMeaning: "A person who hunts wild animals.",
    examples: ["The hunter hunts deer.", "Hunters are brave."],
    emoji: "🏹",
    syllables: "hunt-er",
    distractorGroup: "people",
  },
  {
    word: "miner",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who digs for coal or metal.",
    examples: ["The miner digs coal.", "Miners are strong."],
    emoji: "⛏️",
    syllables: "min-er",
    distractorGroup: "people",
  },
  {
    word: "carpenter",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who makes things from wood.",
    examples: ["The carpenter makes tables.", "Carpenters are skilled."],
    emoji: "🔨",
    syllables: "car-pent-er",
    distractorGroup: "people",
  },
  {
    word: "electrician",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who fixes electrical wires and lights.",
    examples: ["The electrician fixes wires.", "Electricians are smart."],
    emoji: "⚡",
    syllables: "e-lec-tri-cian",
    distractorGroup: "people",
  },
  {
    word: "plumber",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who fixes water pipes and taps.",
    examples: ["The plumber fixes pipes.", "Plumbers are helpful."],
    emoji: "🚰",
    syllables: "plumb-er",
    distractorGroup: "people",
  },
  {
    word: "gardener",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who looks after a garden.",
    examples: ["The gardener plants flowers.", "Gardeners are patient."],
    emoji: "🌻",
    syllables: "gard-en-er",
    distractorGroup: "people",
  },
  {
    word: "decorator",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who paints and decorates rooms.",
    examples: ["The decorator decorates the room.", "Decorators are artistic."],
    emoji: "🎨",
    syllables: "dec-o-rat-or",
    distractorGroup: "people",
  },
  {
    word: "architect",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who designs new buildings.",
    examples: ["The architect designs houses.", "Architects are creative."],
    emoji: "🏢",
    syllables: "ar-chi-tect",
    distractorGroup: "people",
  },
  {
    word: "chemist",
    pos: "noun",
    level: 5,
    kidMeaning: "A scientist who studies what things are made of.",
    examples: ["The chemist does experiments.", "Chemists are careful."],
    emoji: "🧪",
    syllables: "chem-ist",
    distractorGroup: "people",
  },
  {
    word: "historian",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who studies and writes about history.",
    examples: ["The historian studies the past.", "Historians are knowledgeable."],
    emoji: "📖",
    syllables: "his-to-ri-an",
    distractorGroup: "people",
  },
  {
    word: "accountant",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who keeps money records for others.",
    examples: ["The accountant keeps accounts.", "Accountants are careful."],
    emoji: "💼",
    syllables: "ac-count-ant",
    distractorGroup: "people",
  },
  {
    word: "banker",
    pos: "noun",
    level: 2,
    kidMeaning: "A person whose job is running a bank.",
    examples: ["The banker helps with money.", "Bankers are professional."],
    emoji: "🏦",
    syllables: "bank-er",
    distractorGroup: "people",
  },
  {
    word: "businessman",
    pos: "noun",
    level: 6,
    kidMeaning: "A man who runs or works in business.",
    examples: ["The businessman makes deals.", "Businessmen are busy."],
    emoji: "💼",
    syllables: "bus-i-ness-man",
    distractorGroup: "people",
  },
  {
    word: "dealer",
    pos: "noun",
    level: 4,
    kidMeaning: "A person whose job is buying and selling.",
    examples: ["The dealer sells cars.", "Dealers are friendly."],
    emoji: "🚗",
    syllables: "deal-er",
    distractorGroup: "people",
  },
  {
    word: "trader",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who buys and sells goods.",
    examples: ["The trader trades goods.", "Traders are smart."],
    emoji: "💼",
    syllables: "trad-er",
    distractorGroup: "people",
  },
  {
    word: "smuggler",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who moves goods in secret.",
    examples: ["The smuggler breaks the law.", "Smugglers are sneaky."],
    emoji: "🚫",
    syllables: "smug-gler",
    distractorGroup: "people",
  },
  {
    word: "thief",
    pos: "noun",
    level: 2,
    kidMeaning: "A person who steals things from others.",
    examples: ["The thief steals money.", "Thieves are sneaky."],
    emoji: "🚨",
    syllables: "thief",
    distractorGroup: "people",
  },
  {
    word: "pirate",
    pos: "noun",
    level: 4,
    kidMeaning: "A robber who attacks ships at sea.",
    examples: ["The pirate attacks ships.", "Pirates are dangerous."],
    emoji: "🏴‍☠️",
    syllables: "pi-rate",
    distractorGroup: "people",
  },
  {
    word: "witness",
    pos: "noun",
    level: 5,
    kidMeaning: "A person who sees something happen.",
    examples: ["The witness tells the police.", "Witnesses are scared."],
    emoji: "👁️",
    syllables: "wit-ness",
    distractorGroup: "people",
  },
  {
    word: "dictionary",
    pos: "noun",
    level: 6,
    kidMeaning: "A book that tells you what words mean.",
    examples: ["She looks up a word in the dictionary.", "Dictionaries help you learn new words."],
    emoji: "📖",
    syllables: "dic-tion-ar-y",
    distractorGroup: "objects",
  },
  {
    word: "essay",
    pos: "noun",
    level: 5,
    kidMeaning: "A short piece of writing about one subject.",
    examples: ["She writes an essay about trees.", "The essay is very good."],
    emoji: "✏️",
    syllables: "es-say",
    distractorGroup: "activities",
  },
  {
    word: "poem",
    pos: "noun",
    level: 4,
    kidMeaning: "Writing with short lines that often rhyme.",
    examples: ["He reads a poem in class.", "The poem is very beautiful."],
    emoji: "📖",
    syllables: "po-em",
    distractorGroup: "activities",
  },
  {
    word: "rhyme",
    pos: "noun",
    level: 4,
    kidMeaning: "A word that ends with the same sound.",
    examples: ["Cat and mat rhyme.", "She finds rhymes in poems."],
    emoji: "🎵",
    syllables: "rhyme",
    distractorGroup: "language",
  },
  {
    word: "vowel",
    pos: "noun",
    level: 6,
    kidMeaning: "One of the letters a, e, i, o, u.",
    examples: ["The vowel is in the word apple.", "Vowels are important for speaking."],
    emoji: "ABC",
    syllables: "vow-el",
    distractorGroup: "language",
  },
  {
    word: "consonant",
    pos: "noun",
    level: 6,
    kidMeaning: "Any letter that is not a vowel.",
    examples: ["B and c are consonants.", "Most letters are consonants."],
    emoji: "ABC",
    syllables: "con-so-nant",
    distractorGroup: "language",
  },
  {
    word: "syllable",
    pos: "noun",
    level: 6,
    kidMeaning: "A part of a word you say together.",
    examples: ["The word cat has one syllable.", "She counts syllables in words."],
    emoji: "🔤",
    syllables: "syl-la-ble",
    distractorGroup: "language",
  },
  {
    word: "sentence",
    pos: "noun",
    level: 4,
    kidMeaning: "A group of words that makes sense together.",
    examples: ["She writes a complete sentence.", "The sentence has a subject."],
    emoji: "📝",
    syllables: "sen-tence",
    distractorGroup: "language",
  },
  {
    word: "paragraph",
    pos: "noun",
    level: 6,
    kidMeaning: "A group of sentences about one idea.",
    examples: ["The paragraph is about animals.", "She writes three paragraphs."],
    emoji: "📄",
    syllables: "par-a-graph",
    distractorGroup: "language",
  },
  {
    word: "punctuation",
    pos: "noun",
    level: 6,
    kidMeaning: "Marks like commas and full stops in writing.",
    examples: ["Punctuation marks sentences.", "She adds punctuation to her writing."],
    emoji: "◦",
    syllables: "punc-tu-a-tion",
    distractorGroup: "language",
  },
  {
    word: "comma",
    pos: "noun",
    level: 6,
    kidMeaning: "The mark that shows a short pause.",
    examples: ["Put a comma between words.", "She puts a comma in the sentence."],
    emoji: "⌣",
    syllables: "com-ma",
    distractorGroup: "language",
  },
  {
    word: "period",
    pos: "noun",
    level: 4,
    kidMeaning: "A length of time with a start and end.",
    examples: ["The rainy period lasted three weeks.", "She rested for a short period."],
    emoji: "⭕",
    syllables: "pe-ri-od",
    distractorGroup: "language",
  },
  {
    word: "exclamation",
    pos: "noun",
    level: 6,
    kidMeaning: "Words shouted suddenly because of strong feeling.",
    examples: ["Exclamations show big feelings.", "She writes an exclamation mark."],
    emoji: "◦",
    syllables: "ex-cla-ma-tion",
    distractorGroup: "language",
  },
  {
    word: "revise",
    pos: "verb",
    level: 6,
    kidMeaning: "To study your work again before a test.",
    examples: ["She revises for the test.", "He revises the chapter."],
    emoji: "📚",
    syllables: "re-vise",
    distractorGroup: "actions",
  },
  {
    word: "memorise",
    pos: "verb",
    level: 6,
    kidMeaning: "To learn something so you can repeat it.",
    examples: ["She memorises the poem.", "He memorises vocabulary words."],
    emoji: "🧠",
    syllables: "mem-o-rise",
    distractorGroup: "actions",
  },
  {
    word: "recite",
    pos: "verb",
    level: 5,
    kidMeaning: "To say words aloud that you have learnt.",
    examples: ["She recites the poem.", "They recite the alphabet together."],
    emoji: "🎤",
    syllables: "re-cite",
    distractorGroup: "actions",
  },
  {
    word: "debate",
    pos: "verb",
    level: 4,
    kidMeaning: "To argue about an idea with other people.",
    examples: ["The student debates the topic.", "They debate in class."],
    emoji: "💬",
    syllables: "de-bate",
    distractorGroup: "actions",
  },
  {
    word: "concert",
    pos: "noun",
    level: 5,
    kidMeaning: "A show where people play or sing music.",
    examples: ["We watch a concert together.", "The concert is very fun."],
    emoji: "🎤",
    syllables: "pres-en-ta-tion",
    distractorGroup: "activities",
  },
  {
    word: "lecture",
    pos: "noun",
    level: 4,
    kidMeaning: "A talk that teaches many people at once.",
    examples: ["The professor gives a lecture.", "She listens to the lecture."],
    emoji: "👨",
    syllables: "lec-ture",
    distractorGroup: "activities",
  },
  {
    word: "chapter",
    pos: "noun",
    level: 3,
    kidMeaning: "One of the main parts of a book.",
    examples: ["The book has ten chapters.", "She reads chapter five."],
    emoji: "📖",
    syllables: "chap-ter",
    distractorGroup: "objects",
  },
  {
    word: "margin",
    pos: "noun",
    level: 5,
    kidMeaning: "The empty space at the side of a page.",
    examples: ["Write in the margin.", "Leave margins when you write."],
    emoji: "📄",
    syllables: "mar-gin",
    distractorGroup: "objects",
  },
  {
    word: "highlight",
    pos: "verb",
    level: 6,
    kidMeaning: "To mark important words with bright colour.",
    examples: ["She highlights key words.", "He highlights the important part."],
    emoji: "🖍️",
    syllables: "high-light",
    distractorGroup: "actions",
  },
  {
    word: "underline",
    pos: "verb",
    level: 6,
    kidMeaning: "To draw a line under a word.",
    examples: ["She underlines new vocabulary.", "He underlines the answer."],
    emoji: "✏️",
    syllables: "un-der-line",
    distractorGroup: "actions",
  },
  {
    word: "erase",
    pos: "verb",
    level: 5,
    kidMeaning: "To rub out writing you no longer want.",
    examples: ["She erases her mistake.", "He erases the pencil mark."],
    emoji: "🧹",
    syllables: "e-rase",
    distractorGroup: "actions",
  },
  {
    word: "sketch",
    pos: "verb",
    level: 4,
    kidMeaning: "To draw something quickly and simply.",
    examples: ["She sketches the flower.", "He sketches what he sees."],
    emoji: "🎨",
    syllables: "sketch",
    distractorGroup: "actions",
  },
  {
    word: "crayon",
    pos: "noun",
    level: 6,
    kidMeaning: "A stick of coloured wax for drawing.",
    examples: ["She colours with crayons.", "The crayon is soft."],
    emoji: "🖍️",
    syllables: "cray-on",
    distractorGroup: "objects",
  },
  {
    word: "charcoal",
    pos: "noun",
    level: 5,
    kidMeaning: "A black stick used for drawing and shading.",
    examples: ["She draws with charcoal.", "Charcoal makes dark lines."],
    emoji: "🖤",
    syllables: "char-coal",
    distractorGroup: "objects",
  },
  {
    word: "locker",
    pos: "noun",
    level: 2,
    kidMeaning: "A small cupboard where you keep your things.",
    examples: ["She keeps books in the locker.", "The locker has a lock."],
    emoji: "🔓",
    syllables: "lock-er",
    distractorGroup: "places",
  },
  {
    word: "bell",
    pos: "noun",
    level: 1,
    kidMeaning: "A metal cup that rings when struck.",
    examples: ["The bell rings for the start of class.", "She hears the bell."],
    emoji: "🔔",
    syllables: "bell",
    distractorGroup: "objects",
  },
  {
    word: "recess",
    pos: "noun",
    level: 5,
    kidMeaning: "The break at school for eating and playing.",
    examples: ["The children play at recess.", "Recess is fun time."],
    emoji: "🎮",
    syllables: "re-cess",
    distractorGroup: "time",
  },
  {
    word: "laboratory",
    pos: "noun",
    level: 6,
    kidMeaning: "A room where scientists do their experiments.",
    examples: ["They do experiments in the laboratory.", "The laboratory has tools."],
    emoji: "🔬",
    syllables: "lab-o-ra-tor-y",
    distractorGroup: "places",
  },
  {
    word: "gymnasium",
    pos: "noun",
    level: 6,
    kidMeaning: "A large room for exercise and sport.",
    examples: ["They play basketball in the gymnasium.", "The gymnasium is big."],
    emoji: "🏋️",
    syllables: "gym-na-si-um",
    distractorGroup: "places",
  },
  {
    word: "wardrobe",
    pos: "noun",
    level: 4,
    kidMeaning: "A tall cupboard where clothes are hung.",
    examples: ["She hangs a dress in the wardrobe.", "The wardrobe has many clothes."],
    emoji: "👗",
    syllables: "ward-robe",
    distractorGroup: "objects",
  },
  {
    word: "drawer",
    pos: "noun",
    level: 2,
    kidMeaning: "A box that slides in and out of furniture.",
    examples: ["She opens the drawer.", "Socks are in the drawer."],
    emoji: "🗄️",
    syllables: "draw-er",
    distractorGroup: "objects",
  },
  {
    word: "mattress",
    pos: "noun",
    level: 4,
    kidMeaning: "The soft pad you lie on in bed.",
    examples: ["The mattress is comfortable.", "She sleeps on the mattress."],
    emoji: "🛏️",
    syllables: "mat-tress",
    distractorGroup: "objects",
  },
  {
    word: "carpet",
    pos: "noun",
    level: 4,
    kidMeaning: "A thick cloth that covers a whole floor.",
    examples: ["She walks on the carpet.", "The carpet is soft."],
    emoji: "🟫",
    syllables: "car-pet",
    distractorGroup: "objects",
  },
  {
    word: "rug",
    pos: "noun",
    level: 3,
    kidMeaning: "A small thick cloth that covers part of a floor.",
    examples: ["The rug is colourful.", "She puts a rug in the room."],
    emoji: "🟫",
    syllables: "rug",
    distractorGroup: "objects",
  },
  {
    word: "painting",
    pos: "noun",
    level: 3,
    kidMeaning: "A picture made with paint.",
    examples: ["The painting is beautiful.", "She hangs the painting on the wall."],
    emoji: "🎨",
    syllables: "paint-ing",
    distractorGroup: "objects",
  },
  {
    word: "vase",
    pos: "noun",
    level: 4,
    kidMeaning: "A tall container for holding cut flowers.",
    examples: ["She puts flowers in the vase.", "The vase is fragile."],
    emoji: "🌸",
    syllables: "vase",
    distractorGroup: "objects",
  },
  {
    word: "utensil",
    pos: "noun",
    level: 6,
    kidMeaning: "A tool used for cooking or eating.",
    examples: ["Kitchen utensils are useful.", "She uses utensils to eat."],
    emoji: "🍴",
    syllables: "u-ten-sil",
    distractorGroup: "objects",
  },
  {
    word: "cutlery",
    pos: "noun",
    level: 6,
    kidMeaning: "The knives, forks and spoons you eat with.",
    examples: ["She sets the cutlery.", "The cutlery is clean."],
    emoji: "🍴",
    syllables: "cut-ler-y",
    distractorGroup: "objects",
  },
  {
    word: "spoon",
    pos: "noun",
    level: 3,
    kidMeaning: "An eating tool with a small round bowl.",
    examples: ["She eats soup with a spoon.", "The spoon is silver."],
    emoji: "🥄",
    syllables: "spoon",
    distractorGroup: "objects",
  },
  {
    word: "fork",
    pos: "noun",
    level: 3,
    kidMeaning: "An eating tool with sharp points.",
    examples: ["She uses a fork to eat.", "The fork has four points."],
    emoji: "🍴",
    syllables: "fork",
    distractorGroup: "objects",
  },
  {
    word: "knife",
    pos: "noun",
    level: 2,
    kidMeaning: "A tool with a sharp blade for cutting.",
    examples: ["She cuts with a knife.", "The knife is sharp."],
    emoji: "🔪",
    syllables: "knife",
    distractorGroup: "objects",
  },
  {
    word: "plate",
    pos: "noun",
    level: 2,
    kidMeaning: "A flat round dish you eat from.",
    examples: ["She puts food on the plate.", "The plate is clean."],
    emoji: "🍽️",
    syllables: "plate",
    distractorGroup: "objects",
  },
  {
    word: "bowl",
    pos: "noun",
    level: 2,
    kidMeaning: "A deep round dish for soup or cereal.",
    examples: ["She eats rice in the bowl.", "The bowl is deep."],
    emoji: "🥣",
    syllables: "bowl",
    distractorGroup: "objects",
  },
  {
    word: "mug",
    pos: "noun",
    level: 3,
    kidMeaning: "A large cup with a handle.",
    examples: ["She drinks tea in the mug.", "The mug is warm."],
    emoji: "☕",
    syllables: "mug",
    distractorGroup: "objects",
  },
  {
    word: "jug",
    pos: "noun",
    level: 4,
    kidMeaning: "A deep container with a handle for pouring.",
    examples: ["She pours water from the jug.", "The jug is full."],
    emoji: "🫖",
    syllables: "jug",
    distractorGroup: "objects",
  },
  {
    word: "dustpan",
    pos: "noun",
    level: 6,
    kidMeaning: "A flat pan that swept dust goes into.",
    examples: ["She uses a dustpan to collect dust.", "The dustpan is near the broom."],
    emoji: "🧹",
    syllables: "dust-pan",
    distractorGroup: "objects",
  },
  {
    word: "mop",
    pos: "noun",
    level: 4,
    kidMeaning: "A tool with a long handle for washing floors.",
    examples: ["She cleans the floor with a mop.", "The mop is wet."],
    emoji: "🧼",
    syllables: "mop",
    distractorGroup: "objects",
  },
  {
    word: "scrub",
    pos: "verb",
    level: 4,
    kidMeaning: "To rub something hard to get it clean.",
    examples: ["She scrubs the floor.", "He scrubs his hands clean."],
    emoji: "🧹",
    syllables: "scrub",
    distractorGroup: "actions",
  },
  {
    word: "rinse",
    pos: "verb",
    level: 5,
    kidMeaning: "To wash something lightly with clean water.",
    examples: ["She rinses the plate.", "He rinses his mouth."],
    emoji: "💧",
    syllables: "rinse",
    distractorGroup: "actions",
  },
  {
    word: "wring",
    pos: "verb",
    level: 5,
    kidMeaning: "To twist something to squeeze the water out.",
    examples: ["She wrings the cloth.", "He wrings the mop dry."],
    emoji: "💧",
    syllables: "wring",
    distractorGroup: "actions",
  },
  {
    word: "sweep",
    pos: "verb",
    level: 4,
    kidMeaning: "To clean a floor with a broom.",
    examples: ["She sweeps the floor.", "He sweeps away the dust."],
    emoji: "🧹",
    syllables: "sweep",
    distractorGroup: "actions",
  },
  {
    word: "vacuum",
    pos: "verb",
    level: 5,
    kidMeaning: "To clean a floor with a vacuum cleaner.",
    examples: ["She vacuums the carpet.", "He vacuums the room."],
    emoji: "🧹",
    syllables: "vac-u-um",
    distractorGroup: "actions",
  },
  {
    word: "decorate",
    pos: "verb",
    level: 6,
    kidMeaning: "To make a place look pretty.",
    examples: ["She decorates the room.", "He decorates the cake."],
    emoji: "🎨",
    syllables: "dec-o-rate",
    distractorGroup: "actions",
  },
  {
    word: "polish",
    pos: "verb",
    level: 4,
    kidMeaning: "To rub something until it is shiny.",
    examples: ["She polishes the shoe.", "He polishes the floor."],
    emoji: "✨",
    syllables: "pol-ish",
    distractorGroup: "actions",
  },
  {
    word: "niece",
    pos: "noun",
    level: 3,
    kidMeaning: "The daughter of your brother or sister.",
    examples: ["She is my niece.", "My niece is very cute."],
    emoji: "👧",
    syllables: "niece",
    distractorGroup: "people",
  },
  {
    word: "nephew",
    pos: "noun",
    level: 4,
    kidMeaning: "The son of your brother or sister.",
    examples: ["He is my nephew.", "My nephew likes to play."],
    emoji: "👦",
    syllables: "neph-ew",
    distractorGroup: "people",
  },
  {
    word: "ancestor",
    pos: "noun",
    level: 6,
    kidMeaning: "A member of your family from long ago.",
    examples: ["Her ancestors came from China.", "Ancestors are family history."],
    emoji: "👴",
    syllables: "an-ces-tor",
    distractorGroup: "people",
  },
  {
    word: "stepmother",
    pos: "noun",
    level: 6,
    kidMeaning: "The wife your father married later.",
    examples: ["She is my stepmother.", "My stepmother is kind."],
    emoji: "👩",
    syllables: "step-moth-er",
    distractorGroup: "people",
  },
  {
    word: "stepfather",
    pos: "noun",
    level: 6,
    kidMeaning: "The husband your mother married later.",
    examples: ["He is my stepfather.", "My stepfather helps me."],
    emoji: "👨",
    syllables: "step-fath-er",
    distractorGroup: "people",
  },
  {
    word: "stepsister",
    pos: "noun",
    level: 6,
    kidMeaning: "The daughter of your stepmother or stepfather.",
    examples: ["She is my stepsister.", "My stepsister likes books."],
    emoji: "👧",
    syllables: "step-sis-ter",
    distractorGroup: "people",
  },
  {
    word: "stepbrother",
    pos: "noun",
    level: 6,
    kidMeaning: "The son of your stepmother or stepfather.",
    examples: ["He is my stepbrother.", "My stepbrother likes games."],
    emoji: "👦",
    syllables: "step-broth-er",
    distractorGroup: "people",
  },
  {
    word: "tradition",
    pos: "noun",
    level: 5,
    kidMeaning: "Something a family has done for many years.",
    examples: ["Celebrating with family is a tradition.", "This tradition is old."],
    emoji: "🎏",
    syllables: "tra-di-tion",
    distractorGroup: "abstract",
  },
  {
    word: "surgeon",
    pos: "noun",
    level: 4,
    kidMeaning: "A doctor who operates on sick people.",
    examples: ["The surgeon helps the patient.", "She wants to be a surgeon."],
    emoji: "👨",
    syllables: "sur-geon",
    distractorGroup: "people",
  },
  {
    word: "therapist",
    pos: "noun",
    level: 5,
    kidMeaning: "A person trained to help you get better.",
    examples: ["The therapist helps her feel happy.", "He goes to a therapist."],
    emoji: "👨",
    syllables: "ther-a-pist",
    distractorGroup: "people",
  },
  {
    word: "guidebook",
    pos: "noun",
    level: 6,
    kidMeaning: "A book with information for visitors and travellers.",
    examples: ["He reads the guidebook.", "The guidebook is helpful."],
    emoji: "📖",
    syllables: "guide-book",
    distractorGroup: "school",
  },
  {
    word: "conductor",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who leads musicians as they play.",
    examples: ["The conductor leads the orchestra.", "A conductor directs the band."],
    emoji: "🚌",
    syllables: "con-duc-tor",
    distractorGroup: "people",
  },
  {
    word: "clerk",
    pos: "noun",
    level: 4,
    kidMeaning: "A person who keeps records in an office.",
    examples: ["The clerk helps with papers.", "He works as a clerk."],
    emoji: "📋",
    syllables: "clerk",
    distractorGroup: "people",
  },
  {
    word: "courier",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who delivers letters and parcels.",
    examples: ["The courier brings packages.", "She works as a courier."],
    emoji: "📦",
    syllables: "cour-i-er",
    distractorGroup: "people",
  },
  {
    word: "pamphlet",
    pos: "noun",
    level: 6,
    kidMeaning: "A thin booklet that gives you information.",
    examples: ["She reads the pamphlet.", "The pamphlet has useful tips."],
    emoji: "📄",
    syllables: "pam-phlet",
    distractorGroup: "school",
  },
  {
    word: "firefighter",
    pos: "noun",
    level: 6,
    kidMeaning: "A person whose job is putting out fires.",
    examples: ["The firefighter puts out fires.", "She is a brave firefighter."],
    emoji: "🚒",
    syllables: "fire-fight-er",
    distractorGroup: "people",
  },
  {
    word: "paramedic",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who treats people hurt in accidents.",
    examples: ["The paramedic helps the hurt person.", "He is a paramedic."],
    emoji: "🚒",
    syllables: "par-a-med-ic",
    distractorGroup: "people",
  },
  {
    word: "umpire",
    pos: "noun",
    level: 6,
    kidMeaning: "The official who makes sure a game is fair.",
    examples: ["The umpire makes decisions.", "He is an umpire of the game."],
    emoji: "👨",
    syllables: "um-pire",
    distractorGroup: "people",
  },
  {
    word: "spectator",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who watches a game or show.",
    examples: ["The spectator claps for the player.", "She is a spectator at the game."],
    emoji: "👀",
    syllables: "spec-ta-tor",
    distractorGroup: "people",
  },
  {
    word: "audience",
    pos: "noun",
    level: 4,
    kidMeaning: "The people who watch or listen to a show.",
    examples: ["The audience claps at the end.", "Large audiences come."],
    emoji: "👥",
    syllables: "au-di-ence",
    distractorGroup: "groups",
  },
  {
    word: "tricycle",
    pos: "noun",
    level: 6,
    kidMeaning: "A cycle with three wheels for young children.",
    examples: ["He rides a tricycle.", "The tricycle has a seat."],
    emoji: "🛺",
    syllables: "tri-cy-cle",
    distractorGroup: "transport",
  },
  {
    word: "yacht",
    pos: "noun",
    level: 3,
    kidMeaning: "A boat used for racing or for pleasure.",
    examples: ["He sails in a yacht.", "The yacht is beautiful."],
    emoji: "⛵",
    syllables: "yacht",
    distractorGroup: "transport",
  },
  {
    word: "submarine",
    pos: "noun",
    level: 5,
    kidMeaning: "A ship that can travel under the sea.",
    examples: ["The submarine goes deep.", "She sees a submarine in the museum."],
    emoji: "🚢",
    syllables: "sub-ma-rine",
    distractorGroup: "transport",
  },
  {
    word: "pedestrian",
    pos: "noun",
    level: 6,
    kidMeaning: "A person who is walking, not driving.",
    examples: ["Pedestrians cross the road.", "He is a pedestrian."],
    emoji: "🚶",
    syllables: "pe-des-tri-an",
    distractorGroup: "people",
  },
  {
    word: "fare",
    pos: "noun",
    level: 4,
    kidMeaning: "The money you pay to travel somewhere.",
    examples: ["She pays the fare for the bus.", "The fare is expensive."],
    emoji: "💰",
    syllables: "fare",
    distractorGroup: "abstract",
  },
  {
    word: "accelerate",
    pos: "verb",
    level: 6,
    kidMeaning: "To go faster, or make something go faster.",
    examples: ["He accelerates the car.", "The car accelerates quickly."],
    emoji: "⚡",
    syllables: "ac-cel-er-ate",
    distractorGroup: "actions",
  },
  {
    word: "trousers",
    pos: "noun",
    level: 4,
    kidMeaning: "Clothing that covers your legs and waist.",
    examples: ["He wears trousers to school.", "Her trousers were too long."],
    emoji: "👖",
    syllables: "trou-sers",
    distractorGroup: "objects",
  },
  {
    word: "jeans",
    pos: "noun",
    level: 2,
    kidMeaning: "Trousers made of thick blue cotton cloth.",
    examples: ["She wears jeans.", "The jeans are blue."],
    emoji: "👖",
    syllables: "jeans",
    distractorGroup: "objects",
  },
  {
    word: "skirt",
    pos: "noun",
    level: 3,
    kidMeaning: "Clothing that hangs from the waist down.",
    examples: ["She wears a skirt.", "The skirt is pink."],
    emoji: "👗",
    syllables: "skirt",
    distractorGroup: "objects",
  },
  {
    word: "blouse",
    pos: "noun",
    level: 4,
    kidMeaning: "A loose shirt worn by women and girls.",
    examples: ["She wears a blouse.", "The blouse is pretty."],
    emoji: "👚",
    syllables: "blouse",
    distractorGroup: "objects",
  },
  {
    word: "jumper",
    pos: "noun",
    level: 2,
    kidMeaning: "A warm knitted top with long sleeves.",
    examples: ["She wears a jumper in winter.", "The jumper is warm."],
    emoji: "🧶",
    syllables: "jump-er",
    distractorGroup: "objects",
  },
  {
    word: "cardigan",
    pos: "noun",
    level: 6,
    kidMeaning: "A knitted top that buttons up the front.",
    examples: ["She wears a cardigan.", "The cardigan is cosy."],
    emoji: "🧥",
    syllables: "car-di-gan",
    distractorGroup: "objects",
  },
  {
    word: "blazer",
    pos: "noun",
    level: 5,
    kidMeaning: "A smart jacket worn with a school uniform.",
    examples: ["He wears a blazer.", "The blazer is smart."],
    emoji: "🧥",
    syllables: "blaz-er",
    distractorGroup: "objects",
  },
  {
    word: "raincoat",
    pos: "noun",
    level: 5,
    kidMeaning: "A coat that keeps the rain off you.",
    examples: ["She wears a raincoat.", "The raincoat is yellow."],
    emoji: "🧥",
    syllables: "rain-coat",
    distractorGroup: "objects",
  },
  {
    word: "overall",
    pos: "noun",
    level: 5,
    kidMeaning: "A loose suit worn over clothes to keep them clean.",
    examples: ["She wears overalls for work.", "His overalls were covered in paint."],
    emoji: "🧥",
    syllables: "o-ver-all",
    distractorGroup: "objects",
  },
  {
    word: "apron",
    pos: "noun",
    level: 5,
    kidMeaning: "A cloth you wear to protect your clothes.",
    examples: ["She wears an apron to cook.", "The apron has a pocket."],
    emoji: "👕",
    syllables: "a-pron",
    distractorGroup: "objects",
  },
  {
    word: "glove",
    pos: "noun",
    level: 3,
    kidMeaning: "A covering for your hand and each finger.",
    examples: ["She wears gloves in winter.", "The glove is warm."],
    emoji: "🧤",
    syllables: "glove",
    distractorGroup: "objects",
  },
  {
    word: "mitten",
    pos: "noun",
    level: 6,
    kidMeaning: "A warm hand covering with one part for fingers.",
    examples: ["He wears mittens.", "The mitten is soft."],
    emoji: "🧤",
    syllables: "mit-ten",
    distractorGroup: "objects",
  },
  {
    word: "scarf",
    pos: "noun",
    level: 3,
    kidMeaning: "A long cloth you wear around your neck.",
    examples: ["She wears a scarf.", "The scarf is warm."],
    emoji: "🧣",
    syllables: "scarf",
    distractorGroup: "objects",
  },
  {
    word: "worksheet",
    pos: "noun",
    level: 3,
    kidMeaning: "A sheet of paper with exercises to do.",
    examples: ["She completes the worksheet in class.", "The worksheet has many questions."],
    emoji: "📝",
    syllables: "work-sheet",
    distractorGroup: "school",
  },
  {
    word: "highlighter",
    pos: "noun",
    level: 6,
    kidMeaning: "A pen with bright ink for marking words.",
    examples: ["She highlights key words.", "The highlighter is yellow."],
    emoji: "🖍️",
    syllables: "high-light-er",
    distractorGroup: "school",
  },
  {
    word: "classroom",
    pos: "noun",
    level: 4,
    kidMeaning: "The room where a class has lessons.",
    examples: ["She learns in the classroom.", "The classroom has desks."],
    emoji: "🏫",
    syllables: "class-room",
    distractorGroup: "school",
  },
  {
    word: "pupil",
    pos: "noun",
    level: 4,
    kidMeaning: "A child who is learning at school.",
    examples: ["The pupil learns quickly.", "She is a good pupil."],
    emoji: "👧",
    syllables: "pu-pil",
    distractorGroup: "school",
  },
  {
    word: "lesson",
    pos: "noun",
    level: 2,
    kidMeaning: "A time when a teacher teaches one subject.",
    examples: ["The lesson is about maths.", "She listens to the lesson."],
    emoji: "📖",
    syllables: "les-son",
    distractorGroup: "school",
  },
  {
    word: "assignment",
    pos: "noun",
    level: 5,
    kidMeaning: "A piece of work you are given to do.",
    examples: ["She finishes her assignment.", "The assignment is long."],
    emoji: "📋",
    syllables: "as-sign-ment",
    distractorGroup: "school",
  },
  {
    word: "test",
    pos: "noun",
    level: 1,
    kidMeaning: "A set of questions that checks what you know.",
    examples: ["He takes a test tomorrow.", "The test is hard."],
    emoji: "✏️",
    syllables: "test",
    distractorGroup: "school",
  },
  {
    word: "quiz",
    pos: "noun",
    level: 4,
    kidMeaning: "A short test with a few questions.",
    examples: ["They have a quiz Friday.", "The quiz is short."],
    emoji: "❓",
    syllables: "quiz",
    distractorGroup: "school",
  },
  {
    word: "calendar",
    pos: "noun",
    level: 5,
    kidMeaning: "A chart showing the days and months of a year.",
    examples: ["She marks the date on the calendar.", "The calendar hangs on the wall."],
    emoji: "📅",
    syllables: "cal-en-dar",
    distractorGroup: "school",
  },
  {
    word: "medal",
    pos: "noun",
    level: 4,
    kidMeaning: "A metal disc given as a prize.",
    examples: ["She wins a gold medal.", "He wears his medal proudly."],
    emoji: "🥇",
    syllables: "med-al",
    distractorGroup: "school",
  },
  {
    word: "trophy",
    pos: "noun",
    level: 4,
    kidMeaning: "A cup or prize given to a winner.",
    examples: ["She holds the trophy.", "The trophy is shiny."],
    emoji: "🏆",
    syllables: "tro-phy",
    distractorGroup: "school",
  },
  {
    word: "breaktime",
    pos: "noun",
    level: 1,
    kidMeaning: "The short rest between lessons at school.",
    examples: ["Breaktime is at ten o'clock.", "She eats at breaktime."],
    emoji: "⏰",
    syllables: "break-time",
    distractorGroup: "school",
  },
  {
    word: "lunchtime",
    pos: "noun",
    level: 5,
    kidMeaning: "The part of the day when you eat lunch.",
    examples: ["Lunchtime is at noon.", "They eat in the canteen at lunchtime."],
    emoji: "🍽️",
    syllables: "lunch-time",
    distractorGroup: "school",
  },
  {
    word: "semester",
    pos: "noun",
    level: 5,
    kidMeaning: "One of the two halves of a school year.",
    examples: ["The first semester ends soon.", "She works hard each semester."],
    emoji: "📅",
    syllables: "se-mes-ter",
    distractorGroup: "school",
  },
  {
    word: "term",
    pos: "noun",
    level: 4,
    kidMeaning: "One of the parts a school year is divided into.",
    examples: ["The term ends in July.", "There are three terms per year."],
    emoji: "📅",
    syllables: "term",
    distractorGroup: "school",
  },
  {
    word: "report",
    pos: "noun",
    level: 3,
    kidMeaning: "A written account of how you are doing.",
    examples: ["He gets a report card.", "The report shows good grades."],
    emoji: "📄",
    syllables: "re-port",
    distractorGroup: "school",
  },
  {
    word: "discipline",
    pos: "noun",
    level: 5,
    kidMeaning: "Training that teaches you to behave well.",
    examples: ["He faces discipline for bad behaviour.", "Discipline helps learning."],
    emoji: "🚫",
    syllables: "dis-ci-pline",
    distractorGroup: "school",
  },
  {
    word: "bedtime",
    pos: "noun",
    level: 4,
    kidMeaning: "The time when you go to bed.",
    examples: ["Her bedtime is nine o'clock.", "Bedtime is early on school nights."],
    emoji: "🛏️",
    syllables: "bed-time",
    distractorGroup: "home",
  },
  {
    word: "breakfast",
    pos: "noun",
    level: 2,
    kidMeaning: "The first meal you eat each day.",
    examples: ["She eats breakfast.", "Breakfast is important."],
    emoji: "🍳",
    syllables: "break-fast",
    distractorGroup: "home",
  },
  {
    word: "dinner",
    pos: "noun",
    level: 1,
    kidMeaning: "The main meal of the day.",
    examples: ["He eats dinner at six.", "Dinner is delicious."],
    emoji: "🍽️",
    syllables: "din-ner",
    distractorGroup: "home",
  },
  {
    word: "supper",
    pos: "noun",
    level: 3,
    kidMeaning: "A light meal eaten in the evening.",
    examples: ["She has supper at eight.", "Supper is quick."],
    emoji: "🍲",
    syllables: "sup-per",
    distractorGroup: "home",
  },
  {
    word: "lunch",
    pos: "noun",
    level: 1,
    kidMeaning: "The meal you eat in the middle of the day.",
    examples: ["He eats lunch at school.", "Lunch is tasty."],
    emoji: "🥪",
    syllables: "lunch",
    distractorGroup: "home",
  },
  {
    word: "recipe",
    pos: "noun",
    level: 4,
    kidMeaning: "A list of steps for cooking a dish.",
    examples: ["She follows the recipe.", "The recipe has ten steps."],
    emoji: "📖",
    syllables: "rec-i-pe",
    distractorGroup: "home",
  },
  {
    word: "ingredient",
    pos: "noun",
    level: 6,
    kidMeaning: "One of the foods you put in a dish.",
    examples: ["Flour is an ingredient.", "She has all the ingredients."],
    emoji: "🥘",
    syllables: "in-gred-i-ent",
    distractorGroup: "home",
  },
  {
    word: "crockery",
    pos: "noun",
    level: 6,
    kidMeaning: "The plates, bowls and cups you eat from.",
    examples: ["The crockery is white.", "She washes the crockery."],
    emoji: "🍽️",
    syllables: "crock-er-y",
    distractorGroup: "home",
  },
  {
    word: "dishwasher",
    pos: "noun",
    level: 6,
    kidMeaning: "A machine that washes plates and cups.",
    examples: ["She puts dishes in the dishwasher.", "The dishwasher runs at night."],
    emoji: "🍽️",
    syllables: "dish-wash-er",
    distractorGroup: "home",
  },
  {
    word: "pantry",
    pos: "noun",
    level: 5,
    kidMeaning: "A small room where food is stored.",
    examples: ["She looks in the pantry.", "The pantry has flour."],
    emoji: "🥫",
    syllables: "pant-ry",
    distractorGroup: "home",
  },
  {
    word: "cellar",
    pos: "noun",
    level: 4,
    kidMeaning: "A room under a house, below the ground.",
    examples: ["He stores things in the cellar.", "The cellar is cold."],
    emoji: "🏠",
    syllables: "cel-lar",
    distractorGroup: "home",
  },
  {
    word: "attic",
    pos: "noun",
    level: 4,
    kidMeaning: "The room just under the roof of a house.",
    examples: ["She plays in the attic.", "The attic is dusty."],
    emoji: "🏠",
    syllables: "at-tic",
    distractorGroup: "home",
  },
  {
    word: "hallway",
    pos: "noun",
    level: 4,
    kidMeaning: "A passage that joins the rooms of a house.",
    examples: ["She walks down the hallway.", "The hallway is long."],
    emoji: "🚪",
    syllables: "hall-way",
    distractorGroup: "home",
  },
  {
    word: "lobby",
    pos: "noun",
    level: 4,
    kidMeaning: "The large entrance hall of a building.",
    examples: ["They wait in the lobby.", "The lobby is bright."],
    emoji: "🏢",
    syllables: "lob-by",
    distractorGroup: "home",
  },
  {
    word: "furniture",
    pos: "noun",
    level: 4,
    kidMeaning: "Things like chairs, tables and beds.",
    examples: ["The furniture is wooden.", "She buys new furniture."],
    emoji: "🪑",
    syllables: "fur-ni-ture",
    distractorGroup: "home",
  },
  {
    word: "dresser",
    pos: "noun",
    level: 2,
    kidMeaning: "A piece of furniture with drawers for clothes.",
    examples: ["She puts clothes in the dresser.", "The dresser is tall."],
    emoji: "🪑",
    syllables: "dress-er",
    distractorGroup: "home",
  },
  {
    word: "bookshelf",
    pos: "noun",
    level: 6,
    kidMeaning: "A shelf where books are kept.",
    examples: ["His bookshelf is full.", "She arranges the bookshelf."],
    emoji: "📚",
    syllables: "book-shelf",
    distractorGroup: "home",
  },
  {
    word: "headboard",
    pos: "noun",
    level: 6,
    kidMeaning: "The upright board at the head of a bed.",
    examples: ["The headboard is padded.", "She leans on the headboard."],
    emoji: "🛏️",
    syllables: "head-board",
    distractorGroup: "home",
  },
  {
    word: "footboard",
    pos: "noun",
    level: 2,
    kidMeaning: "The upright board at the foot of a bed.",
    examples: ["The footboard is wooden.", "She sits on the footboard."],
    emoji: "🛏️",
    syllables: "foot-board",
    distractorGroup: "home",
  },
  {
    word: "bedframe",
    pos: "noun",
    level: 3,
    kidMeaning: "The frame that holds up a mattress.",
    examples: ["The bedframe is metal.", "She makes the bedframe."],
    emoji: "🛏️",
    syllables: "bed-frame",
    distractorGroup: "home",
  },
  {
    word: "duvet",
    pos: "noun",
    level: 6,
    kidMeaning: "A thick soft quilt you sleep under.",
    examples: ["He sleeps under a duvet.", "The duvet is warm."],
    emoji: "🛏️",
    syllables: "du-vet",
    distractorGroup: "home",
  },
  {
    word: "canopy",
    pos: "noun",
    level: 6,
    kidMeaning: "A cloth roof held above a bed.",
    examples: ["The canopy is purple.", "She climbs under the canopy."],
    emoji: "🛏️",
    syllables: "can-o-py",
    distractorGroup: "home",
  },
  {
    word: "playpen",
    pos: "noun",
    level: 6,
    kidMeaning: "A small fenced area where a baby plays.",
    examples: ["She puts the baby in the playpen.", "The playpen is safe."],
    emoji: "👶",
    syllables: "play-pen",
    distractorGroup: "home",
  },
  {
    word: "highchair",
    pos: "noun",
    level: 2,
    kidMeaning: "A tall chair where a baby sits to eat.",
    examples: ["The baby sits in the highchair.", "The highchair has a tray."],
    emoji: "👶",
    syllables: "high-chair",
    distractorGroup: "home",
  },
  {
    word: "swing",
    pos: "noun",
    level: 2,
    kidMeaning: "A hanging seat you sit on and move.",
    examples: ["She plays on the swing.", "The swing goes high."],
    emoji: "🛝",
    syllables: "swing",
    distractorGroup: "home",
  },
  {
    word: "seesaw",
    pos: "noun",
    level: 6,
    kidMeaning: "A long board that goes up and down.",
    examples: ["They play on the seesaw.", "The seesaw bounces."],
    emoji: "🪝",
    syllables: "see-saw",
    distractorGroup: "home",
  },
  {
    word: "trampoline",
    pos: "noun",
    level: 6,
    kidMeaning: "A springy sheet you bounce up and down on.",
    examples: ["He jumps on the trampoline.", "The trampoline is fun."],
    emoji: "🎪",
    syllables: "tram-po-line",
    distractorGroup: "home",
  },
  {
    word: "toolbox",
    pos: "noun",
    level: 6,
    kidMeaning: "A box for keeping your tools in.",
    examples: ["He opens the toolbox.", "The toolbox is full."],
    emoji: "🔧",
    syllables: "tool-box",
    distractorGroup: "home",
  },
  {
    word: "hammer",
    pos: "noun",
    level: 3,
    kidMeaning: "A tool with a heavy head for hitting nails.",
    examples: ["He uses a hammer.", "The hammer is heavy."],
    emoji: "🔨",
    syllables: "ham-mer",
    distractorGroup: "home",
  },
  {
    word: "screwdriver",
    pos: "noun",
    level: 6,
    kidMeaning: "A tool for turning screws in and out.",
    examples: ["She uses a screwdriver.", "The screwdriver is small."],
    emoji: "🔧",
    syllables: "screw-driv-er",
    distractorGroup: "home",
  },
  {
    word: "nail",
    pos: "noun",
    level: 2,
    kidMeaning: "A thin metal pin hammered into wood.",
    examples: ["She hammers the nail.", "The nail is sharp."],
    emoji: "🔨",
    syllables: "nail",
    distractorGroup: "home",
  },
  {
    word: "screw",
    pos: "noun",
    level: 2,
    kidMeaning: "A metal pin with a winding ridge around it.",
    examples: ["He turns the screw.", "The screw is tight."],
    emoji: "🔧",
    syllables: "screw",
    distractorGroup: "home",
  },
  {
    word: "bolt",
    pos: "noun",
    level: 3,
    kidMeaning: "A thick metal pin that fastens with a nut.",
    examples: ["She tightens the bolt.", "The bolt is strong."],
    emoji: "🔧",
    syllables: "bolt",
    distractorGroup: "home",
  },
  {
    word: "nut",
    pos: "noun",
    level: 3,
    kidMeaning: "A small metal ring that screws onto a bolt.",
    examples: ["He twists the nut.", "The nut is small."],
    emoji: "🔩",
    syllables: "nut",
    distractorGroup: "home",
  },
  {
    word: "washer",
    pos: "noun",
    level: 2,
    kidMeaning: "A machine that washes your dirty clothes.",
    examples: ["She puts clothes in the washer.", "The washer is clean."],
    emoji: "🧺",
    syllables: "wash-er",
    distractorGroup: "home",
  },
  {
    word: "dryer",
    pos: "noun",
    level: 2,
    kidMeaning: "A machine that dries wet clothes with heat.",
    examples: ["He puts clothes in the dryer.", "The dryer is warm."],
    emoji: "🧺",
    syllables: "dry-er",
    distractorGroup: "home",
  },
  {
    word: "clothesline",
    pos: "noun",
    level: 6,
    kidMeaning: "A rope for hanging wet clothes to dry.",
    examples: ["She hangs clothes on the clothesline.", "The clothesline is full."],
    emoji: "🧺",
    syllables: "clothes-line",
    distractorGroup: "home",
  },
  {
    word: "garment",
    pos: "noun",
    level: 5,
    kidMeaning: "One piece of clothing that you wear.",
    examples: ["The garment is clean.", "She folds the garment."],
    emoji: "👗",
    syllables: "gar-ment",
    distractorGroup: "home",
  },
  {
    word: "outfit",
    pos: "noun",
    level: 3,
    kidMeaning: "A set of clothes that are worn together.",
    examples: ["She wears a nice outfit.", "The outfit is colourful."],
    emoji: "👗",
    syllables: "out-fit",
    distractorGroup: "home",
  },
  {
    word: "necktie",
    pos: "noun",
    level: 6,
    kidMeaning: "A narrow cloth worn knotted under a collar.",
    examples: ["He wears a necktie.", "The necktie is striped."],
    emoji: "👔",
    syllables: "neck-tie",
    distractorGroup: "home",
  },
  {
    word: "bowtie",
    pos: "noun",
    level: 6,
    kidMeaning: "Neckwear knotted into a small bow.",
    examples: ["He wears a bowtie.", "The bowtie is red."],
    emoji: "🎀",
    syllables: "bow-tie",
    distractorGroup: "home",
  },
  {
    word: "shoelace",
    pos: "noun",
    level: 6,
    kidMeaning: "The string that ties up your shoe.",
    examples: ["He ties his shoelace.", "The shoelace is long."],
    emoji: "👞",
    syllables: "shoe-lace",
    distractorGroup: "home",
  },
  {
    word: "slipper",
    pos: "noun",
    level: 5,
    kidMeaning: "A soft, light shoe you wear indoors.",
    examples: ["She wears slippers at home.", "Slippers are cosy."],
    emoji: "🩴",
    syllables: "slip-per",
    distractorGroup: "home",
  },
  {
    word: "knit",
    pos: "verb",
    level: 5,
    kidMeaning: "To make cloth from wool using needles.",
    examples: ["She knits a sweater.", "He knits a scarf."],
    emoji: "🧶",
    syllables: "knit",
    distractorGroup: "hobby",
  },
  {
    word: "embroider",
    pos: "verb",
    level: 6,
    kidMeaning: "To sew a picture onto cloth with thread.",
    examples: ["She embroiders a picture.", "He embroiders flowers."],
    emoji: "🧵",
    syllables: "em-broid-er",
    distractorGroup: "hobby",
  },
  {
    word: "weave",
    pos: "verb",
    level: 5,
    kidMeaning: "To cross threads over and under to make cloth.",
    examples: ["She weaves at the loom.", "He weaves baskets."],
    emoji: "🧶",
    syllables: "weave",
    distractorGroup: "hobby",
  },
  {
    word: "quilt",
    pos: "noun",
    level: 5,
    kidMeaning: "A warm bed covering with padding inside.",
    examples: ["She makes a quilt.", "The quilt is pretty."],
    emoji: "🧣",
    syllables: "quilt",
    distractorGroup: "hobby",
  },
  {
    word: "patchwork",
    pos: "noun",
    level: 6,
    kidMeaning: "Cloth sewn from many small different pieces.",
    examples: ["She does patchwork.", "The patchwork is beautiful."],
    emoji: "🧵",
    syllables: "patch-work",
    distractorGroup: "hobby",
  },
  {
    word: "collage",
    pos: "noun",
    level: 6,
    kidMeaning: "A picture made by gluing pieces onto paper.",
    examples: ["She makes a collage.", "The collage is colourful."],
    emoji: "🎨",
    syllables: "col-lage",
    distractorGroup: "hobby",
  },
  {
    word: "scrapbook",
    pos: "noun",
    level: 6,
    kidMeaning: "A book where you stick pictures you keep.",
    examples: ["She keeps a scrapbook.", "The scrapbook has memories."],
    emoji: "📖",
    syllables: "scrap-book",
    distractorGroup: "hobby",
  },
  {
    word: "jigsaw",
    pos: "noun",
    level: 6,
    kidMeaning: "A picture puzzle you fit together.",
    examples: ["He finished the jigsaw in one afternoon.", "The jigsaw had five hundred pieces."],
    emoji: "🧩",
    syllables: "jig-saw",
    distractorGroup: "hobby",
  },
  {
    word: "dollhouse",
    pos: "noun",
    level: 6,
    kidMeaning: "A tiny toy house made for dolls.",
    examples: ["She plays with a dollhouse.", "The dollhouse is detailed."],
    emoji: "🏠",
    syllables: "doll-house",
    distractorGroup: "hobby",
  },
  {
    word: "boardgame",
    pos: "noun",
    level: 2,
    kidMeaning: "A game you play on a marked board.",
    examples: ["They play a boardgame.", "The boardgame is fun."],
    emoji: "🎲",
    syllables: "board-game",
    distractorGroup: "hobby",
  },
  {
    word: "dice",
    pos: "noun",
    level: 4,
    kidMeaning: "Small cubes with dots, used in games.",
    examples: ["She rolls the dice.", "The dice are fair."],
    emoji: "🎲",
    syllables: "dice",
    distractorGroup: "hobby",
  },
  {
    word: "deck",
    pos: "noun",
    level: 3,
    kidMeaning: "A full set of playing cards.",
    examples: ["He has a deck of cards.", "The deck is complete."],
    emoji: "🃏",
    syllables: "deck",
    distractorGroup: "hobby",
  },
  {
    word: "checker",
    pos: "noun",
    level: 4,
    kidMeaning: "A round piece used in the game of draughts.",
    examples: ["She moves a checker.", "The checker is red."],
    emoji: "🔴",
    syllables: "check-er",
    distractorGroup: "hobby",
  },
  {
    word: "dartboard",
    pos: "noun",
    level: 6,
    kidMeaning: "The round target you throw darts at.",
    examples: ["He throws at the dartboard.", "The dartboard is round."],
    emoji: "🎯",
    syllables: "dart-board",
    distractorGroup: "hobby",
  },
  {
    word: "dart",
    pos: "noun",
    level: 4,
    kidMeaning: "A small pointed object you throw at a target.",
    examples: ["She throws a dart.", "The dart is sharp."],
    emoji: "🎯",
    syllables: "dart",
    distractorGroup: "hobby",
  },
  {
    word: "archery",
    pos: "noun",
    level: 6,
    kidMeaning: "The sport of shooting arrows from a bow.",
    examples: ["He does archery.", "Archery is fun."],
    emoji: "🏹",
    syllables: "arch-er-y",
    distractorGroup: "hobby",
  },
  {
    word: "bowstring",
    pos: "noun",
    level: 4,
    kidMeaning: "The tight cord joining the ends of a bow.",
    examples: ["She pulls the bowstring.", "The bowstring is tight."],
    emoji: "🏹",
    syllables: "bow-string",
    distractorGroup: "hobby",
  },
  {
    word: "racket",
    pos: "noun",
    level: 5,
    kidMeaning: "A bat with strings for hitting a ball.",
    examples: ["She holds a racket.", "The racket is strong."],
    emoji: "🎾",
    syllables: "rack-et",
    distractorGroup: "hobby",
  },
  {
    word: "paddle",
    pos: "noun",
    level: 5,
    kidMeaning: "A short bat used for hitting a ball.",
    examples: ["He uses a paddle.", "The paddle is wooden."],
    emoji: "🏸",
    syllables: "pad-dle",
    distractorGroup: "hobby",
  },
  {
    word: "pogo-stick",
    pos: "noun",
    level: 6,
    kidMeaning: "A spring stick you bounce along on.",
    examples: ["She bounces on a pogo-stick.", "The pogo-stick is fun."],
    emoji: "🎪",
    syllables: "po-go-stick",
    distractorGroup: "hobby",
  },
  {
    word: "skates",
    pos: "noun",
    level: 6,
    kidMeaning: "Boots with wheels or blades for gliding.",
    examples: ["She wears skates.", "Skates are fun."],
    emoji: "⛸️",
    syllables: "roll-er-blades",
    distractorGroup: "hobby",
  },
  {
    word: "tent",
    pos: "noun",
    level: 3,
    kidMeaning: "A cloth shelter you sleep in when camping.",
    examples: ["They sleep in a tent.", "The tent is waterproof."],
    emoji: "⛺",
    syllables: "tent",
    distractorGroup: "hobby",
  },
  {
    word: "campfire",
    pos: "noun",
    level: 6,
    kidMeaning: "A small fire built outdoors for warmth.",
    examples: ["They sit around the campfire.", "The campfire is warm."],
    emoji: "🔥",
    syllables: "camp-fire",
    distractorGroup: "hobby",
  },
  {
    word: "bedroll",
    pos: "noun",
    level: 3,
    kidMeaning: "A soft roll for sleeping outside.",
    examples: ["He sleeps in a bedroll.", "The bedroll is warm."],
    emoji: "🛏️",
    syllables: "sleep-ing-bag",
    distractorGroup: "hobby",
  },
  {
    word: "thermos",
    pos: "noun",
    level: 6,
    kidMeaning: "A flask that keeps drinks hot or cold.",
    examples: ["She pours from the thermos.", "The thermos keeps it warm."],
    emoji: "🫖",
    syllables: "ther-mos",
    distractorGroup: "hobby",
  },
  {
    word: "flask",
    pos: "noun",
    level: 5,
    kidMeaning: "A bottle with a narrow neck for liquid.",
    examples: ["He carries a flask.", "The flask is full."],
    emoji: "🫖",
    syllables: "flask",
    distractorGroup: "hobby",
  },
  {
    word: "lantern",
    pos: "noun",
    level: 5,
    kidMeaning: "A light in a case that you carry.",
    examples: ["She carries a lantern.", "The lantern glows."],
    emoji: "🏮",
    syllables: "lant-ern",
    distractorGroup: "hobby",
  },
  {
    word: "telescope",
    pos: "noun",
    level: 6,
    kidMeaning: "A tube with lenses for seeing faraway things.",
    examples: ["He uses a telescope.", "The telescope is powerful."],
    emoji: "🔭",
    syllables: "tel-e-scope",
    distractorGroup: "hobby",
  },
  {
    word: "microscope",
    pos: "noun",
    level: 6,
    kidMeaning: "A tool that makes tiny things look big.",
    examples: ["She uses a microscope.", "The microscope is powerful."],
    emoji: "🔬",
    syllables: "mi-cro-scope",
    distractorGroup: "hobby",
  },
  {
    word: "clipboard",
    pos: "noun",
    level: 6,
    kidMeaning: "A board with a clip that holds paper.",
    examples: ["She writes on a clipboard.", "The clipboard holds the papers."],
    emoji: "📋",
    syllables: "clip-board",
    distractorGroup: "school",
  },
  {
    word: "bookcase",
    pos: "noun",
    level: 6,
    kidMeaning: "A set of shelves for keeping books on.",
    examples: ["She puts books in the bookcase.", "The bookcase is tall."],
    emoji: "📚",
    syllables: "book-case",
    distractorGroup: "home",
  },
  {
    word: "daycare",
    pos: "noun",
    level: 5,
    kidMeaning: "Care for young children while parents work.",
    examples: ["She goes to daycare.", "Daycare is fun."],
    emoji: "🏠",
    syllables: "day-care",
    distractorGroup: "school",
  },
  {
    word: "torch",
    pos: "noun",
    level: 3,
    kidMeaning: "A small light you hold in your hand.",
    examples: ["He carries a torch.", "The torch is bright."],
    emoji: "🔦",
    syllables: "torch",
    distractorGroup: "home",
  },
];
